
text_1100__089CFDCC:
	.string "{END}"


text_1101__089CFDCD:
	.string "Helllllp!!! Help meeee!!!{END}"


text_1102__089CFDE7:
	.string "Ouch! Won{SINGLE_QUOTE}t somebody stop them!?{END}"


text_1103__089CFE08:
	.string "Ow! Ow! Help... Somebody!{NL}Can{SINGLE_QUOTE}t anybody hear me?{END}"


text_1104__089CFE39:
	.string "OUCH!!!{END}"


text_1105__089CFE41:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hey! Kid! You there!{END}"


text_1106__089CFE59:
	.string "Ow!{END}"


text_1107__089CFE5D:
	.string "Hey! Don{SINGLE_QUOTE}t just stand there!{NL}Do something!!!{END}"


text_1108__089CFE8A:
	.string "Ow!{END}"


text_1109__089CFE8E:
	.string "What{SINGLE_QUOTE}s wrong with you!? Do you like{NL}watching me take this abuse!? Help me!{END}"


text_110A__089CFED9:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Phew! Well done! That was close. Not{NL}that I couldn{SINGLE_QUOTE}t handle them myself.{NL}But that{SINGLE_QUOTE}s beside the point!{NL}{NL}What in the world is a lone child{NL}doing so deep in the woods?{END}"


text_110B__089CFF81:
	.string "Ho ho! I see.{END}"


text_110C__089CFF8F:
	.string "The...{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}, you say? And {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}?{END}"


text_110D__089CFFB9:
	.string "Vaati{SINGLE_QUOTE}s cursed someone? What?{NL}The sacred blade?!?{END}"


text_110E__089CFFEB:
	.string "Is that so? I see, I see... You know,{NL}you and I have quite a lot in common.{NL}You see, I, too, am on a quest to{NL}break a curse of Vaati{SINGLE_QUOTE}s.{NL}And you say that reforging the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred{NL}blade{SPECIAL_02_PAR_1}{END} can break his curse, eh?{NL}Well, then you have found yourself{NL}a companion, my boy!{NL}My name is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Ezlo{SPECIAL_02_PAR_1}{END}. It{SINGLE_QUOTE}s a pleasure to{NL}make your acquaintance.{END}"


text_110F__089D0134:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Wait! Wait, I say!{NL}{NL}You walk so quickly!{NL}Too quickly, in fact!{NL}Can{SINGLE_QUOTE}t you go any slower? Surely{NL}you{SINGLE_QUOTE}ve noticed that I have no legs...{END}"


text_1110__089D01BC:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Boy! Take a good look at me! Do you{NL}really think I can walk that fast!?{END}"


text_1111__089D0207:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E4}Augh!{NL}{NL}If it isn{SINGLE_QUOTE}t one thing, it{SINGLE_QUOTE}s another!{NL}You are a troublesome boy!{END}"


text_1112__089D0251:
	.string "{SPECIAL_03_PAR_2}{END}_There! Now, you can{SINGLE_QUOTE}t possibly{NL}leave me behind.{NL}My... It{SINGLE_QUOTE}s quite comfortable up here.{NL}More comfortable than it looks, surely.{NL}And much easier on me!{NL}{NL}Hey! Quit your squirming! Can{SINGLE_QUOTE}t{NL}you sit still? See! There...{NL}Yes, yes! That{SINGLE_QUOTE}s it. Much better.{NL}{NL}Now, I suppose a boy like you still has{NL}much to learn about the world.{NL}If ever you need my insight, press{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}SELECT{SPECIAL_02_PAR_1}{END}. I{SINGLE_QUOTE}ll be happy to help!{NL}Ah, such a hopeless child...{END}"


text_1113__089D03F4:
	.string "Hey! Where are you going?{NL}You heartless brat! Help me!!!{END}"


text_1114__089D042D:
	.string "What are you doing? Aren{SINGLE_QUOTE}t you going{NL}to finish them off?{END}"


text_1115__089D0466:
	.string "...What? Is there something on my{NL}face? Quit staring! It{SINGLE_QUOTE}s rude!{END}"


text_1116__089D04A7:
	.string "{END}"


text_1117__089D04A8:
	.string "Oh, {SPECIAL_06_PAR_1}{END}. You{SINGLE_QUOTE}re heading for{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END} now, aren{SINGLE_QUOTE}t you?{NL}Leave the monsters that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{NL}{SPECIAL_02_PAR_1}{END}freed to us, and go find the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}!{END}"


text_1118__089D0530:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods {SPECIAL_02_PAR_1}{END}lie far to the south from{NL}here. If you get lost, check your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}.{END}"


text_1119__089D0586:
	.string "{END}"


text_111A__089D0587:
	.string "Hey, kid! Where are you going!?{NL}That{SINGLE_QUOTE}s the way we just came from!{END}"


text_111B__089D05C9:
	.string "{END}"


text_111C__089D05CA:
	.string "{END}"


text_111D__089D05CB:
	.string "You who desire to enter the realm of{NL}the Minish, seek out the hidden portal.{NL}Offer up your song at the portal{SINGLE_QUOTE}s{NL}base, and be guided to the world below.{END}"


text_111E__089D0663:
	.string "{END}"


text_111F__089D0664:
	.string "{END}"


text_1120__089D0665:
	.string "{END}"


text_1121__089D0666:
	.string "{END}"


text_1122__089D0667:
	.string "{END}"


text_1123__089D0668:
	.string "{END}"


text_1124__089D0669:
	.string "{END}"


text_1125__089D066A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmmm... It appears we have found the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish village{SPECIAL_02_PAR_1}{END}.{END}"


text_1126__089D06A6:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_B1}Pico picori!{END}"


text_1127__089D06B6:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_B3}Ripi ripico picori!{END}"


text_1128__089D06CD:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_B2}Picoco pico ripico!{END}"


text_1129__089D06E4:
	.string "I gather it{SINGLE_QUOTE}s been quite some time{NL}since they last saw a human.{NL}...What{SINGLE_QUOTE}s that? You didn{SINGLE_QUOTE}t understand{NL}what they were saying just now?{NL}Ah, yes. That was the language{NL}of the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END}.{NL}It{SINGLE_QUOTE}s a little different from the dialect{NL}I am most familiar with.{NL}I{SINGLE_QUOTE}m afraid I didn{SINGLE_QUOTE}t catch most{NL}of what they said myself.{NL}But perhaps there is someone here{NL}who {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}understands your language{SPECIAL_02_PAR_1}{END}.{NL}We should look around.{END}"


text_112A__089D0873:
	.string "{END}"


text_112B__089D0874:
	.string "Fortunately, the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element {SPECIAL_02_PAR_1}{END}is in the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}shrine {SPECIAL_02_PAR_1}{END}at the far end of the village.{NL}A horde of beasts lives in that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}shrine{SPECIAL_02_PAR_1}{END},{NL}though, so enter with caution.{END}"


text_112C__089D0916:
	.string "{END}"


text_112D__089D0917:
	.string "{END}"


text_112E__089D0918:
	.string "{END}"


text_112F__089D0919:
	.string "{END}"


text_1130__089D091A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}Oh! You speak our language!{NL}{NL}It{SINGLE_QUOTE}s been quite a while since we{SINGLE_QUOTE}ve{NL}heard outsiders speak our tongue!{NL}We have little to offer you in these{NL}woods, but please, enjoy your stay.{END}"


text_1131__089D09C9:
	.string "Thank you for your offer, but we have{NL}no time to relax. My name is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Ezlo{SPECIAL_02_PAR_1}{END}.{NL}This child is {SPECIAL_06_PAR_1}{END}.{NL}{NL}We need to break a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}curse {SPECIAL_02_PAR_1}{END}that has{NL}been cast on the princess of Hyrule.{NL}To do so, we{SINGLE_QUOTE}ll need to reforge{NL}the broken {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picori Blade{SPECIAL_02_PAR_1}{END}.{END}"


text_1132__089D0AB1:
	.string "Ah, yes. And you{SINGLE_QUOTE}ve come here now{NL}hoping to have the blade reforged?{NL}Hm... Well, if that{SINGLE_QUOTE}s what you{SINGLE_QUOTE}re after,{NL}you{SINGLE_QUOTE}ll need four mystic {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END}.{NL}These elements are the crystalline{NL}forms of the energies of this world.{NL}Only by {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}infusing the blade{SPECIAL_02_PAR_1}{END} with these{NL}energies can a new blade be forged.{NL}Here, give me your map. I can mark{NL}where these {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END} can be found.{END}"


text_1133__089D0C25:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END} can be found in the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}shrine{SPECIAL_02_PAR_1}{END} to the north of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Festari{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s abbey.{NL}Speak with {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Festari{SPECIAL_02_PAR_1}{END}. He will show you the{NL}path to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}shrine{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s entrance.{NL}Go with caution. Evil creatures have{NL}lately made their home in our {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}shrine{SPECIAL_02_PAR_1}{END}.{NL}Return to me at once after you have{NL}found the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END}.{END}"


text_1134__089D0D5F:
	.string "{END}"


text_1135__089D0D60:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}So! You have found the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END}!{NL}{NL}You are blessed with much courage and{NL}strength for one so young.{NL}If your conviction holds strong, head{NL}to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}.{NL}There, you will find a man named {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}.{NL}{NL}Among all the Minish, there is no one{NL}more able to repair your sword.{NL}If you ask him, I am certain he will{NL}reforge your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}broken Picori Blade{SPECIAL_02_PAR_1}{END}.{NL}I shall send word to him in advance.{NL}{NL}Travel safely. You are brave, but{NL}there are many evils now in the world.{END}"


text_1136__089D0F38:
	.string "Leave through this door here. It will{NL}take you out of the forest quickly.{END}"


text_1137__089D0F82:
	.string "Great elder, we are in your debt.{NL}{NL}We shall head for {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}{NL}at once!{END}"


text_1138__089D0FD1:
	.string "{END}"


text_1139__089D0FD2:
	.string "{END}"


text_113A__089D0FD3:
	.string "{END}"


text_113B__089D0FD4:
	.string "{END}"


text_113C__089D0FD5:
	.string "{END}"


text_113D__089D0FD6:
	.string "{END}"


text_113E__089D0FD7:
	.string "{END}"

