
text_2D00__089DF82C:
	.string "{SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1}-{NL}Don{SINGLE_QUOTE}t buy{END}"


text_2D01__089DF83F:
	.string "Ahh, welcome.{NL}{NL}Care for some of Granny{SINGLE_QUOTE}s{NL}homemade {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}blue potion{SPECIAL_02_PAR_1}{END}?{NL}One sip, and you{SINGLE_QUOTE}re full of energy!{NL}Please, look around...{END}"


text_2D02__089DF8BD:
	.string "That{SINGLE_QUOTE}s Granny{SINGLE_QUOTE}s homemade{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}blue potion{SPECIAL_02_PAR_1}{END}, my dear!{NL}I{SINGLE_QUOTE}ll fill your bottle for 60 Rupees.{NL}What do you say?{NL}{SPECIAL_07_PAR_1}-{END}"


text_2D03__089DF92A:
	.string "Ever heard of Granny{SINGLE_QUOTE}s{NL}homemade {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}blue potion{SPECIAL_02_PAR_1}{END}?{NL}One sip, and you{SINGLE_QUOTE}re full of energy!{NL}{NL}Fill a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle {SPECIAL_02_PAR_1}{END}and carry it around with{NL}you! After all, it{SINGLE_QUOTE}s only 60 Rupees!{NL}Will you buy some?{NL}{SPECIAL_07_PAR_1}-{END}"


text_2D04__089DF9E7:
	.string "Granny{SINGLE_QUOTE}s stuff is the best! This is my{NL}traditional {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}red potion{SPECIAL_02_PAR_1}{END}!{NL}Shall I fill your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle{SPECIAL_02_PAR_1}{END} for...{NL}150 Rupees? What do you say?{NL}{SPECIAL_07_PAR_1}-{END}"


text_2D05__089DFA6F:
	.string "Once you{SINGLE_QUOTE}ve tried my new {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}red potion{SPECIAL_02_PAR_1}{END},{NL}you{SINGLE_QUOTE}ll never go back to the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}blue{SPECIAL_02_PAR_1}{END} stuff!{NL}Shall I fill your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle {SPECIAL_02_PAR_1}{END}for 150 Rupees?{NL}What do you say, my pretty young boy?{NL}{SPECIAL_07_PAR_1}-{END}"


text_2D06__089DFB1B:
	.string "Come back when you need more...{NL}Hehehehe!{END}"


text_2D07__089DFB45:
	.string "Ah, yes! A fine choice, my dear!{NL}That{SINGLE_QUOTE}s a limited-time article!{NL}One whiff, and you{SINGLE_QUOTE}re wide-awake! That{NL}is why it{SINGLE_QUOTE}s called a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}wake-up mushroom{SPECIAL_02_PAR_1}{END}!{NL}Would you like to buy it for 60 Rupees?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1}{BYTE_FF}Don{SINGLE_QUOTE}t buy{END}"


text_2D08__089DFC11:
	.string "You{SINGLE_QUOTE}ve got an eye for fine goods!{NL}{NL}That, my dear, is my highly regarded,{NL}homemade {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}blue potion{SPECIAL_02_PAR_1}{END}!{END}"


text_2D09__089DFC74:
	.string "Ahh, welcome.{NL}{NL}Back for Granny{SINGLE_QUOTE}s famous {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}red{SPECIAL_02_PAR_1}{END}{NL}and {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}blue potions{SPECIAL_02_PAR_1}{END}?{NL}One sip, and you{SINGLE_QUOTE}re full of energy!{NL}Which do you like, deary, red or blue?{END}"


text_2D0A__089DFD05:
	.string "None for you? Well, remember that when{NL}you run out of pep later! Hehehehe!{END}"


text_2D0B__089DFD50:
	.string "I can{SINGLE_QUOTE}t sell it to you!{NL}You don{SINGLE_QUOTE}t have enough Rupees!{NL}Come back when you{SINGLE_QUOTE}ve got the money!{NL}My potions are always waiting!{NL}Hehehehe!{END}"


text_2D0C__089DFDD4:
	.string "You {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}don{SINGLE_QUOTE}t have an empty bottle{SPECIAL_02_PAR_1}{END} that I{NL}can fill with medicine!{NL}Come back with an {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}empty bottle{SPECIAL_02_PAR_1}{END}!{NL}{END}"


text_2D0D__089DFE3B:
	.string "Heheheh... Just face the sleepy{NL}snoozer and press {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}...{NL}That{SINGLE_QUOTE}ll pop his eyes right open!{NL}POP!{END}"

