
text_3B00__089E96B0:
	.string "{END}"


text_3B01__089E96B1:
	.string "{END}"


text_3B02__089E96B2:
	.string "{END}"


text_3B03__089E96B3:
	.string "{END}"


text_3B04__089E96B4:
	.string "{END}"


text_3B05__089E96B5:
	.string "{END}"


text_3B06__089E96B6:
	.string "{END}"


text_3B07__089E96B7:
	.string "{END}"


text_3B08__089E96B8:
	.string "{END}"


text_3B09__089E96B9:
	.string "{END}"


text_3B0A__089E96BA:
	.string "{END}"


text_3B0B__089E96BB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_1A}Oh, hello there.{NL}{NL}I{SINGLE_QUOTE}m selling creamy, nutritious {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon{NL}Milk{SPECIAL_02_PAR_1}{END} for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees per {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle{SPECIAL_02_PAR_1}{END}.{NL}Would you like to buy some?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1};{BYTE_0D}Don{SINGLE_QUOTE}t buy{END}"


text_3B0C__089E974D:
	.string "Thanks!{NL}I{SINGLE_QUOTE}ll just fill your bottle now.{END}"


text_3B0D__089E9775:
	.string "Oh? Well, ask me anytime.{NL}I{SINGLE_QUOTE}m always right here!{END}"


text_3B0E__089E97A6:
	.string "Oh, I{SINGLE_QUOTE}m sorry. You don{SINGLE_QUOTE}t seem to have{NL}enough Rupees.{END}"


text_3B0F__089E97DB:
	.string "I{SINGLE_QUOTE}m sorry, you don{SINGLE_QUOTE}t seem to have{NL}an empty {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle{SPECIAL_02_PAR_1}{END}.{NL}Please come back when you have{NL}an empty {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle {SPECIAL_02_PAR_1}{END}for me.{END}"


text_3B10__089E984D:
	.string "How about another?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1};{BYTE_0D}No{END}"


text_3B11__089E986C:
	.string "Thanks so much! Remember, {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon{NL}Milk{SPECIAL_02_PAR_1}{END} is the best in all Hyrule!{END}"


text_3B12__089E98B2:
	.string "{END}"


text_3B13__089E98B3:
	.string "{END}"

