
text_4D00__089F79F4:
	.string "LEFT{SPECIAL_0F_PAR_1}{BYTE_1F}000{END}"


text_4D01__089F79FE:
	.string "What is all of this!?{NL}I{SINGLE_QUOTE}m busy, don{SINGLE_QUOTE}t you see that?{NL}Do not disturb my research! If you have{NL}no business, begone! You heard me!{END}"


text_4D02__089F7A7D:
	.string "What, huh?{NL}A book? From the library?{NL}Ah, yes...of course. I knew this{NL}day would come. Please, come in.{END}"


text_4D03__089F7AE4:
	.string "LEFT{SPECIAL_0F_PAR_1}{BYTE_1F}003{END}"


text_4D04__089F7AEE:
	.string "LEFT{SPECIAL_0F_PAR_1}{BYTE_1F}004{END}"


text_4D05__089F7AF8:
	.string "I am a researcher of Picori legend{NL}and lore. My name is {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Dr. Left{SPECIAL_02_PAR_1}{END}.{NL}You{SINGLE_QUOTE}re here about that book,{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Legend of the Picori{SPECIAL_02_PAR_1}{END}, aren{SINGLE_QUOTE}t you?{NL}Well, I hate to say this, but I haven{SINGLE_QUOTE}t{NL}seen it in several days.{NL}Perhaps a mischievous little mouse{NL}has taken it?{NL}Well, I{SINGLE_QUOTE}m sure it{SINGLE_QUOTE}s in this house{NL}somewhere. I just don{SINGLE_QUOTE}t know where.{NL}But I{SINGLE_QUOTE}m very busy right now, so why{NL}don{SINGLE_QUOTE}t you just look for it yourself?{END}"


text_4D06__089F7C82:
	.string "A book fell with a {DOUBLE_QUOTE}THUD!{DOUBLE_QUOTE} a little{NL}while ago.{NL}It gave me such a shock that{NL}my heart skipped a beat!{END}"


text_4D07__089F7CE7:
	.string "You found and returned the book for{NL}me, did you? I{SINGLE_QUOTE}m very grateful.{NL}Here, let me tell you something{NL}interesting as thanks.{NL}You see, the Minish did not always live{NL}in our world.{NL}No, they came through a secret portal{NL}many ages ago from their world to ours!{NL}But don{SINGLE_QUOTE}t tell anyone! It{SINGLE_QUOTE}s a valuable{NL}bit of knowledge that only I know!{NL}And I gleaned it only after hours of{NL}study from an incredibly old book.{END}"


text_4D08__089F7E78:
	.string "So you{SINGLE_QUOTE}ve come to hear more about the{NL}Minish, have you?{NL}Well, I can part with one more tidbit,{NL}I suppose... It could be useful.{NL}The portal linking us to the Minish{NL}world opens only once every 100 years.{NL}That means the Minish here now are{NL}descendants of those who came before.{NL}That{SINGLE_QUOTE}s right! Those Minish came here{NL}100 years ago, or even longer ago!{NL}Now that the portal is open this year,{NL}perhaps new Minish will come through...{END}"


text_4D09__089F8023:
	.string "The more I study the Minish, the closer{NL}I feel to them!{NL}It{SINGLE_QUOTE}s almost as if they were right{NL}here with me, all the time...{END}"


text_4D0A__089F809B:
	.string "I never leave my house, whether there{NL}are monsters outside or not!{END}"


text_4D0B__089F80DE:
	.string "Hey, do you know the clues that reveal{NL}the location of the treasure?{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Cross the bridge that spans{NL}the rapid flow...{NL}Through the land of{NL}the fearsome beast...{NL}Until you reach{NL}the misty falls...{NL}The treasure sleeps on the other side{NL}of the secret entrance there...{SPECIAL_02_PAR_1}{END}{NL}They say it{SINGLE_QUOTE}s a magical tool that allows{NL}even little people to push big things!{NL}According to the legend, you{SINGLE_QUOTE}re{NL}supposed to start from this house!{END}"


text_4D0C__089F827B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Ahh... What should I do? Should I stay{NL}or go? If I go, there could be...{NL}...What{SINGLE_QUOTE}s that?{NL}{NL}You{SINGLE_QUOTE}ve already found the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bracelet {SPECIAL_02_PAR_1}{END}that{NL}makes one strong?!{NL}Ahhh, I knew it! I{SINGLE_QUOTE}d been stumped on{NL}that for so long! I knew I{SINGLE_QUOTE}d lose out!{END}"


text_4D0D__089F8362:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}You{SINGLE_QUOTE}re so brave!{NL}I really respect that!{END}"


text_4D0E__089F838D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Have you been using the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bracelet {SPECIAL_02_PAR_1}{END}that{NL}makes you strong? Must come in handy!{END}"


text_4D0F__089F83E0:
	.string "Oh, look! You{SINGLE_QUOTE}ve found it! Could I ask{NL}you to return that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}book {SPECIAL_02_PAR_1}{END}for me, lad?{END}"

