
text_3D00__089E9F08:
	.string "{END}"


text_3D01__089E9F09:
	.string "Ho ho! Here we are! You{SINGLE_QUOTE}ve come to the{NL}fabulous {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Simon{SINGLE_QUOTE}s Simulations{SPECIAL_02_PAR_1}{END}!{NL}Would you like to hear about us?{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}{NL}{SPECIAL_02_PAR_1}{END} {SPECIAL_05_PAR_1}={SPECIAL_03_PAR_2}No, thanks    {SPECIAL_05_PAR_1}={SPECIAL_02_PAR_1}Yes, please{END}"


text_3D02__089E9F98:
	.string "Ho ho! Well certainly!{NL}Now how shall I put this...{NL}{DOUBLE_QUOTE}We offer you the chance to be{NL}the hero you dream of becoming!{DOUBLE_QUOTE}{NL}We allow you to fight grand monsters{NL}without any danger!{NL}This is our unique service!{NL}Now...{NL}I can{SINGLE_QUOTE}t say this too loudly, but...{NL}{NL}If you dispatch a monster skillfully{NL}enough, you might get {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}something nice{SPECIAL_02_PAR_1}{END}.{NL}Now, even though this is only a{NL}simulation...{NL}It is still not for the faint of heart!{NL}{NL}If you should die in this simulation,{NL}why then... Well, I don{SINGLE_QUOTE}t know!{NL}It{SINGLE_QUOTE}s never happened!!{NL}{NL}{SPECIAL_07_PAR_1}={SPECIAL_03_PAR_2}{END}It{SINGLE_QUOTE}s {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}10 Rupees for one try{SPECIAL_02_PAR_1}{END}! Interested?{NL} {SPECIAL_05_PAR_1}{BYTE_FF}I{SINGLE_QUOTE}ll do it!    {SPECIAL_05_PAR_1}={SPECIAL_04_PAR_2}No, thanks!{END}"


text_3D03__089EA193:
	.string "It{SINGLE_QUOTE}s {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}10 Rupees for one try{SPECIAL_02_PAR_1}{END}! Interested?{NL} {SPECIAL_05_PAR_1}{BYTE_FF}I{SINGLE_QUOTE}ll do it!    {SPECIAL_05_PAR_1}={SPECIAL_04_PAR_2}No, thanks!{END}"


text_3D04__089EA1E0:
	.string "I see. Well, then how about some{NL}pickles? They{SINGLE_QUOTE}re homemade!{END}"


text_3D05__089EA21C:
	.string "Ho hee ho...{NL}Huh? Hey!! Did I miscount or something?{NL}Nope! You just don{SINGLE_QUOTE}t have enough{NL}Rupees!{NL}You mean to tell me you don{SINGLE_QUOTE}t even{NL}have {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}10 {SPECIAL_02_PAR_1}{END}stinkin{SINGLE_QUOTE} {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Rupees{SPECIAL_02_PAR_1}{END}?{NL}No way! That{SINGLE_QUOTE}s hilarious!{END}"


text_3D06__089EA2D8:
	.string "I see... So you{SINGLE_QUOTE}re going then...{NL}Well, lemme get her fired up here...{NL}Now, you{SINGLE_QUOTE}re getting veeeery sleeepy...{NL}Sooo veery sleeeepy...{NL}Ho...{NL}Hee...{NL}Ho...{NL}{NL}Howza!!{END}"


text_3D07__089EA378:
	.string "How was it? Did you enjoy the ride?{NL}{NL}Please come back and try it{NL}again anytime!{NL}We{SINGLE_QUOTE}re always open! Selling dreams to{NL}John Q. Public! Yessir!{END}"


text_3D08__089EA405:
	.string "{END}"


text_3D09__089EA406:
	.string "{END}"


text_3D0A__089EA407:
	.string "{END}"


text_3D0B__089EA408:
	.string "{END}"


text_3D0C__089EA409:
	.string "{END}"


text_3D0D__089EA40A:
	.string "{END}"


text_3D0E__089EA40B:
	.string "{END}"


text_3D0F__089EA40C:
	.string "{END}"


text_3D10__089EA40D:
	.string "{END}"


text_3D11__089EA40E:
	.string "{END}"


text_3D12__089EA40F:
	.string "{END}"


text_3D13__089EA410:
	.string "I love my dad!{END}"


text_3D14__089EA41F:
	.string "{END}"


text_3D15__089EA420:
	.string "{END}"


text_3D16__089EA421:
	.string "{END}"


text_3D17__089EA422:
	.string "{END}"


text_3D18__089EA423:
	.string "{END}"


text_3D19__089EA424:
	.string "{END}"


text_3D1A__089EA425:
	.string "{END}"


text_3D1B__089EA426:
	.string "{END}"


text_3D1C__089EA427:
	.string "{END}"

