
text_4F00__089F959C:
	.string "We do our best to make this a nice,{NL}cozy place, where people can relax.{NL}My ideal cafe is a place where everyone{NL}can just let it all hang out. Ah, yeah.{END}"


text_4F01__089F9634:
	.string "My ideal cafe is a place where everyone{NL}can just let it all hang out. Ah, yeah.{END}"


text_4F02__089F9684:
	.string "We hear all sorts of interesting gossip{NL}in here. Stop by from time to time.{END}"


text_4F03__089F96D0:
	.string "Make yourself at home...{NL}Heehee...{END}"


text_4F04__089F96F3:
	.string "I am a laid-back, easygoing kind{NL}of guy. Not a care in the world.{NL}And that{SINGLE_QUOTE}s just the way I like it!{END}"


text_4F05__089F9758:
	.string "He who can enjoy a nice cup of{NL}steaming hot tea at his leisure...{NL}is truly master of his own time.{END}"


text_4F06__089F97BB:
	.string "Let me tell you something that{NL}might come in handy someday.{NL}You can move bookcases and stuff.{NL}Try to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}push and pull different things{SPECIAL_02_PAR_1}{END}...{NL}After all, you{SINGLE_QUOTE}re young! You should{NL}be trying all kinds of new things! Ha!{END}"


text_4F07__089F9891:
	.string "I{SINGLE_QUOTE}m one smart cookie!{END}"


text_4F08__089F98A7:
	.string "Cheers! Yaay! Cheers!{NL}Raise your milk for a toast!{NL}I wonder what I should have for{NL}dinner...{END}"


text_4F09__089F9904:
	.string "I wonder what I should have for{NL}dinner...{END}"


text_4F0A__089F992E:
	.string "Everyone{SINGLE_QUOTE}s so relaxed here.{NL}That{SINGLE_QUOTE}s a good thing.{NL}My ideal cafe is a place where everyone{NL}can just let it all hang out. Ah, yeah.{END}"


text_4F0B__089F99AF:
	.string "My ideal cafe is a place where everyone{NL}can just let it all hang out. Ah, yeah.{END}"


text_4F0C__089F99FF:
	.string "Welcoooooome!{NL}Nice to see you!{END}"


text_4F0D__089F9A1E:
	.string "Take a load off.{NL}Heehee...{END}"


text_4F0E__089F9A39:
	.string "This is my special time...{NL}{NL}Just me and my cuppa joe.{END}"


text_4F0F__089F9A6F:
	.string "Well, I don{SINGLE_QUOTE}t actually drink coffee...{END}"


text_4F10__089F9A96:
	.string "It seems the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}has commanded all of{NL}the guards to search for magic power.{NL}Folks say that this {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE} will{NL}grant any wish, but I don{SINGLE_QUOTE}t buy it...{END}"


text_4F11__089F9B38:
	.string "I know all kinds of stuff.{END}"


text_4F12__089F9B53:
	.string "Cheers! Yaay! Cheers!{NL}Raise your millk for a toast!{NL}Can{SINGLE_QUOTE}t we just have the same thing for{NL}dinner tonight that we had last night?{END}"


text_4F13__089F9BD4:
	.string "I wonder if we can{SINGLE_QUOTE}t just have the same{NL}thing for dinner we had last night...{END}"


text_4F14__089F9C22:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}This cafe is so busy. You can hear all{NL}sorts of stuff from all the people here.{END}"


text_4F15__089F9C75:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}It{SINGLE_QUOTE}s just right for people like us who{NL}thrive on the hustle and bustle, huh?{END}"


text_4F16__089F9CC5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}It{SINGLE_QUOTE}s hard not to get stepped on when{NL}there are so many people here.{END}"


text_4F17__089F9D0C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}And adults can{SINGLE_QUOTE}t even see us, right?{END}"


text_4F18__089F9D34:
	.string "Everyone{SINGLE_QUOTE}s so relaxed here.{NL}That{SINGLE_QUOTE}s a good thing.{NL}My ideal cafe is a place where everyone{NL}can relax, relax, and relax some more.{END}"


text_4F19__089F9DB4:
	.string "My ideal cafe is a place where everyone{NL}can relax, relax, and relax some more.{END}"


text_4F1A__089F9E03:
	.string "Hey there, sweety!{NL}Welcome!{END}"


text_4F1B__089F9E1F:
	.string "Just sit anywhere you like,{NL}heehee...{END}"


text_4F1C__089F9E45:
	.string "Talking only to oneself...{NL}{NL}is an exercise in eloquent silence.{END}"


text_4F1D__089F9E85:
	.string "I wonder if that makes any sense...{END}"


text_4F1E__089F9EA9:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}was always such a nice man,{NL}but lately, he{SINGLE_QUOTE}s been such a brute...{NL}I wonder what happened to him?{NL}Hohoho...{END}"


text_4F1F__089F9F21:
	.string "Maybe a monster crawled in his skin and{NL}is parading around as the real {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}!{NL}Hohohoho!{END}"


text_4F20__089F9F7C:
	.string "Cheers! Yaay! Cheers!{NL}Raise your milk for a toast!{NL}Would they even notice if I made the{NL}same thing for dinner tonight?{END}"


text_4F21__089F9FF3:
	.string "I wonder...{NL}{NL}Would they even notice if I made the{NL}same thing for dinner tonight?{END}"


text_4F22__089FA044:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Welcome back, honey!{NL}Good to see ya!{END}"


text_4F23__089FA06C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}The old lady in front of this house{NL}drinks nothing but milk.{END}"


text_4F24__089FA0AC:
	.string "Everyone{SINGLE_QUOTE}s so relaxed here.{NL}That{SINGLE_QUOTE}s a good thing.{NL}A place you don{SINGLE_QUOTE}t ever want to leave.{NL}That{SINGLE_QUOTE}s my idea of a good cafe.{END}"


text_4F25__089FA122:
	.string "A place you don{SINGLE_QUOTE}t ever want to leave.{NL}That{SINGLE_QUOTE}s my idea of a good cafe.{END}"


text_4F26__089FA167:
	.string "Welcome back, you!{NL}You{SINGLE_QUOTE}re my favorite customer!{END}"


text_4F27__089FA197:
	.string "So you{SINGLE_QUOTE}ve been good lately?{NL}Gooood, heehee...{END}"


text_4F28__089FA1C5:
	.string "You can tell all of your deepest{NL}secrets to a wall.{NL}The wall will never talk back.{END}"


text_4F29__089FA218:
	.string "But I{SINGLE_QUOTE}ve found if you talk to {SINGLE_QUOTE}em right,{NL}walls will give up all sorts of secrets!{END}"


text_4F2A__089FA26A:
	.string "You{SINGLE_QUOTE}re going to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Royal Valley{SPECIAL_02_PAR_1}{END}?{NL}I hear that place is haunted...{NL}But there{SINGLE_QUOTE}s a secret entrance that will{NL}get you there from {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Field{SPECIAL_02_PAR_1}{END}.{NL}I mean, that{SINGLE_QUOTE}s what I{SINGLE_QUOTE}ve heard.{END}"


text_4F2B__089FA31D:
	.string "That place is dark even in the daytime.{NL}{NL}And you know how ghosts love{NL}the dark! Hohohoho...{END}"


text_4F2C__089FA379:
	.string "Cheers! Yaay! Cheers!{NL}Raise your milk for a toast!{NL}Hey, I know... Why don{SINGLE_QUOTE}t we just have{NL}milk for dinner?{END}"


text_4F2D__089FA3E3:
	.string "Why can{SINGLE_QUOTE}t we just have{NL}milk for dinner?{END}"


text_4F2E__089FA40B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Oh, hey there...{NL}Good to see you.{END}"


text_4F2F__089FA430:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}We Minish all get along very well.{END}"


text_4F30__089FA456:
	.string "Everyone{SINGLE_QUOTE}s so relaxed here.{NL}That{SINGLE_QUOTE}s a good thing.{NL}A place where you{SINGLE_QUOTE}re so familiar that{NL}you don{SINGLE_QUOTE}t even have to order.{NL}That{SINGLE_QUOTE}s my idea of a good cafe.{END}"


text_4F31__089FA4EA:
	.string "A place where you{SINGLE_QUOTE}re so familiar that{NL}you don{SINGLE_QUOTE}t even have to order.{NL}That{SINGLE_QUOTE}s my idea of a good cafe.{END}"


text_4F32__089FA54D:
	.string "Howdy, hon.{NL}Glad to see you again.{END}"


text_4F33__089FA570:
	.string "Aren{SINGLE_QUOTE}t you looking manly now!{NL}Heehee...{END}"


text_4F34__089FA598:
	.string "Actually, there is a VERY GOOD reason{NL}I cannot stand...{NL}What would you do if I told you that?{END}"


text_4F35__089FA5F6:
	.string "What is truth?{NL}{NL}When we understand this, then we will{NL}conquer even time itself...{END}"


text_4F36__089FA648:
	.string "The{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1} source of the flow{SPECIAL_02_PAR_1}{END}? Well, that{SINGLE_QUOTE}s{NL}easy. It{SINGLE_QUOTE}s talking about water!{NL}The water flowing into {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}town {SPECIAL_02_PAR_1}{END}and into{NL}the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}lake {SPECIAL_02_PAR_1}{END}all comes from the same place.{NL}Hohohoh...{END}"


text_4F37__089FA6F1:
	.string "If you{SINGLE_QUOTE}re looking for the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}source of{NL}the flow{SPECIAL_02_PAR_1}{END}...{NL}Well, you{SINGLE_QUOTE}d better make sure you{SINGLE_QUOTE}re{NL}well equipped is all I{SINGLE_QUOTE}m sayin{SINGLE_QUOTE}! Hohoho!{END}"


text_4F38__089FA772:
	.string "Cheers! Yaay! Cheers!{NL}Raise your milk for a toast!{NL}I wonder...do we even need to eat{NL}dinner at all?{END}"


text_4F39__089FA7D6:
	.string "I wonder...do we even need to eat{NL}dinner at all?{END}"


text_4F3A__089FA807:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Welcome, sugar pie!{END}"


text_4F3B__089FA81E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}It{SINGLE_QUOTE}s so convenient to live in a human{NL}house as a Minish.{END}"


text_4F3C__089FA85A:
	.string "Everyone{SINGLE_QUOTE}s so relaxed here.{NL}That{SINGLE_QUOTE}s a good thing.{NL}A place where you can relax despite{NL}what{SINGLE_QUOTE}s going on outside.{NL}That{SINGLE_QUOTE}s my idea of a good cafe.{END}"


text_4F3D__089FA8E7:
	.string "A place where you can relax despite{NL}what{SINGLE_QUOTE}s going on outside.{NL}That{SINGLE_QUOTE}s my idea of a good cafe.{END}"


text_4F3E__089FA943:
	.string "Heeeey!{NL}Weeeelcome!{END}"


text_4F3F__089FA957:
	.string "You{SINGLE_QUOTE}re turning into a fine little man,{NL}aren{SINGLE_QUOTE}t you! Heehee...{END}"


text_4F40__089FA994:
	.string "Though I am nondescript, you notice me{NL}and talk to me.{NL}That makes me the prize, and you{NL}are the winner of that prize!{END}"


text_4F41__089FAA0A:
	.string "Someday, you will understand.{END}"


text_4F42__089FAA28:
	.string "I hear a guard who was looking for the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force {SPECIAL_02_PAR_1}{END}got thrown in the dungeon!{NL}Why, the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}is hardly worthy of being{NL}called {DOUBLE_QUOTE}noble{DOUBLE_QUOTE} anymore!{END}"


text_4F43__089FAABE:
	.string "But I should be careful, lest I be jailed{NL}myself just for criticizing the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}!{END}"


text_4F44__089FAB12:
	.string "Cheers! Yaay! Cheers!{NL}Raise your milk for a toast!{NL}It{SINGLE_QUOTE}s not like the world would come to an{NL}end if I didn{SINGLE_QUOTE}t make dinner, right?{END}"


text_4F45__089FAB92:
	.string "It{SINGLE_QUOTE}s not like the world would come to an{NL}end if I didn{SINGLE_QUOTE}t make dinner, right?{END}"


text_4F46__089FABDF:
	.string "Everyone{SINGLE_QUOTE}s so relaxed here.{NL}That{SINGLE_QUOTE}s a good thing.{NL}A place where you could happily let the{NL}world crumble around you.{NL}That{SINGLE_QUOTE}s my idea of a good cafe.{END}"


text_4F47__089FAC71:
	.string "A place where you could happily let the{NL}world crumble around you.{NL}That{SINGLE_QUOTE}s my idea of a good cafe.{END}"


text_4F48__089FACD2:
	.string "Hey there!{NL}Doin{SINGLE_QUOTE} well?{END}"


text_4F49__089FACE9:
	.string "We{SINGLE_QUOTE}re counting on you, young man!{NL}Heehee!{END}"


text_4F4A__089FAD13:
	.string "Everything with a beginning{NL}also has an end.{NL}To put it another way, all things move{NL}toward their end...{NL}Even from the moment they begin.{END}"


text_4F4B__089FAD9C:
	.string "The end is near.{NL}For me, as well as for you.{END}"


text_4F4C__089FADC9:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END} is covered in darkness.{NL}This is the end.{END}"


text_4F4D__089FAE04:
	.string "I never imagined something like this{NL}would happen in my lifetime.{NL}I wonder if the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori {SPECIAL_02_PAR_1}{END}will show up{NL}and help us once again...{END}"


text_4F4E__089FAE88:
	.string "Cheers! Yaay! Cheers!{NL}Raise your milk for a toast!{NL}I never knew that failing to make{NL}dinner would have such consequences!{END}"


text_4F4F__089FAF02:
	.string "I never knew that failing to make{NL}dinner would have such consequences!{END}"


text_4F50__089FAF49:
	.string "{END}"


text_4F51__089FAF4A:
	.string "Just try fusing {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone pieces{SPECIAL_02_PAR_1}{END} with{NL}lots of people.{NL}There are a lot of people out there{NL}looking for someone to fuse with.{END}"


text_4F52__089FAFC9:
	.string "You{SINGLE_QUOTE}d be surprised to find who--and{NL}what--you can {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones {SPECIAL_02_PAR_1}{END}with!{NL}Yeah, you{SINGLE_QUOTE}ve got a lot of fusing in{NL}your future, pal...{END}"


text_4F53__089FB04C:
	.string "I recommend visiting {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}places you{SINGLE_QUOTE}ve{NL}already been{SPECIAL_02_PAR_1}{END}.{NL}You may then be able to fuse Kinstone{NL}pieces in those places, you know?{END}"


text_4F54__089FB0C9:
	.string "You can get special items by fusing{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone pieces{SPECIAL_02_PAR_1}{END}!{NL}Don{SINGLE_QUOTE}t miss out on the opportunity!{END}"


text_4F55__089FB125:
	.string "There{SINGLE_QUOTE}s a {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}group of lovely young ladies{NL}{SPECIAL_02_PAR_1}{END}visiting Hyrule...{NL}Maybe I{SINGLE_QUOTE}ll get a chance to talk to them{NL}if I offer to fuse {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone pieces{SPECIAL_02_PAR_1}{END}. Heh.{END}"


text_4F56__089FB1B8:
	.string "I hear there{SINGLE_QUOTE}s a wall in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END}{NL}with a spot for a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone piece{SPECIAL_02_PAR_1}{END}.{NL}I{SINGLE_QUOTE}m sure you can find other places{NL}where you can place Kinstone pieces.{END}"


text_4F57__089FB250:
	.string "Do you know of the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Goron Cave{SPECIAL_02_PAR_1}{END}? It{SINGLE_QUOTE}s a{NL}tunnel that the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Gorons {SPECIAL_02_PAR_1}{END}are digging.{NL}And if you can get all the way to the{NL}cave{SINGLE_QUOTE}s end and place a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone{SPECIAL_02_PAR_1}{END}...{NL}Well, why don{SINGLE_QUOTE}t I just let you try it{NL}for yourself!{END}"


text_4F58__089FB323:
	.string "I hear you can fuse {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone pieces{SPECIAL_02_PAR_1}{END}{NL}with the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}ghost {SPECIAL_02_PAR_1}{END}in the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Royal Crypt{SPECIAL_02_PAR_1}{END}.{NL}Or at least so I hear. I{SINGLE_QUOTE}m too scared{NL}to find out for sure.{END}"


text_4F59__089FB3B2:
	.string "You can{SINGLE_QUOTE}t always just charge straight{NL}ahead to new places in life, you know.{NL}You need to go back to places you{SINGLE_QUOTE}ve{NL}already been and reflect on things.{NL}Who knows? That quiet reflection may{NL}give you a chance to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}!{END}"


text_4F5A__089FB496:
	.string "You know, fusing {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone pieces{SPECIAL_02_PAR_1}{END} can{NL}get you more than mere {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Rupees{SPECIAL_02_PAR_1}{END}...{NL}It can call new people to a place or{NL}even change the way the town looks.{NL}And all those things can lead{NL}to happiness as well, right?{END}"


text_4F5B__089FB568:
	.string "Are you enjoying fusing {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone{NL}pieces{SPECIAL_02_PAR_1}{END}?{NL}Fusing can bring happiness to you and{NL}your fusing buddy! That{SINGLE_QUOTE}s what I say!{END}"


text_4F5C__089FB5E1:
	.string "I wonder what happens if you fuse all{NL}of the Kinstones a person is holding...{END}"


text_4F5D__089FB62F:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END} has fallen to the{NL}darkness...{NL}I suppose this is no time to be fusing{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone pieces{SPECIAL_02_PAR_1}{END}, is it?{END}"


text_4F5E__089FB6A2:
	.string "Nonsense! Maybe we need it now more{NL}than ever before!{NL}Fusing {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstone pieces{SPECIAL_02_PAR_1}{END} can bring{NL}people happiness!{NL}This is the true motive for fusing, my{NL}friend! Not Rupees, but happiness!{END}"


text_4F5F__089FB759:
	.string "{END}"


text_4F60__089FB75A:
	.string "{END}"


text_4F61__089FB75B:
	.string "{END}"


text_4F62__089FB75C:
	.string "{END}"


text_4F63__089FB75D:
	.string "{END}"


text_4F64__089FB75E:
	.string "{END}"


text_4F65__089FB75F:
	.string "{END}"

