
text_1F00__089D7E1C:
	.string "{END}"


text_1F01__089D7E1D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Green clothes? And a mystical hat?!?{NL}{NL}Sir! Would you by chance be {SPECIAL_06_PAR_1}{END},{NL}the one who found the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END}?{NL}Surely you are! I have heard so many{NL}tales about you.{NL}I am {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Belari{SPECIAL_02_PAR_1}{END}, researcher of antiquities.{NL}I am also, well, a bit of an inventor.{NL}You know, you won{SINGLE_QUOTE}t be able to get{NL}back to town, due to all the debris...{NL}Here, I have something that might{NL}come in handy.{END}"


text_1F02__089D7F93:
	.string "Let me know if you find it useful.{END}"


text_1F03__089D7FB6:
	.string "So you like those {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs{SPECIAL_02_PAR_1}{END}, huh?{NL}I still have some, so here you go.{END}"


text_1F04__089D7FFB:
	.string "I don{SINGLE_QUOTE}t suppose you know where the{NL}hot springs are, do you?{NL}My current experiment requires{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}mineral-rich spring water{SPECIAL_02_PAR_1}{END}.{END}"


text_1F05__089D8075:
	.string "Eh? Did you bring me some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mt. Crenel {NL}Mineral Water{SPECIAL_02_PAR_1}{END}?{NL}Thank you! At last, I can complete my{NL}experiment! I must reward you!{END}"


text_1F06__089D80F3:
	.string "{END}"


text_1F07__089D80F4:
	.string "Well, back to my research.{END}"


text_1F08__089D810F:
	.string "Wouldn{SINGLE_QUOTE}t it be handy to have a bomb{NL}that blew up only when you wanted?{END}"


text_1F09__089D8156:
	.string "I{SINGLE_QUOTE}m sorry, but I already gave you all{NL}the bombs I have.{END}"


text_1F0A__089D818E:
	.string "You{SINGLE_QUOTE}ve brought a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{SPECIAL_02_PAR_1}{END}, haven{SINGLE_QUOTE}t{NL}you? Let{SINGLE_QUOTE}s see if we can {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse {SPECIAL_02_PAR_1}{END}ours.{END}"


text_1F0B__089D81DD:
	.string "Excellent! A perfect match! And I{NL}suspect this might result in an item!{END}"


text_1F0C__089D8225:
	.string "You know, we really ought to try{NL}fusing Kinstones sometime.{END}"


text_1F0D__089D8261:
	.string "{END}"


text_1F0E__089D8262:
	.string "At last, it{SINGLE_QUOTE}s complete! The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Remote{NL}Bomb{SPECIAL_02_PAR_1}{END}! It blows up whenever you want!{NL}If you ever need normal {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs {SPECIAL_02_PAR_1}{END}again,{NL}just trade me back for them. So...{NL}Want to trade for {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Remote Bombs{SPECIAL_02_PAR_1}{END}?{NL}   {SPECIAL_05_PAR_1}{BYTE_FF}Sure   {SPECIAL_05_PAR_1}{BYTE_1F}{BYTE_10}No, thanks{END}"


text_1F0F__089D8338:
	.string "You traded for {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Remote Bombs{SPECIAL_02_PAR_1}{END}.{NL}{NL}Press the button to use a bomb, then{NL}press the button again to detonate it.{END}"


text_1F10__089D83A6:
	.string "If you ever need a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Remote Bomb{SPECIAL_02_PAR_1}{END}, just{NL}say the word.{END}"


text_1F11__089D83DD:
	.string "You want to use normal {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs {SPECIAL_02_PAR_1}{END}again?{NL}Just trade back those {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Remote Bombs{SPECIAL_02_PAR_1}{END}.{NL}Want to trade for normal {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs{SPECIAL_02_PAR_1}{END}?{NL}   {SPECIAL_05_PAR_1}{BYTE_FF}Sure   {SPECIAL_05_PAR_1}{BYTE_1F}{BYTE_13}Maybe later{END}"


text_1F12__089D846C:
	.string "You traded for normal {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs{SPECIAL_02_PAR_1}{END}!{NL}{NL}If you ever want to use {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Remote Bombs{SPECIAL_02_PAR_1}{END}{NL}again, just come see me.{END}"


text_1F13__089D84D0:
	.string "If you ever want to use normal {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs{SPECIAL_02_PAR_1}{END}{NL}again, just come see me.{END}"


text_1F14__089D8512:
	.string "Tell me if you want to swap for{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Remote Bombs{SPECIAL_02_PAR_1}{END}.{NL}I can trade with you if you like.{NL}   {SPECIAL_05_PAR_1}{BYTE_FF}Sure   {SPECIAL_05_PAR_1}{BYTE_1F}{BYTE_10}No, thanks{END}"


text_1F15__089D8580:
	.string "{END}"


text_1F16__089D8581:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E5}Hm... I{SINGLE_QUOTE}ve never seen an outfit like{NL}that before. Are you a...human?{NL}Oh, my! It{SINGLE_QUOTE}s been quite some time{NL}since any humans came here.{NL}My name is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Festari{SPECIAL_02_PAR_1}{END}. I watch the abbey,{NL}as well as the shrine to the north.{NL}You...seem to be having some trouble{NL}with our language, don{SINGLE_QUOTE}t you?{NL}You could use a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut{SPECIAL_02_PAR_1}{END}. It will{NL}allow you to understand our tongue.{NL}You should be able to find one in{NL}the barrel house just south of here.{END}"


text_1F17__089D872C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E5}You wish to go to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}shrine{SPECIAL_02_PAR_1}{END}?{NL}Very well. This way...{END}"


text_1F18__089D8768:
	.string "Vile beasts have settled in recently.{NL}Be careful: it is quite dangerous.{END}"


text_1F19__089D87B1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E5}You retrieved the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element {SPECIAL_02_PAR_1}{END}from{NL}that fiend-infested shrine?{NL}Incredible!{NL}{NL}Humans are amazing creatures.{NL}The elder is sure to be amazed, too.{END}"


text_1F1A__089D8849:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E5}So you{SINGLE_QUOTE}re on a quest to restore the{NL}sacred blade so you can save the{NL}princess? Yeah, I{SINGLE_QUOTE}m sure you{SINGLE_QUOTE}ll{NL}manage...{END}"


text_1F1B__089D88BB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E5}So you{SINGLE_QUOTE}ve eaten the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut{SPECIAL_02_PAR_1}{END},{NL}and now you can understand us?{NL}...{NL}{NL}{SPECIAL_07_PAR_1}{BYTE_1F}{BYTE_1C}{END}"


text_1F1C__089D890A:
	.string "Sorry, but I know little about {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}swords{SPECIAL_02_PAR_1}{END}.{NL}I{SINGLE_QUOTE}m sure the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elder{SPECIAL_02_PAR_1}{END} can help you.{END}"


text_1F1D__089D895A:
	.string "{END}"


text_1F1E__089D895B:
	.string "{END}"


text_1F1F__089D895C:
	.string "Oh, {SPECIAL_06_PAR_1}{END}.{NL}{NL}This must be the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut {SPECIAL_02_PAR_1}{END}Festari{NL}told you about.{NL}Well, you{SINGLE_QUOTE}d better eat it if you plan{NL}on making any progress at all.{END}"


text_1F20__089D89E2:
	.string "{END}"


text_1F21__089D89E3:
	.string "{END}"


text_1F22__089D89E4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Pico riki poko ti po!{END}"


text_1F23__089D89FD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}So you{SINGLE_QUOTE}ve eaten the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut{SPECIAL_02_PAR_1}{END} and{NL}now you can understand us...{NL}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elder {SPECIAL_02_PAR_1}{END}said that humans can no{NL}longer see us as they once could.{NL}It{SINGLE_QUOTE}s amazing that you can see us.{END}"


text_1F24__089D8AAE:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}This is where we cultivate {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Pico Blooms{SPECIAL_02_PAR_1}{END}.{NL}{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picolyte {SPECIAL_02_PAR_1}{END}sold in the human town is{NL}made from the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}nectar of our plants{SPECIAL_02_PAR_1}{END}.{NL}We sneak into town at night and leave{NL}it there for the humans to find.{END}"


text_1F25__089D8B78:
	.string "South of here, there{SINGLE_QUOTE}s a house{NL}shaped like a barrel.{NL}Inside, you will find a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut{SPECIAL_02_PAR_1}{END}.{NL}{NL}If you eat this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut{SPECIAL_02_PAR_1}{END}, you will be{NL}able to understand the Minish tongue.{END}"


text_1F26__089D8C28:
	.string "{END}"


text_1F27__089D8C29:
	.string "{END}"


text_1F28__089D8C2A:
	.string "{END}"


text_1F29__089D8C2B:
	.string "{END}"


text_1F2A__089D8C2C:
	.string "{END}"


text_1F2B__089D8C2D:
	.string "{END}"


text_1F2C__089D8C2E:
	.string "{END}"


text_1F2D__089D8C2F:
	.string "{END}"


text_1F2E__089D8C30:
	.string "{END}"


text_1F2F__089D8C31:
	.string "{END}"


text_1F30__089D8C32:
	.string "{END}"


text_1F31__089D8C33:
	.string "{END}"


text_1F32__089D8C34:
	.string "We sneak our {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Pico Blooms{SPECIAL_02_PAR_1}{END} to areas{NL}near where the humans live.{NL}Just having some of it makes{NL}you incredibly lucky.{NL}We{SINGLE_QUOTE}re preparing for our next delivery{NL}right now.{END}"


text_1F33__089D8CDA:
	.string "{END}"


text_1F34__089D8CDB:
	.string "{END}"


text_1F35__089D8CDC:
	.string "{END}"


text_1F36__089D8CDD:
	.string "{END}"


text_1F37__089D8CDE:
	.string "{END}"


text_1F38__089D8CDF:
	.string "{END}"


text_1F39__089D8CE0:
	.string "{END}"


text_1F3A__089D8CE1:
	.string "{END}"


text_1F3B__089D8CE2:
	.string "{END}"


text_1F3C__089D8CE3:
	.string "{END}"

