
text_4B00__089F6588:
	.string "{END}"


text_4B01__089F6589:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F7}What a nice smell...{END}"


text_4B02__089F65A1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}I like those red hats the Forest Minish{NL}wear...{END}"


text_4B03__089F65D4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}I like these blue hats the Town{NL}Minish wear...{END}"


text_4B04__089F6606:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Forest Minish{SPECIAL_02_PAR_1}{END}{NL}have come for a visit.{END}"


text_4B05__089F6636:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}I knew the city life would be exciting!{END}"


text_4B06__089F6661:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Everyone here is so refined...{END}"


text_4B07__089F6683:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}I get hungry just from that smell!{END}"


text_4B08__089F66A9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}I want a red hat...{END}"


text_4B09__089F66C0:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}I want a blue hat...{END}"


text_4B0A__089F66D8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Our reunion with the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Forest Minish{SPECIAL_02_PAR_1}{END} is{NL}still in full swing!{END}"


text_4B0B__089F671A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}We{SINGLE_QUOTE}re getting more refined just{NL}BEING here!{END}"


text_4B0C__089F6749:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Maybe I should just stay here and{NL}never go back home...{END}"


text_4B0D__089F6784:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}What a wonderful smell...{END}"


text_4B0E__089F67A1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}We just love bread...{END}"


text_4B0F__089F67BA:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Sometimes I sneak off with a little{NL}nibble of leftover bread.{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4B10__089F67FD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}The bread {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Wheaton {SPECIAL_02_PAR_1}{END}makes has got{NL}to be the best bread in Hyrule!{END}"


text_4B11__089F6844:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Isn{SINGLE_QUOTE}t {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Pita {SPECIAL_02_PAR_1}{END}cute?{END}"


text_4B12__089F685C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Every one of their breads is{NL}so delicious!{END}"


text_4B13__089F688A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}Those two newlyweds are being more{NL}fresh than this fresh-baked bread!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4B14__089F68D5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}It{SINGLE_QUOTE}s such a thrill coming up here from{NL}below, just like PSHOOOO!{END}"


text_4B15__089F6919:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Fewer and fewer people are coming{NL}to buy bread...{END}"


text_4B16__089F694E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}I can{SINGLE_QUOTE}t believe how dangerous{NL}it{SINGLE_QUOTE}s gotten around here...{END}"


text_4B17__089F698A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Now more than ever, we all need to get{NL}some good-luck bread!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4B18__089F69CC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}I like eating leftovers, but I just wish{NL}business were going better for them...{END}"


text_4B19__089F6A1F:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HARI{SPECIAL_0F_PAR_1}{BYTE_1F}025{END}"


text_4B1A__089F6A31:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HARI{SPECIAL_0F_PAR_1}{BYTE_1F}026{END}"


text_4B1B__089F6A43:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HARI{SPECIAL_0F_PAR_1}{BYTE_1F}027{END}"


text_4B1C__089F6A55:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HARI{SPECIAL_0F_PAR_1}{BYTE_1F}028{END}"


text_4B1D__089F6A67:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HARI{SPECIAL_0F_PAR_1}{BYTE_1F}029{END}"


text_4B1E__089F6A79:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HARI{SPECIAL_0F_PAR_1}{BYTE_1F}030{END}"


text_4B1F__089F6A8B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Hmmm! I see! Oh, that makes sense!{NL}...Human books are so interesting!{NL}And that guy {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Dr. Left{SPECIAL_02_PAR_1}{END} living down there{NL}has great taste in reading material!{END}"


text_4B20__089F6B25:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}I{SINGLE_QUOTE}m almost done with this book. I should{NL}go nab another of the doctor{SINGLE_QUOTE}s books.{END}"


text_4B21__089F6B77:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}I would love to read something a little{NL}more romantic next...{END}"


text_4B22__089F6BB8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Ho! Ha! Hey!!{NL}{NL}Phew... I want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}return this book by{NL}dropping it down below{SPECIAL_02_PAR_1}{END}.{NL}It{SINGLE_QUOTE}s impossible without some{NL}extra weight here...{NL}But my brother is so busy with a book{NL}of his own that he won{SINGLE_QUOTE}t help me out!{NL}Maybe I can do it if I try again...{END}"


text_4B23__089F6CAE:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}I think my brother is going to finish{NL}that book he{SINGLE_QUOTE}s reading soon.{NL}I bet I{SINGLE_QUOTE}ll have to return that one, too.{NL}Guess I{SINGLE_QUOTE}d better put on a little weight!{END}"


text_4B24__089F6D46:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}My brother loves reading books!{NL}{NL}And I love pushing my brother{SINGLE_QUOTE}s books{NL}off the rafters to return them!{END}"


text_4B25__089F6DB0:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}It{SINGLE_QUOTE}s a bit dusty up here, huh?{NL}Maybe I should do a little cleaning...{END}"


text_4B26__089F6DF9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Thanks for cleaning up!{NL}Now, all that dust is gone!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4B27__089F6E32:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HARI{SPECIAL_0F_PAR_1}{BYTE_1F}039{END}"


text_4B28__089F6E44:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HARI{SPECIAL_0F_PAR_1}{BYTE_1F}040{END}"

