
text_1400__089D4490:
	.string "{END}"


text_1401__089D4491:
	.string "Wh-wh-what?!?{END}"


text_1402__089D449F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0E}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}...   ...   {NL}{NL}O young one...{NL}{NL}Child who seeks to aid{NL}the princess of Hyrule...{NL}My name is Gustaf...{NL}{NL}I was king of Hyrule, countless{NL}ages ago.{NL}Stand before me...{NL}{NL}Only then will the path open{NL}to you.{END}"


text_1403__089D456C:
	.string "Hmph! Was that...just a dream?{NL}He said he was a king of Hyrule.{NL}Wait! Look at your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}, {SPECIAL_06_PAR_1}{END}.{NL}There{SINGLE_QUOTE}s some kind of mark on it.{NL}Hm. I guess that means it wasn{SINGLE_QUOTE}t{NL}a dream!{NL}We should head there once we{SINGLE_QUOTE}ve{NL}infused your sword with that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}.{NL}To the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental sanctuary{SPECIAL_02_PAR_1}{END}!{END}"


text_1404__089D4681:
	.string "{END}"


text_1405__089D4682:
	.string "{END}"


text_1406__089D4683:
	.string "{END}"

