
text_4700__089F3904:
	.string "{END}"


text_4701__089F3905:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}If you want to get across the swamp,{NL}you need to be swift on your feet.{NL}You know, a friend of mine makes shoes{NL}in Hyrule{SINGLE_QUOTE}s shoe shop.{NL}I{SINGLE_QUOTE}m pretty sure he can make{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Pegasus Boots{SPECIAL_02_PAR_1}{END}...{END}"


text_4702__089F39BF:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Would you like to fuse{NL}Kinstones with me?{END}"


text_4703__089F39EC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}You don{SINGLE_QUOTE}t want to? You don{SINGLE_QUOTE}t{NL}even want to try?{END}"


text_4704__089F3A1E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}We did it! They fit perfectly! You know{NL}what that means? Good luck for us!{END}"


text_4705__089F3A6C:
	.string "{END}"


text_4706__089F3A6D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F7}I found some amazingly rare {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{SPECIAL_02_PAR_1}{END}{NL}pieces! At least, I think they{SINGLE_QUOTE}re rare!{END}"


text_4707__089F3AC1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Oh?! You want to fuse pieces? Yay!{END}"


text_4708__089F3AE7:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}You don{SINGLE_QUOTE}t want to try?{END}"


text_4709__089F3B01:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}Look at that! A perfect match!{NL}I can{SINGLE_QUOTE}t wait to see what happens!{END}"


text_470A__089F3B45:
	.string "{END}"


text_470B__089F3B46:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}Hmmm... I found a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone {SPECIAL_02_PAR_1}{END}piece over{NL}there.{NL}I{SINGLE_QUOTE}ve never seen anything like it.{NL}It must be a really rare one...{END}"


text_470C__089F3BBC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}You want to fuse pieces? Do you think{NL}you have one that matches mine?{END}"


text_470D__089F3C05:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Mmmm... I guess it{SINGLE_QUOTE}s hard to find{NL}a match for such a rare piece...{END}"


text_470E__089F3C4B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Hmm! It fits perfectly!{NL}{NL}How could you have a piece that fits{NL}my ultra-rare one so well!?{END}"


text_470F__089F3CA8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}I think this is a really{NL}rare {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}!{END}"


text_4710__089F3CDD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}Hey, look at this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}!{NL}Have you ever seen one like this?{NL}What? You don{SINGLE_QUOTE}t know what a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{NL}piece{SPECIAL_02_PAR_1}{END} is? Well, tell you what...{NL}Why don{SINGLE_QUOTE}t you come back and see me{NL}when you get one, OK?{END}"


text_4711__089F3DAB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}What{SINGLE_QUOTE}s that? You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse{NL}Kinstone pieces{SPECIAL_02_PAR_1}{END} with me?{END}"


text_4712__089F3DE9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}I guess it{SINGLE_QUOTE}s hard to find{NL}a match for such a rare piece...{END}"


text_4713__089F3E27:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}Whaa! It fits! You must have had{NL}a really rare piece, too!{END}"


text_4714__089F3E65:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}What? You don{SINGLE_QUOTE}t know what a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{NL}piece{SPECIAL_02_PAR_1}{END} is? Well, tell you what...{NL}Why don{SINGLE_QUOTE}t you come back and see me{NL}when you get one, OK?{END}"


text_4715__089F3EEB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}A visitor! How rare... I don{SINGLE_QUOTE}t have much{NL}to offer, but you{SINGLE_QUOTE}re welcome to stay.{END}"


text_4716__089F3F3D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}What{SINGLE_QUOTE}s that? You want to fuse{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces {SPECIAL_02_PAR_1}{END}with me? Sure.{END}"


text_4717__089F3F81:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}You{SINGLE_QUOTE}re quitting?{END}"


text_4718__089F3F95:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}We did it! They fit perfectly!{NL}Maybe I{SINGLE_QUOTE}ll get some luck finally!{END}"


text_4719__089F3FD9:
	.string "{END}"


text_471A__089F3FDA:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}You moved the rock for me? Great!{NL}I thought I{SINGLE_QUOTE}d never get outside!{END}"


text_471B__089F4020:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}Oh, you want to fuse with me?{NL}Now let{SINGLE_QUOTE}s see here...{END}"


text_471C__089F4057:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}I guess it{SINGLE_QUOTE}ll be a while before I find{NL}a piece that fits this one...{END}"


text_471D__089F409F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}Look! They fit!{NL}How lucky! Amazing, even!{END}"


text_471E__089F40CC:
	.string "{END}"


text_471F__089F40CD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}What{SINGLE_QUOTE}s your problem?{NL}{NL}Mmmm! You{SINGLE_QUOTE}re staring at my amazingly{NL}rare {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}, aren{SINGLE_QUOTE}t you?!{END}"


text_4720__089F4131:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}How dare you! You want to fuse{NL}my precious {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}?!{END}"


text_4721__089F4174:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Phew... Sweet little {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}.{NL}It{SINGLE_QUOTE}s OK. No one{SINGLE_QUOTE}s gonna hurt you...{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4722__089F41C6:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Ahh... They fit...{NL}My poor little {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}...{END}"


text_4723__089F4201:
	.string "{END}"


text_4724__089F4202:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Hey! Your clothes... You must be{NL}human! Oh, I just LOVE human fashion!{NL}I just can{SINGLE_QUOTE}t help feeling that humans{NL}are more sophisticated than {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END}.{NL}You know, I even think some other{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}feel that way, too...{END}"


text_4725__089F42DD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Water is life for {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Crenel Beans{SPECIAL_02_PAR_1}{END}!{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{NL}{SPECIAL_02_PAR_1}{END}The blue beans grow when you pour{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}water {SPECIAL_02_PAR_1}{END}on them...{NL}But the green beans like{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mt. Crenel Mineral Water{SPECIAL_02_PAR_1}{END}.{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mt. Crenel Mineral Water {SPECIAL_02_PAR_1}{END}can be found{NL}only in a spring here on {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}.{NL}Well, really, the spring is closer to{NL}the base of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}.{END}"


text_4726__089F4412:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}These {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}soldier statues{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2} {SPECIAL_02_PAR_1}{END}here were built{NL}by the Minish ages ago to help humans.{NL}It{SINGLE_QUOTE}s kind of a secret, but there{SINGLE_QUOTE}s a{NL}switch inside that {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}turns them on or off{SPECIAL_02_PAR_1}{END}.{END}"


text_4727__089F44BA:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Go get the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}flippers {SPECIAL_02_PAR_1}{END}from the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{NL}elder {SPECIAL_02_PAR_1}{END}who lives in the library.{NL}They{SINGLE_QUOTE}ll make it so you can swim{NL}through the water with ease.{END}"


text_4728__089F4546:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}Can you solve my riddle?{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Splish, splash, the sound of water.{NL}He lives in the answer house.{SPECIAL_02_PAR_1}{END}{NL}I wonder if you{SINGLE_QUOTE}ll meet my friend?{END}"


text_4729__089F45CC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}A fearsome, unfriendly feline...{NL}The answer lives here!{SPECIAL_02_PAR_1}{END}{NL}You did well to come this far.{NL}Please take this.{END}"


text_472A__089F463C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Man, woman, or middle?{NL}He lives in the answer house.{SPECIAL_02_PAR_1}{END}{NL}I wonder if you{SINGLE_QUOTE}ll meet my friend?{END}"


text_472B__089F469B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}That meow is mighty!{NL}He lives in the answer house.{SPECIAL_02_PAR_1}{END}{NL}I wonder if you{SINGLE_QUOTE}ll meet my friend?{END}"


text_472C__089F46F8:
	.string "{END}"


text_472D__089F46F9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}I gave you my last {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}{NL}a while ago! But I{SINGLE_QUOTE}ll go look for more.{END}"

