
text_4000__089EC74C:
	.string "STAMP! STAMP!{NL}Right to left...{END}"


text_4001__089EC76B:
	.string "STAMP! STAMP!{NL}It never ends...{END}"


text_4002__089EC78A:
	.string "STAMP! STAMP!{NL}Even if we hire more people...{END}"


text_4003__089EC7B7:
	.string "STAMP! STAMP!{NL}It just doesn{SINGLE_QUOTE}t matter...{END}"


text_4004__089EC7DF:
	.string "Welcome!{NL}{NL}I{SINGLE_QUOTE}m selling issues of a helpful{NL}adventurer{SINGLE_QUOTE}s guide...{NL}It{SINGLE_QUOTE}s called the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Swordsman Newsletter{SPECIAL_02_PAR_1}{END}.{NL}It{SINGLE_QUOTE}s full of useful advice.{NL}Right now, you can buy the latest issue{NL}for only 200 Rupees! It{SINGLE_QUOTE}s a bargain!{NL}Would you like to buy an issue?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1}@{SPECIAL_06_PAR_1}No{END}"


text_4005__089EC8DE:
	.string "Very good! I{SINGLE_QUOTE}ll just collect{NL}your 200 Rupees...{END}"


text_4006__089EC90E:
	.string "Oh, really?{NL}{NL}Well, if you change your mind, come on{NL}back! It can only help you!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4007__089EC960:
	.string "Thanks for supporting local business!{NL}{NL}Remember, they come out as swift as a{NL}blade stroke, so check often!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4008__089EC9CD:
	.string "I{SINGLE_QUOTE}m sorry. You don{SINGLE_QUOTE}t have enough money{NL}to buy an issue.{END}"


text_4009__089ECA05:
	.string "Hello! We{SINGLE_QUOTE}ve got a new issue for you!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_400A__089ECA2D:
	.string "I{SINGLE_QUOTE}m sorry, your new issue of the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Swordsman Newsletter {SPECIAL_02_PAR_1}{END}is not in yet...{NL}Swiftblade said he would turn in a new{NL}issue to the publisher soon.{NL}He{SINGLE_QUOTE}s just waiting until he can pass{NL}another technique on to a student...{NL}So you can wait, right?{END}"


text_400B__089ECB1D:
	.string "You now have the full collection of{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Swordsman Newsletter{SPECIAL_02_PAR_1}{END}!!{NL}Well, I guess you must know all KINDS{NL}of stuff now, huh, {DOUBLE_QUOTE}Professor{DOUBLE_QUOTE}?{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_400C__089ECBA8:
	.string "I am the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}postman{SPECIAL_02_PAR_1}{END}, crossing town at{NL}incredible speed to bring you your mail!{END}"


text_400D__089ECBF8:
	.string "Faster than fast delivery! Swift and{NL}certain, that is the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}postman{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s aim!{END}"


text_400E__089ECC45:
	.string "Lightly, lightly, lightly...{NL}Lightly treads the carefree {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}postman{SPECIAL_02_PAR_1}{END}!!{END}"


text_400F__089ECC8C:
	.string "Dash, jump, delivery!!{NL}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}postman {SPECIAL_02_PAR_1}{END}cometh!{END}"


text_4010__089ECCBB:
	.string "Here before you know it, it{SINGLE_QUOTE}s your{NL}amazing neighborhood {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}postman{SPECIAL_02_PAR_1}{END}!{END}"


text_4011__089ECD00:
	.string "Known all through Hyrule for his charm{NL}and service, it{SINGLE_QUOTE}s your friendly {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}postman{SPECIAL_02_PAR_1}{END}!{END}"


text_4012__089ECD54:
	.string "Able to withstand the greatest{NL}of delivery challenges!{NL}I am the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}postman {SPECIAL_02_PAR_1}{END}of tomorrow,{NL}here today!{END}"

