
text_4100__089ECDD4:
	.string "Listen up, you! I{SINGLE_QUOTE}m a skilled carpenter,{NL}and I{SINGLE_QUOTE}m looking for a challenge!{END}"


text_4101__089ECE1E:
	.string "My ancestors built that castle, you{NL}know! Of course they did!{NL}After all, they are MY ancestors,{NL}aren{SINGLE_QUOTE}t they?{END}"


text_4102__089ECE8B:
	.string "Do you know of any refined work full of{NL}vim and vigor that might suit my taste?{NL}You know, something with a bit of punch{NL}to it! That{SINGLE_QUOTE}s what I{SINGLE_QUOTE}m after!{END}"


text_4103__089ECF21:
	.string "Do you know of any challenging work?{NL}Anything with pep? A real test of skill?{NL}You know, any work that{SINGLE_QUOTE}s got a bit of{NL}punch to it! That{SINGLE_QUOTE}s what I{SINGLE_QUOTE}m after!{END}"


text_4104__089ECFBA:
	.string "Guffaw! Well, that was a blast! And I{NL}guess it did have some punch to it!{NL}And I{SINGLE_QUOTE}ll wager I{SINGLE_QUOTE}m the only person who{NL}could have gotten it done that quickly!{END}"


text_4105__089ED053:
	.string "What{SINGLE_QUOTE}s that? I should stay indoors just{NL}because there are monsters about?{NL}Don{SINGLE_QUOTE}t be silly! I{SINGLE_QUOTE}ll go wherever there{NL}is work for me...work with punch!{NL}For I am PUNCH MUTOH!{END}"

