
text_0700__089B9AEC:
	.string "{END}"


text_0701__089B9AED:
	.string "You{SINGLE_QUOTE}ve finally fused all of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{NL}pieces{SPECIAL_02_PAR_1}{END}! Go speak to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Grandpa Smith{SPECIAL_02_PAR_1}{END}!{END}"


text_0702__089B9B41:
	.string "The two {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces {SPECIAL_02_PAR_1}{END}fit perfectly!{NL}Maybe something good will happen!{END}"


text_0703__089B9B8E:
	.string "{END}"


text_0704__089B9B8F:
	.string "{SPECIAL_04_PAR_2}{BYTE_13}Travel to this Wind Crest?{NL}{SPECIAL_04_PAR_2}{BYTE_13}{SPECIAL_05_PAR_1}{BYTE_FF}Yes     {SPECIAL_05_PAR_1}{BYTE_FF}No{BYTE_08}{BYTE_FF}{END}"


text_0705__089B9BBF:
	.string "{END}"


text_0706__089B9BC0:
	.string "{END}"


text_0707__089B9BC1:
	.string "{END}"


text_0708__089B9BC2:
	.string "{END}"


text_0709__089B9BC3:
	.string "{END}"


text_070A__089B9BC4:
	.string "{END}"


text_070B__089B9BC5:
	.string "Mt. Crenel{END}"


text_070C__089B9BD0:
	.string "Mt. Crenel{SINGLE_QUOTE}s Base{END}"


text_070D__089B9BE2:
	.string "Castor Wilds{END}"


text_070E__089B9BEF:
	.string "Wind Ruins{END}"


text_070F__089B9BFA:
	.string "Royal Valley{END}"


text_0710__089B9C07:
	.string "Trilby Highlands{END}"


text_0711__089B9C18:
	.string "Western Wood{END}"


text_0712__089B9C25:
	.string "Hyrule Castle Garden{END}"


text_0713__089B9C3A:
	.string "North Hyrule Field{END}"


text_0714__089B9C4D:
	.string "Hyrule Town{END}"


text_0715__089B9C59:
	.string "South Hyrule Field{END}"


text_0716__089B9C6C:
	.string "Veil Springs{END}"


text_0717__089B9C79:
	.string "Veil Falls{END}"


text_0718__089B9C84:
	.string "Lon Lon Ranch{END}"


text_0719__089B9C92:
	.string "Eastern Hills{END}"


text_071A__089B9CA0:
	.string "Cloud Tops{END}"


text_071B__089B9CAB:
	.string "Lake Hylia{END}"


text_071C__089B9CB6:
	.string "Minish Woods{END}"


text_071D__089B9CC3:
	.string "Elemental Sanctuary{END}"


text_071E__089B9CD7:
	.string "Minish Village{END}"


text_071F__089B9CE6:
	.string "Melari{SINGLE_QUOTE}s Mines{END}"


text_0720__089B9CF5:
	.string "Deepwood Shrine{END}"


text_0721__089B9D05:
	.string "Cave of Flames{END}"


text_0722__089B9D14:
	.string "Fortress of Winds{END}"


text_0723__089B9D26:
	.string "Temple of Droplets{END}"


text_0724__089B9D39:
	.string "Royal Crypt{END}"


text_0725__089B9D45:
	.string "Palace of Winds{END}"


text_0726__089B9D55:
	.string "Hyrule Castle{END}"


text_0727__089B9D63:
	.string "Dark Hyrule Castle{END}"


text_0728__089B9D76:
	.string "Biggoron{SINGLE_QUOTE}s Dungeon{END}"

