
text_3600__089E4E5C:
	.string "{NL}{END}"


text_3601__089E4E5E:
	.string "You{SINGLE_QUOTE}re always running around like{NL}you{SINGLE_QUOTE}ve got some urgent business.{NL}Why don{SINGLE_QUOTE}t you just sit{NL}a spell and relax?{END}"


text_3602__089E4ECB:
	.string "You{SINGLE_QUOTE}re getting pretty tough,{NL}aren{SINGLE_QUOTE}t you, kid?{NL}Bet you{SINGLE_QUOTE}re still no match{NL}for me, though...{END}"


text_3603__089E4F25:
	.string "Meooooow...{END}"


text_3604__089E4F31:
	.string "Rowrrr!{END}"


text_3605__089E4F39:
	.string "{END}"


text_3606__089E4F3A:
	.string "{END}"


text_3607__089E4F3B:
	.string "{END}"


text_3608__089E4F3C:
	.string "{END}"


text_3609__089E4F3D:
	.string "{END}"


text_360A__089E4F3E:
	.string "{END}"


text_360B__089E4F3F:
	.string "{END}"


text_360C__089E4F40:
	.string "{END}"


text_360D__089E4F41:
	.string "{END}"


text_360E__089E4F42:
	.string "{END}"


text_360F__089E4F43:
	.string "{END}"


text_3610__089E4F44:
	.string "{END}"


text_3611__089E4F45:
	.string "{END}"


text_3612__089E4F46:
	.string "Buggedy-buggedy-BOO!{NL}{NL}Did I scare ya?{END}"


text_3613__089E4F6C:
	.string "Sigh. I guess my heart{SINGLE_QUOTE}s just not in it.{NL}Maybe I{SINGLE_QUOTE}m not cut out for this...{END}"


text_3614__089E4FB7:
	.string "Arf! Arf arf!{END}"


text_3615__089E4FC5:
	.string "Haven{SINGLE_QUOTE}t you ever wondered why I{SINGLE_QUOTE}m{NL}always hanging out around here?{NL}Well, you see...{NL}{NL}I{SINGLE_QUOTE}ve been waiting to EAT you!{NL}{NL}Just kidding.{NL}Did I scare ya?{END}"


text_3616__089E5056:
	.string "I just can{SINGLE_QUOTE}t find that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}...{NL}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}is gonna be SO mad at me.{END}"


text_3617__089E50A7:
	.string "I don{SINGLE_QUOTE}t know... The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s mood{NL}just keeps getting worse and worse.{END}"


text_3618__089E50EF:
	.string "I haven{SINGLE_QUOTE}t seen {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda {SPECIAL_02_PAR_1}{END}in ages,{NL}and the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s just plain loopy!{NL}What{SINGLE_QUOTE}s going on around here?{END}"


text_3619__089E515C:
	.string "This stall is such a mess! Does that{NL}mean Beedle{SINGLE_QUOTE}s not going to show up?{END}"


text_361A__089E51A5:
	.string "Don{SINGLE_QUOTE}t they have anything other than{NL}fruits and vegetables here?{END}"


text_361B__089E51E5:
	.string "Hey, hey!{NL}Lookie, lookie!{END}"


text_361C__089E51FF:
	.string "Hurry up and buy something,{NL}or I smack you!{END}"


text_361D__089E522B:
	.string "Hey, hey! Cabbage and leeks, carrots{NL}and eggplant! Get {SINGLE_QUOTE}em all right here!{END}"


text_361E__089E5276:
	.string "Wha--? It{SINGLE_QUOTE}s so small you can{SINGLE_QUOTE}t{NL}understand? Hey hey!{END}"


text_361F__089E52AA:
	.string "What{SINGLE_QUOTE}s going on with the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}lately?{NL}He seems like...he{SINGLE_QUOTE}s not himself...{END}"


text_3620__089E52F8:
	.string "{END}"


text_3621__089E52F9:
	.string "That river sure is fishy!{NL}I mean suspicious...{NL}But I can{SINGLE_QUOTE}t quite figure out why...{END}"


text_3622__089E534C:
	.string "Hey, kid! Did you stay at the inn?{NL}Well? And did you get your gift?{END}"


text_3623__089E5390:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}hasn{SINGLE_QUOTE}t made any public{NL}appearances lately.{NL}And with so many guards surrounding{NL}the castle over the past few days...{NL}nobody in town has a clue what{SINGLE_QUOTE}s{NL}going on in there!{END}"


text_3624__089E5445:
	.string "We{SINGLE_QUOTE}re having a VERY important class{NL}right now, and I simply can{SINGLE_QUOTE}t let you in!{END}"


text_3625__089E5493:
	.string "We{SINGLE_QUOTE}re studying math right now, but once{NL}we{SINGLE_QUOTE}re done, that{SINGLE_QUOTE}s it for the day!{END}"


text_3626__089E54DE:
	.string "I{SINGLE_QUOTE}m starting to think I won{SINGLE_QUOTE}t find any{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force {SPECIAL_02_PAR_1}{END}near the castle.{END}"


text_3627__089E5526:
	.string "There{SINGLE_QUOTE}s an old legend that something{NL}big will happen when Hyrule{SINGLE_QUOTE}s bell rings.{END}"


text_3628__089E5575:
	.string "I{SINGLE_QUOTE}m too scared to ring it myself, so I{SINGLE_QUOTE}m{NL}hoping someone else will come along...{END}"


text_3629__089E55C5:
	.string "Gah! Why won{SINGLE_QUOTE}t someone hurry up and{NL}find that stupid {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}!?{END}"


text_362A__089E560C:
	.string "Figures that the search for that {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light{NL}force{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE} isn{SINGLE_QUOTE}t going too well...{NL}I mean, that stuff never existed{NL}in the first place!{NL}I{SINGLE_QUOTE}m just disappointed in the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}. He{NL}should have known better.{END}"


text_362B__089E56D0:
	.string "Figures that the search for that {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light{NL}force{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE} isn{SINGLE_QUOTE}t going too well...{NL}I mean, that stuff never existed{NL}in the first place!{NL}I{SINGLE_QUOTE}m just disappointed in the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}. He{NL}should have known better.{END}"


text_362C__089E5794:
	.string "Rrrrr...ARF ARF!{END}"


text_362D__089E57A5:
	.string "Arf arf arf!{END}"


text_362E__089E57B2:
	.string "Awooooo!{END}"


text_362F__089E57BB:
	.string "Nobody even bothered to ask why I was{NL}blocking the way for so long...{NL}The people here are so polite, but they{NL}lack backbone, you know what I mean?{END}"


text_3630__089E584E:
	.string "Maybe I can get this dog to go out and{NL}search for the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force {SPECIAL_02_PAR_1}{END}for me...{NL}Because I just can{SINGLE_QUOTE}t take it anymore!{END}"


text_3631__089E58C4:
	.string "People are getting really crazy{NL}about collecting those {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurines{SPECIAL_02_PAR_1}{END}...{NL}You probably don{SINGLE_QUOTE}t know much about{NL}that, though, do you?{END}"


text_3632__089E5945:
	.string "You know what? I don{SINGLE_QUOTE}t even feel like{NL}looking for that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force {SPECIAL_02_PAR_1}{END}anymore.{END}"


text_3633__089E5995:
	.string "Aww, gee. It looks like they{SINGLE_QUOTE}re having{NL}fun. I wish I could be in there...{END}"


text_3634__089E59DF:
	.string "I wanna play games, too!{END}"


text_3635__089E59F8:
	.string "It looks like the simulation arcade is{NL}open for business. Simon{SINGLE_QUOTE}s here now.{END}"


text_3636__089E5A44:
	.string "Nobody ever returns the books they{NL}check out from the library.{END}"


text_3637__089E5A83:
	.string "Don{SINGLE_QUOTE}t they realize that other people{NL}might want to read these books, too?{END}"


text_3638__089E5ACD:
	.string "I would love to have a figurine,{NL}too, but they{SINGLE_QUOTE}re too big for me...{END}"


text_3639__089E5B11:
	.string "I want to dive into the fountain!{NL}But I{SINGLE_QUOTE}m not such a good swimmer.{END}"


text_363A__089E5B54:
	.string "Ghosts are scary.{NL}He seems like a funny ghost,{NL}but ghosts are still scary.{NL}Aren{SINGLE_QUOTE}t they scary?{END}"


text_363B__089E5BB2:
	.string "Oooofff...{NL}Ahh, it{SINGLE_QUOTE}s no good.{NL}I just can{SINGLE_QUOTE}t get anywhere.{NL}Man oh man oh man...{END}"


text_363C__089E5C00:
	.string "!!!!?{NL}{NL}You made it?!{NL}No way!!{END}"


text_363D__089E5C1E:
	.string "Thanks for coming.{NL}{NL}Hardly anyone ever visits, and it gets{NL}lonely here. Please take this.{END}"


text_363E__089E5C78:
	.string "The view from here is nice.{NL}{NL}And Swiftblade{SINGLE_QUOTE}s screams during{NL}training seem to complement the scene.{END}"


text_363F__089E5CDC:
	.string "Good job getting up here.{NL}Really. That{SINGLE_QUOTE}s impressive.{NL}You must have really put yourself out{NL}to find a way here. Please take this.{END}"


text_3640__089E5D5D:
	.string "I wonder how I{SINGLE_QUOTE}m going to get down...{NL}Those cucco chicks just terrify me.{END}"


text_3641__089E5DA7:
	.string "Lately, Mutoh{SINGLE_QUOTE}s been grumbling about{NL}how there{SINGLE_QUOTE}s no work with any punch.{NL}I wish I could do something about that,{NL}but I don{SINGLE_QUOTE}t even know what he means!{END}"


text_3642__089E5E3D:
	.string "I{SINGLE_QUOTE}m so glad the boss is back to his{NL}usual self.{NL}It just makes you grateful{NL}for the good times, you know?{END}"

