
text_1300__089D2BE4:
	.string "{END}"


text_1301__089D2BE5:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_07_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_9B}Interesting. You{SINGLE_QUOTE}re the last person{NL}I expected to find here.{NL}And just as I was wondering who could{NL}be behind this, I find my old master...{END}"


text_1302__089D2C76:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E7}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}!{END}"


text_1303__089D2C84:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E9}And, as always, you are dressed in...{NL}heh heh heh...the shabbiest of rags.{NL}My {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}curses{SPECIAL_02_PAR_1}{END} are not to be mocked. The{NL}one I cast on you is most powerful.{NL}No matter what power you wield, you{NL}will never break it.{END}"


text_1304__089D2D57:
	.string "You haven{SINGLE_QUOTE}t changed in the slightest.{NL}{NL}I should never have created that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}cap{SPECIAL_02_PAR_1}{END}.{NL}It only fueled your insane desires!{END}"


text_1305__089D2DCC:
	.string "Fool! A hat that grants the wishes of{NL}its wearer is a spectacular creation!{NL}Thanks to you, I have gone from being{NL}a meek, miniscule nothing to...{NL}the greatest sorcerer alive!{NL}{NL}You cannot stop me now, and{NL}I have you to thank for it!{NL}Accept this small gesture{NL}of gratitude from me.{END}"


text_1306__089D2EE4:
	.string "Wait! {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}, wait!!!{END}"


text_1307__089D2EFD:
	.string "{END}"


text_1308__089D2EFE:
	.string "{END}"


text_1309__089D2EFF:
	.string "{END}"


text_130A__089D2F00:
	.string "{END}"


text_130B__089D2F01:
	.string "{END}"


text_130C__089D2F02:
	.string "That foul {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}! What could he be{NL}scheming now?{NL}{SPECIAL_06_PAR_1}{END}... I feel I owe you an{NL}explanation of what has happened.{NL}You see, Vaati and I are both {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END}.{NL}{NL}I was once a famous sage and a{NL}renowned {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}craftsman.{NL}Vaati was only a boy when I took him{NL}on as my apprentice.{NL}But...he became enchanted by the{NL}wickedness in the hearts of men.{NL}One day, Vaati took a hat I made for{NL}the humans--my pride and joy.{NL}It granted the wishes of its wearer.{NL}He put it on without permission...{END}"


text_130D__089D30E2:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E7}{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_07_PAR_1}Oh! What a vile form you{SINGLE_QUOTE}ve taken!{END}"


text_130E__089D310B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_9B}Vile? I am a sorcerer now, and my{NL}power is beyond compare!{NL}No longer will I tire away as your{NL}apprentice!{NL}Now, all shall call ME master!{END}"


text_130F__089D3197:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_06_PAR_1}Why, Vaati? What are you plotting?{END}"


text_1310__089D31BD:
	.string "This year, on the day that comes but{NL}once a century, the portal opens.{NL}And when it does, I shall claim the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force {SPECIAL_02_PAR_1}{END}as my own.{NL}I will be transformed, perfect, and{NL}there will be none who can stop me...{END}"


text_1311__089D328D:
	.string "GAAAAAA!!!{END}"


text_1312__089D3298:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_07_PAR_1}Ah ha ha ha ha ha ha ha!{NL}{NL}Tell me, how does it feel,{NL}my {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}sorcerer{SINGLE_QUOTE}s curse{SPECIAL_02_PAR_1}{END}?{NL}Do you see, Ezlo? I am truly your{NL}master now, and you cannot stop me.{NL}And with that, I must be leaving.{END}"


text_1313__089D3351:
	.string "Wait! Wait, I tell you!{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}!!!{END}"


text_1314__089D3376:
	.string "You know the legends, of course. The{NL}gifts the Picori gave the humans...{NL}What you call the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picori Blade{SPECIAL_02_PAR_1}{END} was{NL}the first of those gifts. The second...{NL}Well, you call it {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}, but it is{NL}a source of limitless magical power.{NL}If {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati {SPECIAL_02_PAR_1}{END}were to get it now, it would{NL}be devastating.{NL}I came to the world of men hoping to{NL}stop Vaati, and I met you in the woods.{NL}But it seems we won{SINGLE_QUOTE}t be breaking{NL}the curse on me anytime soon.{NL}However, with the sacred blade, we can{NL}certainly restore {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}.{NL}I{SINGLE_QUOTE}m sorry. All that has happened has{NL}been due to my own pride. My folly.{NL}I must rely on you, on your power,{NL}until we{SINGLE_QUOTE}ve put an end to Vaati.{END}"


text_1315__089D3601:
	.string "Well, {SPECIAL_06_PAR_1}{END}, enough fairy tales!{NL}We must search for the next {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}!{END}"


text_1316__089D3648:
	.string "Vaati! What are you doing?{END}"


text_1317__089D3663:
	.string "{END}"


text_1318__089D3664:
	.string "Eh? What a strange feeling. I sensed{NL}something from the castle{SINGLE_QUOTE}s direction.{NL}Or...was it just me?{END}"


text_1319__089D36C5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A3}Hm? Who{SINGLE_QUOTE}s there?!?{NL}{NL}What? Vaati! How did you get in here!?{END}"


text_131A__089D3703:
	.string "Uhn... What are you doing?!?{END}"


text_131B__089D3720:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_9B}Ah ha ha ha ha ha ha ha ha!{SPECIAL_03_PAR_2}{END}{BYTE_A7}{END}"


text_131C__089D3742:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A9}It looks like you{SINGLE_QUOTE}re all here. Very well.{NL}The king of Hyrule has words for you.{END}"


text_131D__089D3795:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A3}You all know of the power the Picori{NL}gave to mankind, do you not?{NL}The golden {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END} of limitless{NL}magical power...{NL}I want it!!! It is somewhere here in{NL}Hyrule! Go now, and bring me this power!{END}"


text_131E__089D3861:
	.string "Waste no time! Go forth at once, and{NL}bring me the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}!{NL}Fling anyone who refuses into the{NL}dungeon! Him and his family, too!{NL}I will tolerate no disobedience!{NL}{NL}Now, search high and low throughout{NL}the lands of Hyrule!{END}"


text_131F__089D3943:
	.string "Hmm... Maybe it{SINGLE_QUOTE}s just the wind...{NL}But I hope nothing bad has happened.{NL}Anyway, we need to look for the next{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}.{NL}The map says it should be{NL}around here somewhere...{END}"


text_1320__089D39F0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AA}By the order of the king,{NL}none shall pass!!{NL}Now! Begone with you!!{END}"


text_1321__089D3A36:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AA}Hey, you!!{NL}{NL}None may enter!{END}"


text_1322__089D3A55:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AA}I have heard that this castle has{NL}a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}secret entrance{SPECIAL_02_PAR_1}{END}...{NL}If you ever have need of it, you should{NL}look for that {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}entrance {SPECIAL_02_PAR_1}{END}sometime...{END}"


text_1323__089D3AE2:
	.string "{END}"


text_1324__089D3AE3:
	.string "We are the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tribe of the Winds{SPECIAL_02_PAR_1}{END}.{NL}{NL}Long have we lived with the winds. We{NL}have mastered them. Now, we join them.{NL}Together, with the great winds at our{NL}backs, we head for the skies.{NL}Those who come seeking our power must{NL}play the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}notes{SPECIAL_02_PAR_1}{END} Zeffa teaches.{NL}May they lead you onward to{NL}the power that you seek.{END}"


text_1325__089D3C15:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}I do believe this is where the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tribe of the Winds{SPECIAL_02_PAR_1}{END} once lived.{NL}Hm... So they{SINGLE_QUOTE}ve left for the heavens,{NL}and taken their {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END} with them.{NL}It looks like the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Wind Element {SPECIAL_02_PAR_1}{END}is beyond{NL}our reach for the time being.{NL}We have no choice but to press on.{NL}Let{SINGLE_QUOTE}s get out of here.{END}"


text_1326__089D3D2D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A3}Oh! {SPECIAL_06_PAR_1}{END}! You have returned!{NL}And have you found the Picori?{NL}I see. And they want you to gather{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}four elements{SPECIAL_02_PAR_1}{END}?{NL}Well, it seems I must rely on you once{NL}more if we are to restore Zelda.{NL}Please, you must forge the{NL}sacred blade anew, and quickly!{NL}I am counting on you, {SPECIAL_06_PAR_1}{END}!{END}"


text_1327__089D3E41:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A9}Oh! {SPECIAL_06_PAR_1}{END}! Tell me, have you{NL}been taking care of yourself?{END}"


text_1328__089D3E7C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AA}What{SINGLE_QUOTE}s that, {SPECIAL_06_PAR_1}{END}? His Majesty{NL}is in the room in back.{END}"


text_1329__089D3EB4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A3}Oh! {SPECIAL_06_PAR_1}{END}? You have returned!{NL}Welcome. Did you gather the elements?{NL}What? A {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}sanctuary{SPECIAL_02_PAR_1}{END}, you say? Why, I{SINGLE_QUOTE}ve{NL}heard of no such thing in my castle!{END}"


text_132A__089D3F47:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A9}Hmmm... A {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}sanctuary{SPECIAL_02_PAR_1}{END}...{NL}{NL}You know, I do recall a story my{NL}grandmother once told me long ago.{NL}She said she saw a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}doorway{SPECIAL_02_PAR_1}{END} appear in{NL}the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}palace courtyard{SPECIAL_02_PAR_1}{END} as a child.{NL}If this door does indeed open only once{NL}a century, it may be open even now!{NL}As with the Picori themselves, the door{NL}is visible only to the eyes of a child.{NL}We might have walked past it recently{NL}and never even known it was there...{END}"


text_132B__089D40DF:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AA}A {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}sanctuary{SPECIAL_02_PAR_1}{END}? No, I think I{SINGLE_QUOTE}d have seen{NL}something like that in the castle...{END}"


text_132C__089D4132:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AA}A {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}sanctuary{SPECIAL_02_PAR_1}{END}? Hm... The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}minister{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s fairy{NL}tales mention a sanctuary, I think...{END}"


text_132D__089D418B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}, look!{NL}See how that doorway glows?{NL}Could that be the door that{NL}leads to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}sanctuary{SPECIAL_02_PAR_1}{END}?{NL}Nobody in the castle seems able{NL}to see it but you and me...{NL}Let{SINGLE_QUOTE}s go! Quickly!{END}"


text_132E__089D423B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A3}The doorway to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental{NL}sanctuary{SPECIAL_02_PAR_1}{END} is in the castle courtyard?{NL}All we adults see is just another{NL}ordinary wall... Incredible!{NL}Please, just gather the remaining two{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END} and repair the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred sword{SPECIAL_02_PAR_1}{END}.{NL}I{SINGLE_QUOTE}m counting on you, {SPECIAL_06_PAR_1}{END}.{NL}Never forget that.{END}"


text_132F__089D4344:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A9}Oh, ho! The doorway was indeed in the{NL}garden? My grandmother was right!{NL}Well, my family has always been known{NL}for its honesty above all else.{NL}But I still can{SINGLE_QUOTE}t understand...{NL}{NL}Why is it that children can see the{NL}Picori and the doorway, but I cannot?{END}"


text_1330__089D4440:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_07_PAR_1}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}! What are you doing there?{END}"

