
text_1C00__089D7030:
	.string "{END}"


text_1C01__089D7031:
	.string "Ah, we{SINGLE_QUOTE}ve got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END}!{NL}You must go tell the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elder{SPECIAL_02_PAR_1}{END} at once!{END}"


text_1C02__089D707E:
	.string "Oh, that was hot! It was so hot,{NL}I thought my fibers would catch fire!{NL}Ah, but it{SINGLE_QUOTE}s over now! I suppose we{NL}should go back and speak to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}.{END}"


text_1C03__089D7111:
	.string "The element was not here, but at least{NL}we now have a clue to its whereabouts.{NL}You must use the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Ocarina of Wind{SPECIAL_02_PAR_1}{END} to{NL}open a new path.{NL}Well, there{SINGLE_QUOTE}s no point in standing{NL}around! Go get that last element!{END}"


text_1C04__089D71DD:
	.string "Brrrrrrrrr... I almost froze my{NL}beak off in there!{END}"


text_1C05__089D7210:
	.string "At last, we{SINGLE_QUOTE}ve got all four elements!{NL}Let{SINGLE_QUOTE}s go revive the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END}!{END}"

