
text_3200__089E2360:
	.string "{END}"


text_3201__089E2361:
	.string "Oh, welcome back, {SPECIAL_06_PAR_1}{END}. My, but{NL}you{SINGLE_QUOTE}re looking so much stronger!{NL}If you get tired, just go ahead and{NL}take a nap upstairs in your room.{NL}I{SINGLE_QUOTE}m busy making swords for the{NL}guards to keep the monsters at bay.{NL}I wish I could do more, but for now,{NL}we need you to save {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}.{END}"


text_3202__089E2476:
	.string "Hey, {SPECIAL_06_PAR_1}{END}. Every time I see you,{NL}you seem more and more confident!{NL}Say, have you been to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Rem{SINGLE_QUOTE}s Shoe{NL}Shop{SPECIAL_02_PAR_1}{END}? His shoes really are the best.{NL}I{SINGLE_QUOTE}m sure they could help you on your{NL}quest. Why don{SINGLE_QUOTE}t you give him a visit?{END}"


text_3203__089E254D:
	.string "Hey, {SPECIAL_06_PAR_1}{END}. You{SINGLE_QUOTE}re looking so{NL}much tougher these days...{NL}Say, have you been to{NL}the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}library {SPECIAL_02_PAR_1}{END}yet?{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}{NL}{SPECIAL_02_PAR_1}{END}I{SINGLE_QUOTE}ve heard some kids say that they{SINGLE_QUOTE}ve{NL}seen Picori there...{NL}I thought maybe that would help{NL}you on this quest of yours.{END}"


text_3204__089E2629:
	.string "Welcome back, {SPECIAL_06_PAR_1}{END}. I feel like{NL}it{SINGLE_QUOTE}s been so long since you visited!{NL}Looks like you need to find{NL}just one more {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}. Say...{NL}Have you been to the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Royal Valley{SPECIAL_02_PAR_1}{END},{NL}west of Hyrule Castle?{NL}You used to be able to get there{NL}easily from {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Trilby Highlands{SPECIAL_02_PAR_1}{END}.{NL}Nowadays, however, you have to take{NL}a secret path to get there.{NL}I{SINGLE_QUOTE}m sure it was to the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}west of{NL}the northern part of Hyrule Field{SPECIAL_02_PAR_1}{END}...{END}"


text_3205__089E27B3:
	.string "Ah, I{SINGLE_QUOTE}m so glad you{SINGLE_QUOTE}ve come{NL}to see me, {SPECIAL_06_PAR_1}{END}.{NL}You look like you{SINGLE_QUOTE}ve been just{NL}about everywhere in Hyrule, huh?{NL}But say...{NL}Have you been to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Veil Falls{SPECIAL_02_PAR_1}{END}?{NL}I hear no one has ever found the{NL}source of water that feeds the falls.{NL}So if that{SINGLE_QUOTE}s where you{SINGLE_QUOTE}re going,{NL}promise me you{SINGLE_QUOTE}ll be careful!{END}"


text_3206__089E28D0:
	.string "I{SINGLE_QUOTE}m so glad you{SINGLE_QUOTE}re safe, {SPECIAL_06_PAR_1}{END}.{NL}{NL}I hear that terrible things are{NL}happening over at{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1} Hyrule Castle{SPECIAL_02_PAR_1}{END}.{NL}By the way...{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}{NL}{NL}{SPECIAL_02_PAR_1}{END}Have you been using all of the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}items {SPECIAL_02_PAR_1}{END}you{SINGLE_QUOTE}ve found so far?{NL}If you get stuck somewhere, you{SINGLE_QUOTE}ll{NL}need to try every trick you{SINGLE_QUOTE}ve got!{NL}Just try using everything in your{NL}inventory, OK? You{SINGLE_QUOTE}ll sort it out...{END}"


text_3207__089E2A12:
	.string "Hey, aren{SINGLE_QUOTE}t you tired?{NL}{NL}Do you want to take a rest?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}2{BYTE_08}No{END}"


text_3208__089E2A54:
	.string "What, you{SINGLE_QUOTE}re certain? Boy, kids these{NL}days sure are full of beans...{NL}I{SINGLE_QUOTE}m all tuckered out, and all I do is{NL}ride around on your head all day!{END}"


text_3209__089E2AE1:
	.string "Ohhhh, yeah!{NL}{NL}That was just what I needed to{NL}get back in the fight!{NL}Let{SINGLE_QUOTE}s go, {SPECIAL_06_PAR_1}{END}!{END}"


text_320A__089E2B33:
	.string "{END}"


text_320B__089E2B34:
	.string "{END}"

