
text_0000__089B1F28:
	.string "{END}"


text_0001__089B1F29:
	.string "{END}"


text_0002__089B1F2A:
	.string "{END}"


text_0003__089B1F2B:
	.string "{NL}The data in File {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} is corrupted.{END}"


text_0004__089B1F4E:
	.string "{NL}There are no empty save files.{NL}{END}"


text_0005__089B1F6F:
	.string "{NL}Copying...{NL}Do not touch the Game Pak{NL}or turn the power off.{NL}{END}"


text_0006__089B1FAD:
	.string "{NL}Unable to copy file.{NL}{END}"


text_0007__089B1FC4:
	.string "{NL}Erasing file...{NL}Do not touch the Game Pak{NL}or turn the power off.{END}"


text_0008__089B2006:
	.string "{NL}Saving file...{NL}Do not touch the Game Pak{NL}or turn the power off.{END}"


text_0009__089B2047:
	.string "{NL}Unable to save file.{NL}{END}"


text_000A__089B205E:
	.string "{END}"


text_000B__089B205F:
	.string "{NL}Saving...{NL}{NL}Do not touch the Game Pak{NL}or turn the power off.{NL}{END}"


text_000C__089B209D:
	.string "{NL}Save was not performed correctly.{NL}{END}"


text_000D__089B20C1:
	.string "Activate Sleep Mode?{NL}{NL}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Yes      {SPECIAL_06_PAR_1}{SPECIAL_02_PAR_1} No{NL}{NL}To exit Sleep Mode, press SELECT and{NL}the L and R Buttons simultaneously.{END}"


text_000E__089B2133:
	.string "{END}"


text_000F__089B2134:
	.string "{END}"


text_0010__089B2135:
	.string "{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Save{NL}{NL}{SPECIAL_06_PAR_1}{SPECIAL_02_PAR_1} Don{SINGLE_QUOTE}t Save{END}"


text_0011__089B214C:
	.string "{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Continue{NL}{NL}{SPECIAL_06_PAR_1}{SPECIAL_02_PAR_1} Quit{END}"


text_0012__089B2161:
	.string "{END}"


text_0013__089B2162:
	.string "{END}"


text_0014__089B2163:
	.string "{END}"


text_0015__089B2164:
	.string "{END}"

