
text_0C00__089C2FB0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What!? I haven{SINGLE_QUOTE}t even had time to{NL}settle in, and you{SINGLE_QUOTE}re bothering me?{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Deepwood Shrine{SPECIAL_02_PAR_1}{END} lies, obviously enough,{NL}deep in the heart of these woods!{NL}So says my superior intuitive sense.{NL}{SPECIAL_01_PAR_1}{SPECIAL_05_PAR_1}Now, get a move on!{END}"


text_0C01__089C3082:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}This place is dangerous...{NL}There are so many monsters.{NL}{SPECIAL_01_PAR_1}{SPECIAL_06_PAR_1}Kid! Be careful!{NL}{SPECIAL_01_PAR_1}{SPECIAL_05_PAR_1}You wouldn{SINGLE_QUOTE}t want to let them hurt me!{END}"


text_0C02__089C30F8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{DOUBLE_QUOTE}Check your surroundings to make{NL}sure there{SINGLE_QUOTE}s nothing hidden!{DOUBLE_QUOTE}{NL}That{SINGLE_QUOTE}s the cardinal rule of{NL}adventuring! {SPECIAL_01_PAR_1}{SPECIAL_07_PAR_1}So don{SINGLE_QUOTE}t you forget it!{END}"


text_0C03__089C317D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Sometimes, a way will open for you{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}when you are smaller{SPECIAL_02_PAR_1}{END}.{NL}You{SINGLE_QUOTE}ve got to try everything{NL}you can, my boy!{END}"


text_0C04__089C31EB:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}are exceptionally tiny!{NL}{NL}That means, when you{SINGLE_QUOTE}re their size,{NL}you can fit into some {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}pretty tiny spots{SPECIAL_02_PAR_1}{END}!{NL}That includes places you couldn{SINGLE_QUOTE}t{NL}go at your normal size.{NL}That{SINGLE_QUOTE}s a pretty good tip, huh?{END}"


text_0C05__089C32C0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hey, kid! Maybe now you{SINGLE_QUOTE}ll have a little{NL}respect for me, huh?{NL}That{SINGLE_QUOTE}s right! I can turn you tiny{NL}anytime you want!{NL}{SPECIAL_01_PAR_1}{NL}Well, that is, if there{SINGLE_QUOTE}s a stump{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1} or{NL}some other kind of {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}portal{SPECIAL_02_PAR_1}{END} nearby...{END}"


text_0C06__089C3386:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hm. We{SINGLE_QUOTE}re not going to get anywhere{NL}if the Minish can{SINGLE_QUOTE}t understand you{SPECIAL_01_PAR_1}{NL}...{END}"


text_0C07__089C33D5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}certainly do seem to be{NL}curious about the ways of humans...{END}"


text_0C08__089C3423:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{DOUBLE_QUOTE}Don{SINGLE_QUOTE}t ponder{SPECIAL_0F_PAR_1}{BYTE_16} wander!{DOUBLE_QUOTE}{NL}{NL}Don{SINGLE_QUOTE}t waste your time trying to{NL}think things through too quickly.{NL}Take your time! Look around {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{NL}Village{SPECIAL_02_PAR_1}{END} and see what you can see!{END}"


text_0C09__089C34CB:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}A strange nut that will allow us to{NL}understand the Minish language{SPECIAL_01_PAR_1}{NL}...{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jingle Nut{SPECIAL_02_PAR_1}{END}, did he say...?{NL}No, wait... That{SINGLE_QUOTE}s not it...{NL}Ah, I remember now! It was the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut{SPECIAL_02_PAR_1}{END}.{NL}That{SINGLE_QUOTE}s what it was... Come on, my boy!{NL}We{SINGLE_QUOTE}ve got to find the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut{SPECIAL_02_PAR_1}{END}!{END}"


text_0C0A__089C35D4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Jabber Nut{SPECIAL_02_PAR_1}{END} was, uhh...{NL}{NL}Yeah, the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish with{NL}glasses{SPECIAL_02_PAR_1}{END} said,{SPECIAL_01_PAR_1}{NL} um...{NL}Was his name Feltari?{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Anyway, we{SINGLE_QUOTE}re supposed to go south{NL}until we find a house {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}inside a barrel{SPECIAL_02_PAR_1}{END}.{END}"


text_0C0B__089C3692:
	.string "Once you{SINGLE_QUOTE}ve learned how to speak{NL}the Minish language,{NL}we{SINGLE_QUOTE}ll be able to ask about the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END}. {SPECIAL_03_PAR_2}{END}{BYTE_8D}Let{SINGLE_QUOTE}s get to it!{END}"


text_0C0C__089C370D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Well? What are you waiting for? You{NL}can understand their language, right?{NL}So stop wasting time and find out{NL}about that sacred blade!{END}"


text_0C0D__089C3795:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So only the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}can repair{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}, hm?{NL}Maybe we should find out what the{NL}other {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}know about that.{END}"


text_0C0E__089C3811:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}You{SINGLE_QUOTE}ve never actually seen the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}before, have you?{NL}Ah, well, they are mostly good{NL}folk. Yes{SPECIAL_01_PAR_1}{NL}...mostly...{END}"


text_0C0F__089C3887:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}If you have any hopes of reforging the{NL}sacred blade, do as the elder says.{NL}Go find the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END}!{END}"


text_0C10__089C38F4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}A Minish shrine filled with monsters?{NL}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}It sounds dangerous in there!{SPECIAL_01_PAR_1}{NL} We{SINGLE_QUOTE}d{NL}better be careful...{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}I mean, you{SINGLE_QUOTE}d better be careful!{END}"


text_0C11__089C397E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}What? Don{SINGLE_QUOTE}t tell me you{SINGLE_QUOTE}re lost!{NL}{NL}Listen, if you get lost, just {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}examine{NL}your surroundings{SPECIAL_02_PAR_1}{END} closely...{NL}I{SINGLE_QUOTE}m sure you can find some kind{NL}of clue nearby.{END}"


text_0C12__089C3A1A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}We got through that monster-filled{NL}shrine and found the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}Great work, kid! You{SINGLE_QUOTE}re doing a fine{NL}job! Thanks to my help, of course.{END}"


text_0C13__089C3AB3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}The Minish elder wanted us to speak{NL}with him once we found that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}.{NL}That{SINGLE_QUOTE}s where we ought to go.{END}"


text_0C14__089C3B20:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}{SPECIAL_01_PAR_1}{NL}We need to learn how to reforge{NL}the broken {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END}.{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}We{SINGLE_QUOTE}ll have to speak with the Minish{NL}elder {SPECIAL_02_PAR_1}{END}about that, won{SINGLE_QUOTE}t we?{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}Well? What are you waiting for!? Evil{NL}won{SINGLE_QUOTE}t go vanquishing itself, you know!{END}"


text_0C15__089C3BF8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}So we{SINGLE_QUOTE}re supposed to meet a Minish{NL}blacksmith named {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END} on {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mt. Crenel{SPECIAL_02_PAR_1}{END}?{NL}You know, maybe we should stop in at{NL}the town of Hyrule before leaving...{END}"


text_0C16__089C3C97:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What{SINGLE_QUOTE}s the matter? Are you lost?{NL}{NL}Just where do you think you{SINGLE_QUOTE}re{NL}taking us, anyway?{NL}Look at a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map {SPECIAL_02_PAR_1}{END}or something! Just{NL}press START to see it.{END}"


text_0C17__089C3D2A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Have you ever visited Hyrule before?{NL}{NL}What? You have?{NL}...What{SINGLE_QUOTE}s it like?{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}Not that I... I mean, I{SINGLE_QUOTE}ve seen it{NL}before! Of course I have!{NL}I{SINGLE_QUOTE}m very well traveled. I just wanted{NL}to see...what you thought of it!{END}"


text_0C18__089C3DFD:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END} is a forbidding and{NL}rocky place with many steep cliffs.{NL}It lies just west of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Town{SPECIAL_02_PAR_1}{END}.{NL}{NL}We ought to equip ourselves in town{NL}before risking the journey.{END}"


text_0C19__089C3EB0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Aww...{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}I guess the festival that was going on{NL}here in town has already ended.{NL}I really wanted to see that...{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}It must have looked quite different{NL}when the festival was going on, hm?{END}"


text_0C1A__089C3F73:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Look at all these shops! This is so{NL}different from {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Village{SPECIAL_02_PAR_1}{END}!{NL}I-I-I... I can{SINGLE_QUOTE}t decide where to{NL}go next!{NL}Come on, my boy! Let{SINGLE_QUOTE}s go shopping!{END}"


text_0C1B__089C400B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Oh, don{SINGLE_QUOTE}t tell me you{SINGLE_QUOTE}ve forgotten{NL}already! What is WRONG with you?{NL}The Minish elder told us to see {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}{NL}up on {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}.{NL}{SPECIAL_03_PAR_2}{END}{BYTE_90}But how do you suppose we{SINGLE_QUOTE}re going to{NL}climb that pile of rocks, anyway?{SPECIAL_01_PAR_1}{NL}{END}"


text_0C1C__089C40E2:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmmm...{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}If the mountain is anything like those{NL}woods, there will be monsters ahead.{NL}{SPECIAL_03_PAR_2}{END}{BYTE_90}I{SINGLE_QUOTE}m not really busting a seam to see{NL}this {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}, but...we have no choice.{SPECIAL_01_PAR_1}{NL}{END}"


text_0C1D__089C4192:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Oh, hey! I totally forgot!{NL}{NL}That sword technique you learned from{NL}the swordsman...{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Spin Attack{SPECIAL_02_PAR_1}{END}, that{SINGLE_QUOTE}s what it{SINGLE_QUOTE}s{NL}called, right? That is so incredible!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}Do you think you could teach{NL}it to me sometime?{NL}Hm?! Hey! Don{SINGLE_QUOTE}t give me that look!{NL}I can do anything that you can do!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}Just give me some arms, and I{SINGLE_QUOTE}ll{NL}show you what{SINGLE_QUOTE}s what!{END}"


text_0C1E__089C42E7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}A {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean{SPECIAL_02_PAR_1}{END} that {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}grows{SPECIAL_02_PAR_1}{END} when you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}pour water{NL}{SPECIAL_02_PAR_1}{END}on it{SPECIAL_01_PAR_1}{NL}...{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}I guess it was a good idea to buy that{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle{SPECIAL_02_PAR_1}{END} from the Deku Scrub after all!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}See, my boy? Listen to me,{NL}and you{SINGLE_QUOTE}ll go far!{END}"


text_0C1F__089C43AB:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Hrm... Where on {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel {SPECIAL_02_PAR_1}{END}is this{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari {SPECIAL_02_PAR_1}{END}the blacksmith, anyway?{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}Well, we know he{SINGLE_QUOTE}s Minish, so try{NL}to keep your eyes peeled!{END}"


text_0C20__089C4439:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hey, kid! What{SINGLE_QUOTE}s the matter?{NL}You don{SINGLE_QUOTE}t know which way to go?{NL}At times like these, try everything you{NL}can at spots that {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}seem like dead ends{SPECIAL_02_PAR_1}{END}!{NL}Sometimes, you can find a way hidden in{NL}the most unlikely of spots!{NL}...Um, sometimes.{END}"


text_0C21__089C4522:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmm... It seems there are {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}two types of{NL}bean{SPECIAL_02_PAR_1}{END} on Mount Crenel: blue and green.{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}If the color is different, I suppose how{NL}you treat each one is different, too.{END}"


text_0C22__089C45C9:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Remember, we have to find our way to{NL}the top of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}!{NL}Once we{SINGLE_QUOTE}re there, we{SINGLE_QUOTE}ll start looking{NL}for that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}.{END}"


text_0C23__089C4649:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Explain something to me, my boy...{NL}Why are we just wandering around?{NL}We{SINGLE_QUOTE}re supposed to be scaling {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount{NL}Crenel{SPECIAL_02_PAR_1}{END} and looking for {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}!{END}"


text_0C24__089C46DB:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Somewhere on {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}, there{SINGLE_QUOTE}s{NL}a Minish blacksmith named {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}!{NL}We have to find him!{END}"


text_0C25__089C4740:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}There are some strange creatures on{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}...{NL}Creatures I{SINGLE_QUOTE}ve never seen before, and{NL}your sword alone won{SINGLE_QUOTE}t beat them!{NL}Don{SINGLE_QUOTE}t give up hope, though! Try your{NL}other {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}items{SPECIAL_02_PAR_1}{END} on them!{NL}Well...you don{SINGLE_QUOTE}t need me to tell you{NL}how to do your job.{NL}Just deal with those monsters, and{NL}I{SINGLE_QUOTE}ll take care of everything else.{SPECIAL_01_PAR_1}{NL}{END}"


text_0C26__089C4882:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}What?{NL}You{SINGLE_QUOTE}re lost again, aren{SINGLE_QUOTE}t you?{NL}Have you bothered reading any of{NL}those {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}signs{SPECIAL_02_PAR_1}{END} we{SINGLE_QUOTE}ve been seeing?{NL}You really ought to study them. They{NL}might have some useful information!{NL}...Not that I{SINGLE_QUOTE}ve been reading them{NL}either...{END}"


text_0C27__089C4964:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hey! Hurry up and find that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END},{NL}so we can fix the sacred blade!{END}"


text_0C28__089C49AF:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Have you noticed something odd about{NL}the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mountain Minish{SPECIAL_02_PAR_1}{END}?{NL}They{SINGLE_QUOTE}re just a little different from{NL}the Forest Minish, aren{SINGLE_QUOTE}t they?{NL}There seem to be many kinds of Minish,{NL}just as there are many kinds of human.{NL}And...many kinds of hat, too.{NL}Mustn{SINGLE_QUOTE}t forget the hats.{END}"


text_0C29__089C4ABA:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}These Mountain {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}sure are{NL}hard workers!{NL}We should work just as hard and sing{NL}a spiffy little song, like they do!{NL}What do you think? Hey! Kid...?{NL}Are you still listening to me?{END}"


text_0C2A__089C4B76:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}This isn{SINGLE_QUOTE}t the time to idle about,{NL}you lazy boy!{NL}We have to go search for the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END}{NL}while Melari works on that sword!{END}"


text_0C2B__089C4BF6:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So humans made this mine long ago?{NL}{NL}Well it{SINGLE_QUOTE}s full of monsters now,{NL}kid, so watch your back!{END}"


text_0C2C__089C4C56:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Perhaps the humans who made this mine{NL}will have left some things we can use...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}After all, there{SINGLE_QUOTE}s no reason to let{NL}good wares go to waste.{END}"


text_0C2D__089C4CE8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}So we beat the fire monster and got{NL}the second {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}! Incredible!{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Kid, you may just be some kind of{NL}hero or something!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}I knew I sensed potential in you!{END}"


text_0C2E__089C4D91:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Oh, so I bet {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari {SPECIAL_02_PAR_1}{END}has finished with{NL}that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}. We should go pick it up!{END}"


text_0C2F__089C4DE7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}So how about that sword that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}{NL}fixed up for you, huh?{NL}I may be just a hat, but I can admire{NL}good craftsmanship!{END}"


text_0C30__089C4E63:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}We must find the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental sanctuary{SPECIAL_02_PAR_1}{END}{NL}to fill the sword with elemental power.{NL}I{SINGLE_QUOTE}d never have looked for the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental{NL}sanctuary{SPECIAL_02_PAR_1}{END} in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}, though!{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}You know how to get there, right?{NL}Let{SINGLE_QUOTE}s go!{END}"


text_0C31__089C4F3B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}So of the four {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END}, we{SINGLE_QUOTE}ve got{NL}Earth and Fire...{NL}And now, we have the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}White Sword{SPECIAL_02_PAR_1}{END}{NL}to absorb their power!{NL}That means the sacred blade{SINGLE_QUOTE}s power{NL}has almost been restored!{END}"


text_0C32__089C4FF1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Why do you look so confused? Don{SINGLE_QUOTE}t you{NL}understand what{SINGLE_QUOTE}s going on?{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental sanctuary {SPECIAL_02_PAR_1}{END}exists between{NL}the human world and the Minish world.{NL}Here, let me explain with a little{NL}example: in a ham sandwich...{NL}the elemental sanctuary would be the{NL}ham between the two slices of bread!{NL}...You{SINGLE_QUOTE}ve still got that look.{NL}Did I just make it more confusing?{END}"


text_0C33__089C5159:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}So! We must infuse the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}White Sword{SPECIAL_02_PAR_1}{END}{NL}with the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elemental power{SPECIAL_02_PAR_1}{END}.{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}That means we must find the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental sanctuary{SPECIAL_02_PAR_1}{END}.{NL}And the way we do that is... Um...{NL}Well, I{SINGLE_QUOTE}m sure we{SINGLE_QUOTE}ll figure it out!{END}"


text_0C34__089C5221:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}I think that you and I may be the only{NL}ones who can see the mystic doorway...{NL}Well, that{SINGLE_QUOTE}s fine by me. That means{NL}no one will notice anything unusual!{END}"


text_0C35__089C52BB:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}We just need to infuse the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END} with{NL}the power of these two {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END}.{NL}Then, the sacred blade will be{NL}nearly complete!{END}"


text_0C36__089C533D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Only two {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END} remain!{NL}{NL}They must be in the places marked on{NL}your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END} by the Minish elder!{NL}Why don{SINGLE_QUOTE}t we take another look at that{NL}map? If memory serves me correctly...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}There should be a mark out on the{NL}westernmost edge of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Castor Wilds{SPECIAL_02_PAR_1}{END}.{END}"


text_0C37__089C543F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}So the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END} has finally started{NL}to show us a portion of its power!{NL}If we use this new skill of yours well,{NL}we should be able to access new areas!{END}"


text_0C38__089C54E0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}If you{SINGLE_QUOTE}re after the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END}, just{NL}check your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END} by pressing START.{NL}I believe the elder of the Forest{NL}Minish marked the locations there.{END}"


text_0C39__089C5575:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hrm... According to the map, we{SINGLE_QUOTE}ll need{NL}to cross {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Castor Wilds{SPECIAL_02_PAR_1}{END}.{SPECIAL_01_PAR_1}{NL}{NL}That unexplored region is where we{NL}must go to find the next {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}!{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}{END}"


text_0C3A__089C5608:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}The swamp covering {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Castor Wilds{SPECIAL_02_PAR_1}{END} looks{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}impassable on foot{SPECIAL_02_PAR_1}{END}. What will we do!?{SPECIAL_01_PAR_1}{NL}{END}"


text_0C3B__089C5661:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}, how long has it been since{NL}you left home?{NL}Your grandfather must be worried.{NL}Why don{SINGLE_QUOTE}t you show your face at home?{NL}He must have plenty of news to share{NL}with you by now.{END}"


text_0C3C__089C5710:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Hnyaaaawn...{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Mmmmnumumummm...{NL}Even I{SINGLE_QUOTE}m getting tired now...{SPECIAL_01_PAR_1}{NL}{NL}I guess I need a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}wake-up mushroom{SPECIAL_02_PAR_1}{END}{NL}or something to perk me up!{END}"


text_0C3D__089C5798:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hoho! Well...{NL}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8E}The big lake spreading out to the west{NL}of Hyrule is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Lake Hylia{SPECIAL_02_PAR_1}{END}.{NL}The rich water that flows from it has{NL}fed the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END} for millennia.{NL}Every day, you learn something new,{NL}don{SINGLE_QUOTE}t you, {SPECIAL_06_PAR_1}{END}?{END}"


text_0C3E__089C5872:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Well, I say! There seem to be a lot of{NL}Minish living in town, too...{NL}Even if they can{SINGLE_QUOTE}t be seen, I{SINGLE_QUOTE}m sure the{NL}Minish make their presence known...{END}"


text_0C3F__089C5907:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}So, about that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}wake-up mushroom{SPECIAL_02_PAR_1}{END} you{NL}just bought... It kind of, um...smells.{NL}COUGH! COUGH!{NL}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_91}I suppose that awful stink could pull{NL}anyone from the deepest slumber!{END}"


text_0C40__089C59B3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Hey, {SPECIAL_06_PAR_1}{END}. I{SINGLE_QUOTE}ve been up here for{NL}a while, and I{SINGLE_QUOTE}ve been wondering...{NL}I know about hats now, but I don{SINGLE_QUOTE}t{NL}know much about Hyrulean shoes...{NL}Where could we go to learn a little{NL}more about that?{END}"


text_0C41__089C5A73:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So about that old lady in the woods{NL}named {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Syrup{SPECIAL_02_PAR_1}{END} or something...{NL}Didn{SINGLE_QUOTE}t she strike you as a little{NL}bit, well, strange?{NL}I{SINGLE_QUOTE}m confident that her {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}potions{SPECIAL_02_PAR_1}{END} work{NL}as advertised, though.{NL}She looks like someone who could whip{NL}up a mean magic brew...{END}"


text_0C42__089C5B6D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Once we cross {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Castor Wilds{SPECIAL_02_PAR_1}{END}, the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END} should be easy to find.{NL}If you forget where to go, just take{NL}a look at your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}.{END}"


text_0C43__089C5BF5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}When you{SINGLE_QUOTE}re crossing a swamp, you{NL}want to be as swift as the wind...{NL}There{SINGLE_QUOTE}s no point in stopping to look{NL}around. Sightseeing is right out!{NL}What I{SINGLE_QUOTE}m trying to say is that I don{SINGLE_QUOTE}t{NL}much relish the thought of a mud bath!{END}"


text_0C44__089C5CD2:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}That {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}one-eyed stone{SPECIAL_02_PAR_1}{END} statue in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Castor{NL}Wilds{SPECIAL_02_PAR_1}{END} looks like it{SINGLE_QUOTE}s staring at us!{NL}...That eye really creeps me out.{END}"


text_0C45__089C5D49:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Creepy {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}ruins{SPECIAL_02_PAR_1}{END} standing on the far side{NL}of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Castor Wilds{SPECIAL_02_PAR_1}{END}...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Maybe that{SINGLE_QUOTE}s where the ancient people{NL}who guarded the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END} used to live.{END}"


text_0C46__089C5DE1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}That {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element {SPECIAL_02_PAR_1}{END}is sure to be protected by{NL}traps inside those ancient ruins!{NL}{SPECIAL_06_PAR_1}{END}, be careful!{END}"


text_0C47__089C5E42:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Don{SINGLE_QUOTE}t just wander around aimlessly...{NL}That{SINGLE_QUOTE}s the quickest way to get lost!{NL}If you do get lost, look at your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}{NL}immediately to get your bearings.{NL}You will find your way only if you know{NL}where you are AND where you{SINGLE_QUOTE}re going.{END}"


text_0C48__089C5F29:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}The next {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END} is near {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Lake Hylia{SPECIAL_02_PAR_1}{END}.{NL}Now, how are we going to get there?{NL}I wonder who might be able to help{NL}us out with something like that...{END}"


text_0C49__089C5FC3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}All we have to do is use the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Ocarina of{NL}Wind{SPECIAL_02_PAR_1}{END} to call Zeffa!{NL}If we stand on a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Wind Crest{SPECIAL_02_PAR_1}{END} and call{NL}him, he{SINGLE_QUOTE}ll take us where we want to go!{END}"


text_0C4A__089C6057:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Well, now that we{SINGLE_QUOTE}ve got this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Ocarina{NL}of Wind{SPECIAL_02_PAR_1}{END}, shouldn{SINGLE_QUOTE}t we try to use it?{NL}Even places we{SINGLE_QUOTE}ve seen before may hold{NL}new surprises if we try flying there...{END}"


text_0C4B__089C60F8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Well, I{SINGLE_QUOTE}d never have suspected it of{NL}that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish elder{SPECIAL_02_PAR_1}{END} in the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}library{SPECIAL_02_PAR_1}{END}...{NL}To think he was an adventurer! And{NL}that he visited the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of Droplets{SPECIAL_02_PAR_1}{END}!{NL}Maybe we should look up that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END}{NL}and hear what he has to say.{END}"


text_0C4C__089C61E1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hm. Now, how did {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END} get into{NL}the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of Droplets{SPECIAL_02_PAR_1}{END}?{NL}I guess we{SINGLE_QUOTE}ll just have to go visit{NL}him at the library and ask.{END}"


text_0C4D__089C6266:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}So, where in the library would any{NL}Minish folk live, anyway?{NL}Maybe those people who say the Minish{NL}exist {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}only in stories{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE} might be right!{NL}Hey! {SPECIAL_06_PAR_1}{END}! What{SINGLE_QUOTE}s that look for?{NL}Don{SINGLE_QUOTE}t tell me you were one of...them?{NL}You{SINGLE_QUOTE}re kidding me! You{SINGLE_QUOTE}re wearing a{NL}Minish person on your head, you oaf!{NL}I certainly hope you believe in us now!{END}"


text_0C4E__089C63AE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}How did we get roped into running all{NL}over creation returning library books?{NL}I understand it{SINGLE_QUOTE}s all just to learn{NL}how to enter the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of Droplets{SPECIAL_02_PAR_1}{END},{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}but this is hardly the sort of duty{NL}worthy of a great adventurer!{END}"


text_0C4F__089C6490:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Minish people are very interested in{NL}human ways.{NL}I think they watch the people in{NL}town very closely.{NL}They{SINGLE_QUOTE}ve probably been watching you,{NL}too, without your knowing it.{NL}Hey, {SPECIAL_06_PAR_1}{END}, careful what you say{NL}and do when you think you{SINGLE_QUOTE}re alone!{END}"


text_0C50__089C657C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}So there are three books that we{SINGLE_QUOTE}re{NL}supposed to return, right?{NL}{SPECIAL_06_PAR_1}{END}, I{SINGLE_QUOTE}m sure you can handle it!{NL}Don{SINGLE_QUOTE}t get me wrong! I{SINGLE_QUOTE}d love to help!{NL}But I{SINGLE_QUOTE}m a great Minish sage! I don{SINGLE_QUOTE}t{NL}understand your big, human ways!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}So...I{SINGLE_QUOTE}m counting on you!{END}"


text_0C51__089C6667:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}This really is starting to take valuable{NL}time from our search for the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}But buck up, kiddo! We{SINGLE_QUOTE}re almost{NL}done, {SPECIAL_06_PAR_1}{END}!!!{END}"


text_0C52__089C66ED:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}I just can{SINGLE_QUOTE}t figure out how {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END}{NL}got into the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of Droplets{SPECIAL_02_PAR_1}{END}.{NL}I{SINGLE_QUOTE}m going crazy with curiosity!{END}"


text_0C53__089C675D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}You know, even these Minish living in{NL}the town still have their own troubles.{NL}I feel like I{SINGLE_QUOTE}ve learned a lot here.{END}"


text_0C54__089C67D3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of Droplets{SPECIAL_02_PAR_1}{END} holds the last of{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END}, like the Minish elder said.{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}So let{SINGLE_QUOTE}s brace ourselves and do this!{NL}Are you ready, {SPECIAL_06_PAR_1}{END}?!{NL}... ...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}What?! What{SINGLE_QUOTE}s that face for?{NL}You don{SINGLE_QUOTE}t want to brace yourself?! All{NL}right, fine! No bracing! Let{SINGLE_QUOTE}s just go!{END}"


text_0C55__089C68E6:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Did you know the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}flippers{SPECIAL_02_PAR_1}{END} Librari gave{NL}you let you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}dive {SPECIAL_02_PAR_1}{END}as well as {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}swim{SPECIAL_02_PAR_1}{END}?{NL}They{SINGLE_QUOTE}re good for avoiding things when{NL}you{SINGLE_QUOTE}re in the water...{NL}And let{SINGLE_QUOTE}s face it, if something hits you{NL}in the head while you{SINGLE_QUOTE}re swimming...{NL}I{SINGLE_QUOTE}m going to be the one who gets{NL}the worst of it.{NL}So please, remember that. For my sake,{NL}{SPECIAL_06_PAR_1}{END}!{END}"


text_0C56__089C6A26:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Don{SINGLE_QUOTE}t just wander around aimlessly...{NL}That{SINGLE_QUOTE}s the quickest way to get lost!{NL}If you do get lost, look at your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}{NL}immediately to get your bearings.{NL}You will find your way only if you know{NL}where you are AND where you{SINGLE_QUOTE}re going.{END}"


text_0C57__089C6B0D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}That phantom we saw earlier... He said{NL}he was {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}an ancient king of Hyrule{SPECIAL_02_PAR_1}{END}.{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}What else do we know? The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END} was{NL}nowhere to be seen in the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Wind Ruins{SPECIAL_02_PAR_1}{END}.{NL}I guess we{SINGLE_QUOTE}ll just have to go to{NL}the place marked on our {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}...{NL}But first, you should infuse your{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END} with that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}.{NL}We must head for the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental{NL}sanctuary{SPECIAL_02_PAR_1}{END}!{END}"


text_0C58__089C6C6A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}It seems the king and the guards are{NL}not be able to see it...{NL}But the entrance to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental{NL}sanctuary {SPECIAL_02_PAR_1}{END}MUST be inside {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}!{END}"


text_0C59__089C6CFD:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}{SPECIAL_06_PAR_1}{END}! Aren{SINGLE_QUOTE}t you forgetting{NL}a little something?{NL}We need to infuse your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END} with the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element {SPECIAL_02_PAR_1}{END}that we worked so hard to get!{NL}After all, we certainly worked hard{NL}enough to get it. We ought to use it!{END}"


text_0C5A__089C6DCD:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}I suppose we{SINGLE_QUOTE}ll have to try going{NL}to the point marked on the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}...{NL}We have no other clues leading us to{NL}the remaining {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}, that{SINGLE_QUOTE}s for sure.{END}"


text_0C5B__089C6E69:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}, there{SINGLE_QUOTE}s only one{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END} remaining!{NL}Once you{SINGLE_QUOTE}ve used the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END} to{NL}free Princess Zelda from her curse,{NL}perhaps you can ask her out on{NL}a date or something.{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}Don{SINGLE_QUOTE}t worry, I{SINGLE_QUOTE}ll be right there with you!{NL}You will need my advice, after all!{END}"


text_0C5C__089C6F6B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Did you see that?{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}King Gustaf{SPECIAL_02_PAR_1}{END} was calling us...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Perhaps we ought to visit the point{NL}marked on our {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}.{NL}It may have been a dream, but I{SINGLE_QUOTE}m sure{NL}it will make sense if we go there.{END}"


text_0C5D__089C702B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Uhh... Don{SINGLE_QUOTE}t tell me the new path leads{NL}us {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}into a grave{SPECIAL_02_PAR_1}{END}...?{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}That means {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}King Gustaf{SPECIAL_02_PAR_1}{END} must really{NL}have been a...a...{NL}{SPECIAL_03_PAR_2}{END}{BYTE_90}Whoa! I just got a chill down my seam!{END}"


text_0C5E__089C70D6:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}I haven{SINGLE_QUOTE}t mentioned it up to now, but{NL}ghosts and stuff like that...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_91}They really give me the heebie-jeebies.{NL}{NL}So I{SINGLE_QUOTE}d rather not go into that grave if{NL}we can avoid it at all...{NL}But, {SPECIAL_06_PAR_1}{END}, this doesn{SINGLE_QUOTE}t seem{NL}to bother you very much...{NL}Either you{SINGLE_QUOTE}re very much in control of{NL}your fear...{NL}Or you haven{SINGLE_QUOTE}t really registered what{SINGLE_QUOTE}s{NL}going on here...{END}"


text_0C5F__089C7231:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Fine, fine!! {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}King Gustaf{SPECIAL_02_PAR_1}{END} is waiting for{NL}us inside that crypt!{NL}And remember, it IS the Royal Crypt, so{NL}show a little respect in there!{NL}Got that, {SPECIAL_06_PAR_1}{END}?{END}"


text_0C60__089C72CC:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Sooo... Meeting a dead king means...{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}He must have had unfinished business{NL}in the world of the living.{NL}He seemed awfully polite for a ghost.{NL}I expected...spookier, I suppose.{NL}What do you suppose he meant by all{NL}that {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}source of the flow{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE} business?{SPECIAL_01_PAR_1}{NL}{END}"


text_0C61__089C73D0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}The source of the flow{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE}...{NL}{NL}In other words, a place that the water{NL}comes from, wouldn{SINGLE_QUOTE}t you say?{NL}Now, ask yourself: {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}where does all the{NL}water{SPECIAL_02_PAR_1}{END} in Hyrule {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}come from{SPECIAL_02_PAR_1}{END}?{END}"


text_0C62__089C7482:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}We only need to find one more {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}.{NL}{NL}And while we don{SINGLE_QUOTE}t know exactly where it{NL}is, we{SINGLE_QUOTE}ve got a good lead to follow!{NL}I{SINGLE_QUOTE}m sure we{SINGLE_QUOTE}ll be on the right track if{NL}we find Gustaf{SINGLE_QUOTE}s {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}source of the flow{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE}!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}Let{SINGLE_QUOTE}s go, {SPECIAL_06_PAR_1}{END}!!{END}"


text_0C63__089C7564:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Of course! The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}source of the flow{SPECIAL_02_PAR_1}{END}!{NL}He meant {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Veil Springs{SPECIAL_02_PAR_1}{END}!{NL}I wonder what lies up ahead...{NL}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}Well, we know it{SINGLE_QUOTE}s connected to the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}, so let{SINGLE_QUOTE}s go, {SPECIAL_06_PAR_1}{END}!{END}"


text_0C64__089C760E:
	.string "What{SINGLE_QUOTE}s happening to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}source{NL}of the water{SPECIAL_02_PAR_1}{END}?{NL}There shouldn{SINGLE_QUOTE}t be anything but{NL}blue sky up there!{NL}Well, no point sitting around thinking{NL}about it!{NL}... ...{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Hey, I just realized something.{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}I{SINGLE_QUOTE}m starting to think...and talk...{NL}a lot like you lately! What{SINGLE_QUOTE}s with that?{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_8D}I need to get my head straight!{END}"


text_0C65__089C7749:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}There must be {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}something{SPECIAL_02_PAR_1}{END} just beyond{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Veil Springs{SPECIAL_02_PAR_1}{END} that leads to the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}.{NL}We{SINGLE_QUOTE}re just one step away from being{NL}able to lift {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s curse!{END}"


text_0C66__089C77F1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}A world of clouds high above{NL}the ground...{NL}I feel like I{SINGLE_QUOTE}ve seen it all now!{NL}{NL}{SPECIAL_06_PAR_1}{END}, perhaps it would be{NL}best if you didn{SINGLE_QUOTE}t look down.{NL}One false step and...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_90}I don{SINGLE_QUOTE}t even want to think about it!{END}"


text_0C67__089C78BA:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Nothing but clouds, as far as the eye{NL}can see!{NL}But there{SINGLE_QUOTE}s got to be a clue to the{NL}final {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s location somewhere!{NL}Keep those eyes peeled, {SPECIAL_06_PAR_1}{END}!{END}"


text_0C68__089C7954:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}That tornado near {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Veil Springs {SPECIAL_02_PAR_1}{END}took us{NL}to this cloud world! Can you believe it?{NL}I don{SINGLE_QUOTE}t know what awaits us next, {NL}but I can{SINGLE_QUOTE}t wait to find out!{NL}... ...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Hm? Hey, {SPECIAL_06_PAR_1}{END}!!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}Don{SINGLE_QUOTE}t get all scared on me now!{NL}Show me some spirit, lad!{NL}Let{SINGLE_QUOTE}s enjoy ourselves!{END}"


text_0C69__089C7A5A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}The people who live on the clouds must{NL}know something of the last {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}!{NL}We should certainly ask, at any rate!{END}"


text_0C6A__089C7AD2:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}What is it, {SPECIAL_06_PAR_1}{END}?{NL}{NL}Weren{SINGLE_QUOTE}t we going to ask the wind folk{NL}here about that last element?{END}"


text_0C6B__089C7B2A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}We come all this way to the clouds, and{NL}we have ANOTHER building to explore?{NL}And what{SINGLE_QUOTE}s holding that thing up{NL}in the first place?{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}, walk very carefully up{NL}here, you got that!?{END}"


text_0C6C__089C7BE2:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Wow, a {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Palace of Winds{SPECIAL_02_PAR_1}{END} atop a{NL}field of clouds... How elegant.{NL}But that{SINGLE_QUOTE}s not our first concern.{NL}The monsters here are pretty tough.{NL}Watch your footing, and make sure{NL}you don{SINGLE_QUOTE}t fall!{END}"


text_0C6D__089C7C9F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}So the last {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END} is in the deepest{NL}recesses of the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Palace of Winds{SPECIAL_02_PAR_1}{END}...{NL}We{SINGLE_QUOTE}ve finally done it, {SPECIAL_06_PAR_1}{END}!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}You know what you have to do now!{END}"


text_0C6E__089C7D33:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Whoa!{NL}{NL}Maybe fighting the flow isn{SINGLE_QUOTE}t what we{SINGLE_QUOTE}re{NL}supposed to be doing here...{NL}Perhaps we should just let it carry{NL}us along for a bit.{NL}If you can{SINGLE_QUOTE}t beat {SINGLE_QUOTE}em, join {SINGLE_QUOTE}em, right?{END}"


text_0C6F__089C7DE3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}! I{SINGLE_QUOTE}m overcome!{NL}We{SINGLE_QUOTE}ve got all the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}elements{SPECIAL_02_PAR_1}{END} now!{NL}Now we can revive the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END}!{NL}{NL}You{SINGLE_QUOTE}ll have {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END} back to{NL}normal in no time!{END}"


text_0C70__089C7E7F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}This will go down in legend!{NL}{NL}To think that I will witness the{NL}rebirth of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END}!{NL}I can barely contain myself! Quickly!{NL}Quickly! To the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental sanctuary{SPECIAL_02_PAR_1}{END}!{END}"


text_0C71__089C7F31:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}The king and the guards must not be{NL}able to see it...{NL}But the entrance to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental{NL}sanctuary {SPECIAL_02_PAR_1}{END}is right in the courtyard!{END}"


text_0C72__089C7FB5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}How...could he?! {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati {SPECIAL_02_PAR_1}{END}will pay for this!{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}! Now is the time to use the{NL}true power of the sacred {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Four Sword{SPECIAL_02_PAR_1}{END}!!{NL}You can {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}lift the curse{SPECIAL_02_PAR_1}{END} from each of{NL}these people, one by one!{END}"


text_0C73__089C8079:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END} has fallen into darkness.{NL}{NL}This place is a den of evil for {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}{NL}and his beast minions now...{NL}I understand your haste, but it may{NL}be wise to retreat for now...{NL}Just until we{SINGLE_QUOTE}ve prepared ourselves to{NL}face this challenge anew!{END}"


text_0C74__089C8173:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END} has become a castle of{NL}darkness now, and I fear for the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}.{NL}{SPECIAL_06_PAR_1}{END}! You are the only one in all{NL}of Hyrule who can save those people!{END}"


text_0C75__089C820F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}If Vaati is after the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}, he{NL}won{SINGLE_QUOTE}t stop until he{SINGLE_QUOTE}s drained {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Zelda{SPECIAL_02_PAR_1}{END}!{NL}I doubt she will be able to survive the{NL}extraction process...{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}{SPECIAL_06_PAR_1}{END}! We must hurry to the roof{NL}of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}!{END}"


text_0C76__089C82DA:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}We will get through this!{NL}{NL}We have all of the techniques and{NL}power you{SINGLE_QUOTE}ve gained in your journey!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}And we have your wisdom and courage{NL}as well! {SPECIAL_06_PAR_1}{END}! I believe in you!{END}"


text_0C77__089C8385:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Hyrule Castle has grown dark...{NL}Perhaps this repulsive scene...{NL}is just a reflection of the evil lurking{NL}in the heart of my former student.{NL}... ...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Ah, what have I created?{NL}But don{SINGLE_QUOTE}t worry about me, {SPECIAL_06_PAR_1}{END}!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}I know what we must do!!{END}"


text_0C78__089C8473:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}We have no time!!{NL}We must get to Princess Zelda!!{END}"


text_0C79__089C84A8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What are you doing talking to me!!{NL}We have no time for this!!{NL}Let{SINGLE_QUOTE}s go, {SPECIAL_06_PAR_1}{END}!!{END}"


text_0C7A__089C84F8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_06_PAR_1}{END} and I are on the way!!{NL}Wait for us! We{SINGLE_QUOTE}re coming!!{END}"


text_0C7B__089C8545:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Well done, {SPECIAL_06_PAR_1}{END}!{NL}I knew you could do it!!{NL}Now! Let{SINGLE_QUOTE}s {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}remove that curse{SPECIAL_02_PAR_1}{END}{NL}from {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}!{END}"


text_0C7C__089C85AA:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hold on just a little longer, Your{NL}Highness!{NL}Come on, {SPECIAL_06_PAR_1}{END}! Hurry up and{NL}return {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END} to normal!{END}"


text_0C7D__089C8619:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}It{SINGLE_QUOTE}s been a long road, but we{SINGLE_QUOTE}re{NL}almost there. After all...{NL}The sacred {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Four Sword{SPECIAL_02_PAR_1}{END} that you carry{NL}must be able to remove the curse!{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END} will be restored!{END}"


text_0C7E__089C86C8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}It{SINGLE_QUOTE}s dangerous here!{NL}{SPECIAL_06_PAR_1}{END}!{NL}Let{SINGLE_QUOTE}s get the princess to the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental sanctuary{SPECIAL_02_PAR_1}{END} quickly!{END}"


text_0C7F__089C8723:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Now that Vaati{SINGLE_QUOTE}s power is fading,{NL}this place is crumbling!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}!! {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}!!{NL}Watch your footing!!{END}"


text_0C80__089C8793:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}As soon as we take care of one{NL}problem, another one comes up!{NL}{SPECIAL_06_PAR_1}{END}, I{SINGLE_QUOTE}m sorry to have to{NL}say this...{NL}But you{SINGLE_QUOTE}ll have to save your joyful{NL}reunion with {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Zelda{SPECIAL_02_PAR_1}{END} for another time.{END}"


text_0C81__089C8846:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}It{SINGLE_QUOTE}s nice taking in the view from up{NL}here and all, but...{NL}I{SINGLE_QUOTE}m thinking maybe I should be a{NL}little higher up by now...{NL}What I{SINGLE_QUOTE}m trying to say here, kid, is...{NL}have you been drinking your milk?{END}"


text_0C82__089C8909:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hey, kid! Kid!{NL}Slow down a little!{NL}You seem to have completely forgotten{NL}that I{SINGLE_QUOTE}m on top of your head here!{NL}Man, I hate to think of how this is{NL}going to play out...{SPECIAL_01_PAR_1}{NL}{END}"


text_0C83__089C89B3:
	.string "{SPECIAL_01_PAR_1}{SPECIAL_06_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_90}ZZZZZ.......{NL}{SPECIAL_01_PAR_1}{SPECIAL_02_PAR_1}Huh? Whuzza--! What?!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}What are you talking about?!{NL}Me? Sleeping? That{SINGLE_QUOTE}s crazy!{NL}{SPECIAL_01_PAR_1}{SPECIAL_06_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_90}Mmmmnumumummm...{END}"


text_0C84__089C8A2F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Yes? What{SINGLE_QUOTE}s the matter, m{SINGLE_QUOTE}boy?{NL}{NL}What? You were just checking up on{NL}me? What{SINGLE_QUOTE}s that about!?!{NL}You think I just sit on your head,{NL}waiting at your beck and call?{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}I can{SINGLE_QUOTE}t believe it! Grumble, grumble...{END}"


text_0C85__089C8AFB:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hey, kid! Could you lend me a hand?{NL}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}I{SINGLE_QUOTE}ve got a nasty back itch, and I can{SINGLE_QUOTE}t{NL}reach it with my beak.{NL}Could you please scratch me{NL}right there?{NL}No, up! Up! OK, now to the left!{NL}I said left!{NL}... ...{SPECIAL_01_PAR_1}{NL}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_90}{SPECIAL_01_PAR_1}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Ohhh, sweet mercy!{SPECIAL_0F_PAR_1}{BYTE_0B}{SPECIAL_01_PAR_1}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{SPECIAL_04_PAR_2}{SPECIAL_01_PAR_1}{SPECIAL_05_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_04_PAR_2}{SPECIAL_01_PAR_1}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}{END}{NL}That{SINGLE_QUOTE}s the stuff!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Thanks, buddy! I owe you one!{END}"


text_0C86__089C8C25:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hey! Hey! Stop twirling around like that!{NL}You{SINGLE_QUOTE}re giving me the spins, kid!{END}"


text_0C87__089C8C73:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Man, I could really go for a nice,{NL}hot bath right now...{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}Huh?! What{SINGLE_QUOTE}s that?!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}You{SINGLE_QUOTE}d send me to the cleaners!?{SPECIAL_02_PAR_1}{END}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}What makes you think you can treat{NL}me like common laundry, huh?{END}"


text_0C88__089C8D2D:
	.string "Mmmmnumumummm...{NL}{NL}Come on, please...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Just five more minutes...{SPECIAL_02_PAR_1}{END}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_90}I promise I{SINGLE_QUOTE}ll get up in five minutes...{END}"


text_0C89__089C8D9C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Mnyawwwn... I don{SINGLE_QUOTE}t know why{NL}I{SINGLE_QUOTE}m so tired...{NL}I guess I just get a little bored sitting{NL}up here, watching you wander around.{END}"


text_0C8A__089C8E1B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Do you have to ask me about every{NL}single little thing?!{NL}Just figure it out for yourself,{NL}you big baby!{END}"


text_0C8B__089C8E85:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Oh, NOW you need me?{NL}{NL}I was starting to think you{SINGLE_QUOTE}d forgotten{NL}that I was even up here!{NL}...I was starting to get a little lonely.{END}"


text_0C8C__089C8F09:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Mmmmnumumummm...{NL}{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8E}Oh, I couldn{SINGLE_QUOTE}t eat another bite...{NL}Let{SINGLE_QUOTE}s take the rest home...{NL}Wha--! Oh my! Was I talking in my{NL}sleep or something?{NL}How odd...{NL}{SPECIAL_03_PAR_2}{END}{BYTE_90}Mmmmnumumummm...{END}"


text_0C8D__089C8FB5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Ahem! You know, I don{SINGLE_QUOTE}t take students{NL}very often or anything...{NL}But for you, I figured I could make an{NL}exception! Just a little one, you know.{END}"


text_0C8E__089C9047:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}So hungry...{NL}{NL}Rrrrrumble rumble...{NL}{NL}!!!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}That wasn{SINGLE_QUOTE}t my stomach!!{NL}It must have been the wind{NL}or something!{END}"


text_0C8F__089C90B7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}You{SINGLE_QUOTE}re so energetic all the time...{NL}{NL}Not that I{SINGLE_QUOTE}m saying you{SINGLE_QUOTE}re hyperactive{NL}or anything! I meant it as a compliment!{NL}Like...you{SINGLE_QUOTE}ve got a special talent for{NL}being WAY too peppy or something.{END}"


text_0C90__089C9178:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hmn? Huh?{NL}{NL}Strange... I thought a woman was{NL}calling out to me just now...{NL}Maybe it was just my imagination.{END}"


text_0C91__089C91E7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}What{SINGLE_QUOTE}s up, {SPECIAL_06_PAR_1}{END}?{NL}What can I do for yo--GURRK!{NL}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E4}Owowowow... I jutht bit my thung!{NL}Don{SINGLE_QUOTE}t make me thpeak...{NL}{SPECIAL_03_PAR_2}{END}{BYTE_91}Jutht thort it out yourthelf!{END}"


text_0C92__089C9274:
	.string "You know...{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_8E}I{SINGLE_QUOTE}m really suffering from lack of{NL}exercise up here...and I had an idea.{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}, why don{SINGLE_QUOTE}t you climb onto{NL}my head for a while?{END}"


text_0C93__089C9305:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hey, {SPECIAL_06_PAR_1}{END}, why don{SINGLE_QUOTE}t we just take{NL}the rest of the day off?{NL}I{SINGLE_QUOTE}m just beat, I tell you...{END}"


text_0C94__089C935E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hm?! Sniff sniff! Sniff sniff!{NL}Do you smell something...weird?{NL}Oh! Oh my! I{SINGLE_QUOTE}m sorry, {SPECIAL_06_PAR_1}{END}!{NL}You see, I... I...{NL}I hid a little eggy snack in your hair{NL}about a month ago, and...{NL}I completely forgot about it!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_91}Oh, dear... It{SINGLE_QUOTE}s quite disgusting!{END}"


text_0C95__089C9452:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}You know, {SPECIAL_06_PAR_1}{END}, your sword work{NL}really has come a long way.{NL}You remind me of a young me. When I{NL}was your age, I was quite a swordsman!{END}"


text_0C96__089C94DA:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}You know, your hair{SINGLE_QUOTE}s always really{NL}messy... A real rat{SINGLE_QUOTE}s nest...{NL}As long as I{SINGLE_QUOTE}m up here, no one will ever{NL}need to know. You can thank me later.{NL}But I recommend seeing your stylist{NL}before you next meet {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}!{NL}Must look good for the ladies!{END}"


text_0C97__089C95DA:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Mmmmnumumummm...{NL}{NL}Mnn? A test? Oh, no! I forgot to study!{NL}{NL}Oh, wow! {SPECIAL_03_PAR_2}{END}{BYTE_8D}What time is it?! And what{NL}was I dreaming about just now?{NL}Maybe I should go back to sleep and{NL}try to figure it out...{NL}{SPECIAL_03_PAR_2}{END}{BYTE_90}Mmmmnumumummm...{END}"


text_0C98__089C96AE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}La lala lala!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}What do you think, {SPECIAL_06_PAR_1}{END}?{SPECIAL_03_PAR_2}{END}{BYTE_90}{NL}Nice melody, isn{SINGLE_QUOTE}t it?{NL}{NL}I just wrote it myself. I call it{NL}{DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Live Long, Love Long{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE}!{NL}It{SINGLE_QUOTE}s just exploding with fiery romance!{NL}Makes your heart soar, doesn{SINGLE_QUOTE}t it?{END}"


text_0C99__089C977C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}La lala lala!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}What do you think, {SPECIAL_06_PAR_1}{END}?{SPECIAL_03_PAR_2}{END}{BYTE_90}{NL}Nice melody, isn{SINGLE_QUOTE}t it?{NL}{NL}I just wrote it myself. I call it{NL}{DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Live Long, Love Long{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE}!{NL}It{SINGLE_QUOTE}s just exploding with fiery romance!{NL}Makes your heart soar, doesn{SINGLE_QUOTE}t it?{END}"


text_0C9A__089C984A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Well, it{SINGLE_QUOTE}s almost time to bring all of this{NL}to a close, isn{SINGLE_QUOTE}t it? I{SINGLE_QUOTE}m ready!{END}"


text_0C9B__089C989A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}! What{SINGLE_QUOTE}s the matter?{NL}Are you nervous? That{SINGLE_QUOTE}s no good!{NL}We need you relaxed and ready! Take a{NL}deep breath and exhale slowwwwly...{NL}Just stick to what you know, and I{SINGLE_QUOTE}m{NL}sure we{SINGLE_QUOTE}ll come out just fine.{END}"


text_0C9C__089C9963:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}{SPECIAL_06_PAR_1}{END}, I know this may not be{NL}a great time for it, but...{NL}I wanted to say thanks for everything{NL}you{SINGLE_QUOTE}ve done. I{SINGLE_QUOTE}m very grateful for--{NL}Hm? What? You{SINGLE_QUOTE}re freaked out?{NL}You{SINGLE_QUOTE}re not used to me being nice!?{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}Fine, then! Forget I said anything!{END}"


text_0C9D__089C9A50:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hm... You know, I hadn{SINGLE_QUOTE}t noticed,{NL}because I{SINGLE_QUOTE}m with you all the time...{NL}But you{SINGLE_QUOTE}ve grown to be quite a powerful{NL}young lad.{NL}{SPECIAL_03_PAR_2}{END}{BYTE_8D}I just wanted you to know... Anyway,{NL}let{SINGLE_QUOTE}s get moving, {SPECIAL_06_PAR_1}{END}!!{END}"


text_0C9E__089C9B0C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}We make a fine team, don{SINGLE_QUOTE}t we? Why,{NL}I might just stay up here forever!{NL}After all, I{SINGLE_QUOTE}ve grown quite used to my{NL}little {DOUBLE_QUOTE}ringside seat{DOUBLE_QUOTE} to all the action!{NL}And you{SINGLE_QUOTE}d never have to worry about{NL}combing that mess of a hairdo again!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}What do you say to that, {SPECIAL_06_PAR_1}{END}?{END}"

