
text_1500__089D46B4:
	.string "{END}"


text_1501__089D46B5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmm-hmm... Let{SINGLE_QUOTE}s see if I can{SINGLE_QUOTE}t{NL}read that tablet for you...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Fill your sword with power and walk{NL}over the glowing tile...{SPECIAL_02_PAR_1}{END}{NL}Hm... Perhaps it refers to those{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}flashing spots on the floor {SPECIAL_02_PAR_1}{END}around you.{NL}Well? What are you waiting{NL}for? Try it, {SPECIAL_06_PAR_1}{END}!{END}"


text_1502__089D47AE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hmm-hmm...{NL}{NL}It seems that forging the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END}{NL}somehow opened the doorway!{NL}It must lead to the room that holds{NL}the secret of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_06_PAR_1}{END}, we must go inside!{END}"


text_1503__089D4862:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}So, when that {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}beam hits those who have{NL}turned to stone, it will turn them back{SPECIAL_02_PAR_1}{END}.{NL}You{SINGLE_QUOTE}ve done it, {SPECIAL_06_PAR_1}{END}!{NL}Now, you can rescue {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}.{END}"


text_1504__089D48F5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So this is the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elemental sanctuary{SPECIAL_02_PAR_1}{END},{NL}then...{NL}This is where we can {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}infuse your blade{NL}with the power of the elements{SPECIAL_02_PAR_1}{END}...{NL}Yes, there seems to be a pedestal for{NL}your sword right in the middle there.{END}"


text_1505__089D49C1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Whoa! You just {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}split in two{SPECIAL_02_PAR_1}{END}! So this{NL}is the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}power of the White Sword{SPECIAL_02_PAR_1}{END}!{NL}I guess you can double yourself like{NL}that anytime you see those panels...{END}"


text_1506__089D4A5C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmmmm...{NL}This inscription... It says...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Focus power in your blade and{NL}stand on the glowing tile...{END}"


text_1507__089D4AC4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hey, where are you going, {SPECIAL_06_PAR_1}{END}?!{NL}We must go through the door we opened!{END}"


text_1508__089D4B0D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hey, {SPECIAL_06_PAR_1}{END}, you{SINGLE_QUOTE}ve gone too far!{NL}Just step on those glowing panels!{END}"

