
text_1700__089D623C:
	.string "{END}"


text_1701__089D623D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0E}...   ...{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}O young one...{NL}{NL}Child who seeks to rescue my{NL}descendant, Zelda...{NL}Welcome...{NL}{NL}My name is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Gustaf{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}. I was king of{NL}Hyrule countless ages ago...{END}"


text_1702__089D62DD:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}I grant to you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}...{NL}{NL}Seek the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}source of the flow {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}in Hyrule...{NL}{NL}Only then will your path open...{NL}{NL}Save {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Zelda{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}...{NL}{NL}All of Hyrule is counting on you...{END}"


text_1703__089D638B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmm... Fascinating! An ancient{NL}king of Hyrule? How strange...{NL}And the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}source of the flow{SPECIAL_02_PAR_1}{END}?{NL}What do you suppose that could mean?{END}"


text_1704__089D6411:
	.string "{END}"


text_1705__089D6412:
	.string "Let fools tarry here while{NL}the true hero moves forward...{NL}The truth is not seen by the eye,{NL}yet it makes itself known.{END}"

