
text_3C00__089E98F4:
	.string "{END}"


text_3C01__089E98F5:
	.string "Welcome!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}{NL}You{SINGLE_QUOTE}ve come to the one and only{NL}bakery of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Wheaton {SPECIAL_02_PAR_1}{END}and {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Pita{SPECIAL_02_PAR_1}{END}!{NL}Our delicious {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}brioche{SPECIAL_02_PAR_1}{END}, which may or{NL}may not have something special inside,{NL}is a filling and fulfilling bargain{NL}at only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Rupees{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1}<{SPECIAL_03_PAR_2}Don{SINGLE_QUOTE}t buy{END}"


text_3C02__089E99E2:
	.string "Thanks! And be sure to eat it{NL}while it{SINGLE_QUOTE}s warm!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_3C03__089E9A13:
	.string "Oh? Well, come on back anytime!{NL}Our bread is always fresh!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_3C04__089E9A50:
	.string "Oh, what a shame! You don{SINGLE_QUOTE}t have{NL}enough money. I{SINGLE_QUOTE}m sorry!{END}"


text_3C05__089E9A8A:
	.string "There was a Kinstone piece inside your{NL}tasty treat! What incredible luck!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_3C06__089E9AD6:
	.string "Nothing this time...{NL}Too bad!{END}"


text_3C07__089E9AF4:
	.string "Welcome!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}{NL}Please bring {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}whatever you{SINGLE_QUOTE}d like{NL}to buy{SPECIAL_02_PAR_1}{END} up to the register.{END}"


text_3C08__089E9B40:
	.string "Hrrmm... Hrrmm...{NL}Must...make...deliciousness!{END}"


text_3C09__089E9B6F:
	.string "Oh, just bring {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}whatever you{SINGLE_QUOTE}d{NL}like to buy{SPECIAL_02_PAR_1}{END} up to the register.{NL}I{SINGLE_QUOTE}ll be happy to ring you up.{NL}Thanks!{END}"


text_3C0A__089E9BD7:
	.string "Welcome!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}{NL}You{SINGLE_QUOTE}ve come to the one and only{NL}bakery of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Wheaton {SPECIAL_02_PAR_1}{END}and {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Pita{SPECIAL_02_PAR_1}{END}!{NL}Our special {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}croissant{SPECIAL_02_PAR_1}{END}, which may or{NL}may not have something inside it,{NL}is a flaky, buttery bargain at{NL}only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Rupees{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1}<{SPECIAL_03_PAR_2}Don{SINGLE_QUOTE}t buy{END}"


text_3C0B__089E9CB7:
	.string "Welcome!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}{NL}You{SINGLE_QUOTE}ve come to the one and only{NL}bakery of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Wheaton {SPECIAL_02_PAR_1}{END}and {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Pita{SPECIAL_02_PAR_1}{END}!{NL}A {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}slice {SPECIAL_02_PAR_1}{END}of our fantastic fruit {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}pie{SPECIAL_02_PAR_1}{END}, which{NL}may or may not have something inside,{NL}is a snacktacular bargain at{NL}only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Rupees{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1}<{SPECIAL_03_PAR_2}Don{SINGLE_QUOTE}t buy{END}"


text_3C0C__089E9DA3:
	.string "Welcome!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}{NL}You{SINGLE_QUOTE}ve come to the one and only{NL}bakery of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Wheaton {SPECIAL_02_PAR_1}{END}and {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Pita{SPECIAL_02_PAR_1}{END}!{NL}This tasty {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}slice of cake{SPECIAL_02_PAR_1}{END}, which may or{NL}may not have something special inside,{NL}is a moist and cream-filled{NL}bargain at only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Rupees{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1}<{SPECIAL_03_PAR_2}Don{SINGLE_QUOTE}t buy{END}"

