
text_4200__089ED1A8:
	.string "{END}"


text_4201__089ED1A9:
	.string "{END}"


text_4202__089ED1AA:
	.string "Oh, no... A customer...{NL}{NL}Why did I ever start a treasure{NL}game shop, anyway? All right then...{NL}Ahem... Welcome to a fascinating {NL}world of treasure, blah-blah-blah.{NL}In this wonderland, you can test your{NL}luck and win big bucks...maybe.{NL}I don{SINGLE_QUOTE}t really recommend it myself,{NL}but whatever. It{SINGLE_QUOTE}s your wallet.{END}"


text_4203__089ED2D7:
	.string "It{SINGLE_QUOTE}s 10 Rupees for one try, if you still{NL}want to throw your money away on such{NL}a terrible pastime... I would really just{NL}save it if I were you...{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Give it a try {SPECIAL_05_PAR_1}B{SPECIAL_05_PAR_1}Quit{END}"


text_4204__089ED383:
	.string "Oh, good, good! It really is your lucky{NL}day! You don{SINGLE_QUOTE}t have enough Rupees!{NL}I{SINGLE_QUOTE}m telling you, this gambling nonsense{NL}is no good. You{SINGLE_QUOTE}re better off without!{END}"


text_4205__089ED41D:
	.string "Right. Right. That{SINGLE_QUOTE}s great.{NL}{NL}Gambling{SINGLE_QUOTE}s no good, kid.{NL}You made the right choice.{END}"


text_4206__089ED46E:
	.string "{END}"


text_4207__089ED46F:
	.string "{END}"


text_4208__089ED470:
	.string "Ahh... Well, the prize is now up{NL}to {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees.{NL}If you keep playing, your wallet will{NL}explode! Maybe it{SINGLE_QUOTE}s best to stop now.{NL}After all, you never know when your{NL}luck will run out and leave you broke.{NL}But...you probably want to keep{NL}going, don{SINGLE_QUOTE}t you?!{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes, let{SINGLE_QUOTE}s  {SPECIAL_05_PAR_1}{BYTE_FF}No, thanks{END}"


text_4209__089ED586:
	.string "{END}"


text_420A__089ED587:
	.string "{END}"


text_420B__089ED588:
	.string "Level 1 is more than enough to take {NL}your money, but if you{SINGLE_QUOTE}re feeling{NL}particularly self-destructive, we{SINGLE_QUOTE}ve{NL}even got level 2 now, rue the day...{NL}Which level would you like to try?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Level 1: Easy   {SPECIAL_05_PAR_1}{BYTE_FF}Level 2: Hard{END}"


text_420C__089ED660:
	.string "I see...{NL}Well, I guess I can{SINGLE_QUOTE}t talk you out of it.{NL}All right, I{SINGLE_QUOTE}ll get it set up.{NL}Just go in back after I do.{END}"


text_420D__089ED6CE:
	.string "{END}"


text_420E__089ED6CF:
	.string "{END}"


text_420F__089ED6D0:
	.string "{END}"


text_4210__089ED6D1:
	.string "{END}"


text_4211__089ED6D2:
	.string "{END}"


text_4212__089ED6D3:
	.string "{END}"


text_4213__089ED6D4:
	.string "{END}"


text_4214__089ED6D5:
	.string "{END}"


text_4215__089ED6D6:
	.string "Just open whichever chest you like.{NL}{NL}If you win, then I{SINGLE_QUOTE}ll double the amount{NL}of your bet.{END}"


text_4216__089ED730:
	.string "Just open whichever chest you like.{NL}{NL}If you win, then I{SINGLE_QUOTE}ll triple the amount{NL}of your bet.{END}"


text_4217__089ED78A:
	.string "You{SINGLE_QUOTE}ve already paid the man. You might{NL}as well play his game.{END}"


text_4218__089ED7C8:
	.string "Congratulations.{NL}Your prize is {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees.{NL}I wouldn{SINGLE_QUOTE}t recommend it, but...you can{NL}wager your winnings and try again.{NL}Think about it. You already got a prize{NL}and everything. Don{SINGLE_QUOTE}t push your luck.{NL}  {SPECIAL_05_PAR_1}B{BYTE_19}Let{SINGLE_QUOTE}s do it!   {SPECIAL_05_PAR_1}B{BYTE_1A}No, thanks{END}"


text_4219__089ED8AC:
	.string "Ah... I see...{NL}{NL}Well, when you{SINGLE_QUOTE}re ready,{NL}just open another chest.{END}"


text_421A__089ED8EE:
	.string "Right! I{SINGLE_QUOTE}m so glad you{SINGLE_QUOTE}ve finally come{NL}back to reality!{NL}Just go wait in the front room. I{SINGLE_QUOTE}ll{NL}be right out with your prize.{END}"


text_421B__089ED969:
	.string "Ahh, I just can{SINGLE_QUOTE}t take this!{NL}Please, just stop now while you can!{NL}Your prize is 999 Rupees.{NL}Just take it, and never gamble again!{END}"


text_421C__089ED9EB:
	.string "Now, see! See what happens when you{NL}gamble! Oh, I tried to warn you!{NL}So... You{SINGLE_QUOTE}re really done, right?{END}"


text_421D__089EDA51:
	.string "Which level would you like to try?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Level 1: Easy   {SPECIAL_05_PAR_1}{BYTE_FF}Level 2: Hard{END}"


text_421E__089EDA98:
	.string "Now, when you{SINGLE_QUOTE}re ready,{NL}just choose a chest.{END}"


text_421F__089EDAC5:
	.string "Congratulations.{NL}Here{SINGLE_QUOTE}s your prize of {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees.{NL}But I just want to warn you, the wheel{NL}of fortune is ever turning.{NL}You may think you{SINGLE_QUOTE}ve found easy money,{NL}but life{SINGLE_QUOTE}s not always like that.{NL}What I{SINGLE_QUOTE}m saying here is...stay away,{NL}kid. Gambling{SINGLE_QUOTE}s no good.{END}"


text_4220__089EDBBF:
	.string "Sorry, no prize this time.{NL}{NL}That{SINGLE_QUOTE}s right. Gambling{SINGLE_QUOTE}s not what you{NL}thought it was, is it?{NL}And don{SINGLE_QUOTE}t think {DOUBLE_QUOTE}Maybe I{SINGLE_QUOTE}ll win next{NL}time,{DOUBLE_QUOTE} either. {NL}Wake up, man! Get out of here before{NL}you lose the shirt off your back!{END}"


text_4221__089EDC94:
	.string "Ahh... He{SINGLE_QUOTE}s finally opened up!{NL}I can{SINGLE_QUOTE}t wait to get crackin{SINGLE_QUOTE}!{END}"


text_4222__089EDCD1:
	.string "How{SINGLE_QUOTE}s it goin{SINGLE_QUOTE}?{NL}You winnin{SINGLE_QUOTE} much, pal?{END}"


text_4223__089EDCF8:
	.string "Don{SINGLE_QUOTE}t get hooked on gambling.{NL}You always lose in the end...{NL}But people keep playing!{END}"


text_4224__089EDD4D:
	.string "I guess this is no time for games,{NL}really, is it?{END}"


text_4225__089EDD7F:
	.string "{END}"


text_4226__089EDD80:
	.string "{END}"


text_4227__089EDD81:
	.string "{END}"


text_4228__089EDD82:
	.string "{END}"

