
text_4A00__089F56C4:
	.string "{END}"


text_4A01__089F56C5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Hey, hey, hey! This is no good!{NL}No good at all!{NL}The humans have {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}checked some books{NL}out of the library{SPECIAL_02_PAR_1}{END}!{NL}Thanks to them, none of us can get{NL}back to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Elder Librari{SPECIAL_02_PAR_1}{END}...{NL}How will he get by all alone?{NL}I{SINGLE_QUOTE}m so worried...{NL}I{SINGLE_QUOTE}m sure the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}librarian{SPECIAL_02_PAR_1}{END} knows something{NL}about where those books went...{NL}I wish I were big. Why, I{SINGLE_QUOTE}d walk right{NL}up and ask her where those books went!{END}"


text_4A02__089F583C:
	.string "{END}"


text_4A03__089F583D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Hey, hey, hey! Listen up! Listen good!{NL}The books are back now!{NL}It{SINGLE_QUOTE}s true! It{SINGLE_QUOTE}s true! Haha!{NL}Now we can get back to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Elder Librari{SPECIAL_02_PAR_1}{END}!{NL}So you brought the books back?{NL}Good for you! Thank you!{NL}{SPECIAL_07_PAR_1}J{SPECIAL_04_PAR_2}{END}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}Please take this as a{NL}sign of our thanks!{END}"


text_4A04__089F5901:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}Please take this as a{NL}sign of our thanks!{END}"


text_4A05__089F592E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}I{SINGLE_QUOTE}d better get back to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Elder Librari{SPECIAL_02_PAR_1}{END}{NL}now! He{SINGLE_QUOTE}ll be wondering where I am.{NL}Especially now that I can climb over the{NL}books, right? I mean, it{SINGLE_QUOTE}s so easy now!{END}"


text_4A06__089F59CF:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}Thanks again for your help!{END}"


text_4A07__089F59EE:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}007{END}"


text_4A08__089F5A03:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}008{END}"


text_4A09__089F5A18:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F7}What a great combo!{NL}{NL}You{SINGLE_QUOTE}re going to meet{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Elder Librari{SPECIAL_02_PAR_1}{END} and {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Jotori{SPECIAL_02_PAR_1}{END}?{NL}Oh, and how about Librari{SINGLE_QUOTE}s long,{NL}boring adventure stories? Haha!{NL}Talk about thrilling! Har har!{NL}{NL}Well, if you{SINGLE_QUOTE}re going over there,{NL}just climb over the books!{END}"


text_4A0A__089F5B06:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}010{END}"


text_4A0B__089F5B1B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}We can{SINGLE_QUOTE}t get up the shelf, because{NL}some human checked that book out!{NL}But at least we don{SINGLE_QUOTE}t have to listen to{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Elder Librari{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s boring old stories!{END}"


text_4A0C__089F5BB3:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}Ahh, it{SINGLE_QUOTE}s so nice to have all my little{NL}books in a row!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4A0D__089F5BF0:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}013{END}"


text_4A0E__089F5C05:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}014{END}"


text_4A0F__089F5C1A:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}015{END}"


text_4A10__089F5C2F:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}016{END}"


text_4A11__089F5C44:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}I am {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Jotori{SPECIAL_02_PAR_1}{END}, one of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s students!{NL}{NL}And to be perfectly honest, I think{NL}that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s adventure stories are...{NL}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}The best!!{NL}No, really!{NL}I may be a mental giant, but I have{NL}the body of just a tiny Minish lad...{NL}That{SINGLE_QUOTE}s why I really admire strong folk!{END}"


text_4A12__089F5D54:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}018{END}"


text_4A13__089F5D69:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Oh! So you passed the trial and{NL}returned with {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Elder Librari{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s flippers?{NL}I{SINGLE_QUOTE}m so jealous!{NL}I{SINGLE_QUOTE}m not much for exercise myself...{NL}But if you{SINGLE_QUOTE}re going on an adventure,{NL}there{SINGLE_QUOTE}s no one better to learn from!{NL}Ah, that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Elder Librari{SPECIAL_02_PAR_1}{END}! He{SINGLE_QUOTE}s so manly!{NL}So brave! And so full of FIRE!{END}"


text_4A14__089F5E80:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}020{END}"


text_4A15__089F5E95:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}021{END}"


text_4A16__089F5EAA:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}022{END}"


text_4A17__089F5EBF:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}023{END}"


text_4A18__089F5ED4:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}024{END}"


text_4A19__089F5EE9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}Wohohoho! What business have you{NL}with old {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END}?{NL}But! Before you ask, please allow me{NL}to introduce myself.{NL}Wohohoho! Ahem, aheeeeem...{NL}{NL}My name is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END}, and I have lived{NL}many long years.{NL}So many, in fact, that I{SINGLE_QUOTE}ve rather{NL}forgotten how old I am!{NL}But when I was young, oh,{NL}I crossed mountain and sea!{NL}I had many great adventures, but now{NL}I stay here and teach students.{NL}Yes, I enjoy my life of quiet study.{NL}I have so many stories yet to tell...{END}"


text_4A1A__089F60B5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}Yes, you are speaking to the world-{NL}famous treasure-hunter {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END}!{END}"


text_4A1B__089F6100:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}027{END}"


text_4A1C__089F6115:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}028{END}"


text_4A1D__089F612A:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}029{END}"


text_4A1E__089F613F:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}030{END}"


text_4A1F__089F6154:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}031{END}"


text_4A20__089F6169:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}032{END}"


text_4A21__089F617E:
	.string "KOBITO{SPECIAL_0F_PAR_1}{BYTE_1F}HONDANA{SPECIAL_0F_PAR_1}{BYTE_1F}033{END}"


text_4A22__089F6193:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}Wohohoho! Oh?{NL}A visitor after many long weeks!{NL}Even {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Jotari{SPECIAL_02_PAR_1}{END} has been away so long,{NL}I{SINGLE_QUOTE}ve grown almost...lonely.{NL}...But what is it? What do you need?{NL}{NL}Hm? You want to visit the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of{NL}Droplets{SPECIAL_02_PAR_1}{END}?{NL}Very well... You are the first such{NL}brave person in a long while!{NL}Stand on the clover in front of me!{END}"


text_4A23__089F62C6:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}Hrmm?{NL}What{SINGLE_QUOTE}s this? What{SINGLE_QUOTE}s this?{NL}You want me to cut to the chase and{NL}tell you about the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of Droplets{SPECIAL_02_PAR_1}{END}?{END}"


text_4A24__089F6338:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}All right, all right. You kids today...{NL}No patience for an old man.{NL}Well, just stand right there, like{NL}I told you!{END}"


text_4A25__089F63AE:
	.string "Wohoho!{NL}Now...OPEN, secret mystery panel!!{END}"


text_4A26__089F63D9:
	.string "Wohoho! Wasn{SINGLE_QUOTE}t that fun?{NL}Now then...{NL}It{SINGLE_QUOTE}s up to you to pass this {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}trial {SPECIAL_02_PAR_1}{END}safely{NL}and recover the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}item {SPECIAL_02_PAR_1}{END}you require.{NL}Oh, what fun! I do so love the real{NL}nitty-gritty of adventuring!{END}"


text_4A27__089F6492:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}Well done, indeed! Why, you{SINGLE_QUOTE}re almost{NL}as spry as I was at that age!{END}"

