
text_2800__089DDB20:
	.string "{END}"


text_2801__089DDB21:
	.string "My name{SINGLE_QUOTE}s Damp{BYTE_E9}. I{SINGLE_QUOTE}m the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}gravedigger{SPECIAL_02_PAR_1}{END} here.{NL}What{SINGLE_QUOTE}s that? You were called here by{NL}the ghost of a king?{NL}That{SINGLE_QUOTE}d be the ancient king of Hyrule{NL}who rests here. I{SINGLE_QUOTE}ve seen him myself.{NL}Well, if the king has called you, I can{SINGLE_QUOTE}t{NL}see any reason not to let you in...{NL}Here, take this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}graveyard key{SPECIAL_02_PAR_1}{END}.{END}"


text_2802__089DDC46:
	.string "What? A crow took the key and flew{NL}off into a tree?{NL}Well, don{SINGLE_QUOTE}t just stand around!{NL}The crow{SINGLE_QUOTE}ll get away!{NL}Charge at him and give that tree{NL}he{SINGLE_QUOTE}s in a rattle if you want it back!{END}"


text_2803__089DDCF6:
	.string "I{SINGLE_QUOTE}ll open the gate for you.{NL}Be careful in there.{END}"


text_2804__089DDD27:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Left{SPECIAL_02_PAR_1}{END}, {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}left{SPECIAL_02_PAR_1}{END}, {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}left{SPECIAL_02_PAR_1}{END}... {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Up{SPECIAL_02_PAR_1}{END}, {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}up{SPECIAL_02_PAR_1}{END}, {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}up{SPECIAL_02_PAR_1}{END}...{NL}Dang! What{SINGLE_QUOTE}s that last turn?{END}"


text_2805__089DDD7E:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END} with me?{NL}{END}"


text_2806__089DDDA7:
	.string "Wow! Hey! Look at that! They fused!{NL}{NL}I hope that means business will{NL}be booming from now on.{END}"


text_2807__089DDE04:
	.string "Hey, come back if you find another{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}.{END}"


text_2808__089DDE3B:
	.string "My name{SINGLE_QUOTE}s Damp{BYTE_E9}. I{SINGLE_QUOTE}m the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}gravedigger{SPECIAL_02_PAR_1}{END}{NL}here. What can I do for you?{NL}What{SINGLE_QUOTE}s that? You say you were called{NL}here by the ghost of a king?{NL}That{SINGLE_QUOTE}d be the ancient king of Hyrule{NL}who rests here. I{SINGLE_QUOTE}ve seen him myself.{END}"


text_2809__089DDF0E:
	.string "What{SINGLE_QUOTE}s with that crow? He up and{NL}flew off with the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}graveyard key{SPECIAL_02_PAR_1}{END}!{NL}Charge after him and get that key!{END}"


text_280A__089DDF77:
	.string "So, you managed to get the key back?{NL}Keep a tighter grip on it this time!{NL}At least now, you can get into the{NL}graveyard...{END}"

