
text_0B00__089BF294:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Ew! What is that? Is that a{NL}caterpillar? It{SINGLE_QUOTE}s disgusting!{NL}Hey, kid! I{SINGLE_QUOTE}ll just let you{NL}take care of this one!{END}"


text_0B01__089BF304:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What are you doing, talking to me at a{NL}time like this! You{SINGLE_QUOTE}ve got work to do!{END}"


text_0B02__089BF355:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}My word! It has spikes, it jumps...{NL}What can{SINGLE_QUOTE}t it do!? Ah, such a bother!{END}"


text_0B03__089BF3A2:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Ahhhh! Watch your feet!! Such an{NL}inhospitable monster this is!{END}"


text_0B04__089BF3E4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}This must be another guardian,{NL}wouldn{SINGLE_QUOTE}t you agree?{NL}Hm... Knock him down, and he just gets{NL}back up again!{NL}{SPECIAL_06_PAR_1}{END}! It{SINGLE_QUOTE}s time to see if you{NL}can knock him down for good!{END}"


text_0B05__089BF489:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}{SPECIAL_06_PAR_1}{END}! If you need my help, you{NL}know where to find me!{NL}Just give me a shout, and I{SINGLE_QUOTE}ll see{NL}what I can do to lend a...er...beak.{END}"


text_0B06__089BF508:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}, I would imagine that you can{NL}take this thing out with ease now.{NL}Just remember everything I{SINGLE_QUOTE}ve{NL}taught you!{END}"


text_0B07__089BF579:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}This weather{SINGLE_QUOTE}s miserable! I think I{SINGLE_QUOTE}m{NL}catching a cold...{NL}Ah...ah...achoo!{NL}{NL}Oh, don{SINGLE_QUOTE}t worry about me, {SPECIAL_06_PAR_1}{END}.{NL}I{SINGLE_QUOTE}m sure I{SINGLE_QUOTE}ll be just fine... Sniffle...{END}"


text_0B08__089BF60E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}These sky-flying rays will be no match{NL}for my {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}White Sword{SPECIAL_02_PAR_1}{END}!{NL}I mean your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}White Sword{SPECIAL_02_PAR_1}{END}, {SPECIAL_06_PAR_1}{END}!!{END}"


text_0B09__089BF672:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Maybe I forgot to mention it,{NL}but I{SINGLE_QUOTE}m not so good with heights...{NL}But this thing would be a piece of cake{NL}on land, am I not right?{NL}Well, no point worrying about that now!{END}"


text_0B0A__089BF720:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}These Black Knights are{NL}in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s service!{NL}Exercise caution, {SPECIAL_06_PAR_1}{END}!{END}"


text_0B0B__089BF769:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}If we don{SINGLE_QUOTE}t stop {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END} here, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess{NL}Zelda{SPECIAL_02_PAR_1}{END}--and all of Hyrule--is done for!{NL}We cannot allow that to happen,{NL}{SPECIAL_06_PAR_1}{END}!{END}"


text_0B0C__089BF7E5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So this is the true form{NL}of the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}sorcerer {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}!{NL}So dark... So powerful... So evil!{END}"


text_0B0D__089BF841:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}{SPECIAL_06_PAR_1}{END}, judging by the look in your{NL}eyes, I{SINGLE_QUOTE}d say you{SINGLE_QUOTE}ve made up your mind!{NL}Excellent! Perhaps now, we are ready{NL}to face {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}!{END}"


text_0B0E__089BF8C4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}He{SINGLE_QUOTE}s mad with power! He{SINGLE_QUOTE}s nothing but{NL}a swirling mass of raw chaos now!{NL}He will consume everything and reduce{NL}the world to darkness!{NL}If we let him go now, he will engulf{NL}the world in an eternal night!{END}"


text_0B0F__089BF990:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What are you doing!? We{SINGLE_QUOTE}ve no{NL}time for any of your nonsense!{END}"


text_0B10__089BF9D0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Waugh! What a hideous face!{NL}...It{SINGLE_QUOTE}s no good, {SPECIAL_06_PAR_1}{END}.{NL}We tried to settle this peacefully, but{NL}some people can{SINGLE_QUOTE}t be reasoned with...{END}"


text_0B11__089BFA52:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}{SPECIAL_06_PAR_1}{END}, save your breath!{NL}Fight now and talk later!{END}"


text_0B12__089BFA85:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}So this would be the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Deepwood{NL}Shrine{SPECIAL_02_PAR_1}{END} the Minish elder spoke of...{NL}He...said something about there being{NL}monsters inside, didn{SINGLE_QUOTE}t he?{NL}He-Hey now! No reason to be afraid or{NL}anything... I{SINGLE_QUOTE}ll be waiting right here.{NL}No, wait! What am I saying!? I{SINGLE_QUOTE}m not{NL}letting you leave me alone out here!{END}"


text_0B13__089BFBA8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Wow... It{SINGLE_QUOTE}s hot in here! Come on!{NL}Let{SINGLE_QUOTE}s not stand around wasting time!{NL}Find that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}, so we can{NL}get out of here!{END}"


text_0B14__089BFC24:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hm. To think the ruins were hidden{NL}within this cliff the whole time!{NL}Watch your step, {SPECIAL_06_PAR_1}{END}. There{NL}may be traps in here.{END}"


text_0B15__089BFC9D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Who knew there{SINGLE_QUOTE}d be someplace like this{NL}behind one of the town{SINGLE_QUOTE}s fountains?!{NL}Well, let{SINGLE_QUOTE}s get moving and see if we can{NL}find that item those Minish mentioned.{END}"


text_0B16__089BFD3D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Urk... Owowow!! I just smacked my{NL}hip on something!{NL}Well, not my hip... My...whatever it{NL}is I have now... My brim? Whatever!{NL}That old fool must just love sending{NL}people on dangerous missions!{NL}And how did that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END} get into{NL}the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of Droplets{SPECIAL_02_PAR_1}{END}, anyway?{NL}I guess the answer lies up ahead.{NL}Keep moving, boy!{END}"


text_0B17__089BFE7E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Brrr...chatter chatter...{NL}I{SINGLE_QUOTE}m freezing in here...!!{NL}If you don{SINGLE_QUOTE}t find that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element {SPECIAL_02_PAR_1}{END}quickly,{NL}I{SINGLE_QUOTE}m going to turn into a hatsicle!!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}Hurry up, {SPECIAL_06_PAR_1}{END}!{NL}{END}"


text_0B18__089BFF17:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}It may be the Royal Crypt, but graves{NL}are creepy, no matter whose they are!{NL}Where are we supposed to go to meet{NL}this {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}King Gustaf{SPECIAL_02_PAR_1}{END} anyway?{NL}I{SINGLE_QUOTE}m not so sure I even want to anymore!{NL}Can we just go somewhere less creepy?{END}"


text_0B19__089BFFF5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What an irritation! We find our way to{NL}the very tops of the clouds...{NL}And now we have to go even higher{NL}to find a floating palace?{NL}I can{SINGLE_QUOTE}t believe what a long way we{SINGLE_QUOTE}ve{NL}come. And look how high we are!{NL}Don{SINGLE_QUOTE}t look down, {SPECIAL_06_PAR_1}{END}! And watch{NL}your step! It{SINGLE_QUOTE}s a long fall from here!{END}"


text_0B1A__089C0107:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}How much farther do we have to go!?{NL}This place goes on forever!{NL}Ah, there{SINGLE_QUOTE}s no point in complaining{NL}about it. We must press onward!{NL}After all, how much more could there{NL}be? Come on, {SPECIAL_06_PAR_1}{END}! Let{SINGLE_QUOTE}s go!{END}"


text_0B1B__089C01CE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Whoa...!{NL}{NL}Is this really {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}? I can{SINGLE_QUOTE}t{NL}believe it! What{SINGLE_QUOTE}s happened here?{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s magic has grown more{NL}powerful than I{SINGLE_QUOTE}d imagined...{NL}{SPECIAL_03_PAR_2}{END}{BYTE_92}But the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END} and {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Zelda{SPECIAL_02_PAR_1}{END} are in danger,{NL}{SPECIAL_06_PAR_1}{END}! Let{SINGLE_QUOTE}s go!{END}"


text_0B1C__089C02A5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}These raindrops are like boulders of{NL}water to us, kid! Watch out!{NL}If one of them hits us, it{SINGLE_QUOTE}ll sting{NL}something fierce!{END}"


text_0B1D__089C0320:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Hehehe! So, what do you think,{NL}{SPECIAL_06_PAR_1}{END}?{NL}{SPECIAL_01_PAR_1}{NL}Pretty dark and spooky, isn{SINGLE_QUOTE}t it?{NL}Makes you wanna cry, doesn{SINGLE_QUOTE}t it?{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}What? You{SINGLE_QUOTE}re...not scared?{NL}Well, good! Neither am I!{NL}{SPECIAL_03_PAR_2}{END}{BYTE_91}So, um... Come on, let{SINGLE_QUOTE}s go...{END}"


text_0B1E__089C03E4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Wow! Look at the size of that waterfall!{NL}Beautiful! Simply beautiful, my boy!{END}"


text_0B1F__089C0435:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}A stone door!{NL}{NL}So! This was what they meant by all of{NL}that {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}source of the flow{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE} business!{NL}Well, this waterfall certainly is the{NL}source of all Hyrule{SINGLE_QUOTE}s water.{NL}According to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}King Gustaf{SPECIAL_02_PAR_1}{END}, the final{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element {SPECIAL_02_PAR_1}{END}lies somewhere behind the falls.{NL}We{SINGLE_QUOTE}ve dawdled long enough, {SPECIAL_06_PAR_1}{END}!{NL}Let{SINGLE_QUOTE}s go find that element!{END}"


text_0B20__089C056A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What have we here? Some kind{NL}of vortex?{NL}Well, we seem to have hit a dead end...{NL}What shall we do from here?{END}"


text_0B21__089C05D9:
	.string "{SPECIAL_01_PAR_1}{NL}... ...{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}Am I still alive?{NL}{NL}{SPECIAL_01_PAR_1}{NL}... ...{NL}... ...{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_8D}{SPECIAL_06_PAR_1}{END}!!{NL}What were you thinking, child!{NL}You just reaped the whirlwind, as{NL}they say! We could be dead right now!{NL}{SPECIAL_01_PAR_1}{NL}... ...{NL}... ...{NL}...{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}But I must admit, it did the trick!{SPECIAL_03_PAR_2}{END}{BYTE_8E}{NL}Are we...in the land above the clouds?{NL}Then {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}there must be something{SPECIAL_02_PAR_1}{END} here that{NL}can lead us to the final {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}!{NL}Let{SINGLE_QUOTE}s go find it!{END}"


text_0B22__089C0744:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Now how do you build something{NL}like this on top of a cloud?{NL}Maybe someone lives inside. If so,{NL}perhaps we could ask for the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}?{NL}It{SINGLE_QUOTE}s worth a shot, {SPECIAL_06_PAR_1}{END}!{END}"


text_0B23__089C07E7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So this perfectly normal-looking stone{NL}was another {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}portal{SPECIAL_02_PAR_1}{END} to the Minish world!{NL}There may be other {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}rock portals{SPECIAL_02_PAR_1}{END}. Keep{NL}your eyes peeled, boy...{END}"


text_0B24__089C0880:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}That{SINGLE_QUOTE}s right! Even some human objects{NL}are {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}portals{SPECIAL_02_PAR_1}{END} to the Minish world!{NL}Those Minish may not look like much,{NL}but they are quite crafty!{END}"


text_0B25__089C090E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What? ...What is this?{NL}What{SINGLE_QUOTE}s happened here!?{NL}They{SINGLE_QUOTE}ve been turned to stone! All of{NL}them! The minister...and the guards!{NL}Everyone in the castle, all just{NL}like {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}...{NL}This can only be the work of that evil{NL}Vaati! What cruelty. {SPECIAL_06_PAR_1}{END}!{NL}We must use the power of the sacred{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Four Sword{SPECIAL_02_PAR_1}{END} to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}undo this evil{SPECIAL_02_PAR_1}{END}!{END}"


text_0B26__089C0A4F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Once you{SINGLE_QUOTE}ve pulled off their {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}iron masks{SPECIAL_02_PAR_1}{END},{NL}those guys are no trouble whatsoever.{END}"


text_0B27__089C0AA5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Your sword won{SINGLE_QUOTE}t make a dent in their{NL}thorny armor!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Flip them over{SPECIAL_02_PAR_1}{END} before you strike!{END}"


text_0B28__089C0B02:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Don{SINGLE_QUOTE}t panic, {SPECIAL_06_PAR_1}{END}! {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Only one of{NL}them is real!{SPECIAL_02_PAR_1}{END} The rest are fakes!{END}"


text_0B29__089C0B48:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}With their {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}stone masks{SPECIAL_02_PAR_1}{END} on, these{NL}things can put up quite a fight.{NL}If you just unmask them, though, they{NL}won{SINGLE_QUOTE}t pose much of a threat.{END}"


text_0B2A__089C0BD4:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}Hmn?! Hmmmmnnnn...{NL}Ah, of course! How silly of me!{SPECIAL_03_PAR_2}{END}{BYTE_92}{NL}Hey, my boy! {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Jump into that whirlwind{SPECIAL_02_PAR_1}{END}{NL}over there for me!{NL}Heh heh heh... I wonder, is this a{NL}great idea or a terrible one?{END}"


text_0B2B__089C0C8B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Whoa! How about that?! Of all the{NL}places for them to hide a portal!{NL}You{SINGLE_QUOTE}ve done well, my boy. Was that{NL}intuition? Or...just a lucky guess?{SPECIAL_03_PAR_2}{END}{BYTE_90}{END}"


text_0B2C__089C0D1C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Hmn? There{SINGLE_QUOTE}s something fishy about{NL}this area...{NL}I can{SINGLE_QUOTE}t say exactly what, though...{NL}Just something weird in general...{NL}Don{SINGLE_QUOTE}t you feel it?{END}"


text_0B2D__089C0DA9:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Whoa! So there WAS a portal{NL}hidden there!{NL}I knew I sensed something!{END}"


text_0B2E__089C0DF1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So, this must be {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Castor Wilds{SPECIAL_02_PAR_1}{END}...{NL}{NL}It{SINGLE_QUOTE}s a nasty, dank place, filled with{NL}swampland and mire...{NL}But we know there{SINGLE_QUOTE}s an {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END} waiting{NL}for us somewhere in here, so...{NL}In we go! Come on, {SPECIAL_06_PAR_1}{END}!{NL}Into the muck with us!{END}"


text_0B2F__089C0ECF:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Now, that is one nasty-looking statue!{NL}That {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}eye{SPECIAL_02_PAR_1}{END} has such an evil glower to it.{END}"


text_0B30__089C0F25:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}There{SINGLE_QUOTE}s only one thing to do here. Just{NL}break those pots that are in the way!{NL}Stand in front of them and press {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}{NL}to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}lift them over your head{SPECIAL_02_PAR_1}{END}.{NL}Then press it again to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}throw them{SPECIAL_02_PAR_1}{END}!{END}"


text_0B31__089C0FE2:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}With this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}small key{SPECIAL_02_PAR_1}{END}, we should be able{NL}to open any locked door here!{NL}But I should warn you, {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}once you{SINGLE_QUOTE}ve{NL}used the key{SPECIAL_02_PAR_1}{END}, {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}it will vanish{SPECIAL_02_PAR_1}{END} forever.{NL}To use it, just stand in front of{NL}a locked door and press {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}.{END}"


text_0B32__089C10BD:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Do you see that lever? I think you{NL}should be able to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}pull it{SPECIAL_02_PAR_1}{END}.{NL}Just stand in front of it and press {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}{NL}to grab it, then press {SPECIAL_0C_PAR_1}{SPECIAL_05_PAR_1} to pull.{END}"


text_0B33__089C114C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Once you take hold of something with{NL}{SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}, use {SPECIAL_0C_PAR_1}{BYTE_08} to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}push{SPECIAL_02_PAR_1}{END} or {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}pull{SPECIAL_02_PAR_1}{END} it.{NL}This is extremely important, so I hope{NL}you take pains to remember it!{END}"


text_0B34__089C11E1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Wow! Look at the size of that barrel!{NL}{NL}Hm? Oh, right! Right! How silly of me!{NL}It{SINGLE_QUOTE}s not big{SPECIAL_0F_PAR_1}{BYTE_16} {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}we{SINGLE_QUOTE}re just small{SPECIAL_02_PAR_1}{END}!{END}"


text_0B35__089C1257:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Wha--!? Hey, be careful, my lad!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}The barrel just moved{SPECIAL_02_PAR_1}{END}!{END}"


text_0B36__089C1296:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}What we need now is something to{NL}hold down this switch...{END}"


text_0B37__089C12D3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Now what?{NL}{NL}Unless we find a way to travel by{NL}water, we won{SINGLE_QUOTE}t be going much farther.{END}"


text_0B38__089C132A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}This must be what the humans who built{NL}this mine used to get around in here.{NL}Maybe we should hop in.{NL}{NL}Hm? What? After all this, you don{SINGLE_QUOTE}t{NL}expect me to believe you{SINGLE_QUOTE}re scared!{NL}There{SINGLE_QUOTE}s nothing to be afraid of here!{NL}Come on, let{SINGLE_QUOTE}s go!{END}"


text_0B39__089C1414:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_93}Sweet jumping jellyfish, that was awful!{NL}Hey, kid, what are you smiling about?{NL}I knew it was madness to risk our lives{NL}in that rickety human contraption!{NL}From now on, let{SINGLE_QUOTE}s just stick to our{NL}feet! Well, I mean...your feet.{END}"


text_0B3A__089C14F6:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Oh my! It looks really, REALLY{NL}hot in that lava!{NL}Trust me: falling into that would{NL}be a bad idea. I{SINGLE_QUOTE}m sure you agree.{END}"


text_0B3B__089C156F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}How interesting! So there was a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}portal{SPECIAL_02_PAR_1}{END}{NL}hidden away in here, hm?{NL}Whenever you want me to shrink you{NL}down, just hop up here and press {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}!{END}"


text_0B3C__089C15FE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Phew...! We barely made it! I was{NL}certain we{SINGLE_QUOTE}d run out of time!{END}"


text_0B3D__089C1641:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hmn?! Did something just fall down,{NL}or was it just my imagination?{END}"


text_0B3E__089C1687:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}What?! This floor is made out of ice!{NL}{NL}Be careful not to fall and freeze{NL}your backside to the floor, {SPECIAL_06_PAR_1}{END}!{END}"


text_0B3F__089C16F3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hm. It looks like something is frozen{NL}inside this block of ice...{NL}{SPECIAL_06_PAR_1}{END}, why don{SINGLE_QUOTE}t you go take a{NL}look?{END}"


text_0B40__089C175A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hey! The sunlight{SINGLE_QUOTE}s shining through!{NL}{NL}Ahhh... It{SINGLE_QUOTE}s so nice and warm. I can{NL}feel myself starting to defrost again.{END}"


text_0B41__089C17CF:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_04_PAR_2}{BYTE_10}{END}Hey...!!{NL}{NL}Well done, {SPECIAL_06_PAR_1}{END}!{NL}This looks to be the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}, all right.{NL}But what will we do?{NL}{NL}We can{SINGLE_QUOTE}t even touch it while it{SINGLE_QUOTE}s{NL}trapped in that ice...{NL}We{SINGLE_QUOTE}ll need to melt it off somehow...{END}"


text_0B42__089C188F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Of course! Sunlight! Once we get some{NL}sunlight in to melt the ice,{NL}that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element {SPECIAL_02_PAR_1}{END}will be as good as ours!{NL}{END}"


text_0B43__089C1900:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}We did it, {SPECIAL_06_PAR_1}{END}!{NL}Now we can take the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}!{NL}That was a lot of trouble,{NL}but we finally did it, and...{NL}What in blazes!?{NL}{NL}Hey, something{SINGLE_QUOTE}s not right here!!{END}"


text_0B44__089C19A0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}What!? What{SINGLE_QUOTE}s this?!{NL}{NL}That stupid Octorok stole our {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element{SPECIAL_02_PAR_1}{END}!{NL}{NL}Don{SINGLE_QUOTE}t just stand there! We{SINGLE_QUOTE}ve got to go{NL}get it! {SPECIAL_06_PAR_1}{END}! Now!{END}"


text_0B45__089C1A1E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}{SPECIAL_06_PAR_1}{END}! Where are you?{NL}Are you still there under me?{NL}It{SINGLE_QUOTE}s so dark, I can{SINGLE_QUOTE}t see my beak{NL}in front of my face!{NL}Watch your step! I don{SINGLE_QUOTE}t want you{NL}to trip over anything...{END}"


text_0B46__089C1AC4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Oh my! There was a portal hidden{NL}in there?{END}"


text_0B47__089C1AF2:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}There{SINGLE_QUOTE}s a fluffy cloud floating here.{NL}It looks awfully comfortable.{END}"


text_0B48__089C1B39:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}That panel... I think if we stomped on{NL}it hard enough, it might flip over...{END}"


text_0B49__089C1B89:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}There{SINGLE_QUOTE}s a strong gale blowing here!{NL}Try not to get swept away!{NL}And hold on to your hat!{END}"


text_0B4A__089C1BE4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Perhaps your sword could reflect the{NL}blasts coming from those statues.{END}"


text_0B4B__089C1C2E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}What in the world is that?!{END}"


text_0B4C__089C1C4D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmmm... Yes, yes... It certainly{NL}does look suspicious...{END}"


text_0B4D__089C1C89:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Huh? Wha--? What in the world!?{END}"


text_0B4E__089C1CAC:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8F}My word! It{SINGLE_QUOTE}s a treasure chest!{END}"


text_0B4F__089C1CCF:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8F}There seems to be a switch here!{END}"


text_0B50__089C1CF3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8F}Oh, a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Piece of Heart{SPECIAL_02_PAR_1}{END}!{NL}Well, that IS useful.{END}"


text_0B51__089C1D26:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}So this is your house...{NL}Well, it seems like a nice place.{NL}...So, where{SINGLE_QUOTE}s my room?{END}"


text_0B52__089C1D7C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}So! This is your room? That makes it{NL}my room, too, right?{END}"


text_0B53__089C1DB9:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}I sense something unusual here...{NL}Is it something hidden?{NL}I won{SINGLE_QUOTE}t tell anyone, so come on!{NL}Show me!{END}"


text_0B54__089C1E20:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Why, this is the shopkeeper{NL}Stockwell{SINGLE_QUOTE}s house!{NL}You can tell much about a person{NL}from the house he keeps, hm?{NL}It{SINGLE_QUOTE}s pretty unusual, even by Hyrulean{NL}standards. It even has a pool!{END}"


text_0B55__089C1ED5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}That mustachioed guy strikes me as{NL}somewhat unreliable.{NL}There{SINGLE_QUOTE}s something fishy about this{NL}room, too.{END}"


text_0B56__089C1F3E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}Sniff sniff sniff! Mmmm, doesn{SINGLE_QUOTE}t that{NL}smell spectacular?{NL}Perhaps they give out free samples.{NL}I say, would you...ask for me?{END}"


text_0B57__089C1FBD:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}There seem to be many interesting{NL}books in here...{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Hyrule on 10 Rupees a Day{SPECIAL_02_PAR_1}{END},{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}So Your Son Wants to Be a Hero{SPECIAL_02_PAR_1}{END}...{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}It Could Be Verse!{SPECIAL_02_PAR_1}{END}, by Percy, and{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Rem{SINGLE_QUOTE}s Anthology for Sleepless Nights{SPECIAL_02_PAR_1}{END}.{NL}Hmmm, they all look pretty good,{NL}but which one to read first?{END}"


text_0B58__089C20CE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Are you sure I look all right? I never{NL}know what to wear to formal occasions.{END}"


text_0B59__089C211F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}How tranquil...{NL}And those cows look so...delicious.{END}"


text_0B5A__089C2156:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Whoa! Did you see that cat looking{NL}at me?! I know it wants a piece of me!{END}"


text_0B5B__089C21A3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Waaah! That really startled me!{NL}Everything{SINGLE_QUOTE}s scary when you{SINGLE_QUOTE}re small!{END}"


text_0B5C__089C21EC:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hm? Whoa! It...blew up?{NL}{NL}Hey, kid! Look at where that stone{NL}marker used to be...{NL}There{SINGLE_QUOTE}s some strange {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}symbol {SPECIAL_02_PAR_1}{END}on the{NL}ground.{NL}Yes, of course{SPECIAL_01_PAR_1}{NL}... Why, this must be...{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}...Well, I haven{SINGLE_QUOTE}t the foggiest, to be{NL}honest. Hm...{END}"


text_0B5D__089C22D0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hey! That stone marker crumbled! And{NL}there{SINGLE_QUOTE}s another of those {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}symbols{SPECIAL_02_PAR_1}{END}!{NL}...You know, no matter how many times{NL}I see that happen, it still rattles me.{END}"


text_0B5E__089C236C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hey! We{SINGLE_QUOTE}ve found another {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Wind Crest{SPECIAL_02_PAR_1}{END}!{NL}{NL}Now we have one more point of travel{NL}when we use the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Ocarina of Wind{SPECIAL_02_PAR_1}{END}!{END}"


text_0B5F__089C23E3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Aha!! So that mysterious mark we{SINGLE_QUOTE}ve{NL}been seeing is a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Wind Crest{SPECIAL_02_PAR_1}{END}.{NL}If you play the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Ocarina of Wind{SPECIAL_02_PAR_1}{END}, Zeffa{NL}comes to pick you up and fly you away.{NL}That means we can have Zeffa carry us{NL}to any other {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Wind Crest{SPECIAL_02_PAR_1}{END} we{SINGLE_QUOTE}ve seen.{NL}Are you following me, {SPECIAL_06_PAR_1}{END}?{NL}Don{SINGLE_QUOTE}t hurt your brain thinking about it.{NL}Just give it a try, and you{SINGLE_QUOTE}ll see what{NL}I{SINGLE_QUOTE}m talking about.{END}"


text_0B60__089C2549:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hmn?!{NL}Say, look at that, {SPECIAL_06_PAR_1}{END}!{NL}There{SINGLE_QUOTE}s a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}book {SPECIAL_02_PAR_1}{END}up on top of the{NL}bookcase!{NL}But how are we going to get it? We{NL}can{SINGLE_QUOTE}t reach it, and we have no ladder.{NL}And I don{SINGLE_QUOTE}t think just shaking the{NL}bookcase will make it fall, either.{NL}This presents an interesting{NL}problem, wouldn{SINGLE_QUOTE}t you say?{END}"


text_0B61__089C2660:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hey now! You can{SINGLE_QUOTE}t just go waltzing{NL}into people{SINGLE_QUOTE}s homes like that!{NL}If the owner isn{SINGLE_QUOTE}t home, you{SINGLE_QUOTE}ll just{NL}have to come back later.{END}"


text_0B62__089C26E4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hm. This house appears to be empty...{NL}Maybe we shouldn{SINGLE_QUOTE}t go in here.{END}"


text_0B63__089C272C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hm? That{SINGLE_QUOTE}s unfortunate...{NL}They{SINGLE_QUOTE}re not open yet.{NL}Ah, well. We{SINGLE_QUOTE}ll just have to come{NL}back later, won{SINGLE_QUOTE}t we?{END}"


text_0B64__089C2797:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}The door is shut.{NL}We can{SINGLE_QUOTE}t open it from this side{SPECIAL_01_PAR_1}{NL}...{END}"


text_0B65__089C27D1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hey, you don{SINGLE_QUOTE}t have any {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{NL}pieces{SPECIAL_02_PAR_1}{END}!{NL}How can you fuse Kinstones if you{NL}don{SINGLE_QUOTE}t have any Kinstone pieces!?{END}"


text_0B66__089C2844:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}I don{SINGLE_QUOTE}t think we can walk fast enough{NL}to cross this swamp.{NL}We{SINGLE_QUOTE}re going to have to find some way{NL}to get across safely...{END}"


text_0B67__089C28BF:
	.string "{END}"


text_0B68__089C28C0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hey, kid! Why don{SINGLE_QUOTE}t you take that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Cane{NL}of Pacci{SPECIAL_02_PAR_1}{END} and fire it at that hole?{NL}I mean, you never know what{SINGLE_QUOTE}ll happen{NL}until you try, right?{END}"


text_0B69__089C294D:
	.string "{END}"


text_0B6A__089C294E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_91}Oooooog. I{SINGLE_QUOTE}m sure I{SINGLE_QUOTE}ve mentioned this{NL}before, but I{SINGLE_QUOTE}m no good with heights.{NL}Wait, hold on... I think I see{NL}something down there!{NL}Sigh... I guess that means we have to{NL}take the plunge after all, hm?{END}"


text_0B6B__089C2A17:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Hmph! There{SINGLE_QUOTE}s a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}locked{SPECIAL_02_PAR_1}{END} door here! See if{NL}you can find a key to open it.{END}"


text_0B6C__089C2A66:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}That noise just now! What was that?{NL}Something must have happened...{NL}Be careful, {SPECIAL_06_PAR_1}{END}!!{END}"


text_0B6D__089C2ABE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmm! Yes, yes, yes! Why, it all makes{NL}sense now, doesn{SINGLE_QUOTE}t it, boy?{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Librari{SPECIAL_02_PAR_1}{END} used these {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}flippers {SPECIAL_02_PAR_1}{END}to swim to{NL}the entrance to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of Droplets{SPECIAL_02_PAR_1}{END}.{NL}So, if you put these on, you should be{NL}able to swim, too! Remarkable!{END}"


text_0B6E__089C2BA4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}If I recall correctly, and I guarantee{NL}that I do, my boy...{NL}I think Syrup said to stand in front of{NL}a sleeping person and press {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}.{END}"


text_0B6F__089C2C2B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Now there{SINGLE_QUOTE}s a puzzler...{SPECIAL_01_PAR_1}{NL}{NL}{NL}{SPECIAL_01_PAR_1}{SPECIAL_01_PAR_1}I suspect there{SINGLE_QUOTE}s not much more we can{NL}do here right now. Let{SINGLE_QUOTE}s press on.{NL}Perhaps we can work this from another{NL}angle later on.{END}"


text_0B70__089C2CCC:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}That hand is a real pain, {SPECIAL_06_PAR_1}{END}.{NL}{NL}Perhaps one of those gizmos you carry{NL}around can do something to it!{END}"

