
text_4800__089F4778:
	.string "{END}"


text_4801__089F4779:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}Oh, ho! A visitor! How rare!{NL}{NL}But you have found me, the{NL}wisest of the wisest of the wise!{NL}You what? You want to enter the{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}temple you can see in the lake{SPECIAL_02_PAR_1}{END}?{NL}They call that place the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Temple of{NL}Droplets{SPECIAL_02_PAR_1}{END}.{NL}I have heard rumors that one Minish{NL}actually did find a way in, long ago...{NL}That Minish is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Elder Librari{SPECIAL_02_PAR_1}{END}, and he is{NL}in semi-retirement in the town library.{NL}The library should be opening soon.{NL}Perhaps you can go find him.{END}"


text_4802__089F492D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Yes, the elder Librari once found an{NL}entrance to the Temple of Droplets.{NL}And now, he lives in the town library!{NL}{NL}And this is all the wisdom of the wisest{NL}of the wise I have to offer you!{END}"


text_4803__089F49EB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}So you met with elder Librari?!{NL}{NL}And he said that he really HAS been{NL}inside of the Temple of Droplets?{NL}I knew it! Once again, my wisdom has{NL}surpassed the wisdom of the wisest!{END}"


text_4804__089F4A9E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}I have lots of wise and thought-{NL}provoking information...{NL}But nothing for you right now.{END}"


text_4805__089F4AFA:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Hello! How nice to have a visitor!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}{NL}But...I{SINGLE_QUOTE}m having some trouble!{NL}{NL}They{SINGLE_QUOTE}ve changed the room around, and{NL}now I can{SINGLE_QUOTE}t get into the fireplace!{END}"


text_4806__089F4B8C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}They{SINGLE_QUOTE}ve changed the room around!{NL}It{SINGLE_QUOTE}s terrible now! So gauche!{END}"


text_4807__089F4BCE:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Thank you! Now I can climb in through{NL}the fireplace and get some sleep!{END}"


text_4808__089F4C19:
	.string "{END}"

