
text_0800__089B9FB4:
	.string "{SPECIAL_04_PAR_2}{BYTE_15}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_04_PAR_2}{BYTE_14}:{SPECIAL_07_PAR_1}{BYTE_08}{END}"


text_0801__089B9FBF:
	.string "Capless {SPECIAL_06_PAR_1}{END}{END}"


text_0802__089B9FCA:
	.string "Ezlo and {SPECIAL_06_PAR_1}{END}{END}"


text_0803__089B9FD6:
	.string "Princess Zelda{END}"


text_0804__089B9FE5:
	.string "Ezlo (Cap){END}"


text_0805__089B9FF0:
	.string "Sorcerer Vaati{END}"


text_0806__089B9FFF:
	.string "King Daltus{END}"


text_0807__089BA00B:
	.string "Minister Potho{END}"


text_0808__089BA01A:
	.string "Smith{END}"


text_0809__089BA020:
	.string "Mayor Hagen{END}"


text_080A__089BA02C:
	.string "Marcy{END}"


text_080B__089BA032:
	.string "Stamp{END}"


text_080C__089BA038:
	.string "Rem{END}"


text_080D__089BA03C:
	.string "Dr. Left{END}"


text_080E__089BA045:
	.string "Carlov{END}"


text_080F__089BA04C:
	.string "Borlov{END}"


text_0810__089BA053:
	.string "Stockwell{END}"


text_0811__089BA05D:
	.string "Simon{END}"


text_0812__089BA063:
	.string "Gorman{END}"


text_0813__089BA06A:
	.string "Anju{END}"


text_0814__089BA06F:
	.string "Brocco{END}"


text_0815__089BA076:
	.string "Pina{END}"


text_0816__089BA07B:
	.string "Beedle{END}"


text_0817__089BA082:
	.string "Postman{END}"


text_0818__089BA08A:
	.string "Crenel Hermit{END}"


text_0819__089BA098:
	.string "Monster Lady{END}"


text_081A__089BA0A5:
	.string "Damp{BYTE_E9}{END}"


text_081B__089BA0AB:
	.string "Gustaf, Royal Spirit{END}"


text_081C__089BA0C0:
	.string "Syrup{END}"


text_081D__089BA0C6:
	.string "Great Butterfly Fairy{END}"


text_081E__089BA0DC:
	.string "Great Mayfly Fairy{END}"


text_081F__089BA0EF:
	.string "Great Dragonfly Fairy{END}"


text_0820__089BA105:
	.string "Percy{END}"


text_0821__089BA10B:
	.string "Nayru{END}"


text_0822__089BA111:
	.string "Farore{END}"


text_0823__089BA118:
	.string "Din{END}"


text_0824__089BA11C:
	.string "Joy Butterfly{END}"


text_0825__089BA12A:
	.string "Gina{END}"


text_0826__089BA12F:
	.string "Festari{END}"


text_0827__089BA137:
	.string "Gentari{END}"


text_0828__089BA13F:
	.string "Forest Picori{END}"


text_0829__089BA14D:
	.string "Librari{END}"


text_082A__089BA155:
	.string "Town Picori{END}"


text_082B__089BA161:
	.string "Melari{END}"


text_082C__089BA168:
	.string "Mountain Picori{END}"


text_082D__089BA178:
	.string "Goron{END}"


text_082E__089BA17E:
	.string "Minish Vaati{END}"


text_082F__089BA18B:
	.string "Vassals{END}"


text_0830__089BA193:
	.string "Library{END}"


text_0831__089BA19B:
	.string "Blade Brothers{END}"


text_0832__089BA1AA:
	.string "Wheaton {SPECIAL_0F_PAR_1}{BYTE_0D} Pita{END}"


text_0833__089BA1BA:
	.string "Funday School{END}"


text_0834__089BA1C8:
	.string "Mama{SINGLE_QUOTE}s Cafe{END}"


text_0835__089BA1D4:
	.string "Happy Hearth Inn{END}"


text_0836__089BA1E5:
	.string "Zill and Friends{END}"


text_0837__089BA1F6:
	.string "The Carpenters{END}"


text_0838__089BA205:
	.string "Young Couple{END}"


text_0839__089BA212:
	.string "Peaceful Hyrule 1{END}"


text_083A__089BA224:
	.string "Peaceful Hyrule 2{END}"


text_083B__089BA236:
	.string "Peaceful Hyrule 3{END}"


text_083C__089BA248:
	.string "Cucco!{END}"


text_083D__089BA24F:
	.string "At Lon Lon Ranch{END}"


text_083E__089BA260:
	.string "The Wind Tribe{END}"


text_083F__089BA26F:
	.string "Gregal {SPECIAL_0F_PAR_1}{BYTE_0D} the Ghost{END}"


text_0840__089BA283:
	.string "Tingle Siblings?{END}"


text_0841__089BA294:
	.string "Eenie {SPECIAL_0F_PAR_1}{BYTE_0D} Meenie{END}"


text_0842__089BA2A4:
	.string "Goron Merchant{END}"


text_0843__089BA2B3:
	.string "Spookter {SPECIAL_0F_PAR_1}{BYTE_0D} Spekter{END}"


text_0844__089BA2C7:
	.string "Sluggula{END}"


text_0845__089BA2D0:
	.string "Scissors Beetle{END}"


text_0846__089BA2E0:
	.string "Moldworm{END}"


text_0847__089BA2E9:
	.string "Spiked Beetle{END}"


text_0848__089BA2F7:
	.string "Eyegore Statue{END}"


text_0849__089BA306:
	.string "Business Scrub{END}"


text_084A__089BA315:
	.string "Armos{END}"


text_084B__089BA31B:
	.string "Keese{END}"


text_084C__089BA321:
	.string "Keaton{END}"


text_084D__089BA328:
	.string "Ghini{END}"


text_084E__089BA32E:
	.string "Gibdo{END}"


text_084F__089BA334:
	.string "Rollobite{END}"


text_0850__089BA33E:
	.string "Spark{END}"


text_0851__089BA344:
	.string "Dark Nut{END}"


text_0852__089BA34D:
	.string "Red Dark Nut{END}"


text_0853__089BA35A:
	.string "Chaser{END}"


text_0854__089BA361:
	.string "Rock Chuchu{END}"


text_0855__089BA36D:
	.string "Moldorm{END}"


text_0856__089BA375:
	.string "Door Mimic{END}"


text_0857__089BA380:
	.string "Peahat{END}"


text_0858__089BA387:
	.string "Helmasaur{END}"


text_0859__089BA391:
	.string "Wall Master{END}"


text_085A__089BA39D:
	.string "Floor Master{END}"


text_085B__089BA3AA:
	.string "Acro-Bandits{END}"


text_085C__089BA3B7:
	.string "Bob-omb{END}"


text_085D__089BA3BF:
	.string "Bombarossa{END}"


text_085E__089BA3CA:
	.string "Like Like{END}"


text_085F__089BA3D4:
	.string "Rupee Like{END}"


text_0860__089BA3DF:
	.string "Rope{END}"


text_0861__089BA3E4:
	.string "Boulder{END}"


text_0862__089BA3EC:
	.string "Ball {SPECIAL_0F_PAR_1}{BYTE_0D} Chain Soldier{END}"


text_0863__089BA402:
	.string "Spiny Beetle{END}"


text_0864__089BA40F:
	.string "Spear Moblin{END}"


text_0865__089BA41C:
	.string "Bow Moblin{END}"


text_0866__089BA427:
	.string "Cloud Piranha{END}"


text_0867__089BA435:
	.string "Mulldozer{END}"


text_0868__089BA43F:
	.string "Pesto{END}"


text_0869__089BA445:
	.string "Puffstool{END}"


text_086A__089BA44F:
	.string "Wizzrobe{END}"


text_086B__089BA458:
	.string "Fire Wizzrobe{END}"


text_086C__089BA466:
	.string "Ice Wizzrobe{END}"


text_086D__089BA473:
	.string "Wisp{END}"


text_086E__089BA478:
	.string "Octorok{END}"


text_086F__089BA480:
	.string "Golden Octorok{END}"


text_0870__089BA48F:
	.string "Golden Tektite{END}"


text_0871__089BA49E:
	.string "Golden Rope{END}"


text_0872__089BA4AA:
	.string "Crow {SPECIAL_0F_PAR_1}{BYTE_0D} Takkuri{END}"


text_0873__089BA4BA:
	.string "Lakitu{END}"


text_0874__089BA4C1:
	.string "Stalfos{END}"


text_0875__089BA4C9:
	.string "Beetle{END}"


text_0876__089BA4D0:
	.string "Chuchu{END}"


text_0877__089BA4D7:
	.string "Tektite{END}"


text_0878__089BA4DF:
	.string "Trap{END}"


text_0879__089BA4E4:
	.string "Leever{END}"


text_087A__089BA4EB:
	.string "Madderpillar{END}"


text_087B__089BA4F8:
	.string "Spiny Chuchu{END}"


text_087C__089BA505:
	.string "Big Octorok{END}"


text_087D__089BA511:
	.string "Gyorg Pair{END}"


text_087E__089BA51C:
	.string "Biggoron{END}"


text_087F__089BA525:
	.string "Big Green Chuchu{END}"


text_0880__089BA536:
	.string "Gleerok{END}"


text_0881__089BA53E:
	.string "Mazaal{END}"


text_0882__089BA545:
	.string "Big Blue Chuchu{END}"


text_0883__089BA555:
	.string "Zelda {SPECIAL_0F_PAR_1}{BYTE_0D} {SPECIAL_06_PAR_1}{END}{END}"


text_0884__089BA561:
	.string "Minish Ezlo{END}"


text_0885__089BA56D:
	.string "Black Knight{END}"


text_0886__089BA57A:
	.string "Vaati Reborn{END}"


text_0887__089BA587:
	.string "Vaati Transfigured{END}"


text_0888__089BA59A:
	.string "Vaati{SINGLE_QUOTE}s Wrath{END}"


text_0889__089BA5A8:
	.string "- - - - - - - - -{END}"

