
text_0500__089B6404:
	.string "...{END}"


text_0501__089B6408:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_0C_PAR_1}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Smith{SINGLE_QUOTE}s Sword{SPECIAL_02_PAR_1}{END}! It{SINGLE_QUOTE}s a sharp{NL}blade made by your grandfather.{END}"


text_0502__089B6457:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}White Sword{SPECIAL_02_PAR_1}{END}! Its beautiful{NL}white blade sparkles with light!{NL}You can put away your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}grandfather{SINGLE_QUOTE}s{NL}sword{SPECIAL_02_PAR_1}{END} now.{END}"


text_0503__089B64D9:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}The powers of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth{SPECIAL_02_PAR_1}{END} and {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Fire{NL}Elements{SPECIAL_02_PAR_1}{END} have infused your blade!{END}"


text_0504__089B6527:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}The power of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Water Element{SPECIAL_02_PAR_1}{END}{NL}has infused your blade!{NL}The power of this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}element {SPECIAL_02_PAR_1}{END}allows you to{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}split into three copies{SPECIAL_02_PAR_1}{END}!{END}"


text_0505__089B65AE:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}The power of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Wind Element{SPECIAL_02_PAR_1}{END}{NL}has infused your blade!{NL}{SPECIAL_07_PAR_1}{SPECIAL_05_PAR_1}{SPECIAL_06_PAR_1}{END}{SPECIAL_04_PAR_2}{BYTE_10}{END}With the power of the four elements,{NL}your blade has become the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Four Sword{SPECIAL_02_PAR_1}{END}!{NL}Focus power in your blade and release{NL}to fire a beam.{NL}Use it to break Vaati{SINGLE_QUOTE}s curse and{NL}restore the people of Hyrule.{END}"


text_0506__089B65EF:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}With the power of the four elements,{NL}your blade has become the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Four Sword{SPECIAL_02_PAR_1}{END}!{NL}Focus power in your blade and release{NL}to fire a beam.{NL}Use it to break Vaati{SINGLE_QUOTE}s curse and{NL}restore the people of Hyrule.{END}"


text_0507__089B66B7:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Bomb Bag{SPECIAL_02_PAR_1}{END}!{NL}{NL}And it has ten {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs{SPECIAL_02_PAR_1}{END} in it!{NL}Now you can blow up lots of stuff!{END}"


text_0508__089B6716:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Remote Bomb{SPECIAL_02_PAR_1}{END}!{NL}{NL}Press the button to place a bomb, then{NL}press the button again to detonate it.{END}"


text_0509__089B6783:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bow{SPECIAL_02_PAR_1}{END}! Now you can take{NL}out enemies from afar!{END}"


text_050A__089B67C1:
	.string "You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Light Arrow{SPECIAL_02_PAR_1}{END}! Now, you can{NL}fire arrows filled with sacred light!{END}"


text_050B__089B6811:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}boomerang{SPECIAL_02_PAR_1}{END}! This well-{NL}crafted weapon returns when thrown!{END}"


text_050C__089B6859:
	.string "You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Magical Boomerang{SPECIAL_02_PAR_1}{END}!{NL}{NL}Hold the button you threw it with and{NL}use {SPECIAL_0C_PAR_1}{BYTE_08} to control its path!{END}"


text_050D__089B68BF:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}Princess Zelda gave you a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}small shield{SPECIAL_02_PAR_1}{END}!{NL}{NL}Hold the button to protect yourself.{NL}{NL}...It IS a little embarrassing, though.{NL}It{SINGLE_QUOTE}s so tiny!{END}"


text_050E__089B694B:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mirror Shield{SPECIAL_02_PAR_1}{END}!{NL}{NL}This mighty shield shines like a mirror.{NL}Use it to reflect enemy attacks!{END}"


text_050F__089B69B8:
	.string "You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Flame Lantern{SPECIAL_02_PAR_1}{END}!{NL}{NL}This handy item lights up the night!{NL}Press the button to turn it on or off.{END}"


text_0510__089B6A24:
	.string "Flame Lantern (Fire){NL}{NL}On your Items screen, equip it to either{NL}{SPECIAL_0C_PAR_1}{END} or {SPECIAL_0C_PAR_1}{SPECIAL_01_PAR_1} to use it!{END}"


text_0511__089B6A77:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Gust Jar{SPECIAL_02_PAR_1}{END}!{NL}{NL}Hold the button to draw things in,{NL}and release it to fire them out!{NL}Set it to {SPECIAL_0C_PAR_1}{END} or {SPECIAL_0C_PAR_1}{SPECIAL_01_PAR_1} on the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Items screen{SPECIAL_02_PAR_1}{END}{NL}to use it!{END}"


text_0512__089B6B0F:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Cane of Pacci{SPECIAL_02_PAR_1}{END}!{NL}{NL}This mystical rod has the power to{NL}flip things over.{NL}Use it to charge up energy in holes{NL}and then flip up on out of it!{END}"


text_0513__089B6BAA:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mole Mitts{SPECIAL_02_PAR_1}{END}! Dig, dig,{NL}dig to your heart{SINGLE_QUOTE}s content!{END}"


text_0514__089B6BF0:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Roc{SINGLE_QUOTE}s Cape{SPECIAL_02_PAR_1}{END}!{NL}{NL}Jump with the greatest of ease!{NL}Hold the button to jump farther.{END}"


text_0515__089B6C51:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Pegasus Boots{SPECIAL_02_PAR_1}{END}! Hold the{NL}button to run faster than the wind!{END}"


text_0516__089B6CA0:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Fire Rod{SPECIAL_02_PAR_1}{END}! This mystical rod{NL}shoots forth mighty flames.{END}"


text_0517__089B6CEB:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Ocarina of Wind{SPECIAL_02_PAR_1}{END}!{NL}{NL}North, south, east, and west are{NL}all just a breath away!{END}"


text_0518__089B6D49:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Piece of Heart{SPECIAL_02_PAR_1}{END}!{NL}{NL}Collect four to make a new Heart{NL}Container for even more {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}life energy{SPECIAL_02_PAR_1}{END}!{END}"


text_0519__089B6DB2:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Piece of Heart{SPECIAL_02_PAR_1}{END}!{NL}{NL}Now you have two pieces. {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Collect two{NL}more{SPECIAL_02_PAR_1}{END} to increase your life energy!{END}"


text_051A__089B6E1D:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Piece of Heart{SPECIAL_02_PAR_1}{END}!{NL}{NL}You now have three. {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Collect just one{NL}more{SPECIAL_02_PAR_1}{END} to increase your life energy!{END}"


text_051B__089B6E88:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Piece of Heart{SPECIAL_02_PAR_1}{END}!{NL}{NL}You completed a new Heart Container!{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Your life energy has been replenished{NL}and increased!{END}"


text_051C__089B6F04:
	.string "You swapped for {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs{SPECIAL_02_PAR_1}{END}!{END}"


text_051D__089B6F1F:
	.string "You bought a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}small shield{SPECIAL_02_PAR_1}{END}!{END}"


text_051E__089B6F3E:
	.string "{END}"


text_051F__089B6F3F:
	.string "{END}"


text_0520__089B6F40:
	.string "You got an {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}empty bottle{SPECIAL_02_PAR_1}{END}!{NL}Use it to store all sorts of things.{END}"


text_0521__089B6F82:
	.string "Your Lon Lon Milk turned into {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}butter{SPECIAL_02_PAR_1}{END}!{NL}It{SINGLE_QUOTE}s very fresh and delicious!{END}"


text_0522__089B6FCB:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon Milk{SPECIAL_02_PAR_1}{END}!{END}"


text_0523__089B6FED:
	.string "{END}"


text_0524__089B6FEE:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}red potion{SPECIAL_02_PAR_1}{END}! Drink it to{NL}replenish all of your life energy!{END}"


text_0525__089B703A:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}blue potion{SPECIAL_02_PAR_1}{END}! Drink it to{NL}replenish your life energy.{END}"


text_0526__089B7080:
	.string "You put {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}water{SPECIAL_02_PAR_1}{END} in your bottle!{NL}Sprinkle it on different things!{END}"


text_0527__089B70C3:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You put {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mt. Crenel Mineral Water{SPECIAL_02_PAR_1}{END} in your{NL}bottle! It{SINGLE_QUOTE}s piping hot!{END}"


text_0528__089B710C:
	.string "You caught a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}fairy{SPECIAL_02_PAR_1}{END} in your bottle!{NL}{NL}This winged friend will come to your{NL}aid if your life energy is depleted.{END}"


text_0529__089B717E:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Red Picolyte{SPECIAL_02_PAR_1}{END}! If you use{NL}it, you might find lots of hearts!{END}"


text_052A__089B71CE:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Orange Picolyte{SPECIAL_02_PAR_1}{END}! If you{NL}use it, you might find lots of fairies!{END}"


text_052B__089B7222:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Yellow Picolyte{SPECIAL_02_PAR_1}{END}! If you use{NL}it, you might find lots of Rupees!{END}"


text_052C__089B7275:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Green Picolyte{SPECIAL_02_PAR_1}{END}! If you{NL}use it, you might find lots of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shells{SPECIAL_02_PAR_1}{END}!{END}"


text_052D__089B72CB:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Blue Picolyte{SPECIAL_02_PAR_1}{END}! If you use{NL}it, you might find lots of items!{END}"


text_052E__089B731B:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}White Picolyte{SPECIAL_02_PAR_1}{END}! If you use{NL}it, you might find lots of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstones{SPECIAL_02_PAR_1}{END}!{END}"


text_052F__089B7374:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Nayru{SINGLE_QUOTE}s Charm{SPECIAL_02_PAR_1}{END}! Your guard{NL}will be strengthened for a while!{END}"


text_0530__089B73BF:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Farore{SINGLE_QUOTE}s Charm{SPECIAL_02_PAR_1}{END}! Your power and{NL}guard will be boosted for a while!{END}"


text_0531__089B7410:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Din{SINGLE_QUOTE}s Charm{SPECIAL_02_PAR_1}{END}! Your strength will{NL}be boosted for a while!{END}"


text_0532__089B7457:
	.string "{END}"


text_0533__089B7458:
	.string "{END}"


text_0534__089B7459:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You accepted the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Smith{SINGLE_QUOTE}s Sword{SPECIAL_02_PAR_1}{END}!{NL}{NL}Make sure you don{SINGLE_QUOTE}t lose this extremely{NL}important delivery!{END}"


text_0535__089B74BD:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_0C_PAR_1}You accepted the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Broken Picori Blade{SPECIAL_02_PAR_1}{END}!{NL}{NL}This is part of the sword needed to{NL}reforge the sacred sword. Don{SINGLE_QUOTE}t lose it!{END}"


text_0536__089B7538:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}a bottle of dog food{SPECIAL_02_PAR_1}{END}!{NL}Now, head out on your errand!{END}"


text_0537__089B757B:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon Ranch key{SPECIAL_02_PAR_1}{END}!{NL}Now you can open the ranch door!{END}"


text_0538__089B75C2:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}wake-up mushroom{SPECIAL_02_PAR_1}{END}! Its nasty{NL}stench chases away the sleepies!{END}"


text_0539__089B7610:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a library book called{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}A Hyrulean Bestiary{SPECIAL_02_PAR_1}{END}!{END}"


text_053A__089B764A:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a library book called{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Legend of the Picori{SPECIAL_02_PAR_1}{END}!{END}"


text_053B__089B7685:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a library book called{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}A History of Masks{SPECIAL_02_PAR_1}{END}!{END}"


text_053C__089B76BE:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}graveyard key{SPECIAL_02_PAR_1}{END}! Now, you{NL}can open the graveyard gate!{END}"


text_053D__089B7706:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}graveyard key {SPECIAL_02_PAR_1}{END}back! Now,{NL}you can open the graveyard gate!{END}"


text_053E__089B7753:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious Shell{SPECIAL_02_PAR_1}{END}! Don{SINGLE_QUOTE}t know{NL}what it{SINGLE_QUOTE}s for, but hang on to it anyway!{END}"


text_053F__089B77A7:
	.string "You{SINGLE_QUOTE}ve got {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious Shells{SPECIAL_02_PAR_1}{END}!{NL}{NL}I{SINGLE_QUOTE}m not sure what they{SINGLE_QUOTE}re for, but{NL}let{SINGLE_QUOTE}s just hold on to them for now.{END}"


text_0540__089B7814:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END}!{NL}{NL}The power of the earth is the{NL}source of all living things.{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END} is the embodiment{NL}of that power.{END}"


text_0541__089B78A9:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}You got the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} Fire Element{SPECIAL_02_PAR_1}{END}!{NL}{NL}Flames bring light to darkness and{NL}warmth to all.{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Fire Element{SPECIAL_02_PAR_1}{END} is the embodiment{NL}of that power.{END}"


text_0542__089B7933:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} Water Element{SPECIAL_02_PAR_1}{END}!{NL}{NL}Water quenches thirst, ends drought,{NL}and nourishes life.{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Water Element{SPECIAL_02_PAR_1}{END} is the embodiment of{NL}that power.{END}"


text_0543__089B79CA:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} Wind Element{SPECIAL_02_PAR_1}{END}!{NL}{NL}The wind carries the seeds of flowers,{NL}scattering life across the land.{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Wind Element{SPECIAL_02_PAR_1}{END} is the embodiment of{NL}that power.{END}"


text_0544__089B7A6A:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} Grip Ring{SPECIAL_02_PAR_1}{END}!{NL}{NL}Now, you can easily climb cliffs that{NL}you could not scale before.{END}"


text_0545__089B7ACB:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} Power Bracelets{SPECIAL_02_PAR_1}{END}! You{SINGLE_QUOTE}re{NL}filled with strength, even while tiny!{END}"


text_0546__089B7B1D:
	.string "You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}flippers{SPECIAL_02_PAR_1}{END}! Press {SPECIAL_0C_PAR_1}{END} to glide{NL}through the water and {SPECIAL_0C_PAR_1}{SPECIAL_01_PAR_1} to dive!{END}"


text_0547__089B7B6B:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map of Hyrule{SPECIAL_02_PAR_1}{END}!{NL}Now, you{SINGLE_QUOTE}ll never get lost!{END}"


text_0548__089B7BA7:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You learned the secret {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Spin Attack{SPECIAL_02_PAR_1}{END}{NL}fighting technique!{NL}This is the first sword technique you{SINGLE_QUOTE}ve{NL}learned from Master Swiftblade!{END}"


text_0549__089B7C2E:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You learned the secret {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Roll Attack{SPECIAL_02_PAR_1}{END}{NL}fighting technique!{NL}Slay with one stroke! Aim and release!{END}"


text_054A__089B7C93:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You learned the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{END}secret {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Dash Attack{SPECIAL_02_PAR_1}{END}{NL}fighting technique!{NL}Run like the wind and attack!{END}"


text_054B__089B7CF3:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You learned the secret {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Rock Breaker{SPECIAL_02_PAR_1}{END}{NL}fighting technique!{NL}Shatter pots and pulverize boulders{NL}with a single blow!{END}"


text_054C__089B7D6A:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You learned the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{END}secret {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Sword Beam{SPECIAL_02_PAR_1}{END}{NL}fighting technique!{NL}Fire beams from the tip of your blade!{NL}{NL}You can only do this when your life{NL}energy is full.{END}"


text_054D__089B7E07:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You learned the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{END}secret {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Great Spin{NL}Attack {SPECIAL_02_PAR_1}{END}fighting technique!{NL}This is it! At last! The ultimate sword{NL}technique!{END}"


text_054E__089B7E82:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You learned the secret {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Down Thrust{SPECIAL_02_PAR_1}{END}{NL}fighting technique!{NL}Thrust down with your blade from{NL}midair with this mighty attack!{END}"


text_054F__089B7F01:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You learned the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{END}secret {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Peril Beam{SPECIAL_02_PAR_1}{END}{NL}fighting technique!{NL}Release a mighty beam from the tip of{NL}your blade! Use it in dire moments!{END}"


text_0550__089B7F8C:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You found a{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} dungeon map{SPECIAL_02_PAR_1}{END}!{NL}Check it on your {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Map screen{SPECIAL_02_PAR_1}{END}.{NL}Lighter rooms are ones you{SINGLE_QUOTE}ve visited.{NL}The blinking room is your location.{NL}Press Up or Down on {SPECIAL_0C_PAR_1}{BYTE_08} to{NL}check different floors.{END}"


text_0551__089B804A:
	.string "You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}compass{SPECIAL_02_PAR_1}{END}! Use it to find the{NL}locations of hidden items.{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}Press START and then {SPECIAL_0C_PAR_1}{SPECIAL_02_PAR_1} or {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2} to{NL}view the Map screen.{END}"


text_0552__089B80CB:
	.string "You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Big Key{SPECIAL_02_PAR_1}{END}!{NL}Use it to open big doors!{END}"


text_0553__089B80FE:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}small key{SPECIAL_02_PAR_1}{END}!{NL}{NL}Use it to open locked doors and blocks.{NL}You can use it only in this dungeon.{END}"


text_0554__089B8165:
	.string "You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}1 Rupee{SPECIAL_02_PAR_1}{END}. It{SINGLE_QUOTE}s green! Don{SINGLE_QUOTE}t{NL}spend it all in one place!{END}"


text_0555__089B81A7:
	.string "You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}5 Rupees{SPECIAL_02_PAR_1}{END}! That{SINGLE_QUOTE}s kind of nice.{END}"


text_0556__089B81D2:
	.string "You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}20 Rupees{SPECIAL_02_PAR_1}{END}!{NL}That{SINGLE_QUOTE}s great.{END}"


text_0557__089B81F7:
	.string "You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}50 Rupees{SPECIAL_02_PAR_1}{END}!{NL}You must be very happy!{END}"


text_0558__089B8226:
	.string "You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}100 Rupees{SPECIAL_02_PAR_1}{END}!{NL}How exciting!{END}"


text_0559__089B824C:
	.string "You got {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}200 Rupees{SPECIAL_02_PAR_1}{END}!{NL}Your face is beaming!{END}"


text_055A__089B827A:
	.string "{END}"


text_055B__089B827B:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You ate the{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} Jabber Nut{SPECIAL_02_PAR_1}{END}! Now you can{NL}understand the language of the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END}.{END}"


text_055C__089B82D1:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}! These mystic{NL}stones are said to bring happiness.{END}"


text_055D__089B8320:
	.string "You got 5 {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs{SPECIAL_02_PAR_1}{END}! Store them in your{NL}bomb bag!{END}"


text_055E__089B8352:
	.string "You got 5 {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}arrows{SPECIAL_02_PAR_1}{END}!{NL}Store them in your quiver.{END}"


text_055F__089B8383:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}heart{SPECIAL_02_PAR_1}{END}! These replenish{NL}your life energy a little bit.{END}"


text_0560__089B83C7:
	.string "You found a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}fairy{SPECIAL_02_PAR_1}{END}. This reliable ally{NL}will replenish your life energy!{END}"


text_0561__089B8412:
	.string "{END}"


text_0562__089B8413:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Heart Container{SPECIAL_02_PAR_1}{END}!{NL}{NL}Your life energy has increased and{NL}been replenished!{END}"


text_0563__089B8468:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}big bomb bag{SPECIAL_02_PAR_1}{END}! Now you can{NL}carry more bombs!{END}"


text_0564__089B84A2:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}big wallet{SPECIAL_02_PAR_1}{END}! Now, you can{NL}carry more Rupees!{END}"


text_0565__089B84DC:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bigger bomb bag{SPECIAL_02_PAR_1}{END}!{NL}{NL}Now, you can carry more bombs!{NL}Let{SINGLE_QUOTE}s blow up everything!{END}"


text_0566__089B8538:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}large quiver{SPECIAL_02_PAR_1}{END}! Now, you can{NL}carry more arrows!{END}"


text_0567__089B8574:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone bag{SPECIAL_02_PAR_1}{END}! You can now{NL}carry {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces {SPECIAL_02_PAR_1}{END}with you.{NL}Press START to view its contents from{NL}your Quest Status screen.{END}"


text_0568__089B8603:
	.string "You bought a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}brioche{SPECIAL_02_PAR_1}{END}! It looks so{NL}crusty and delicious!{END}"


text_0569__089B863F:
	.string "You bought a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}croissant{SPECIAL_02_PAR_1}{END}! It looks so{NL}buttery and delicious!{END}"


text_056A__089B867E:
	.string "You bought a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}slice of pie{SPECIAL_02_PAR_1}{END}! One bite,{NL}and you{SINGLE_QUOTE}re in heaven!{END}"


text_056B__089B86BD:
	.string "You bought a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}slice of cake{SPECIAL_02_PAR_1}{END}!{NL}Time to get your snack on!{END}"


text_056C__089B86F8:
	.string "You bought 10{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} bombs{SPECIAL_02_PAR_1}{END}!{NL}Store them in your bomb bag!{END}"


text_056D__089B872E:
	.string "You bought 30{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} bombs{SPECIAL_02_PAR_1}{END}!{NL}Store them in your bomb bag!{END}"


text_056E__089B8764:
	.string "You bought 10 {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}arrows{SPECIAL_02_PAR_1}{END}!{NL}Store them in your quiver!{END}"


text_056F__089B8799:
	.string "You bought 30{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} arrows{SPECIAL_02_PAR_1}{END}!{NL}Store them in your quiver!{END}"


text_0570__089B87CE:
	.string "You caught a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Joy Butterfly{SPECIAL_02_PAR_1}{END}! You can{NL}now shoot arrows faster than before.{END}"


text_0571__089B881B:
	.string "You caught a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Joy Butterfly{SPECIAL_02_PAR_1}{END}! You can{NL}now dig faster than before!{END}"


text_0572__089B885F:
	.string "You caught a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Joy Butterfly{SPECIAL_02_PAR_1}{END}! You can{NL}now swim faster than before!{END}"


text_0573__089B88A4:
	.string "This is it! You {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sped up your{NL}Great Spin Attack charge{SPECIAL_02_PAR_1}{END}!{NL}You won{SINGLE_QUOTE}t have to hold the button{NL}down as long anymore!{END}"


text_0574__089B8917:
	.string "This is it! Your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Split Gauge {SPECIAL_02_PAR_1}{END}has{NL}been {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sped up{SPECIAL_02_PAR_1}{END}!{NL}Your sword gauge will fill with power{NL}more quickly!{END}"


text_0575__089B8982:
	.string "This is it! Your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Great Spin Attack{NL}rotation time {SPECIAL_02_PAR_1}{END}has {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}increased{SPECIAL_02_PAR_1}{END}!{NL}Spin around and smash enemies to bits!{END}"


text_0576__089B89F1:
	.string "You got {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious Shells{SPECIAL_02_PAR_1}{END}!{END}"


text_0577__089B8A13:
	.string "You got a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious Shell{SPECIAL_02_PAR_1}{END}!{END}"


text_0578__089B8A33:
	.string "Your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END} was stolen!{NL}{END}"


text_0579__089B8A50:
	.string "You recovered your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}!{NL}{END}"


text_057A__089B8A70:
	.string "{END}"


text_057B__089B8A71:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Welcome to the adventurer{SINGLE_QUOTE}s spring...{NL}{NL}I have need of many Rupees... Please,{NL}throw all of yours into the spring.{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}|Sure  {SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{CLOSE_CURLY}No way{END}"


text_057C__089B8AF8:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Really?{NL}{NL}You know that, if you do this, you will{NL}have absolutely no Rupees left, right?{NL}Will you really throw them all in?{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}~Yes  {SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{CLOSE_CURLY}No{END}"


text_057D__089B8B87:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}I see. Then I will wait for the next{NL}adventurer who comes my way...{END}"


text_057E__089B8BD1:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You are most kind. I do not{NL}really need your Rupees.{NL}But I must reward such a kind{NL}adventurer with some of my power.{END}"


text_057F__089B8C49:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}May light shine on your quest...{END}"


text_0580__089B8C6D:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Welcome to the adventurer{SINGLE_QUOTE}s spring...{NL}{NL}Did you throw the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Golden Bomb{SPECIAL_02_PAR_1}{END} into{NL}the spring? Or the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Silver Bomb{SPECIAL_02_PAR_1}{END}?{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_81}Golden Bomb    {SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_81}Silver Bomb{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_82}Neither{END}"


text_0581__089B8D0E:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You{SINGLE_QUOTE}re lying, aren{SINGLE_QUOTE}t you?{NL}{NL}As punishment for your lie, I will reduce{NL}your number of bombs to zero.{END}"


text_0582__089B8D74:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You are honest.{NL}{NL}I must reward such an honest{NL}adventurer with some of my power.{END}"


text_0583__089B8DC7:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Welcome to the adventurer{SINGLE_QUOTE}s spring.{NL}{NL}Would you tell me of the things you{SINGLE_QUOTE}ve{NL}seen on your adventures?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes  {SPECIAL_05_PAR_1}{BYTE_FF}Not now{END}"


text_0584__089B8E40:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}The first element you found was the{NL}Fire Element, was it not?{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8A}Yes  {SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8C}No{END}"


text_0585__089B8E8F:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Your grandfather{SINGLE_QUOTE}s name is Smee,{NL}isn{SINGLE_QUOTE}t it?{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8A}Yes  {SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8D}No{END}"


text_0586__089B8ECB:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Melari of Mount Crenel has seven{NL}apprentices, does he not?{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8E}Yes  {SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8A}No{END}"


text_0587__089B8F17:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}The Blabber Nut gives one the ability{NL}to understand the Minish, does it not?{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8A}Yes  {SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8F}No{END}"


text_0588__089B8F75:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}The robe of the current king of Hyrule,{NL}Daltus, is white, is it not?{NL}{SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8A}Yes  {SPECIAL_05_PAR_1}{SPECIAL_05_PAR_1}{BYTE_8B}No{END}"


text_0589__089B8FCB:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Thank you. Then please just{NL}answer my questions.{NL}{SPECIAL_07_PAR_1}{SPECIAL_05_PAR_1}{BYTE_84}{END}"


text_058A__089B9003:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}You have lied to me.{NL}{NL}As punishment for your lie, I will reduce{NL}your number of arrows to zero.{END}"


text_058B__089B9065:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}I see. Thank you for telling me about{NL}your quest. You remember it all so well.{NL}Such a faithful memory should be{NL}rewarded with some of my power.{END}"


text_058C__089B90F8:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Yes, I see.{NL}Now for the next question.{NL}{SPECIAL_07_PAR_1}{SPECIAL_05_PAR_1}{BYTE_85}{END}"


text_058D__089B9126:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Yes, I see.{NL}Now for the next question.{NL}{SPECIAL_07_PAR_1}{SPECIAL_05_PAR_1}{BYTE_86}{END}"


text_058E__089B9154:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Yes, I see.{NL}Now for the next question.{NL}{SPECIAL_07_PAR_1}{SPECIAL_05_PAR_1}{BYTE_87}{END}"


text_058F__089B9182:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Yes, I see.{NL}Now for the next question.{NL}{SPECIAL_07_PAR_1}{SPECIAL_05_PAR_1}{BYTE_88}{END}"


text_0590__089B91B0:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Welcome to the adventurer{SINGLE_QUOTE}s spring...{NL}Let me rest your weary body.{END}"


text_0591__089B91F6:
	.string "You bought 10{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} bombs{SPECIAL_02_PAR_1}{END}!{END}"


text_0592__089B920F:
	.string "You bought 30{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} bombs{SPECIAL_02_PAR_1}{END}!{END}"


text_0593__089B9228:
	.string "You bought 10 {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}arrows{SPECIAL_02_PAR_1}{END}!{END}"


text_0594__089B9242:
	.string "You bought 30 {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}arrows{SPECIAL_02_PAR_1}{END}!{END}"


text_0595__089B925C:
	.string "You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tingle Trophy{SPECIAL_02_PAR_1}{END}!{END}"


text_0596__089B927B:
	.string "You got the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Carlov Medal{SPECIAL_02_PAR_1}{END}!{END}"

