
text_3500__089E3E10:
	.string "{END}"


text_3501__089E3E11:
	.string "I{SINGLE_QUOTE}m sad that the festival{SINGLE_QUOTE}s over.{NL}{NL}Now that everyone{SINGLE_QUOTE}s gone back to their{NL}routines, it{SINGLE_QUOTE}s boring around here.{END}"


text_3502__089E3E7E:
	.string "You know, I got pretty far in last{NL}year{SINGLE_QUOTE}s tournament...{END}"


text_3503__089E3EB6:
	.string "Meooow...{END}"


text_3504__089E3EC0:
	.string "Rowrrr!{END}"


text_3505__089E3EC8:
	.string "{END}"


text_3506__089E3EC9:
	.string "{END}"


text_3507__089E3ECA:
	.string "{END}"


text_3508__089E3ECB:
	.string "{END}"


text_3509__089E3ECC:
	.string "{END}"


text_350A__089E3ECD:
	.string "{END}"


text_350B__089E3ECE:
	.string "{END}"


text_350C__089E3ECF:
	.string "{END}"


text_350D__089E3ED0:
	.string "{END}"


text_350E__089E3ED1:
	.string "{END}"


text_350F__089E3ED2:
	.string "{END}"


text_3510__089E3ED3:
	.string "{END}"


text_3511__089E3ED4:
	.string "{END}"


text_3512__089E3ED5:
	.string "Buggedy-buggedy-BOO!{NL}{NL}Did I scare ya?{END}"


text_3513__089E3EFB:
	.string "Awww, man...{END}"


text_3514__089E3F08:
	.string "Arr! Arf arf!{END}"


text_3515__089E3F16:
	.string "Not being anyone{SINGLE_QUOTE}s pet sure does have{NL}its perks...{NL}I don{SINGLE_QUOTE}t have to wait around for anyone{NL}to feed me, for one thing.{END}"


text_3516__089E3F8B:
	.string "What{SINGLE_QUOTE}s that? You{SINGLE_QUOTE}re looking for{NL}something? Some kind of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}?{END}"


text_3517__089E3FD4:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}doesn{SINGLE_QUOTE}t seem like himself{NL}these days... It{SINGLE_QUOTE}s weird.{END}"


text_3518__089E4015:
	.string "Just what{SINGLE_QUOTE}s up with the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}, anyway?{END}"


text_3519__089E403F:
	.string "Man! I REALLY want to get in there{NL}and play a few {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}games{SPECIAL_02_PAR_1}{END}...{NL}I can{SINGLE_QUOTE}t believe they{SINGLE_QUOTE}re still closed!{NL}I{SINGLE_QUOTE}m not going anywhere until they open!{END}"


text_351A__089E40CC:
	.string "This stall is all dirty.{NL}{NL}I guess the guy that usually sells his{NL}stuff here isn{SINGLE_QUOTE}t going to show...{END}"


text_351B__089E412F:
	.string "To tell you the truth, I{SINGLE_QUOTE}m sick of fruit,{NL}and I just plain hate veggies!{END}"


text_351C__089E4178:
	.string "Hey, hey! Come on up and take a look!{NL}You{SINGLE_QUOTE}re sure to see something you like!{END}"


text_351D__089E41C5:
	.string "Come on up and get a good sniff!{NL}Smelling{SINGLE_QUOTE}s always free! Hey, hey!{END}"


text_351E__089E4208:
	.string "Hey, hey! Come on up!{NL}It{SINGLE_QUOTE}s got beta-carotene, people!{NL}It{SINGLE_QUOTE}s good for your eyes!{END}"


text_351F__089E4257:
	.string "You{SINGLE_QUOTE}ll never get big and strong without{NL}eating your greens! Hey, hey!{END}"


text_3520__089E429D:
	.string "I{SINGLE_QUOTE}ve never seen the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}like this!{NL}He{SINGLE_QUOTE}s so angry, so impatient!{NL}I hear he{SINGLE_QUOTE}s been just horrible{NL}to the guards, too.{END}"


text_3521__089E4315:
	.string "Everyone in the castle is{NL}on pins and needles!{END}"


text_3522__089E4344:
	.string "{END}"


text_3523__089E4345:
	.string "{END}"


text_3524__089E4346:
	.string "I don{SINGLE_QUOTE}t even know why I{SINGLE_QUOTE}m bothering to{NL}look for that {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE}...{NL}I doubt anything that powerful{NL}could possibly exist anyway.{END}"


text_3525__089E43CC:
	.string "The inn{SINGLE_QUOTE}s open for business now.{NL}{NL}They{SINGLE_QUOTE}re giving away a special gift{NL}to everyone who stays there!{END}"


text_3526__089E442E:
	.string "Of course there{SINGLE_QUOTE}s no light force here!{NL}What was I thinking? Stupid, stupid!{END}"


text_3527__089E447A:
	.string "We{SINGLE_QUOTE}re in the middle of a very important{NL}class right now, so I can{SINGLE_QUOTE}t let you in.{END}"


text_3528__089E44CA:
	.string "Hello, {SPECIAL_06_PAR_1}{END}. We are studying{NL}Hyrulean Literature right now.{NL}It{SINGLE_QUOTE}s a very important subject!{END}"


text_3529__089E4523:
	.string "The legend says that the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}power of light{SPECIAL_02_PAR_1}{END}{NL}was given to humans by the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}.{NL}I wonder, does it really exist? I mean,{NL}it{SINGLE_QUOTE}s not like anyone{SINGLE_QUOTE}s ever SEEN it.{END}"


text_352A__089E45C3:
	.string "There{SINGLE_QUOTE}s an old legend that something{NL}big will happen when Hyrule{SINGLE_QUOTE}s bell rings.{END}"


text_352B__089E4612:
	.string "But nobody knows exactly{NL}what will happen...{END}"


text_352C__089E463F:
	.string "I came here to check out a book.{NL}{NL}They{SINGLE_QUOTE}re supposed to be open by now.{NL}I wonder what{SINGLE_QUOTE}s going on...{END}"


text_352D__089E46A1:
	.string "Not like you{SINGLE_QUOTE}d know, but...do you think{NL}it{SINGLE_QUOTE}s safe to touch the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}?{NL}With your bare hands, I mean... Do you{NL}think maybe it burns or something?{END}"


text_352E__089E473B:
	.string "That little red thing is really{NL}starting to bug me.{NL}It{SINGLE_QUOTE}s like a house or something.{END}"


text_352F__089E478F:
	.string "That little red thing is really{NL}starting to bug me.{NL}It{SINGLE_QUOTE}s like a house or something.{END}"


text_3530__089E47E3:
	.string "Rrrr...ARF ARF!{END}"


text_3531__089E47F3:
	.string "Arf arf arf!{END}"


text_3532__089E4800:
	.string "Awoooooooo!!!{END}"


text_3533__089E480E:
	.string "Oh, sorry... Am I in your way?{NL}I just wanted a little attention.{NL}Anyway, it was nice of you to say hi.{NL}Sorry for the trouble. I{SINGLE_QUOTE}ll move now.{END}"


text_3534__089E489B:
	.string "Everyone in this town is really nice.{END}"


text_3535__089E48C1:
	.string "But really, why search for something{NL}no one{SINGLE_QUOTE}s ever seen before?{NL}I mean, what does {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE} look{NL}like, anyway? The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s gone loopy.{END}"


text_3536__089E4953:
	.string "I{SINGLE_QUOTE}m really quite good at tracking{NL}down rare {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurines{SPECIAL_02_PAR_1}{END}.{END}"


text_3537__089E498E:
	.string "I{SINGLE_QUOTE}ve collected so many! And not just the{NL}normal ones. I{SINGLE_QUOTE}ve rare ones, too!{NL}But don{SINGLE_QUOTE}t even think about asking me{NL}for {SINGLE_QUOTE}em, because I ain{SINGLE_QUOTE}t givin{SINGLE_QUOTE} you any!{END}"


text_3538__089E4A27:
	.string "So, the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END} is some kind of{NL}treasure that can grant any wish?{NL}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}must be looking for it so{NL}that he can ensure peace in Hyrule.{END}"


text_3539__089E4ABC:
	.string "Hey, you made it over, huh?{NL}{NL}I bet crossing that narrow bridge{NL}made you nervous, right?{END}"


text_353A__089E4B14:
	.string "Doesn{SINGLE_QUOTE}t that hole over there{NL}kind of bother you?{NL}I wonder how to get over to it...{END}"


text_353B__089E4B67:
	.string "Ghosts are scary.{NL}{NL}That one{SINGLE_QUOTE}s nice, but even nice ghosts{NL}are still scary. Aren{SINGLE_QUOTE}t they?{END}"


text_353C__089E4BBE:
	.string "Thanks for coming.{NL}{NL}Hardly anyone ever visits, and it gets{NL}lonely here. Please take this.{END}"


text_353D__089E4C18:
	.string "The view from here is nice.{NL}{NL}And Swiftblade{SINGLE_QUOTE}s screams during{NL}training seem to complement the scene.{END}"


text_353E__089E4C7C:
	.string "Good job getting up here.{NL}Really. That{SINGLE_QUOTE}s impressive.{NL}You must have really put yourself out{NL}to find a way here. Please take this.{END}"


text_353F__089E4CFD:
	.string "I wonder how I{SINGLE_QUOTE}m going to get down...{NL}Those cucco chicks just terrify me.{END}"

