
text_0600__089B9438:
	.string "{END}"


text_0601__089B9439:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Hyrule Castle{END}"


text_0602__089B944B:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Hyrule Castle{NL}{SPECIAL_0F_PAR_1}{BYTE_09}  Hyrule Town     {SPECIAL_0F_PAR_1}{NL}  Minish Woods{END}"


text_0603__089B9482:
	.string "Crenel Wall{NL}(Watch out for falling rocks){END}"


text_0604__089B94AC:
	.string "Dangerous - No Climbing{END}"


text_0605__089B94C4:
	.string "Syrup the Witch{SINGLE_QUOTE}s Hut{END}"


text_0606__089B94DA:
	.string "No bomb throwing!{END}"


text_0607__089B94EC:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Hyrule Town{NL}{SPECIAL_0F_PAR_1}{BYTE_09}  Castor Wilds  {SPECIAL_0F_PAR_1}{NL}  Minish Woods{END}"


text_0608__089B951F:
	.string "Hyrule Town{END}"


text_0609__089B952B:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Royal Valley{NL}{SPECIAL_0F_PAR_1}{BYTE_09}  Mount Crenel{END}"


text_060A__089B954D:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Castor Wilds             Danger!{NL}Don{SINGLE_QUOTE}t forget your Pegasus Boots!{END}"


text_060B__089B9593:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Veil Falls{NL}{SPECIAL_0F_PAR_1}{BYTE_08}  Minish Woods     {SPECIAL_0F_PAR_1}{NL}  Lake Hylia{END}"


text_060C__089B95C6:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Crenel Wall{NL}{SPECIAL_0F_PAR_1}{NL}  Crenel Mines{END}"


text_060D__089B95E7:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Crenel Mines{NL}{SPECIAL_0F_PAR_1}{BYTE_09}  Crenel Wall{END}"


text_060E__089B9608:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Hyrule Castle    {SPECIAL_0F_PAR_1}{BYTE_08}  Hyrule Town{NL}{SPECIAL_0F_PAR_1}{BYTE_09}  Mount Crenel     {SPECIAL_0F_PAR_1}{NL}  Lake Hylia{END}"


text_060F__089B9651:
	.string "Lon Lon Ranch{END}"


text_0610__089B965F:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Crenel Mines{NL}{SPECIAL_0F_PAR_1}{NL}  Shortcut to bottom{END}"


text_0611__089B9687:
	.string "{SPECIAL_0F_PAR_1}{BYTE_08}  Shortcut to bottom{END}"


text_0612__089B969E:
	.string "{SPECIAL_0F_PAR_1}{BYTE_09}  Mount Crenel{END}"


text_0613__089B96AF:
	.string "{SPECIAL_0F_PAR_1}{NL}  Lake Hylia{NL}{SPECIAL_0F_PAR_1}{BYTE_08}  Syrup the Witch{SINGLE_QUOTE}s Hut{END}"


text_0614__089B96D8:
	.string "Percy{SINGLE_QUOTE}s House{END}"


text_0615__089B96E6:
	.string "{SPECIAL_0F_PAR_1}{BYTE_09}  Royal Valley{END}"


text_0616__089B96F7:
	.string "{SPECIAL_0F_PAR_1}{BYTE_08}  This way to Mayor Hagen{SINGLE_QUOTE}s{NL}        Lakeside Cabin{END}"


text_0617__089B972C:
	.string "{SPECIAL_0F_PAR_1}{SPECIAL_07_PAR_1}  Syrup the Witch{SINGLE_QUOTE}s Hut{NL}{SPECIAL_0F_PAR_1}{NL}  Mayor Hagen{SINGLE_QUOTE}s Lakeside Cabin{END}"


text_0618__089B9767:
	.string "{END}"


text_0619__089B9768:
	.string "{END}"


text_061A__089B9769:
	.string "{END}"


text_061B__089B976A:
	.string "Dear Mom,{NL}I{SINGLE_QUOTE}ll be next door if you need me.{END}"


text_061C__089B9796:
	.string "This week{SINGLE_QUOTE}s top titles:{NL}{NL}{SPECIAL_0F_PAR_1}{BYTE_10}3   Learn to Like Your Like Like:{NL}     A Good Guide to a Bad Pet{NL}{SPECIAL_0F_PAR_1}{BYTE_10}2   Gorman{SINGLE_QUOTE}s Guide to Good Grub{NL}{NL}{SPECIAL_0F_PAR_1}{BYTE_10}1   Married to the Moblin{END}"


text_061D__089B9831:
	.string "Hagen{SINGLE_QUOTE}s Words of Wisdom{NL}{NL}If you can{SINGLE_QUOTE}t solve a problem, just ram{NL}headlong into it. BAM!{END}"


text_061E__089B9888:
	.string "{END}"


text_061F__089B9889:
	.string "{SPECIAL_0F_PAR_1}{NL}  Mayor Hagen{SINGLE_QUOTE}s Lakeside Cabin{NL}All digging absolutely prohibited!{END}"


text_0620__089B98CD:
	.string "Under construction.{NL}All digging strictly prohibited!{END}"


text_0621__089B9902:
	.string "Beware crumbling walls!{NL}Blasting strictly prohibited.{END}"


text_0622__089B9938:
	.string "{END}"


text_0623__089B9939:
	.string "{END}"


text_0624__089B993A:
	.string "{END}"


text_0625__089B993B:
	.string "{END}"


text_0626__089B993C:
	.string "{END}"


text_0627__089B993D:
	.string "{END}"


text_0628__089B993E:
	.string "{END}"


text_0629__089B993F:
	.string "{END}"


text_062A__089B9940:
	.string "{END}"


text_062B__089B9941:
	.string "{END}"


text_062C__089B9942:
	.string "{END}"


text_062D__089B9943:
	.string "{END}"


text_062E__089B9944:
	.string "{END}"


text_062F__089B9945:
	.string "{END}"


text_0630__089B9946:
	.string "{END}"


text_0631__089B9947:
	.string "{END}"


text_0632__089B9948:
	.string "{END}"


text_0633__089B9949:
	.string "{END}"


text_0634__089B994A:
	.string "{END}"


text_0635__089B994B:
	.string "{END}"


text_0636__089B994C:
	.string "{END}"


text_0637__089B994D:
	.string "{END}"


text_0638__089B994E:
	.string "{END}"


text_0639__089B994F:
	.string "{END}"


text_063A__089B9950:
	.string "{END}"


text_063B__089B9951:
	.string "{END}"


text_063C__089B9952:
	.string "{END}"


text_063D__089B9953:
	.string "Up{END}"


text_063E__089B9956:
	.string "Left{END}"


text_063F__089B995B:
	.string "Same as before{END}"


text_0640__089B996A:
	.string "Same as the beginning{END}"


text_0641__089B9980:
	.string "Right{END}"


text_0642__089B9986:
	.string "Same as two before{END}"


text_0643__089B9999:
	.string "Down{END}"


text_0644__089B999E:
	.string "{END}"


text_0645__089B999F:
	.string "{END}"


text_0646__089B99A0:
	.string "{END}"


text_0647__089B99A1:
	.string "The truth about the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END} within{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END} is depicted here.{END}"


text_0648__089B99F3:
	.string "{END}"


text_0649__089B99F4:
	.string "{END}"


text_064A__089B99F5:
	.string "{END}"


text_064B__089B99F6:
	.string "{END}"


text_064C__089B99F7:
	.string "{END}"


text_064D__089B99F8:
	.string "{END}"


text_064E__089B99F9:
	.string "{END}"


text_064F__089B99FA:
	.string "{END}"


text_0650__089B99FB:
	.string "{END}"


text_0651__089B99FC:
	.string "{END}"


text_0652__089B99FD:
	.string "{END}"


text_0653__089B99FE:
	.string "{END}"


text_0654__089B99FF:
	.string "{END}"


text_0655__089B9A00:
	.string "{END}"


text_0656__089B9A01:
	.string "{END}"


text_0657__089B9A02:
	.string "The way forward is hidden{NL}in the bottom of the pot.{END}"


text_0658__089B9A36:
	.string "{END}"


text_0659__089B9A37:
	.string "{END}"


text_065A__089B9A38:
	.string "{END}"


text_065B__089B9A39:
	.string "{END}"


text_065C__089B9A3A:
	.string "{END}"


text_065D__089B9A3B:
	.string "{END}"


text_065E__089B9A3C:
	.string "{END}"


text_065F__089B9A3D:
	.string "{END}"


text_0660__089B9A3E:
	.string "{END}"


text_0661__089B9A3F:
	.string "{END}"


text_0662__089B9A40:
	.string "{END}"


text_0663__089B9A41:
	.string "{END}"


text_0664__089B9A42:
	.string "{END}"

