
text_4300__089EDE54:
	.string "{END}"


text_4301__089EDE55:
	.string "{END}"


text_4302__089EDE56:
	.string "{SPECIAL_05_PAR_1}C{BYTE_17}Trade {SPECIAL_05_PAR_1}C{BYTE_08}Don{SINGLE_QUOTE}t trade{END}"


text_4303__089EDE6E:
	.string "{END}"


text_4304__089EDE6F:
	.string "{END}"


text_4305__089EDE70:
	.string "I collect those {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious Shells{SPECIAL_02_PAR_1}{END} you{SINGLE_QUOTE}ve{NL}seen scattered all over the place.{NL}If you bring those shells to me, I{SINGLE_QUOTE}ll{NL}trade you these {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurines {SPECIAL_02_PAR_1}{END}I have made.{END}"


text_4306__089EDF11:
	.string "Ahh, is that a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious Shell{SPECIAL_02_PAR_1}{END}? Hm...{NL}I{SINGLE_QUOTE}ve got an offer I{SINGLE_QUOTE}d like to make you.{NL}What do you say to trading it for{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}a chance at winning a figurine{SPECIAL_02_PAR_1}{END}?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}Oh, you don{SINGLE_QUOTE}t have any {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious{NL}Shells{SPECIAL_02_PAR_1}{END} on you?{NL}Well, please come see me when you do.{END}"


text_4307__089EDFAE:
	.string "Oh, you don{SINGLE_QUOTE}t have any {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious{NL}Shells{SPECIAL_02_PAR_1}{END} on you?{NL}Well, please come see me when you do.{END}"


text_4308__089EE009:
	.string "Too bad. Come back if you ever{NL}change your mind, though.{END}"


text_4309__089EE042:
	.string "{END}"


text_430A__089EE043:
	.string "{END}"


text_430B__089EE044:
	.string "Oh, you{SINGLE_QUOTE}re back. Well, you must have{NL}liked that last {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurine{SPECIAL_02_PAR_1}{END}.{NL}Do you want to try for another one?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}Want to try another drawing?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}{END}"


text_430C__089EE0AF:
	.string "Want to try another drawing?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}{END}"


text_430D__089EE0D0:
	.string "{END}"


text_430E__089EE0D1:
	.string "Oh, hello again. I was hoping{NL}you{SINGLE_QUOTE}d come back.{NL}I {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}made a new figurine{SPECIAL_02_PAR_1}{END}, and I thought{NL}you might like to try to get it.{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}{END}"


text_430F__089EE14E:
	.string "{END}"


text_4310__089EE14F:
	.string "{END}"


text_4311__089EE150:
	.string "Ahh, you again.{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}I don{SINGLE_QUOTE}t have any new figurines yet.{SPECIAL_02_PAR_1}{END}{NL}Would you like to draw for one anyway?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}{END}"


text_4312__089EE1B4:
	.string "{END}"


text_4313__089EE1B5:
	.string "It looks like you already have {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}every{NL}figurine I make{SPECIAL_02_PAR_1}{END}.{NL}Do you still want to have a try?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}Ahh, thanks for coming.{NL}{NL}You seem to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}have won all the figurines{NL}I{SINGLE_QUOTE}ve made so far{SPECIAL_02_PAR_1}{END}.{NL}Would you like to draw for one anyway?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}Hey, I{SINGLE_QUOTE}ve been waiting for you!{NL}I{SINGLE_QUOTE}ve got something new to show you.{NL}It{SINGLE_QUOTE}s our {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}final series{SPECIAL_02_PAR_1}{END}, my friend.{NL}Check it out!{NL}Do you want to try to draw one now?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}{END}"


text_4314__089EE214:
	.string "Ahh, thanks for coming.{NL}{NL}You seem to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}have won all the figurines{NL}I{SINGLE_QUOTE}ve made so far{SPECIAL_02_PAR_1}{END}.{NL}Would you like to draw for one anyway?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}Hey, I{SINGLE_QUOTE}ve been waiting for you!{NL}I{SINGLE_QUOTE}ve got something new to show you.{NL}It{SINGLE_QUOTE}s our {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}final series{SPECIAL_02_PAR_1}{END}, my friend.{NL}Check it out!{NL}Do you want to try to draw one now?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}{END}"


text_4315__089EE295:
	.string "Hey, I{SINGLE_QUOTE}ve been waiting for you!{NL}I{SINGLE_QUOTE}ve got something new to show you.{NL}It{SINGLE_QUOTE}s our {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}final series{SPECIAL_02_PAR_1}{END}, my friend.{NL}Check it out!{NL}Do you want to try to draw one now?{NL}{SPECIAL_07_PAR_1}C{SPECIAL_02_PAR_1}{END}{END}"


text_4316__089EE335:
	.string "{END}"


text_4317__089EE336:
	.string "How many {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shells{SPECIAL_02_PAR_1}{END} would you like to use{NL}in this drawing?{NL}The more shells you use, the more likely{NL}you are to win a figure you don{SINGLE_QUOTE}t have.{END}"


text_4318__089EE3C2:
	.string "         Probability{NL}Shells: {SPECIAL_04_PAR_2}{BYTE_15}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_04_PAR_2}{BYTE_14}  {SPECIAL_04_PAR_2}{BYTE_15}{SPECIAL_06_PAR_1}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}{BYTE_14}{SPECIAL_0F_PAR_1}{BYTE_12}{END}"


text_4319__089EE3F0:
	.string "How many {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shells{SPECIAL_02_PAR_1}{END} do you want to trade{NL}on this drawing?{END}"


text_431A__089EE42A:
	.string "You{SINGLE_QUOTE}re going to trade {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} of them?{END}"


text_431B__089EE44C:
	.string "{SPECIAL_05_PAR_1}C{BYTE_1E}Yes {SPECIAL_05_PAR_1}C{BYTE_17}No {END}"


text_431C__089EE45A:
	.string "{END}"


text_431D__089EE45B:
	.string "{END}"


text_431E__089EE45C:
	.string "Great. Now, just pull the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}lever{SPECIAL_02_PAR_1}{END} on the{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}figure-dispensing machine{SPECIAL_02_PAR_1}{END} over there.{END}"


text_431F__089EE4B1:
	.string "Oh, hold on! You{SINGLE_QUOTE}ve already traded your{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shells{SPECIAL_02_PAR_1}{END} away...{NL}If you leave without trying, you{SINGLE_QUOTE}ve{NL}just wasted your shells!{END}"


text_4320__089EE529:
	.string "{END}"


text_4321__089EE52A:
	.string "{END}"


text_4322__089EE52B:
	.string "Oh! Looks like you{SINGLE_QUOTE}ve already got that{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurine{SPECIAL_02_PAR_1}{END}. Too bad, isn{SINGLE_QUOTE}t it?{NL}Well, I{SINGLE_QUOTE}ll buy that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurine {SPECIAL_02_PAR_1}{END}back from{NL}you for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees if you like.{END}"


text_4323__089EE5BD:
	.string "{END}"


text_4324__089EE5BE:
	.string "{END}"


text_4325__089EE5BF:
	.string "Congratulations!{NL}{NL}I{SINGLE_QUOTE}ll keep the figurine in the case on the{NL}left for you. You can see it anytime.{END}"


text_4326__089EE621:
	.string "I hope you keep collecting and decide{NL}to come back again!{END}"


text_4327__089EE65B:
	.string "Wow!{NL}{NL}My friend, you{SINGLE_QUOTE}ve just gotten the{NL}last figurine in the machine.{NL}But I{SINGLE_QUOTE}ll make some more,{NL}so please come back again.{END}"


text_4328__089EE6D5:
	.string "Congratulations!{NL}{NL}You{SINGLE_QUOTE}ve now collected {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}all of the{NL}figurines that I{SINGLE_QUOTE}ve made{SPECIAL_02_PAR_1}{END}!{NL}I{SINGLE_QUOTE}ll keep a good eye on all of your{NL}figures in the case...{NL}Please, come see them anytime!{END}"


text_4329__089EE77F:
	.string "No way! Congratulations!{NL}{NL}You{SINGLE_QUOTE}ve {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}collected every single figure{NL}I{SINGLE_QUOTE}ve ever made{SPECIAL_02_PAR_1}{END}!{NL}I{SINGLE_QUOTE}ll keep a good eye on your collection{NL}on the shelf here.{NL}And here, I want you to have this!{NL}{NL}It{SINGLE_QUOTE}s the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Carlov Medal{SPECIAL_02_PAR_1}{END}, to commemorate{NL}your copious collection!{NL}I hope you treasure it always!{END}"


text_432A__089EE893:
	.string "{END}"


text_432B__089EE894:
	.string "Are you curious about that machine?{NL}I can explain it if you like.{END}"


text_432C__089EE8D6:
	.string "{END}"


text_432D__089EE8D7:
	.string "{END}"


text_432E__089EE8D8:
	.string "That{SINGLE_QUOTE}s a case for displaying figurines.{NL}No one{SINGLE_QUOTE}s using it right now, though.{END}"


text_432F__089EE925:
	.string "How do you like that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Carlov Medal{SPECIAL_02_PAR_1}{END}?{NL}Pretty impressive, isn{SINGLE_QUOTE}t it?{NL}It{SINGLE_QUOTE}s proof of your super collecting{NL}abilities! Wear it with pride, my friend!{END}"


text_4330__089EE9B7:
	.string "{END}"


text_4331__089EE9B8:
	.string "{END}"


text_4332__089EE9B9:
	.string "{END}"

