
text_0E00__089CCD74:
	.string "Wow... I just had the best idea! I can{NL}rent out my house for some extra cash!{END}"


text_0E01__089CCDC2:
	.string "I{SINGLE_QUOTE}m feeling really motivated now!{NL}{NL}I could probably build a good-sized{NL}house in a matter of minutes!{END}"


text_0E02__089CCE27:
	.string "My special {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}red potion {SPECIAL_02_PAR_1}{END}is almost finished!{NL}Oh, and it{SINGLE_QUOTE}s so very special!{NL}Heeheehee!{END}"


text_0E03__089CCE7E:
	.string "Hey! I{SINGLE_QUOTE}ve just hit on a great idea!{NL}This will add a little more risk!{NL}Heh heh heh! I{SINGLE_QUOTE}m so excited!{NL}I can{SINGLE_QUOTE}t wait to get started!{END}"


text_0E04__089CCEFE:
	.string "I really wish I could do more to help{NL}people...{NL}Wait! I{SINGLE_QUOTE}ve got it! I{SINGLE_QUOTE}ll ask {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade {SPECIAL_02_PAR_1}{END}to{NL}start up a newsletter for adventurers!{NL}That{SINGLE_QUOTE}ll be a great way to provide{NL}a useful service for everyone...{NL}Hm. It{SINGLE_QUOTE}s going to be a lot of work,{NL}though. I should get {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Marcy {SPECIAL_02_PAR_1}{END}to help me.{END}"


text_0E05__089CD015:
	.string "You know what would be great? A bomb{NL}that went off only when you wanted...{NL}Hm... Actually, I think I could probably{NL}make one with just a few minor tweaks!{END}"


text_0E06__089CD0B0:
	.string "It{SINGLE_QUOTE}s been a long time since the last time{NL}I visited {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule{SPECIAL_02_PAR_1}{END}...{NL}I think I{SINGLE_QUOTE}ll set up a little place{NL}where I can sell my Kinstones.{END}"


text_0E07__089CD134:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BE}I don{SINGLE_QUOTE}t know why I{SINGLE_QUOTE}ve been such a{NL}nasty little prankster all the time...{NL}All of a sudden, I feel like a weight{SINGLE_QUOTE}s{NL}been lifted off my shoulders!{NL}I feel like I{SINGLE_QUOTE}ve made up for all my{NL}awful deeds! Haha!{NL}Hey, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Spookter{SPECIAL_02_PAR_1}{END}! See you in paradise!{END}"


text_0E08__089CD225:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}I feel so much stronger now!{NL}Here we go!!!{END}"


text_0E09__089CD253:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BA}Whew! It{SINGLE_QUOTE}s about time... Looking good,{NL}though! I{SINGLE_QUOTE}m going in!{END}"


text_0E0A__089CD293:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}Hn... No, it{SINGLE_QUOTE}s no good...{NL}I can{SINGLE_QUOTE}t break it by myself.{END}"


text_0E0B__089CD2CC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}I had a strange feeling, like a fellow{NL}Goron was in need... Hello? Goro?{NL}Hn? That wall! You can{SINGLE_QUOTE}t get through{NL}that alone! I{SINGLE_QUOTE}m coming to help you!!!{END}"


text_0E0C__089CD363:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}Don{SINGLE_QUOTE}t worry! I{SINGLE_QUOTE}m here to help you! Let{SINGLE_QUOTE}s{NL}break through that wall together! Goro!{END}"


text_0E0D__089CD3B7:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}Hn... This wall is pretty tough. I don{SINGLE_QUOTE}t{NL}think just the two of us can break it.{NL}But that doesn{SINGLE_QUOTE}t mean we{SINGLE_QUOTE}re going{NL}to stop trying! Goro!!!{END}"


text_0E0E__089CD444:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}I thought I smelled some Gorons around{NL}here! What are you guys up to?{END}"


text_0E0F__089CD48D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BA}Hey! Give us a hand breaking{NL}through this wall! Goro!{END}"


text_0E10__089CD4C6:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}That{SINGLE_QUOTE}s a tough wall! The three of us{NL}together couldn{SINGLE_QUOTE}t even break it...{END}"


text_0E11__089CD511:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}I smell delicious stones... They{SINGLE_QUOTE}re right{NL}on the other side of this wall.{END}"


text_0E12__089CD55E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}Can you give me a hand? Gorogoro?{END}"


text_0E13__089CD583:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}That{SINGLE_QUOTE}s one solid wall... No doubt about{NL}it. We{SINGLE_QUOTE}re going to need some more help.{END}"


text_0E14__089CD5D6:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}Oooo... I can smell deliciousness just{NL}on the other side of that wall.{END}"


text_0E15__089CD620:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}Oh, thank goodness! Help has arrived!{END}"


text_0E16__089CD649:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BA}Almost there... Goro! But it{SINGLE_QUOTE}s{NL}still just not breaking!{END}"


text_0E17__089CD684:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}I had a feeling there were some Gorons{NL}in need of a little extra muscle.{NL}Well, I{SINGLE_QUOTE}m here to help!{END}"


text_0E18__089CD6E8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BA}Hey, perfect timing! All right, everyone!{NL}Together now! Gooooroooo!!!{END}"


text_0E19__089CD731:
	.string "{END}"

