
text_1600__089D4CF4:
	.string "{END}"


text_1601__089D4CF5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}Hmmm... How interesting... Look at the{NL}images on the stained glass...{NL}I bet those pictures show us where{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END} is hidden...{END}"


text_1602__089D4D82:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E8}{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Ah ha ha haaaa...{NL}Ezlo, you really are too kind.{NL}First, you give me my {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}magic cap{SPECIAL_02_PAR_1}{END},{NL}and then you guide me here!{NL}You{SINGLE_QUOTE}ve been far too generous, but{NL}now, I no longer have any use for you.{END}"


text_1603__089D4E43:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E8}{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}He ha ha ha ha... At last, I finally{NL}know the location of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}!{END}"


text_1604__089D4E98:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}{SPECIAL_06_PAR_1}{END}! Wake up! Can{SINGLE_QUOTE}t you{NL}wake up, {SPECIAL_06_PAR_1}{END}!?{END}"


text_1605__089D4EC0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8E}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati {SPECIAL_02_PAR_1}{END}disguised himself as the king{NL}to search for the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}.{NL}When he learned of this place, he{NL}waited for us to reforge the blade.{NL}If that stained glass is accurate,{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Princess Zelda holds the light force{SPECIAL_02_PAR_1}{END}!{NL}Vaati will do whatever it takes to{NL}steal that power from her!{NL}If he succeeds, we may never be able{NL}to return the princess to normal!{NL}We{SINGLE_QUOTE}ve wasted too much time, {SPECIAL_06_PAR_1}{END}!{NL}We must stop Vaati!{END}"


text_1606__089D505A:
	.string "{END}"


text_1607__089D505B:
	.string "{END}"


text_1608__089D505C:
	.string "{END}"


text_1609__089D505D:
	.string "{END}"


text_160A__089D505E:
	.string "{END}"


text_160B__089D505F:
	.string "{END}"


text_160C__089D5060:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E8}Ha ha ha!{NL}You ARE persistent, aren{SINGLE_QUOTE}t you?{END}"


text_160D__089D508D:
	.string "Heh heh heh heh heh heh...{NL}{NL}So, you{SINGLE_QUOTE}ve come to stop my little{NL}ceremony. Well, you{SINGLE_QUOTE}re too late.{NL}A mere {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}three more chimes of the bell{SPECIAL_02_PAR_1}{END}{NL}will bring the ceremony to its end!{NL}And with the third toll of the bell,{NL}I will become like a {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}god{SPECIAL_02_PAR_1}{END}!{NL}And your precious {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END} will{NL}be nothing more than cold, dead stone.{END}"


text_160E__089D51CD:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}There{SINGLE_QUOTE}s no time! Quickly, {SPECIAL_06_PAR_1}{END},{NL}to the roof!{END}"


text_160F__089D51FB:
	.string "{END}"


text_1610__089D51FC:
	.string "{END}"


text_1611__089D51FD:
	.string "{END}"


text_1612__089D51FE:
	.string "{END}"


text_1613__089D51FF:
	.string "{END}"


text_1614__089D5200:
	.string "{END}"


text_1615__089D5201:
	.string "{END}"


text_1616__089D5202:
	.string "{END}"


text_1617__089D5203:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Did you hear that, {SPECIAL_06_PAR_1}{END}?{NL}Hurry! There are {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}only two chimes left{SPECIAL_02_PAR_1}{END}!{END}"


text_1618__089D5248:
	.string "{END}"


text_1619__089D5249:
	.string "{END}"


text_161A__089D524A:
	.string "{END}"


text_161B__089D524B:
	.string "{END}"


text_161C__089D524C:
	.string "{END}"


text_161D__089D524D:
	.string "{END}"


text_161E__089D524E:
	.string "{END}"


text_161F__089D524F:
	.string "{END}"


text_1620__089D5250:
	.string "{END}"


text_1621__089D5251:
	.string "{END}"


text_1622__089D5252:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}Another bell has tolled...{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Just one more chime{SPECIAL_02_PAR_1}{END}, and all our{NL}work will have been for naught!{END}"


text_1623__089D52B6:
	.string "{END}"


text_1624__089D52B7:
	.string "{END}"


text_1625__089D52B8:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}{SPECIAL_06_PAR_1}{END}! No, it can{SINGLE_QUOTE}t be! The bell has{NL}rung for a third time!{END}"


text_1626__089D52F4:
	.string "{END}"


text_1627__089D52F5:
	.string "{END}"


text_1628__089D52F6:
	.string "{END}"


text_1629__089D52F7:
	.string "{END}"


text_162A__089D52F8:
	.string "{END}"


text_162B__089D52F9:
	.string "{END}"


text_162C__089D52FA:
	.string "{END}"


text_162D__089D52FB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E8}Hmph! Just a few more moments, and the{NL}ceremony would have been complete.{NL}You really are obsessed with stopping{NL}me, aren{SINGLE_QUOTE}t you? Ah, very well.{NL}I have not yet drained all of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light{NL}force{SPECIAL_02_PAR_1}{END} housed in Princess Zelda.{NL}But what I have should suffice...{NL}I shall be transformed! Unstoppable!{NL}But let me first attend to the pesky{NL}worms who would trifle with me...{END}"


text_162E__089D5467:
	.string "Hmph!{END}"


text_162F__089D546D:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E9}I will have no more of you interfering{NL}with my plans!{NL}Let me show you true power!!{END}"


text_1630__089D54C6:
	.string "{END}"


text_1631__089D54C7:
	.string "{END}"


text_1632__089D54C8:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}{SPECIAL_03_PAR_2}{END}{BYTE_9B}Well, you seem to have some fight in{NL}you. I commend your bravery.{NL}But you will not survive...THIS!!{END}"


text_1633__089D5532:
	.string "{END}"


text_1634__089D5533:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}{SPECIAL_03_PAR_2}{END}{BYTE_9B}Grrrrr.....{NL}I am filled with a power that you cannot{NL}begin to understand! Do you think that{NL}puny sword will save you from ME?!{END}"


text_1635__089D55B8:
	.string "{END}"


text_1636__089D55B9:
	.string "{END}"


text_1637__089D55BA:
	.string "{END}"


text_1638__089D55BB:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_92}You did it! Impressive! Now, quickly!{NL}We must break the curse on {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Zelda{SPECIAL_02_PAR_1}{END}!{END}"


text_1639__089D560A:
	.string "What... What is this madness?{NL}{NL}I have the power of a god!{NL}{NL}I have unstoppable might!!!{NL}{NL}How could I lose to a child?!?{END}"


text_163A__089D5681:
	.string "{END}"


text_163B__089D5682:
	.string "{END}"


text_163C__089D5683:
	.string "{END}"


text_163D__089D5684:
	.string "{END}"


text_163E__089D5685:
	.string "{END}"


text_163F__089D5686:
	.string "{END}"


text_1640__089D5687:
	.string "{END}"


text_1641__089D5688:
	.string "{END}"


text_1642__089D5689:
	.string "{END}"


text_1643__089D568A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E3}{SPECIAL_06_PAR_1}{END}, thank you so much for{NL}saving me.{NL}When I was turned to stone, I saw{NL}visions of you, as if in a dream.{END}"


text_1644__089D56F6:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_DF}Oh! That {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}! I...remember it...{NL}{NL}You still have it? That{SINGLE_QUOTE}s so sweet!{NL}I knew I could count on you.{END}"


text_1645__089D5763:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}It looks like the curse has been{NL}broken. I{SINGLE_QUOTE}m glad we made it in time.{END}"


text_1646__089D57AC:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}No! The castle{SINGLE_QUOTE}s collapsing!{NL}{NL}It{SINGLE_QUOTE}s too dangerous here. Quickly!{NL}We must escape from the castle!{END}"


text_1647__089D580F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}Hrmm... The door is blocked! We have no{NL}choice... Head back to the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}sanctuary{SPECIAL_02_PAR_1}{END}!{END}"


text_1648__089D5864:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_8D}So, {SPECIAL_06_PAR_1}{END}! Now that you have the{NL}power of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Four Sword{SPECIAL_02_PAR_1}{END}...{NL}you must return {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda {SPECIAL_02_PAR_1}{END}to{NL}normal!{END}"


text_1649__089D58D2:
	.string "{END}"


text_164A__089D58D3:
	.string "{END}"


text_164B__089D58D4:
	.string "{END}"


text_164C__089D58D5:
	.string "{END}"


text_164D__089D58D6:
	.string "{END}"


text_164E__089D58D7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_9B}{SPECIAL_06_PAR_1}{END}! And you, Ezlo!{NL}{NL}I will not let you escape this place{NL}alive...{NL}Witness the power of Vaati{SINGLE_QUOTE}s Wrath!{NL}I have transcended! I am all there is!{NL}Allow me to give you a taste of pure{NL}power, of unstoppable might!{END}"


text_164F__089D59A9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E8}Heh heh heh heh...{NL}You will not escape, boy.{NL}Now, you will see the true power of{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}...{NL}For I have become Vaati,{NL}the master of this world!{END}"


text_1650__089D5A47:
	.string "{END}"


text_1651__089D5A48:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_07_PAR_1}Fool! I... But the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}...{NL}My power... I had such power...{END}"


text_1652__089D5A91:
	.string "{END}"


text_1653__089D5A92:
	.string "{END}"


text_1654__089D5A93:
	.string "{END}"


text_1655__089D5A94:
	.string "{END}"


text_1656__089D5A95:
	.string "{END}"


text_1657__089D5A96:
	.string "{END}"


text_1658__089D5A97:
	.string "{END}"


text_1659__089D5A98:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E3}{SPECIAL_06_PAR_1}{END}, thank goodness you{SINGLE_QUOTE}re{NL}safe...{NL}You defeated Vaati...{NL}You were so brave!{NL}But we{SINGLE_QUOTE}ve lost so much...{NL}The castle... All those people...{END}"


text_165A__089D5B22:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E7}What{SINGLE_QUOTE}s this?{NL}{NL}The curse... Defeating Vaati seems to{NL}have broken the curse he cast upon me!{END}"


text_165B__089D5B80:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E6}Allow me to introduce myself{NL}to you, Princess Zelda.{NL}My name is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Ezlo{SPECIAL_02_PAR_1}{END}, master of Minish{NL}lore and sorcery.{NL}The mage{SINGLE_QUOTE}s cap was my creation.{NL}{NL}But its limitless power has caused{NL}nothing but trouble for your kind.{NL}Is there any way you can forgive me?{NL}{NL}I know many have fallen, and much of{NL}the castle has been destroyed...{NL}But it is too soon to give{NL}in to despair.{NL}The curse on me is broken, and Zelda{NL}still possesses some of the light force.{NL}Perhaps, together, we can do{NL}something to make things right.{END}"


text_165C__089D5D78:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E6}If one with a just heart wears this{NL}cap, things can be made right again.{END}"


text_165D__089D5DC4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E5}Princess Zelda!{NL}Let your wishes be made real!{END}"


text_165E__089D5DF5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E6}Hmm-hmm!{NL}{NL}The hat is falling apart. It{SINGLE_QUOTE}s{NL}overflowing with the power of life!{NL}The hat has the power to turn the{NL}thoughts of its wearer into reality.{NL}Vaati{SINGLE_QUOTE}s heart was filled with evil, and{NL}that was reflected in what he became.{NL}But it seems that Zelda{SINGLE_QUOTE}s pure heart,{NL}coupled with the hat{SINGLE_QUOTE}s power...{NL}...has created a miracle!{END}"


text_165F__089D5F3A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E6}Hmm... It looks like the time for us{NL}to part has come.{NL}The Minish Door opens but once every{NL}century, and soon, it must close.{NL}I must leave you both now and return{NL}to my homeland.{NL}I know I{SINGLE_QUOTE}ve caused you much suffering,{NL}but the evil one{SINGLE_QUOTE}s power has withered.{NL}The power of Princess Zelda herself{NL}has restored the light to Hyrule.{END}"


text_1660__089D6084:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}Well, {SPECIAL_06_PAR_1}{END}, my journey with you{NL}has been exciting, to say the least.{NL}In fact, I{SINGLE_QUOTE}m...more than just a little{NL}sad that we must part ways now.{END}"


text_1661__089D6111:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}Please, accept this...{END}"


text_1662__089D612B:
	.string "Heh... You know, I{SINGLE_QUOTE}ve never actually{NL}seen you wearing a cap until now!{BYTE_09}x{NL}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E6}It suits you, little hero.{NL}{BYTE_09}x{END}"


text_1663__089D6195:
	.string "Take care...{NL}{BYTE_09}x{END}"


text_1664__089D61A5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E0}{SPECIAL_04_PAR_2}{BYTE_10}{BYTE_0E}Look! The castle! All the people who{NL}had been turned to stone!{NL}They{SINGLE_QUOTE}re all back to normal!{END}"


text_1665__089D6206:
	.string "Farewell, my friend...{NL}{BYTE_09}x{END}"


text_1666__089D6220:
	.string "{END}"


text_1667__089D6221:
	.string "{END}"

