
text_1000__089CDAF0:
	.string "{END}"


text_1001__089CDAF1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_95}Good morning, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Master Smith{SPECIAL_02_PAR_1}{END}.{END}"


text_1002__089CDB14:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_C2}Goodness me! {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}!{NL}{NL}Did you sneak out of the castle{NL}and come all this way alone?{NL}The minister is sure to be worried{NL}about you! You know how he gets!{END}"


text_1003__089CDBBA:
	.string "Oh, don{SINGLE_QUOTE}t worry about him! He{SINGLE_QUOTE}ll be fine.{NL}Where{SINGLE_QUOTE}s {SPECIAL_06_PAR_1}{END}?{NL}The whole town is bustling for the{NL}annual {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Picori Festival{SPECIAL_02_PAR_1}{END}!{NL}I thought he and I might go together.{NL}Would you mind terribly?{END}"


text_1004__089CDC6E:
	.string "Oh, is that what you{SINGLE_QUOTE}re here for? {NL}{NL}Well, {SPECIAL_06_PAR_1}{END} was up late helping me{NL}last night, and he{SINGLE_QUOTE}s still asleep...{NL}But I do have an errand at the{NL}castle... Yes, that should be fine.{NL}{SPECIAL_07_PAR_1}{BYTE_10}{SPECIAL_05_PAR_1}{END}{SPECIAL_06_PAR_1}{END}, time to get up!{END}"


text_1005__089CDD1E:
	.string "{SPECIAL_06_PAR_1}{END}, time to get up!{END}"


text_1006__089CDD32:
	.string "{END}"


text_1007__089CDD33:
	.string "{END}"


text_1008__089CDD34:
	.string "{END}"


text_1009__089CDD35:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}Hey! {SPECIAL_06_PAR_1}{END}!{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END} is here. She{SINGLE_QUOTE}d like to{NL}know if you{SINGLE_QUOTE}d join her at the festival.{END}"


text_100A__089CDD94:
	.string "Yeah, {SPECIAL_06_PAR_1}{END}. Come on! Let{SINGLE_QUOTE}s{NL}go check out the festival together!{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Master Smith{SPECIAL_02_PAR_1}{END} already gave me{NL}permission to take you!{END}"


text_100B__089CDE0A:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}Yes. After all, the festival only comes{NL}once a year. Go on, have fun!{NL}And while you{SINGLE_QUOTE}re there, you can do me{NL}a favor.{NL}I just finished making this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword {SPECIAL_02_PAR_1}{END}for{NL}the minister at {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}.{NL}I{SINGLE_QUOTE}d like you to deliver it to him.{END}"


text_100C__089CDEF2:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}This is the blade that will be presented{NL}to the winner of the competition.{NL}Don{SINGLE_QUOTE}t lose it. And while the two of you{NL}may be childhood friends, remember...{NL}{SPECIAL_07_PAR_1}{BYTE_10}{BYTE_0E}{END}"


text_100D__089CDF92:
	.string "Master Smith, quit worrying! We{SINGLE_QUOTE}ll be{NL}perfectly safe.{NL}Come on, {SPECIAL_06_PAR_1}{END}! Let{SINGLE_QUOTE}s go{NL}check out the festival!{END}"


text_100E__089CDFF6:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{END}Zelda is the princess of Hyrule.{NL}{NL}You watch over her. Don{SINGLE_QUOTE}t let{NL}anything bad happen to her.{END}"


text_100F__089CE055:
	.string "{END}"


text_1010__089CE056:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_94}{SPECIAL_06_PAR_1}{END}! Over here!{NL}{END}"


text_1011__089CE069:
	.string "Come on, {SPECIAL_06_PAR_1}{END}. Let{SINGLE_QUOTE}s hurry{NL}to the castle.{END}"


text_1012__089CE091:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_95}{SPECIAL_06_PAR_1}{END}!{NL}Hurry! Let{SINGLE_QUOTE}s go!{END}"


text_1013__089CE0A9:
	.string "Over here! Come on!{NL}Hurry up!{END}"


text_1014__089CE0C7:
	.string "Well, here we are! The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}town of Hyrule{SPECIAL_02_PAR_1}{END}!{END}"


text_1015__089CE0F2:
	.string "{END}"


text_1016__089CE0F3:
	.string "{END}"


text_1017__089CE0F4:
	.string "{END}"


text_1018__089CE0F5:
	.string "{END}"


text_1019__089CE0F6:
	.string "{END}"


text_101A__089CE0F7:
	.string "{END}"


text_101B__089CE0F8:
	.string "{END}"


text_101C__089CE0F9:
	.string "{END}"


text_101D__089CE0FA:
	.string "{END}"


text_101E__089CE0FB:
	.string "{END}"


text_101F__089CE0FC:
	.string "{END}"


text_1020__089CE0FD:
	.string "{END}"


text_1021__089CE0FE:
	.string "We have a winner!{END}"


text_1022__089CE110:
	.string "Oh, my! Princess Zelda! You won the{NL}grand prize in our drawing? Wow!{NL}You get your choice of any of these{NL}wonderful prizes. What will it be?{END}"


text_1023__089CE19C:
	.string "First, we have...this lovely{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}heart-shaped stone{SPECIAL_02_PAR_1}{END}!{NL}Next, we have...{END}"


text_1024__089CE1E2:
	.string "this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}magnificent gem{SPECIAL_02_PAR_1}{END}!{NL}And finally, there{SINGLE_QUOTE}s...{END}"


text_1025__089CE214:
	.string "this teeny-tiny {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}.{END}"


text_1026__089CE230:
	.string "So, which one would you like?{NL}{NL}Let me guess...the jewel? Oh, but this{NL}heart stone is very cute, too.{NL}Choose whichever one you like!{NL}{END}"


text_1027__089CE2B5:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield {SPECIAL_02_PAR_1}{END}is so adorable! I think{NL}I{SINGLE_QUOTE}ll take it.{END}"


text_1028__089CE2EA:
	.string "What!? Why? Why would you want that{NL}ugly thing!?{NL}What about the heart stone! It{SINGLE_QUOTE}s cute!{NL}{NL}Or... Or this giant gem! It{SINGLE_QUOTE}s pretty!{NL}{NL}Honestly, they{SINGLE_QUOTE}re both much nicer than{NL}that nasty little shield thing.{END}"


text_1029__089CE3B1:
	.string "Nope! I want the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}.{NL}Can I have it?{END}"


text_102A__089CE3DD:
	.string "What a strange princess you are.{NL}Well...{NL}OK. Here{SINGLE_QUOTE}s your teeny-tiny {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}.{NL}{END}"


text_102B__089CE42E:
	.string "Here! I want to give you a present!{NL}{NL}Doesn{SINGLE_QUOTE}t this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END} suit you perfectly,{NL}{SPECIAL_06_PAR_1}{END}?{END}"


text_102C__089CE483:
	.string "Yep! Just as I thought! You look great!{NL}{NL}Now, if anything happens, you can{NL}protect me with that shield!{NL}Oh! I almost forgot! We have to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}take{NL}Master Smith{SINGLE_QUOTE}s sword to the castle{SPECIAL_02_PAR_1}{END}.{NL}Let{SINGLE_QUOTE}s go, {SPECIAL_06_PAR_1}{END}.{END}"


text_102D__089CE546:
	.string "{END}"


text_102E__089CE547:
	.string "{END}"


text_102F__089CE548:
	.string "{END}"


text_1030__089CE549:
	.string "{END}"


text_1031__089CE54A:
	.string "{END}"


text_1032__089CE54B:
	.string "{END}"


text_1033__089CE54C:
	.string "{END}"


text_1034__089CE54D:
	.string "{END}"


text_1035__089CE54E:
	.string "{END}"


text_1036__089CE54F:
	.string "{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}{END}{BYTE_A9}Oh! {SPECIAL_06_PAR_1}{END}! You brought the{NL}sword, did you?{NL}Then, as minister to the kingdom of{NL}Hyrule, I, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Potho{SPECIAL_02_PAR_1}{END}, accept this blade.{NL}You came just in time. The award{NL}ceremony will begin soon.{END}"


text_1037__089CE605:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_94}{SPECIAL_04_PAR_2}{BYTE_10}{SPECIAL_0C_PAR_1}I{SINGLE_QUOTE}m sorry, {SPECIAL_06_PAR_1}{END}, but I{SINGLE_QUOTE}d better go.{NL}I have to prepare for the ceremony.{NL}I had a good time at the festival.{NL}Thanks for coming with me!{END}"


text_1038__089CE68F:
	.string "Since you{SINGLE_QUOTE}re here, {SPECIAL_06_PAR_1}{END}, why don{SINGLE_QUOTE}t{NL}you join us for the award ceremony?{END}"


text_1039__089CE6D4:
	.string "Do you know about {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}that sword{SPECIAL_02_PAR_1}{END},{NL}{SPECIAL_06_PAR_1}{END}?{NL}It is called the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picori Blade{SPECIAL_02_PAR_1}{END}, and it{NL}locks much evil away in that chest.{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picori Blade{SPECIAL_02_PAR_1}{END} is sacred among the{NL}people of Hyrule.{NL}The legend has it that, long ago, the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END} gave us this blade.{NL}Whoever wins the competition earns the{NL}honor of touching the sacred blade.{END}"


text_103A__089CE813:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F2}Let the award ceremony commence!{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}, champion of the competition,{NL}you may approach the blade!{END}"


text_103B__089CE87C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AA}Ah! Princess Zelda!! Wh--{NL}When did you leave the castle?!{END}"


text_103C__089CE8B9:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AA}Welcome to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}!{END}"


text_103D__089CE8DA:
	.string "Sorry, but we{SINGLE_QUOTE}re getting things ready{NL}for the ceremony. I can{SINGLE_QUOTE}t let you pass.{END}"


text_103E__089CE928:
	.string "Preparations for the award ceremony{NL}are coming along nicely.{END}"


text_103F__089CE965:
	.string "Sorry, but I can{SINGLE_QUOTE}t let you pass. We{SINGLE_QUOTE}ve{NL}sealed the area off because of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}.{END}"


text_1040__089CE9B6:
	.string "Ah, the sword for the award ceremony!{NL}You should take that to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minister Potho{SPECIAL_02_PAR_1}{END}.{NL}You{SINGLE_QUOTE}ll find him in front of the castle.{END}"


text_1041__089CEA30:
	.string "{END}"


text_1042__089CEA31:
	.string "{END}"


text_1043__089CEA32:
	.string "Heh heh heh...{NL}{NL}To think things would go this well!{NL}{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picori Blade{SPECIAL_02_PAR_1}{END} and the Bound Chest{NL}spoken of in Hylian lore...{NL}This chest must hold that which I seek!{NL}I{SINGLE_QUOTE}ll relieve you of its contents now.{END}"


text_1044__089CEAFA:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_9B}Mmmm ah hah hah hah!{NL}Do not interfere with me...{NL}As victor, I{SINGLE_QUOTE}ve earned the right to{NL}approach the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picori Blade{SPECIAL_02_PAR_1}{END}...{NL}I{SINGLE_QUOTE}ve been waiting for this moment!{END}"


text_1045__089CEB96:
	.string "Who are you? Why are you doing this?{END}"


text_1046__089CEBBB:
	.string "The princess with the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}mystic aura{SPECIAL_02_PAR_1}{END}...{NL}{NL}...The power that was gifted to the{NL}people of Hyrule still flows{NL}within the veins of the ladies{NL}of its royal family? Interesting...{NL}If I leave you now, you{SINGLE_QUOTE}ll only cause{NL}me trouble later. That will never do.{END}"


text_1047__089CECB5:
	.string "To stone with you!{END}"


text_1048__089CECC8:
	.string "{SPECIAL_06_PAR_1}{END}! Watch out!{NL}{BYTE_09}{END}"


text_1049__089CECDA:
	.string "...?!?{NL}{NL}Empty? There was nothing in there{NL}but a rabble of monsters?{NL}What is the meaning of this?{NL}{NL}Well, I know the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}force{SPECIAL_02_PAR_1}{END} I{SINGLE_QUOTE}m after is{NL}somewhere out there.{NL}I{SINGLE_QUOTE}m in no hurry. I can take my{NL}time searching for it.{NL}{SPECIAL_03_PAR_2}{END}{BYTE_9B}Heh heh heh...{END}"


text_104A__089CEDC1:
	.string "Heh heh heh heh... All who stand{NL}in my way shall share this fate!{NL}Now, to find out what power awaits{NL}me in this chest!{END}"


text_104B__089CEE38:
	.string "Eeeeeeeek!{END}"


text_104C__089CEE43:
	.string "{END}"


text_104D__089CEE44:
	.string "{END}"


text_104E__089CEE45:
	.string "{END}"


text_104F__089CEE46:
	.string "{END}"


text_1050__089CEE47:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_A3}It is as you have all heard.{NL}{NL}A sorcerer named {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END} has cursed my{NL}fair Zelda and turned her to stone.{NL}If we had the sacred {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picori Blade{SPECIAL_02_PAR_1}{END}, we{NL}likely could have broken the curse.{NL}But Vaati shattered the blade...{NL}{NL}However, I have not given up hope.{NL}What do you know about the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}?{END}"


text_1051__089CEF6F:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}? Not much, beyond what the{NL}fairy tales say...{NL}They{SINGLE_QUOTE}re supposed to be very tiny, if I{SINGLE_QUOTE}m{NL}remembering correctly.{END}"


text_1052__089CEFEC:
	.string "Yes, the ones from the fairy tales...{NL}{NL}But the Picori are no mere legend.{NL}They most certainly exist.{NL}No one outside of the royal family{NL}knows the truth about them.{NL}The Picori, who forged the sacred{NL}blade, live deep within {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END}.{NL}They should be able to repair the{NL}broken blade and reforge the sword.{END}"


text_1053__089CF122:
	.string "Wh-What!? Then we must dispatch the{NL}soldiers there at once!{END}"


text_1054__089CF15E:
	.string "No, soldiers will not do.{NL}{NL}The Picori do not show themselves{NL}to anyone but children.{NL}Our soldiers could search for days{NL}and still find no sign of them.{END}"


text_1055__089CF1F6:
	.string "I see...{NL}{NL}If that{SINGLE_QUOTE}s the case, then why not{NL}send {SPECIAL_06_PAR_1}{END}?{END}"


text_1056__089CF22A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_EB}If {SPECIAL_06_PAR_1}{END} has recovered, then yes,{NL}I would like to ask this of him.{NL}Please, turn my precious Zelda back{NL}to normal.{NL}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END} should know how to create a{NL}new {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred sword{SPECIAL_02_PAR_1}{END}.{NL}It will be a dangerous journey, now{NL}that those monsters have been freed.{NL}Please, take this sword with you,{NL}along with the broken {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Picori Blade{SPECIAL_02_PAR_1}{END}.{END}"


text_1057__089CF370:
	.string "Very well, then. Send the soldiers to{NL}search for {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END} at once!{END}"


text_1058__089CF3B4:
	.string "Deep within the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END}, you will{NL}find a place called {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Deepwood Shrine{SPECIAL_02_PAR_1}{END}.{NL}Once, humans and {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END} shared that{NL}shrine as a meeting place.{NL}I think it would be best if you{NL}started your search there.{END}"


text_1059__089CF486:
	.string "Take this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map {SPECIAL_02_PAR_1}{END}with you.{NL}{NL}{SPECIAL_07_PAR_1}{BYTE_10}^{END}"


text_105A__089CF4A7:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END} lies southeast{NL}of the town of Hyrule.{NL}In fact, it{SINGLE_QUOTE}s due east of your{NL}house, {SPECIAL_06_PAR_1}{END}.{END}"


text_105B__089CF508:
	.string "Oh, {SPECIAL_06_PAR_1}{END}. You{SINGLE_QUOTE}re awake. Are you{NL}feeling all right?{NL}Stand at my side. The king of{NL}Hyrule is about to speak.{END}"


text_105C__089CF571:
	.string "I am counting on you, {SPECIAL_06_PAR_1}{END}.{NL}{NL}Only you can break {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Vaati{SINGLE_QUOTE}s curse{NL}{SPECIAL_02_PAR_1}{END}and free Princess Zelda.{END}"


text_105D__089CF5CA:
	.string "{END}"


text_105E__089CF5CB:
	.string "If you get lost on your way to the{NL}forest, simply check your map.{NL}Just press START and then {SPECIAL_0C_PAR_1}{SPECIAL_02_PAR_1} or{NL}{SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2} to open the map.{NL}I{SINGLE_QUOTE}ve marked the location of the forest{NL}for you. Good luck, and be careful.{END}"


text_105F__089CF68C:
	.string "Oh, thank goodness!{NL}You{SINGLE_QUOTE}ve awakened!{NL}{SPECIAL_07_PAR_1}{BYTE_10}`{END}"


text_1060__089CF6B5:
	.string "Master Smith is here as well. He{SINGLE_QUOTE}s come{NL}to see His Majesty the king.{END}"


text_1061__089CF6FA:
	.string "Please find a way to break the curse{NL}on Princess Zelda.{END}"


text_1062__089CF732:
	.string "Please be careful!{END}"


text_1063__089CF745:
	.string "Press {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2} while walking to roll. This{NL}is useful when you want to move fast.{NL}Don{SINGLE_QUOTE}t forget! And if you want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}save{SPECIAL_02_PAR_1}{END}{NL}during the game, press {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}START{SPECIAL_02_PAR_1}{END}{NL}and choose SAVE from the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Items{NL}screen{SPECIAL_02_PAR_1}{END} or the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Quest Status screen{SPECIAL_02_PAR_1}{END}.{END}"


text_1064__089CF825:
	.string "There are monsters outside the castle.{NL}{NL}If you see one, use your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END} to{NL}defend yourself.{NL}Move in close enough to use your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}{NL}if you need to fight.{END}"


text_1065__089CF8C6:
	.string "{END}"


text_1066__089CF8C7:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E0}Owwwwch!{NL}{NL}That must be the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Business Scrub{SPECIAL_02_PAR_1}{END} I{NL}heard the soldiers talking about.{NL}They were saying a Deku Scrub had{NL}been hassling all the passersby.{NL}{SPECIAL_06_PAR_1}{END}, do something about it!{NL}Otherwise, we can{SINGLE_QUOTE}t get to the castle.{NL}If only we had some way to defend{NL}ourselves against {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}those nuts of his{SPECIAL_02_PAR_1}{END}.{END}"


text_1067__089CF9EC:
	.string "If we could just defend against those{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}nuts{SPECIAL_02_PAR_1}{END}, I{SINGLE_QUOTE}m sure we could do something!{END}"


text_1068__089CFA3C:
	.string "I actually feel a little sorry for that{NL}Business Scrub. But that nut hurt!{NL}Oh, well. He won{SINGLE_QUOTE}t be hassling anyone{NL}now! We{SINGLE_QUOTE}d better hurry to the castle!{END}"


text_1069__089CFAD3:
	.string "Where are you going, {SPECIAL_06_PAR_1}{END}?{NL}Hurry up and do something!{END}"


text_106A__089CFB07:
	.string "Please! Forgive me, sir!{NL}{NL}I heard there was a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}festival{SPECIAL_02_PAR_1}{END}, and I{NL}came to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}town {SPECIAL_02_PAR_1}{END}hoping to hawk my wares.{NL}Unfortunately, we scrubs have a{NL}tendency to spit nuts when we speak!{NL}Everyone got scared and ran away,{NL}and no one would buy anything!{NL}This is a terrible place to do{NL}business! I{SINGLE_QUOTE}m going back to my cave!{END}"


text_106B__089CFC3D:
	.string "{END}"


text_106C__089CFC3E:
	.string "All right! To the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}castle {SPECIAL_02_PAR_1}{END}we go!{END}"


text_106D__089CFC62:
	.string "{END}"


text_106E__089CFC63:
	.string "{END}"


text_106F__089CFC64:
	.string "{END}"


text_1070__089CFC65:
	.string "{END}"


text_1071__089CFC66:
	.string "Even turned to stone by {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Vaati{SINGLE_QUOTE}s{NL}curse{SPECIAL_02_PAR_1}{END}, her eyes are filled with life.{NL}Hurry... Save her...{END}"


text_1072__089CFCC5:
	.string "{END}"

