
text_2C00__089DEBE4:
	.string "{END}"


text_2C01__089DEBE5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}Ah, yes, yes. Welcome, welcome!{NL}Please, feel free to browse!{END}"


text_2C02__089DEC25:
	.string "Only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees for a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}!{NL}You simply won{SINGLE_QUOTE}t find a better deal!{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C03__089DEC6F:
	.string "Only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees for {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}10 bombs{SPECIAL_02_PAR_1}{END}. Such{NL}bargains are unheard of elsewhere!{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C04__089DECBC:
	.string "Only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees for a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}wallet{SPECIAL_02_PAR_1}{END}. It{NL}can hold a king{SINGLE_QUOTE}s ransom in Rupees!{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C05__089DED08:
	.string "Only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees for {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}30 Mysterious{NL}Shells{SPECIAL_02_PAR_1}{END}. Great for buying figurines!{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C06__089DED55:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}Hey, when did you come back here? Did{NL}you come back here just to get that?{NL}My, my, my! You sure do like bottles.{NL}{NL}I had no intentions of selling it, but{NL}you DO seem desperate.{NL}I{SINGLE_QUOTE}ll tell you what... I{SINGLE_QUOTE}ll sell you{NL}that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle {SPECIAL_02_PAR_1}{END}for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees!{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C07__089DEE4F:
	.string "Oh, the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}quiver{SPECIAL_02_PAR_1}{END}? Yes, it{SINGLE_QUOTE}s {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees!{NL}It holds many {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}arrows{SPECIAL_02_PAR_1}{END}, as you can see.{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C08__089DEEA6:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}10 arrows{SPECIAL_02_PAR_1}{END} for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees.{NL}An astounding bargain, you{SINGLE_QUOTE}ll agree.{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C09__089DEEEC:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}30 bombs{SPECIAL_02_PAR_1}{END} for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees! Yes,{NL}for you, I give you my bulk rate!{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C0A__089DEF33:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}30 arrows {SPECIAL_02_PAR_1}{END}for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees!{NL}You can{SINGLE_QUOTE}t beat that with a stick!{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C0B__089DEF76:
	.string "You {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}already have a fine shield{SPECIAL_02_PAR_1}{END}!{NL}Honestly, who needs TWO {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shields{SPECIAL_02_PAR_1}{END}?!{END}"


text_2C0C__089DEFC0:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}Ah, my friend, you{SINGLE_QUOTE}re far too clever by{NL}half, but you won{SINGLE_QUOTE}t be haggling with me!{END}"


text_2C0D__089DF014:
	.string "Why do you bother shopping if you{SINGLE_QUOTE}re{NL}not going to have enough Rupees?{NL}When you have more money, perhaps{NL}we can discuss this further.{END}"


text_2C0E__089DF099:
	.string "You don{SINGLE_QUOTE}t seem to have enough room{NL}for anything more. Hm. A pity.{END}"


text_2C0F__089DF0DB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}Much obliged, my good lad! Please,{NL}do not hesitate to stop by again!{END}"


text_2C10__089DF123:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}Well! You ARE a big spender,{NL}aren{SINGLE_QUOTE}t you? Thank you!{END}"


text_2C11__089DF15A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}Have I told you how much I appreciate{NL}your continued patronage?{NL}Because I do.{END}"


text_2C12__089DF1AB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}Hello! Is anyone back there?{NL}No? Ah, well... I guess not.{NL}How odd.{END}"


text_2C13__089DF1F1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}Egad! I knew there was someone here!{NL}When did you find your way back here?{NL}This area is for employees only. That is{NL}to say, me and me alone!{END}"


text_2C14__089DF281:
	.string "Will you buy it?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1},{SPECIAL_0C_PAR_1}Don{SINGLE_QUOTE}t buy{END}"


text_2C15__089DF2A5:
	.string "{END}"


text_2C16__089DF2A6:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F4}I{SINGLE_QUOTE}m sorry, my good lad, but{NL}that is not for sale!{NL}That bottle contains food{NL}for my dear little dog, Fifi...{NL}What? You just want the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bottle{SPECIAL_02_PAR_1}{END}?{NL}That{SINGLE_QUOTE}s highly unusual...{NL}Well, fine. If you feed Fifi, then{NL}I guess {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}you can have the bottle{SPECIAL_02_PAR_1}{END}.{NL}How does that sound?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}I{SINGLE_QUOTE}ll do it {SPECIAL_05_PAR_1},{BYTE_17}No, thanks{END}"


text_2C17__089DF3CC:
	.string "Fine, fine. It{SINGLE_QUOTE}s up to you.{END}"


text_2C18__089DF3E8:
	.string "Excellent, excellent. He{SINGLE_QUOTE}s at my{NL}home right now. Thank you SO much.{END}"


text_2C19__089DF42C:
	.string "Allow me to mark the location of my{NL}home here on your map.{END}"


text_2C1A__089DF467:
	.string "Bring whatever piece you like.{NL}{NL}The shape you like is simply{NL}a matter of personal taste, goro!{END}"


text_2C1B__089DF4C6:
	.string "All gone! Come again.{END}"


text_2C1C__089DF4DC:
	.string "Yes, Kinstones!{NL}Each one is different, goro!{NL}This Kinstone costs {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees. {NL} {SPECIAL_05_PAR_1}{BYTE_FF}Buy {SPECIAL_05_PAR_1},{BYTE_1D}Don{SINGLE_QUOTE}t buy{END}"


text_2C1D__089DF53D:
	.string "No deal? Goro! Too bad! But come{NL}again. I will always have good pieces!{END}"


text_2C1E__089DF585:
	.string "You don{SINGLE_QUOTE}t have enough Rupees...{NL}Come back with more money, goro.{END}"


text_2C1F__089DF5C6:
	.string "You have too many pieces! I can{SINGLE_QUOTE}t{NL}sell you any until you make room!{END}"


text_2C20__089DF60A:
	.string "Thank you, goro. Come back anytime{NL}and buy the rest!{END}"


text_2C21__089DF63F:
	.string "No more, no more, but come back{NL}again. I promise to find more, goro!{END}"


text_2C22__089DF684:
	.string "I believe there should be a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}doggie{NL}dish{SPECIAL_02_PAR_1}{END} for my dog back at my house.{NL}Just face the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}dish{SPECIAL_02_PAR_1}{END} and press {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2} to{NL}dump the food into little Fifi{SINGLE_QUOTE}s bowl.{END}"


text_2C23__089DF71B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D1}My master, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Stockwell{SPECIAL_02_PAR_1}{END}, has been coming{NL}home far too late to play with me...{NL}I{SINGLE_QUOTE}m so lonely.{END}"


text_2C24__089DF77C:
	.string "That {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}boomerang{SPECIAL_02_PAR_1}{END} is a real bargain{NL}at {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees.{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"


text_2C25__089DF7B3:
	.string "That {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}big bomb bag{SPECIAL_02_PAR_1}{END} is a real bargain{NL}at {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees.{NL}{SPECIAL_07_PAR_1},{BYTE_14}{END}"

