
text_3100__089E1830:
	.string "{END}"


text_3101__089E1831:
	.string "What? What do you want? Why are{NL}you bothering me, kid?{NL}Huh? Oh, my name{SINGLE_QUOTE}s Gorman. I{SINGLE_QUOTE}m trying{NL}my hand at real estate.{NL}Turns out, it{SINGLE_QUOTE}s a total pain. Like right{NL}now, I{SINGLE_QUOTE}m looking for a tenant, you see?{NL}But the thing is, I can only rent to a{NL}woman, single occupancy.{NL}Too many tenants would make the{NL}place dirty. And they{SINGLE_QUOTE}d be loud.{NL}I like things nice and quiet, see?{NL}And this is all just too much hassle.{NL}{SPECIAL_07_PAR_1}1{SPECIAL_02_PAR_1}{END}If you find anyone who can rent this{NL}place, would you let me know?{END}"


text_3102__089E19C5:
	.string "If you find anyone who can rent this{NL}place, would you let me know?{END}"


text_3103__089E1A08:
	.string "Oh! You have a house to show me?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1}1{BYTE_09}No{END}"


text_3104__089E1A35:
	.string "Oh! You{SINGLE_QUOTE}ve found me a house to rent?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1}1{NL}No{END}"


text_3105__089E1A66:
	.string "Oh! You{SINGLE_QUOTE}re showing me an empty house?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1}1{BYTE_0B}No{END}"


text_3106__089E1A98:
	.string "Really? Thanks!{NL}I want to go see it right away!{END}"


text_3107__089E1AC8:
	.string "Thanks!{NL}I can{SINGLE_QUOTE}t wait to check it out!{END}"


text_3108__089E1AEE:
	.string "Thanks!{NL}I{SINGLE_QUOTE}ll get right on it!{END}"


text_3109__089E1B0C:
	.string "Oh... Well, let me know if{NL}you hear anything.{END}"


text_310A__089E1B3A:
	.string "Oh, come on!! Well, you HAVE to tell{NL}me if you hear about anything good!{END}"


text_310B__089E1B83:
	.string "Hey, why not?! Well, let me know{NL}if something comes up!{END}"


text_310C__089E1BBB:
	.string "I{SINGLE_QUOTE}ll build here, I think...{END}"


text_310D__089E1BD7:
	.string "Nice house, huh, kid?{NL}It{SINGLE_QUOTE}s brand-spankin{SINGLE_QUOTE} new, I tell ya!{NL}But I just need another tenant,{NL}a single woman, like before.{NL}{SPECIAL_07_PAR_1}1{BYTE_0E}{END}"


text_310E__089E1C52:
	.string "Well, if you know any nice young{NL}ladies needing a home, let me know!{END}"


text_310F__089E1C97:
	.string "Oh! You have a house to show me?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1}1{BYTE_09}No{END}"


text_3110__089E1CC4:
	.string "Oh! You{SINGLE_QUOTE}ve found me a house?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1}1{NL}No{END}"


text_3111__089E1CED:
	.string "Oh! You{SINGLE_QUOTE}re showing me an empty house?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1}1{BYTE_0B}No{END}"


text_3112__089E1D1F:
	.string "Really?{NL}Oh, and it{SINGLE_QUOTE}s so nice and new!{END}"


text_3113__089E1D45:
	.string "Oh, fabulous!{NL}And it{SINGLE_QUOTE}s so clean and new!{END}"


text_3114__089E1D6E:
	.string "Whoa! Thanks! And it{SINGLE_QUOTE}s a new{NL}house and everything!{END}"


text_3115__089E1DA1:
	.string "I{SINGLE_QUOTE}ve lined up a sizable pile of cash{NL}from my rental properties...{NL}Maybe I should start breeding pets{NL}next. Moohahaha!{END}"


text_3116__089E1E17:
	.string "Oh, hello, {SPECIAL_06_PAR_1}{END}. I sure{NL}do love it here. Thanks again!{NL}{SPECIAL_07_PAR_1}1({END}"


text_3117__089E1E50:
	.string "If you ever need a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charm{SPECIAL_02_PAR_1}{END},{NL}I{SINGLE_QUOTE}ll give you another, so just ask!{END}"


text_3118__089E1E92:
	.string "Want a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charm {SPECIAL_02_PAR_1}{END}for your bottle?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}1{BYTE_1A}No, thanks{END}"


text_3119__089E1ECB:
	.string "All right! There you go!{NL}Come back anytime!{END}"


text_311A__089E1EF7:
	.string "OK... But feel free to ask anytime!{END}"


text_311B__089E1F1B:
	.string "Oh, you don{SINGLE_QUOTE}t have an empty bottle.{NL}Well, come back when you have one.{END}"


text_311C__089E1F62:
	.string "Welcome, {SPECIAL_06_PAR_1}{END}!{NL}I really love this house!{NL}{SPECIAL_07_PAR_1}1){END}"


text_311D__089E1F8D:
	.string "If you ever need a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charm{SPECIAL_02_PAR_1}{END},{NL}I{SINGLE_QUOTE}ll give you another, so just ask!{END}"


text_311E__089E1FCF:
	.string "Want a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charm {SPECIAL_02_PAR_1}{END}for your bottle?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}1 No, thanks{END}"


text_311F__089E2008:
	.string "All right! There it is!{NL}Come back anytime!{END}"


text_3120__089E2033:
	.string "OK... But feel free to ask anytime!{END}"


text_3121__089E2057:
	.string "Oh, you don{SINGLE_QUOTE}t have an empty bottle.{NL}Well, come back when you have one.{END}"


text_3122__089E209E:
	.string "Oh, {SPECIAL_06_PAR_1}{END}! Thanks for coming! I love{NL}this place, and I owe it all to you!{NL}{SPECIAL_07_PAR_1}1*{END}"


text_3123__089E20E9:
	.string "If you ever need a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charm{SPECIAL_02_PAR_1}{END},{NL}I{SINGLE_QUOTE}ll give you another, so just ask!{END}"


text_3124__089E212B:
	.string "Want a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charm {SPECIAL_02_PAR_1}{END}for your bottle?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}1&No, thanks{END}"


text_3125__089E2164:
	.string "All right! There it is!{NL}Come back anytime!{END}"


text_3126__089E218F:
	.string "OK... But feel free to ask anytime!{END}"


text_3127__089E21B3:
	.string "Oh, you don{SINGLE_QUOTE}t have an {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}empty bottle{SPECIAL_02_PAR_1}{END}.{NL}Well, come back when you have one.{END}"


text_3128__089E21FE:
	.string "If you have an empty bottle, I can put{NL}one of my homemade {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charms {SPECIAL_02_PAR_1}{END}inside!{NL}Just ask anytime!{END}"


text_3129__089E225D:
	.string "If you have an empty bottle, I can put{NL}one of my homemade {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charms {SPECIAL_02_PAR_1}{END}inside!{NL}Just ask anytime!{END}"


text_312A__089E22BC:
	.string "If you have an empty bottle, I can put{NL}one of my homemade {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}charms {SPECIAL_02_PAR_1}{END}inside!{NL}Just ask anytime!{END}"


text_312B__089E231B:
	.string "{END}"


text_312C__089E231C:
	.string "{END}"


text_312D__089E231D:
	.string "{END}"


text_312E__089E231E:
	.string "{END}"


text_312F__089E231F:
	.string "{END}"


text_3130__089E2320:
	.string "{END}"


text_3131__089E2321:
	.string "{END}"


text_3132__089E2322:
	.string "{END}"

