
text_4900__089F4C84:
	.string "{END}"


text_4901__089F4C85:
	.string "Welcome to the library!{NL}{NL}Say, aren{SINGLE_QUOTE}t you Smith{SINGLE_QUOTE}s grandson,{NL}{SPECIAL_06_PAR_1}{END}?{NL}Hm? The books missing from the{NL}bookshelf on the second floor?{NL}Yes, they{SINGLE_QUOTE}ve been checked out for{NL}quite a while. They{SINGLE_QUOTE}re VERY overdue!{NL}{SPECIAL_07_PAR_1}I{SPECIAL_02_PAR_1}{NL}{END}"


text_4902__089F4D4E:
	.string "Take {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}A Hyrulean Bestiary{SPECIAL_02_PAR_1}{END}, for{NL}example. Been gone for ages.{NL}Checked out by {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}a girl with a cat{SPECIAL_02_PAR_1}{END}. She{NL}said she had a new cat at her house.{NL}Wanted to learn more about it, she did.{END}"


text_4903__089F4E04:
	.string "The next overdue book is...{NL}Let{SINGLE_QUOTE}s see...{NL}Ah, yes! Of course...{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Legend of the{NL}Picori{SPECIAL_02_PAR_1}{END}! It{SINGLE_QUOTE}s been out forever!{NL}It was checked out by a somewhat{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}absentminded scholar{SPECIAL_02_PAR_1}{END}, I believe...{END}"


text_4904__089F4EBB:
	.string "And the last book we still need{NL}is {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}A History of Masks{SPECIAL_02_PAR_1}{END}.{NL}I think it was checked out by {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hagen{SPECIAL_02_PAR_1}{END},{NL}the mayor.{NL}How could he keep a library book{NL}so long! He{SINGLE_QUOTE}s a public official!{END}"


text_4905__089F4F6C:
	.string "{END}"


text_4906__089F4F6D:
	.string "Hey! Look at that! Our long-lost copy{NL}of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}A Hyrulean Bestiary{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_06_PAR_1}{END}, are you returning{NL}this book?! Thank you so much!{NL}I can{SINGLE_QUOTE}t begin to describe how much I{SINGLE_QUOTE}m{NL}looking forward to putting this back!{END}"


text_4907__089F5031:
	.string "Oh my goodness, will you look at that!{NL}{NL}It{SINGLE_QUOTE}s our copy of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Legend of the Picori{SPECIAL_02_PAR_1}{END}!{NL}It{SINGLE_QUOTE}s been checked out for so long!{NL}{SPECIAL_06_PAR_1}{END}, you deserve a medal{NL}for all this!{NL}I am moved... Deeply, deeply moved{NL}by this thoughtful gesture!{END}"


text_4908__089F510C:
	.string "Would you look at that! I can{SINGLE_QUOTE}t believe{NL}it! It{SINGLE_QUOTE}s our copy of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}A History of Masks{SPECIAL_02_PAR_1}{END}!{NL}That mayor of ours is a real piece of{NL}work, isn{SINGLE_QUOTE}t he?{NL}It must have been quite a challenge{NL}to get this back from him.{NL}You are my new favorite person,{NL}{SPECIAL_06_PAR_1}{END}! Thank you so much!{END}"


text_4909__089F520D:
	.string "{END}"


text_490A__089F520E:
	.string "{END}"


text_490B__089F520F:
	.string "{END}"


text_490C__089F5210:
	.string "You know, {SPECIAL_06_PAR_1}{END}, you{SINGLE_QUOTE}ve now{NL}returned all of our overdue books!{NL}Now I can finally get that bookshelf{NL}on the second floor in order!{NL}Hey, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Sturgeon{SPECIAL_02_PAR_1}{END}! Books to shelve!!{END}"


text_490D__089F52B4:
	.string "Yes, yes! Here I am! I{SINGLE_QUOTE}m here! I{SINGLE_QUOTE}ll have{NL}these books put away lickety-split!{END}"


text_490E__089F5301:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_DB}Sometimes, these books move on their{NL}own! I{SINGLE_QUOTE}ve seen it with my own two eyes!{NL}An{SINGLE_QUOTE} don{SINGLE_QUOTE}t tell me I{SINGLE_QUOTE}m crazy!{NL}I ain{SINGLE_QUOTE}t crazy!{END}"


text_490F__089F537D:
	.string "Say, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Sturgeon{SPECIAL_02_PAR_1}{END}, on the second floor,{NL}has been acting a little strange.{NL}He keeps babbling about the books{NL}moving around on their own!{NL}Do you think maybe we have rats{NL}or something up there?{END}"


text_4910__089F543C:
	.string "I{SINGLE_QUOTE}m in charge of checking out books,{NL}so it{SINGLE_QUOTE}s not my problem.{NL}Still, I feel really bad for the girl{NL}over there in charge of returns...{END}"


text_4911__089F54C2:
	.string "Folks don{SINGLE_QUOTE}t come up here so often.{NL}I get a touch lonely on my own.{END}"


text_4912__089F5505:
	.string "Welcome to the library!{NL}{NL}Hey! Aren{SINGLE_QUOTE}t you Smith{SINGLE_QUOTE}s grandson,{NL}{SPECIAL_06_PAR_1}{END}? Enjoy your browsing!{END}"


text_4913__089F5559:
	.string "The bookshelves are back in order!{NL}Ah, I feel so...so...renewed!{NL}Enjoy your browsing!{END}"


text_4914__089F55AF:
	.string "Wonder what I should check out today.{END}"


text_4915__089F55D5:
	.string "Oh ho ho! All the books are back{NL}on the shelves! Isn{SINGLE_QUOTE}t it grand!{END}"


text_4916__089F5616:
	.string "{END}"

