
text_0200__089B2A70:
	.string "NPC Name{END}"


text_0201__089B2A79:
	.string "Mysterious Cloud{END}"


text_0202__089B2A8A:
	.string "Mysterious Statue{END}"


text_0203__089B2A9C:
	.string "Source of the Flow{END}"


text_0204__089B2AAF:
	.string "Percy{END}"


text_0205__089B2AB5:
	.string "Mysterious Wall{END}"


text_0206__089B2AC5:
	.string "Belari{END}"


text_0207__089B2ACC:
	.string "{END}"


text_0208__089B2ACD:
	.string "Stranger{END}"


text_0209__089B2AD6:
	.string "Din{END}"


text_020A__089B2ADA:
	.string "Farore{END}"


text_020B__089B2AE1:
	.string "Nayru{END}"


text_020C__089B2AE7:
	.string "Swiftblade{END}"


text_020D__089B2AF2:
	.string "Grayblade{END}"


text_020E__089B2AFC:
	.string "Waveblade{END}"


text_020F__089B2B06:
	.string "Grimblade{END}"


text_0210__089B2B10:
	.string "Swiftblade I{END}"


text_0211__089B2B1D:
	.string "Gentari{END}"


text_0212__089B2B25:
	.string "Festari{END}"


text_0213__089B2B2D:
	.string "Melari{END}"


text_0214__089B2B34:
	.string "Librari{END}"


text_0215__089B2B3C:
	.string "Forest Minish{END}"


text_0216__089B2B4A:
	.string "Mountain Minish{END}"


text_0217__089B2B5A:
	.string "Town Minish{END}"


text_0218__089B2B66:
	.string "Village Minish{END}"


text_0219__089B2B75:
	.string "Library Minish{END}"


text_021A__089B2B84:
	.string "{END}"


text_021B__089B2B85:
	.string "Goron{END}"


text_021C__089B2B8B:
	.string "Business Scrub{END}"


text_021D__089B2B9A:
	.string "Spookter{END}"


text_021E__089B2BA3:
	.string "{END}"


text_021F__089B2BA4:
	.string "Damp{BYTE_E9}{END}"


text_0220__089B2BAA:
	.string "Syrup{END}"


text_0221__089B2BB0:
	.string "{END}"


text_0222__089B2BB1:
	.string "Anton{END}"


text_0223__089B2BB7:
	.string "Sheila{END}"


text_0224__089B2BBE:
	.string "June{END}"


text_0225__089B2BC3:
	.string "Keeley{END}"


text_0226__089B2BCA:
	.string "Gepper{END}"


text_0227__089B2BD1:
	.string "Klaus{END}"


text_0228__089B2BD7:
	.string "Marshall{END}"


text_0229__089B2BE0:
	.string "Dottie{END}"


text_022A__089B2BE7:
	.string "Edmond{END}"


text_022B__089B2BEE:
	.string "Martin{END}"


text_022C__089B2BF5:
	.string "Spekter{END}"


text_022D__089B2BFD:
	.string "Guts{END}"


text_022E__089B2C02:
	.string "Match{END}"


text_022F__089B2C08:
	.string "{END}"


text_0230__089B2C09:
	.string "Zill{END}"


text_0231__089B2C0E:
	.string "Lolly{END}"


text_0232__089B2C14:
	.string "Candy{END}"


text_0233__089B2C1A:
	.string "{END}"


text_0234__089B2C1B:
	.string "Crenel Hermit{END}"


text_0235__089B2C29:
	.string "{END}"


text_0236__089B2C2A:
	.string "Verona{END}"


text_0237__089B2C31:
	.string "Julietta{END}"


text_0238__089B2C3A:
	.string "Romio{END}"


text_0239__089B2C40:
	.string "{END}"


text_023A__089B2C41:
	.string "Mama{END}"


text_023B__089B2C46:
	.string "Joe{END}"


text_023C__089B2C4A:
	.string "Baris{END}"


text_023D__089B2C50:
	.string "Chai{END}"


text_023E__089B2C55:
	.string "Herb{END}"


text_023F__089B2C5A:
	.string "Jasmine{END}"


text_0240__089B2C62:
	.string "Breve{END}"


text_0241__089B2C68:
	.string "{END}"


text_0242__089B2C69:
	.string "Mutoh{END}"


text_0243__089B2C6F:
	.string "Mack{END}"


text_0244__089B2C74:
	.string "Doyle{END}"


text_0245__089B2C7A:
	.string "Bremor{END}"


text_0246__089B2C81:
	.string "Brent{END}"


text_0247__089B2C87:
	.string "{END}"


text_0248__089B2C88:
	.string "Beedle{END}"


text_0249__089B2C8F:
	.string "Pina{END}"


text_024A__089B2C94:
	.string "Brocco{END}"


text_024B__089B2C9B:
	.string "{END}"


text_024C__089B2C9C:
	.string "Emma{END}"


text_024D__089B2CA1:
	.string "Bindle{END}"


text_024E__089B2CA8:
	.string "Satchel{END}"


text_024F__089B2CB0:
	.string "{END}"


text_0250__089B2CB1:
	.string "Tina{END}"


text_0251__089B2CB6:
	.string "Dina{END}"


text_0252__089B2CBB:
	.string "Joel{END}"


text_0253__089B2CC0:
	.string "Harrison{END}"


text_0254__089B2CC9:
	.string "Erik{END}"


text_0255__089B2CCE:
	.string "Jim{END}"


text_0256__089B2CD2:
	.string "Berry{END}"


text_0257__089B2CD8:
	.string "Leila{END}"


text_0258__089B2CDE:
	.string "{END}"


text_0259__089B2CDF:
	.string "Anju{END}"


text_025A__089B2CE4:
	.string "Gorman{END}"


text_025B__089B2CEB:
	.string "Monty{END}"


text_025C__089B2CF1:
	.string "Wheaton{END}"


text_025D__089B2CF9:
	.string "Pita{END}"


text_025E__089B2CFE:
	.string "{END}"


text_025F__089B2CFF:
	.string "Dr. Left{END}"


text_0260__089B2D08:
	.string "Rem{END}"


text_0261__089B2D0C:
	.string "{END}"


text_0262__089B2D0D:
	.string "Stamp{END}"


text_0263__089B2D13:
	.string "Marcy{END}"


text_0264__089B2D19:
	.string "{END}"


text_0265__089B2D1A:
	.string "Sturgeon{END}"


text_0266__089B2D23:
	.string "Paige{END}"


text_0267__089B2D29:
	.string "Maggie{END}"


text_0268__089B2D30:
	.string "{END}"


text_0269__089B2D31:
	.string "Hagen{END}"


text_026A__089B2D37:
	.string "{END}"


text_026B__089B2D38:
	.string "Siroc{END}"


text_026C__089B2D3E:
	.string "Hailey{END}"


text_026D__089B2D45:
	.string "Caprice{END}"


text_026E__089B2D4D:
	.string "Gale{END}"


text_026F__089B2D52:
	.string "Strato{END}"


text_0270__089B2D59:
	.string "Gregal{END}"


text_0271__089B2D60:
	.string "{END}"


text_0272__089B2D61:
	.string "Castle Servant{END}"


text_0273__089B2D70:
	.string "Soldier{END}"


text_0274__089B2D78:
	.string "Soldier Captain{END}"


text_0275__089B2D88:
	.string "Potho{END}"


text_0276__089B2D8E:
	.string "Daltus{END}"


text_0277__089B2D95:
	.string "{END}"


text_0278__089B2D96:
	.string "Smith{END}"


text_0279__089B2D9C:
	.string "{END}"


text_027A__089B2D9D:
	.string "Epona{END}"


text_027B__089B2DA3:
	.string "Fifi{END}"


text_027C__089B2DA8:
	.string "Rolf{END}"


text_027D__089B2DAD:
	.string "Growler{END}"


text_027E__089B2DB5:
	.string "Scratcher{END}"


text_027F__089B2DBF:
	.string "Purry{END}"


text_0280__089B2DC5:
	.string "Cucco{END}"


text_0281__089B2DCB:
	.string "Brown Cucco{END}"


text_0282__089B2DD7:
	.string "Cucco Chick{END}"


text_0283__089B2DE3:
	.string "Elsie{END}"


text_0284__089B2DE9:
	.string "{END}"


text_0285__089B2DEA:
	.string "Tingle{END}"


text_0286__089B2DF1:
	.string "Ankle{END}"


text_0287__089B2DF7:
	.string "Knuckle{END}"


text_0288__089B2DFF:
	.string "David Jr.{END}"


text_0289__089B2E09:
	.string "{END}"


text_028A__089B2E0A:
	.string "Postbox{END}"


text_028B__089B2E12:
	.string "{END}"


text_028C__089B2E13:
	.string "{END}"


text_028D__089B2E14:
	.string "Gina{END}"


text_028E__089B2E19:
	.string "Flurris{END}"


text_028F__089B2E21:
	.string "Postman{END}"


text_0290__089B2E29:
	.string "Talon{END}"


text_0291__089B2E2F:
	.string "Malon{END}"


text_0292__089B2E35:
	.string "Eenie{END}"


text_0293__089B2E3B:
	.string "Meenie{END}"


text_0294__089B2E42:
	.string "Hurdy-Gurdy Man{END}"

