
text_1A00__089D6538:
	.string "{END}"


text_1A01__089D6539:
	.string "{END}"


text_1A02__089D653A:
	.string "I love working in my garden. It makes{NL}me feel so close to nature...{NL}And sometimes, just sometimes, I dig up{NL}a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone {SPECIAL_02_PAR_1}{END}from the ground!{END}"


text_1A03__089D65C6:
	.string "What{SINGLE_QUOTE}s up there, bud? You sayin{SINGLE_QUOTE} you{NL}wanna match {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces{SPECIAL_02_PAR_1}{END}?{END}"


text_1A04__089D660C:
	.string "What? Not interested?{NL}All right, that{SINGLE_QUOTE}s cool.{END}"


text_1A05__089D663A:
	.string "Well, look at that! A perfect fit!{END}"


text_1A06__089D665D:
	.string "Hmn? Hey, did you just feel{NL}the earth move?{END}"


text_1A07__089D6689:
	.string "Thanks, pal! I feel like a lean,{NL}mean, earth-tillin{SINGLE_QUOTE} machine!{END}"


text_1A08__089D66C7:
	.string "{END}"


text_1A09__089D66C8:
	.string "{END}"


text_1A0A__089D66C9:
	.string "{END}"


text_1A0B__089D66CA:
	.string "{END}"


text_1A0C__089D66CB:
	.string "{END}"


text_1A0D__089D66CC:
	.string "Rock and roll! I dug up another{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece {SPECIAL_02_PAR_1}{END}from my field!{NL}That rocks!{END}"


text_1A0E__089D671A:
	.string "Wanna {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstone pieces{SPECIAL_02_PAR_1}{END}?{NL}Yeah, rock n{SINGLE_QUOTE} roll!{END}"


text_1A0F__089D674E:
	.string "Boo! You know what you get for{NL}quitting on me? You get a BOOO!{END}"


text_1A10__089D678D:
	.string "Fits like a chip off the ol{SINGLE_QUOTE} rock!{NL}Oh, rock and rolllll!{END}"


text_1A11__089D67C6:
	.string "Rock, rock, rock and roll!{END}"


text_1A12__089D67E1:
	.string "{END}"


text_1A13__089D67E2:
	.string "{END}"


text_1A14__089D67E3:
	.string "{END}"


text_1A15__089D67E4:
	.string "{END}"


text_1A16__089D67E5:
	.string "{END}"


text_1A17__089D67E6:
	.string "{END}"


text_1A18__089D67E7:
	.string "Welcome to Mount Crenel.{NL}I am the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Great Butterfly Fairy{SPECIAL_02_PAR_1}{END}.{NL}I shall increase the size of the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}wallet{SPECIAL_02_PAR_1}{END} you carry.{END}"


text_1A19__089D685B:
	.string "Welcome to Mount Crenel. I am the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Great Mayfly Fairy{SPECIAL_02_PAR_1}{END}.{NL}I shall increase the size of the {NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bomb bag{SPECIAL_02_PAR_1}{END} you carry.{END}"


text_1A1A__089D68CF:
	.string "Welcome to Mount Crenel. I am the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Great Dragonfly Fairy{SPECIAL_02_PAR_1}{END}.{NL}I shall increase the capacity of the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}quiver{SPECIAL_02_PAR_1}{END} you carry.{END}"


text_1A1B__089D6947:
	.string "{END}"


text_1A1C__089D6948:
	.string "{END}"


text_1A1D__089D6949:
	.string "{END}"


text_1A1E__089D694A:
	.string "{END}"


text_1A1F__089D694B:
	.string "{END}"


text_1A20__089D694C:
	.string "{END}"

