
text_4400__089EEA5C:
	.string "{END}"


text_4401__089EEA5D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_CC} Whuzza?! Oh, welcome!{NL}Welcome to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Rem{SINGLE_QUOTE}s Shoe Shop{SPECIAL_02_PAR_1}{END}!{NL}Lately, whenever I take a nap, all my{NL}shoes are done when I wake up!{NL}{SPECIAL_07_PAR_1}D{SPECIAL_02_PAR_1}{END}You know, if I can make shoes in my{NL}sleep, I must be in the right job!{END}"


text_4402__089EEAE0:
	.string "You know, if I can make shoes in my{NL}sleep, I must be in the right job!{END}"


text_4403__089EEB27:
	.string "Mmmmmnumnumnumnum...{END}"


text_4404__089EEB3C:
	.string "Whaa--!{NL}{NL}What is that terrifyingly bad smell!?{NL}A wake-up mushroom?!{NL}I should have guessed!{NL}So you woke me up?{NL}Thanks, I just remembered I have{NL}something urgent to do!{END}"


text_4405__089EEBE3:
	.string "And there we go...{NL}Here, take these.{NL}Those are my special {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Pegasus Boots{SPECIAL_02_PAR_1}{END}!{NL}{NL}They{SINGLE_QUOTE}re so light, you{SINGLE_QUOTE}ll feel like you{SINGLE_QUOTE}re{NL}practically walking on air!{END}"


text_4406__089EEC77:
	.string "Ooh, I need to hurry up and get{NL}working on that special order...{NL}The king asked me to make some{NL}shoes for Princess Zelda, you see.{NL}Thanks for waking me up. Come back if{NL}I can ever help you with shoe problems.{END}"


text_4407__089EED48:
	.string "I need to hurry up and make those{NL}shoes for Princess Zelda!{END}"


text_4408__089EED84:
	.string "Whuzza?! Oh, welcome!{NL}Welcome to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Rem{SINGLE_QUOTE}s Shoe Shop{SPECIAL_02_PAR_1}{END}!{NL}I must have dozed off again...{NL}Time to make the shoes!{END}"


text_4409__089EEDF1:
	.string "{END}"


text_440A__089EEDF2:
	.string "Thank you for waking me up earlier.{NL}{NL}Oh, say, you wouldn{SINGLE_QUOTE}t want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse{NL}Kinstones{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{END}with me, would you?{NL}I have a very special {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}!{END}"


text_440B__089EEE88:
	.string "Come see me again sometime! If I{SINGLE_QUOTE}m{NL}awake, I{SINGLE_QUOTE}ll fuse {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Kinstones{SPECIAL_02_PAR_1}{END} with you!{END}"


text_440C__089EEED4:
	.string "I know! Do you want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}{NL}with me? I have a very special one!{END}"


text_440D__089EEF22:
	.string "I{SINGLE_QUOTE}m really blazing away on these shoes{NL}for Princess Zelda!{END}"


text_440E__089EEF5D:
	.string "?!{NL}Huh? What now?!{NL}There are more new shoes!{NL}You probably won{SINGLE_QUOTE}t believe this, but...{NL}I have a strange habit of making{NL}shoes in my sleep!{NL}So you must have come here because{NL}you want some of my shoes, right?{NL}Tell you what: because you were nice{NL}enough to wake me, you can have {SINGLE_QUOTE}em!{NL}Hold on a sec, though. I just want{NL}to finish this one last bit...{END}"


text_440F__089EF0B7:
	.string "{END}"


text_4410__089EF0B8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}Those {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Pegasus Boots {SPECIAL_02_PAR_1}{END}will make you{NL}want to dash everywhere!{NL}It{SINGLE_QUOTE}s really fun to run headlong into{NL}stuff and really shake things up!{END}"


text_4411__089EF141:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}My {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Pegasus Boots {SPECIAL_02_PAR_1}{END}are so comfortable!{NL}{NL}They{SINGLE_QUOTE}ll make your little piggies{NL}squeal with delight!{END}"


text_4412__089EF1A4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Thanks for wearing my shoes with such{NL}pride, valued customer!{END}"


text_4413__089EF1E5:
	.string "{END}"


text_4414__089EF1E6:
	.string "{END}"


text_4415__089EF1E7:
	.string "{END}"


text_4416__089EF1E8:
	.string "{END}"


text_4417__089EF1E9:
	.string "{END}"


text_4418__089EF1EA:
	.string "{END}"


text_4419__089EF1EB:
	.string "{END}"


text_441A__089EF1EC:
	.string "{END}"


text_441B__089EF1ED:
	.string "{END}"


text_441C__089EF1EE:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}Hey, hey! You{SINGLE_QUOTE}re {SPECIAL_06_PAR_1}{END}, right?{NL}{NL}You{SINGLE_QUOTE}re the one who brought the sword{NL}to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Master Melari{SPECIAL_02_PAR_1}{END}!{NL}You{SINGLE_QUOTE}re on a quest to help the princess,{NL}aren{SINGLE_QUOTE}t you?{NL}I wish I could go on a quest, but{NL}then who{SINGLE_QUOTE}d make {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Rem{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s shoes for him?{END}"


text_441D__089EF2C8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}Ho, ho! You need {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Pegasus Boots{SPECIAL_02_PAR_1}{END}?{NL}Why, you{SINGLE_QUOTE}re just in time!{NL}We made a pair just now while{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Rem {SPECIAL_02_PAR_1}{END}was sleeping.{NL}But only {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Rem {SPECIAL_02_PAR_1}{END}can put the{NL}finishing touches on them...{END}"


text_441E__089EF377:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Ha, ha! That sleepyhead {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Rem {SPECIAL_02_PAR_1}{END}is nearly{NL}impossible to wake up...{NL}If you want to wake him, you{SINGLE_QUOTE}ll need{NL}to get an item from {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Syrup{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s hut.{NL}It{SINGLE_QUOTE}s a little bit of a trek, but{NL}we{SINGLE_QUOTE}ll mark it on your map for you.{END}"


text_441F__089EF44B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}Hey, hey! {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Rem {SPECIAL_02_PAR_1}{END}has some other urgent{NL}business he should be working on...{NL}So please, wake him up as soon as{NL}you can! Time{SINGLE_QUOTE}s a-wastin{SINGLE_QUOTE}!{END}"


text_4420__089EF4D7:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}Ho, ho! We{SINGLE_QUOTE}ve done all we can with{NL}these shoes.{NL}You{SINGLE_QUOTE}ll need to go to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Syrup{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s hut so{NL}Rem can put on the finishing touches.{END}"


text_4421__089EF558:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Ha, ha! {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Syrup{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s hut is north of the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END}. Just check your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}.{END}"


text_4422__089EF5AE:
	.string "I{SINGLE_QUOTE}ll make you shoes! So why don{SINGLE_QUOTE}t you{NL}come back later?{END}"


text_4423__089EF5E5:
	.string "The magic hag may have something{NL}good.{END}"


text_4424__089EF60C:
	.string "Sometimes we help him make shoes.{END}"


text_4425__089EF62E:
	.string "{END}"

