
text_1B00__089D69F8:
	.string "{END}"


text_1B01__089D69F9:
	.string "{END}"


text_1B02__089D69FA:
	.string "The name{SINGLE_QUOTE}s {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mutoh{SPECIAL_02_PAR_1}{END}. I{SINGLE_QUOTE}m head carpenter{NL}{SINGLE_QUOTE}round these parts.{NL}The king of Hyrule has entrusted me{NL}with the town{SINGLE_QUOTE}s reconstruction.{NL}This area you{SINGLE_QUOTE}re standing in right{NL}now? It{SINGLE_QUOTE}s a work zone!{NL}It{SINGLE_QUOTE}s way too dangerous for a little{NL}kid like you.{END}"


text_1B03__089D6AE7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_B5}The name{SINGLE_QUOTE}s {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mutoh{SPECIAL_02_PAR_1}{END}. I{SINGLE_QUOTE}m head carpenter{NL}{SINGLE_QUOTE}round these parts.{NL}The king of Hyrule himself has{NL}entrusted me with this project.{NL}See, that sorcerer{SINGLE_QUOTE}s attack tore{NL}things up pretty bad around here.{NL}You know, kid, you shouldn{SINGLE_QUOTE}t be playing{NL}anywhere near the construction zone.{END}"


text_1B04__089D6BF6:
	.string "{END}"


text_1B05__089D6BF7:
	.string "So, that Picori Blade was just a lock{NL}keeping those monsters in that chest?{NL}The rumor is that Vaati was looking for{NL}something inside the chest...{NL}I mean, something other than monsters.{NL}But nobody knows for sure what it is.{NL}I tell you, he sure has been nothing{NL}but a big headache to the rest of us.{END}"


text_1B06__089D6D21:
	.string "We{SINGLE_QUOTE}ve taken care of most of the{NL}monsters out here.{NL}Be careful around {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END},{NL}though. The woods are thick with {SINGLE_QUOTE}em.{END}"


text_1B07__089D6D9E:
	.string "{END}"


text_1B08__089D6D9F:
	.string "{END}"


text_1B09__089D6DA0:
	.string "{END}"


text_1B0A__089D6DA1:
	.string "{END}"


text_1B0B__089D6DA2:
	.string "{END}"


text_1B0C__089D6DA3:
	.string "{END}"


text_1B0D__089D6DA4:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_CA}Hooo! I{SINGLE_QUOTE}m busy, kid!{NL}{NL}The boss always makes sure we{SINGLE_QUOTE}ve got{NL}our noses to the ol{SINGLE_QUOTE} grindstone.{END}"


text_1B0E__089D6E03:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_CA}Ahh! No time to talk, kid!{NL}{NL}The boss has us working our fingers to{NL}the bone! No time for a break, even!{END}"


text_1B0F__089D6E6E:
	.string "{END}"


text_1B10__089D6E6F:
	.string "{END}"


text_1B11__089D6E70:
	.string "{END}"


text_1B12__089D6E71:
	.string "{END}"


text_1B13__089D6E72:
	.string "{END}"


text_1B14__089D6E73:
	.string "{END}"


text_1B15__089D6E74:
	.string "{END}"


text_1B16__089D6E75:
	.string "{END}"


text_1B17__089D6E76:
	.string "{END}"


text_1B18__089D6E77:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_C0}There have been a lot of creatures on{NL}the rampage lately.{NL}As a result, we{SINGLE_QUOTE}re in a bit of a rush{NL}to get things repaired around here.{END}"


text_1B19__089D6EFE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_C0}That sorcerer was something else!{NL}{NL}He really tore up the town, so we{SINGLE_QUOTE}ve{NL}got a serious backlog of work to do.{END}"


text_1B1A__089D6F6E:
	.string "{END}"


text_1B1B__089D6F6F:
	.string "{END}"


text_1B1C__089D6F70:
	.string "{END}"


text_1B1D__089D6F71:
	.string "{END}"


text_1B1E__089D6F72:
	.string "{END}"


text_1B1F__089D6F73:
	.string "{END}"


text_1B20__089D6F74:
	.string "{END}"


text_1B21__089D6F75:
	.string "{END}"


text_1B22__089D6F76:
	.string "{END}"


text_1B23__089D6F77:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_CA}Creepy... It{SINGLE_QUOTE}s like all these monsters{NL}just appeared out of nowhere...{END}"


text_1B24__089D6FC1:
	.string "{END}"


text_1B25__089D6FC2:
	.string "{END}"


text_1B26__089D6FC3:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_C0}I{SINGLE_QUOTE}m so busy! So busy!{NL}{NL}Gotta finish here, so I can go{NL}repair the steps next!{END}"


text_1B27__089D7013:
	.string "{END}"

