
text_3000__089E1544:
	.string "{END}"


text_3001__089E1545:
	.string "Oh, no! This is horrible!{NL}My cuccos have gotten out!{NL}Can you catch them for me?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}I{SINGLE_QUOTE}ll help! {SPECIAL_05_PAR_1}0{SPECIAL_03_PAR_2}No{END}"


text_3002__089E15A8:
	.string "Try to catch {SPECIAL_06_PAR_1}{SPECIAL_02_PAR_1} of them within{NL}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} seconds, please.{NL}And you can{SINGLE_QUOTE}t go into buildings{NL}or leave town!{END}"


text_3003__089E160A:
	.string "Really? Come on,{NL}why won{SINGLE_QUOTE}t you help me?{END}"


text_3004__089E1632:
	.string "Time{SINGLE_QUOTE}s up!{NL}That{SINGLE_QUOTE}s it!{END}"


text_3005__089E1648:
	.string "Hmmm. Well, it looks like I{SINGLE_QUOTE}m still missing{NL}a lot of cuccos...{NL}But thanks anyway! Maybe you can{NL}help out again another time.{END}"


text_3006__089E16C5:
	.string "You have to catch {SPECIAL_06_PAR_1}{SPECIAL_02_PAR_1} cuccos{NL}in {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} seconds! Good luck!{END}"


text_3007__089E16FB:
	.string "You got {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees! Doesn{SINGLE_QUOTE}t it{NL}feel good to help others?{END}"


text_3008__089E1733:
	.string "{SPECIAL_04_PAR_2}{BYTE_15}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1}{SPECIAL_04_PAR_2}{BYTE_14}{END}"


text_3009__089E173A:
	.string "{END}"


text_300A__089E173B:
	.string "{END}"


text_300B__089E173C:
	.string "{END}"


text_300C__089E173D:
	.string "Thanks!{NL}Here{SINGLE_QUOTE}s your reward.{END}"


text_300D__089E1759:
	.string "{END}"


text_300E__089E175A:
	.string "{END}"


text_300F__089E175B:
	.string "{END}"


text_3010__089E175C:
	.string "{END}"


text_3011__089E175D:
	.string "{END}"


text_3012__089E175E:
	.string "{END}"


text_3013__089E175F:
	.string "{END}"


text_3014__089E1760:
	.string "{END}"

