
text_3E00__089EA45C:
	.string "{END}"


text_3E01__089EA45D:
	.string "The children are on their lunch recess.{NL}Playing is as important as studying!{NL}After all, a healthy body leads to a{NL}healthy mind!{END}"


text_3E02__089EA4DD:
	.string "Hello, {SPECIAL_06_PAR_1}{END}! We haven{SINGLE_QUOTE}t seen you in{NL}school in a while! I{SINGLE_QUOTE}m so glad you came!{END}"


text_3E03__089EA528:
	.string "I tell you, these kids are almost as{NL}mischievous as you are.{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_3E04__089EA567:
	.string "Mmm... Chomp, chomp. We have to eat{NL}fast so we can have a longer recess!{NL}Chomp, chomp.{END}"


text_3E05__089EA5BE:
	.string "Chomp, chomp. I{SINGLE_QUOTE}m always the last to{NL}finish eating...{NL}Chomp, chomp.{END}"


text_3E06__089EA602:
	.string "Recess is almost over...{END}"


text_3E07__089EA61B:
	.string "Mmmmmnumnumnum...{NL}{NL}Zzzzzzzzzzzzz...{END}"


text_3E08__089EA63F:
	.string "I like reading books.{NL}{NL}I get to pretend I{SINGLE_QUOTE}m the hero and run{NL}around having adventures and stuff!{END}"


text_3E09__089EA6A0:
	.string "You kids run along now, you hear?{END}"


text_3E0A__089EA6C2:
	.string "I have to see these kids off{NL}and get home myself.{END}"


text_3E0B__089EA6F4:
	.string "I don{SINGLE_QUOTE}t want to go home.{END}"


text_3E0C__089EA70D:
	.string "I looove school!{END}"

