
text_0F00__089CD754:
	.string "{END}"


text_0F01__089CD755:
	.string "A long, long time ago...{END}"


text_0F02__089CD76E:
	.string "when the world was on the verge of{NL}being swallowed by shadow...{END}"


text_0F03__089CD7AE:
	.string "The tiny Picori{NL}appeared from the{NL}sky, bringing the{NL}hero of men a sword{NL}and a golden light.{END}"


text_0F04__089CD80A:
	.string "With wisdom and{NL}courage, the hero{NL}drove out the{NL}darkness.{END}"


text_0F05__089CD844:
	.string "When peace had been restored, the{NL}people enshrined that blade with care.{END}"


text_0F06__089CD88D:
	.string "And the force of the golden light,{NL}embodied in Hyrule{SINGLE_QUOTE}s princess,{NL}shone forth upon the lands.{END}"


text_0F07__089CD8EB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E8}Heh heh heh...{NL}So that{SINGLE_QUOTE}s what it means...{END}"

