
text_3900__089E81C0:
	.string "{END}"


text_3901__089E81C1:
	.string "There are so few people here now. I{SINGLE_QUOTE}m{NL}afraid something terrible will happen.{END}"


text_3902__089E820E:
	.string "Meoooow...{END}"


text_3903__089E8219:
	.string "Rowrrr!{END}"


text_3904__089E8221:
	.string "{END}"


text_3905__089E8222:
	.string "{END}"


text_3906__089E8223:
	.string "{END}"


text_3907__089E8224:
	.string "{END}"


text_3908__089E8225:
	.string "{END}"


text_3909__089E8226:
	.string "{END}"


text_390A__089E8227:
	.string "{END}"


text_390B__089E8228:
	.string "{END}"


text_390C__089E8229:
	.string "{END}"


text_390D__089E822A:
	.string "{END}"


text_390E__089E822B:
	.string "{END}"


text_390F__089E822C:
	.string "{END}"


text_3910__089E822D:
	.string "{END}"


text_3911__089E822E:
	.string "Buggedy-buggedy-BOO!{NL}{NL}Don{SINGLE_QUOTE}t worry. I{SINGLE_QUOTE}m already looking{NL}for another job.{END}"


text_3912__089E8276:
	.string "Now, it{SINGLE_QUOTE}s time for our rematch!{END}"


text_3913__089E8296:
	.string "Arf arf!{END}"


text_3914__089E829F:
	.string "Fewer people means less trash... I{SINGLE_QUOTE}m{NL}having a tough time finding food...{END}"


text_3915__089E82E8:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle {SPECIAL_02_PAR_1}{END}looks so strange now.{NL}There are monsters everywhere...{NL}Even the town{SINGLE_QUOTE}s not safe anymore.{NL}The people all stay locked up indoors.{END}"


text_3916__089E837A:
	.string "Hey, hey! It{SINGLE_QUOTE}s a closeout sale!{NL}Everything must go!{END}"


text_3917__089E83AE:
	.string "Clearance prices, people! What are{NL}you waiting for!? Hey, hey!{END}"


text_3918__089E83ED:
	.string "Hey, hey! My mom{SINGLE_QUOTE}ll be mad if I take all{NL}this stuff home, so shop up!{END}"


text_3919__089E8433:
	.string "Anyone want to trade for fruit!?{NL}Anybody? Hello? Hey, hey!{END}"


text_391A__089E846E:
	.string "{END}"


text_391B__089E846F:
	.string "I can{SINGLE_QUOTE}t believe this. {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}{NL}has been overrun with monsters...{END}"


text_391C__089E84B9:
	.string "The monsters will be coming for us{NL}next! We{SINGLE_QUOTE}d better stay inside!{END}"


text_391D__089E84FB:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END} has become nothing more{NL}than a giant nest for monsters!{NL}Those of us who are left must protect{NL}the town from those beasts!{END}"


text_391E__089E8587:
	.string "There{SINGLE_QUOTE}s an old legend that something{NL}big will happen when Hyrule{SINGLE_QUOTE}s bell rings.{END}"


text_391F__089E85D6:
	.string "I think the time has come. The time{NL}spoken of in legends.{NL}I{SINGLE_QUOTE}m...moved beyond words...{END}"


text_3920__089E862C:
	.string "Tighten the defenses around the town!{NL}Don{SINGLE_QUOTE}t let them in, no matter what!{END}"


text_3921__089E8675:
	.string "Rrrrr...ARF ARF!{END}"


text_3922__089E8686:
	.string "Arf arf!{END}"


text_3923__089E868F:
	.string "Awooooo!!!{END}"


text_3924__089E869A:
	.string "That kid over there in the glasses{NL}is such a weirdo...{NL}You could probably tell by looking at{NL}him. He{SINGLE_QUOTE}s all right, really.{NL}I mean, it{SINGLE_QUOTE}s just hard to hate{NL}a guy like that! Hehehe...{END}"


text_3925__089E874E:
	.string "My {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurines{SPECIAL_02_PAR_1}{END}! They{SINGLE_QUOTE}re alive!{NL}They{SINGLE_QUOTE}re moving!{NL}Hehehehe...{NL}That{SINGLE_QUOTE}s SO cool!!{END}"


text_3926__089E879C:
	.string "This is definitely not the time to be{NL}looking for that dumb {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}.{END}"


text_3927__089E87E9:
	.string "It{SINGLE_QUOTE}s so lonely here now... I wonder{NL}if the monsters really are coming.{END}"


text_3928__089E8830:
	.string "I{SINGLE_QUOTE}m a rich guy, see?{NL}And I{SINGLE_QUOTE}m a collector to boot.{END}"


text_3929__089E8862:
	.string "If you ever find a complete set of{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurines{SPECIAL_02_PAR_1}{END}, you should tell me.{NL}You...do know what I{SINGLE_QUOTE}m talking about,{NL}don{SINGLE_QUOTE}t you? Well? Get to it!{END}"


text_392A__089E88EA:
	.string "!?{NL}{NL}Whooooooooooooaaaaaaaaaaaaaaa!!!!{NL}{NL}You did it! I can{SINGLE_QUOTE}t believe you did it!{NL}This is...a totally complete set!{NL}How incredibly awesome! And you even{NL}got the legendary Carlov Medal!!! {NL}It shines with a beautiful light...{NL}It{SINGLE_QUOTE}s every collector{SINGLE_QUOTE}s dream!{NL}What you{SINGLE_QUOTE}ve shown me here... It{SINGLE_QUOTE}s{NL}just... It{SINGLE_QUOTE}s just amazing.{NL}Here, feel free to go in my house and{NL}take whatever you want in thanks...{NL}{SINGLE_QUOTE}Cuz, you know, I{SINGLE_QUOTE}m rich! Hahaha!{END}"


text_392B__089E8A8E:
	.string "Way to go, man.{NL}What an awesome day...{END}"


text_392C__089E8AB5:
	.string "Evacuation?! What a pain...{NL}{NL}But I don{SINGLE_QUOTE}t want to cause any trouble,{NL}so I guess I{SINGLE_QUOTE}ll just have to cooperate.{END}"


text_392D__089E8B21:
	.string "Everyone{SINGLE_QUOTE}s getting out of here.{NL}Will there even be a Hyrule Town soon?{END}"


text_392E__089E8B68:
	.string "Maybe I should go hide in the cucco{NL}lady{SINGLE_QUOTE}s house...{NL}It might be dangerous, though. It{NL}seems like there{SINGLE_QUOTE}s danger everywhere.{END}"


text_392F__089E8BE4:
	.string "Hey, you came back?{NL}{NL}Not a lot of people are coming{NL}by anymore... Not these days.{NL}I guess that means you really{NL}like me, huh?{END}"


text_3930__089E8C62:
	.string "We{SINGLE_QUOTE}re under martial law!?{NL}Which Minish house should I go to?{NL}If I end up somewhere alone,{NL}they{SINGLE_QUOTE}ll forget all about me!{NL}Oh goodness, oh goodness!{END}"


text_3931__089E8CF3:
	.string "Thanks for coming.{NL}{NL}Hardly anyone ever visits, and it gets{NL}lonely here. Please take this.{END}"


text_3932__089E8D4D:
	.string "The view from here is nice.{NL}{NL}And {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s screams during{NL}training seem to complement the scene.{END}"


text_3933__089E8DB5:
	.string "Good job getting up here.{NL}Really. That{SINGLE_QUOTE}s impressive.{NL}You must have really put yourself out{NL}to find a way here. Please take this.{END}"


text_3934__089E8E36:
	.string "I wonder how I{SINGLE_QUOTE}m going to get down...{NL}Those cucco chicks just terrify me.{END}"


text_3935__089E8E80:
	.string "Lately, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mutoh{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s been grumbling about{NL}how there{SINGLE_QUOTE}s no work with any punch.{NL}I wish I could do something about that,{NL}but I don{SINGLE_QUOTE}t even know what he means!{END}"


text_3936__089E8F1A:
	.string "I{SINGLE_QUOTE}m so glad the boss is back to his{NL}usual self.{NL}It just makes you grateful{NL}for the good times, you know?{END}"

