
text_0100__089B21DC:
	.string "{NL}{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}DIRECTOR{SPECIAL_02_PAR_1}{END}{NL}{NL}Hidemaro Fujibayashi{END}"


text_0101__089B2204:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}PLANNING{SPECIAL_02_PAR_1}{END}{NL}{NL}Hidemaro Fujibayashi{NL}Suchol Lee{NL}Joko Kazuki{NL}Mitsuki Tsukada{NL}Minoru Nakai{NL}Takashi Hamamura{NL}Shigeki Morihira{END}"


text_0102__089B227D:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}PROGRAMMING{SPECIAL_02_PAR_1}{END}{NL}{NL}Toshihiko Honda{NL}shimitan{NL}Yoshiyuki Fujikawa{NL}N.MINOMIYA{NL}Yohey Doi{NL}K.YOSHIDA{END}"


text_0103__089B22D9:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}OBJECT DESIGN{SPECIAL_02_PAR_1}{END}{NL}{NL}KIMOKIMO{NL}erichop{NL}Kumiko Fujiwara{NL}{NL}Keisuke{NL}     {DOUBLE_QUOTE}TWIGGY{DOUBLE_QUOTE}{NL}         Motozono{END}"


text_0104__089B2336:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}SCROLL DESIGN{SPECIAL_02_PAR_1}{END}{NL}{NL}Nishitsuji Asae{NL}Takayuki Nakayama{NL}Hiroyuki Imahori{NL}Yoshi Maeda{NL}Haruki Suetsugu{END}"


text_0105__089B2398:
	.string "{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}MUSIC{SPECIAL_02_PAR_1}{END}{NL}{NL}Mitsuhiko Takano{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}SOUND EFFECTS{SPECIAL_02_PAR_1}{END}{NL}{NL}Shinji Amagishi{NL}Takashi Moriguchi{END}"


text_0106__089B23EC:
	.string "{NL}{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}CHARACTER DESIGN{SPECIAL_02_PAR_1}{END}{NL}{NL}KIMOKIMO{END}"


text_0107__089B2410:
	.string "{NL}{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}ARTWORK{SPECIAL_02_PAR_1}{END}{NL}{NL}Haruki Suetsugu{END}"


text_0108__089B2432:
	.string "{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}TITLE LOGO DESIGN{SPECIAL_02_PAR_1}{END}{NL}{NL}SHOEI{NL}Satoshi Ukai{END}"


text_0109__089B2460:
	.string "{END}"


text_010A__089B2461:
	.string "{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}SUPERVISOR{SPECIAL_02_PAR_1}{END}{NL}{NL}E. Aonuma{NL}Y. Yamada{NL}M. Narita{NL}T. Tezuka{NL}Y. Yamashita{END}"


text_010B__089B24A8:
	.string "{NL}{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}SOUND ADVISOR{SPECIAL_02_PAR_1}{END}{NL}{NL}K. Kondo{END}"


text_010C__089B24C9:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}SPECIAL THANKS{SPECIAL_02_PAR_1}{END}{NL}{NL}M. TAKEGUCHI{NL}SUPER MARIO CLUB{NL}NOA PRODUCT{NL}         TESTING{NL}{NL}ROCKMAN CLUB{NL}CAPCOM HC{NL}FLAGSHIP Co., Ltd{END}"


text_010D__089B2542:
	.string "{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}SPECIAL THANKS{SPECIAL_02_PAR_1}{END}{NL}{NL}ORIGINAL{NL}     {DOUBLE_QUOTE}ZELDA{DOUBLE_QUOTE} STAFF{END}"


text_010E__089B2576:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}MANAGEMENT{SPECIAL_02_PAR_1}{END}{NL}{NL}nosetake{NL}Masanori Kusumoto{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}PRODUCT{NL}    MANAGEMENT{SPECIAL_02_PAR_1}{END}{NL}{NL}Yasushi Adachi{END}"


text_010F__089B25CE:
	.string "{NL}{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}PRODUCER{SPECIAL_02_PAR_1}{END}{NL}{NL}Keiji Inafune{END}"


text_0110__089B25EF:
	.string "{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}GENERAL{NL}    PRODUCER{SPECIAL_02_PAR_1}{END}{NL}{NL}Shigeru Miyamoto{END}"


text_0111__089B261D:
	.string "{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}EXECUTIVE{NL}      PRODUCER{SPECIAL_02_PAR_1}{END}{NL}{NL}Satoru Iwata{END}"


text_0112__089B264B:
	.string "{END}"


text_0113__089B264C:
	.string "{NL}{NL}{NL}{NL}{NL}NORTH AMERICAN{NL}     LOCALIZATION{NL}{END}"


text_0114__089B2673:
	.string "{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}MANAGEMENT{SPECIAL_02_PAR_1}{END}{NL}{NL}Jeff Miller{NL}Leslie Swan{END}"


text_0115__089B269F:
	.string "{NL}{NL}{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}LOCALIZATION{NL}{NL}{SPECIAL_02_PAR_1}{END}Rich Amtower{NL}Scot Ritchey{NL}Bill Trinen{END}"


text_0116__089B26DB:
	.string "{END}"


text_0117__089B26DC:
	.string "{END}"


text_0118__089B26DD:
	.string "{NL}{NL}{NL}{NL}All Rights, including the copyrights of{NL}Game, Scenario, Music and Program,{NL}reserved by NINTENDO.{END}"


text_0119__089B2742:
	.string "Thus did {SPECIAL_06_PAR_1}{END}{SINGLE_QUOTE}s quest{NL}come to an end.{END}"


text_011A__089B2766:
	.string "But surely, this is not the end of Zelda{NL}and {SPECIAL_06_PAR_1}{END}{SINGLE_QUOTE}s adventures in Hyrule.{END}"


text_011B__089B27AE:
	.string "{NL}The legend will continue...{END}"


text_011C__089B27CB:
	.string "...as long as the power of the light{NL}force echoes throughout the ages.{END}"

