
text_2300__089DB5A4:
	.string "{END}"


text_2301__089DB5A5:
	.string "{END}"


text_2302__089DB5A6:
	.string "The swamp in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Castor Wilds{SPECIAL_02_PAR_1}{END} is{NL}bottomless...I say.{NL}To get across that swamp, you{SINGLE_QUOTE}ll need{NL}to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}run as swiftly as the wind blows{SPECIAL_02_PAR_1}{END}...{END}"


text_2303__089DB62C:
	.string "A dark room settles my soul...I say.{NL}Do not turn on the lights...I say.{END}"


text_2304__089DB674:
	.string "Oh, dear. You found me out!{NL}Don{SINGLE_QUOTE}t tell anyone!{END}"


text_2305__089DB6A3:
	.string "{END}"


text_2306__089DB6A4:
	.string "{END}"


text_2307__089DB6A5:
	.string "{END}"


text_2308__089DB6A6:
	.string "{END}"


text_2309__089DB6A7:
	.string "{END}"


text_230A__089DB6A8:
	.string "{END}"


text_230B__089DB6A9:
	.string "{END}"


text_230C__089DB6AA:
	.string "Hello. I am Percy, poet laureate{NL}of Hyrule.{NL}And you are {SPECIAL_06_PAR_1}{END}? Oh, no,{NL}no! The pleasure is mine!{NL}I travel all over the realm, writing{NL}verse wherever I go.{NL}But here I am, returning after a long{NL}absence only to find the road blocked.{NL}It wouldn{SINGLE_QUOTE}t feel like such a waste if{NL}I hadn{SINGLE_QUOTE}t lost half of my {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{SPECIAL_02_PAR_1}{END}!{NL}When misfortune rains down upon{NL}my head, it pours in torrents!{NL}I think {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}I may have dropped it in the{NL}inn{SPECIAL_02_PAR_1}{END} I stayed at last night...{NL}I see no other course than to put{NL}these tragic events to verse.{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}I see stars beyond the rainbow,{NL}  But I cannot reach them.{NL}  Though the stone I lost is small,{NL}  Large was its place in my heart.{END}"


text_230D__089DB928:
	.string "My way home is blocked. Alas!{NL}{NL}And making matters worse, I lost one of{NL}my {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}stone fragments{SPECIAL_02_PAR_1}{END} in my travels.{NL}When misfortune rains down upon{NL}my head, it pours in torrents!{NL}I wonder if I dropped that stone{NL}fragment {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}in the inn{SPECIAL_02_PAR_1}{END} last night.{NL}I see no other course than to put{NL}these tragic events to verse.{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}I see stars beyond the rainbow,{NL}  But I cannot reach them.{NL}  Though the stone I lost is small,{NL}  Large was its place in my heart.{END}"


text_230E__089DBADF:
	.string "Unfortunately, I only have one{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}fragment{SPECIAL_02_PAR_1}{END}. I{SINGLE_QUOTE}m sorry.{END}"


text_230F__089DBB17:
	.string "Oh, my! That {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}fragment{SPECIAL_02_PAR_1}{END} looks just like{NL}mine! They might even fit together!{END}"


text_2310__089DBB65:
	.string "Oh, perfect! They fit!{NL}{NL}That{SINGLE_QUOTE}s it! I{SINGLE_QUOTE}ve got it now!{NL}The perfect verse!{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Apart or whole,{NL}  These two are one.{NL}  Two lost and broken halves,{NL}  Like me and my beloved.{END}"


text_2311__089DBC0D:
	.string "Oh, dear! {SPECIAL_06_PAR_1}{END}!{NL}Won{SINGLE_QUOTE}t you listen to my verse?{NL}When I finally returned to my home,{NL}sweet home, a stranger was there!{NL}I{SINGLE_QUOTE}m an extremely shy person, and I just{NL}can{SINGLE_QUOTE}t talk to someone I don{SINGLE_QUOTE}t know!{NL}So...I had to put my feelings to verse!{NL}{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}While I was gone, did you break in{NL}  To practice your thieving art?{NL}  Even if you rob my home,{NL}  You can never steal my heart.{END}"


text_2312__089DBD77:
	.string "Oh, my! {SPECIAL_06_PAR_1}{END}! Thanks to you, I can{NL}finally go back in my house.{NL}It{SINGLE_QUOTE}s been totally rearranged, but I{NL}think it{SINGLE_QUOTE}s a good look!{NL}I{SINGLE_QUOTE}ve put my feelings of gratitude{NL}to verse...{NL}  {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}The way made safe, I came back home{NL}  To find me inside, all alone.{NL}  In my chest, my poor heart aches,{NL}  But for you I feel the deepest thanks!{END}"


text_2313__089DBEB4:
	.string "What? You{SINGLE_QUOTE}re going to quit?{NL}Well, come again.{END}"


text_2314__089DBEE2:
	.string "Oh, {SPECIAL_06_PAR_1}{END}!{NL}{NL}Did you come all the way here just to{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END} with me?{END}"


text_2315__089DBF2D:
	.string "Oh, just a moment...{NL}{NL}My dresser is entirely stuffed full{NL}of these icky blue seashells.{NL}Would you clean them out for me?{NL}They{SINGLE_QUOTE}re so...smelly. Please?{END}"

