
text_2000__089D8D50:
	.string "{END}"


text_2001__089D8D51:
	.string "{END}"


text_2002__089D8D52:
	.string "{END}"


text_2003__089D8D53:
	.string "{END}"


text_2004__089D8D54:
	.string "{END}"


text_2005__089D8D55:
	.string "{END}"


text_2006__089D8D56:
	.string "{END}"


text_2007__089D8D57:
	.string "{END}"


text_2008__089D8D58:
	.string "Ruff! Ruff!{END}"


text_2009__089D8D64:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_1A}Honestly! Where did Dad go this time?!?{NL}{NL}I leave for just a few minutes, and he{NL}locks up the ranch and takes off!{END}"


text_200A__089D8DD9:
	.string "I lost my key, and I can{SINGLE_QUOTE}t get inside.{NL}And the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}spare key{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s inside the house!{END}"


text_200B__089D8E2A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_1A}What a pain. And I was thinking of{NL}going into town to sell {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon Milk{SPECIAL_02_PAR_1}{END}.{END}"


text_200C__089D8E7A:
	.string "Oh! Our one and only spare key!{NL}{NL}I don{SINGLE_QUOTE}t know how you got this, but{NL}I can{SINGLE_QUOTE}t thank you enough!{NL}Tell me your name, sonny.{NL}{NL}{SPECIAL_04_PAR_2}{BYTE_12}{SPECIAL_06_PAR_1}{END}"


text_200D__089D8F5D:
	.string "You really helped me out, sonny.{NL}{NL}If you ever want to go to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Lake Hylia{SPECIAL_02_PAR_1}{END},{NL}use the shortcut out behind our ranch.{END}"


text_200E__089D8FD0:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_1A}Thank you, {SPECIAL_06_PAR_1}{END}. Now, I can{NL}finally get back into my house.{NL}Well, I{SINGLE_QUOTE}d better be going. I have a{NL}lot to do before I can leave town.{END}"


text_200F__089D9054:
	.string "Nayhayhayyyy...{END}"


text_2010__089D9064:
	.string "{END}"


text_2011__089D9065:
	.string "Well! If it isn{SINGLE_QUOTE}t {SPECIAL_06_PAR_1}{END}! I just{NL}finished milking our pride and joy.{NL}I{SINGLE_QUOTE}ll tell you what, {SPECIAL_06_PAR_1}{END}... Because{NL}you did us such a big favor...{NL}I{SINGLE_QUOTE}ll sell you some milk at our special,{NL}friends-only price.{NL}If you ever need a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}quick burst of{NL}strength{SPECIAL_02_PAR_1}{END}, just drink it up!{NL}And if you run out, just bring{NL}your empty bottle back for a refill!{NL}Buy some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon Milk {SPECIAL_02_PAR_1}{END}for 30 Rupees?{NL}   {SPECIAL_05_PAR_1}{BYTE_FF}Sure   {SPECIAL_05_PAR_1} {BYTE_14}No, thanks{END}"


text_2012__089D91EC:
	.string "Here you go! Have some freshly{NL}squeezed {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon Milk{SPECIAL_02_PAR_1}{END}!{END}"


text_2013__089D9226:
	.string "Here you go! Have some...{NL}{NL}Whoops!! You don{SINGLE_QUOTE}t have an {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}empty{NL}bottle{SPECIAL_02_PAR_1}{END}! Too bad...{END}"


text_2014__089D9279:
	.string "Drop in for a visit the next time{NL}you{SINGLE_QUOTE}re in the neighborhood.{END}"


text_2015__089D92B7:
	.string "{END}"


text_2016__089D92B8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_1A}Thank you very much, {SPECIAL_06_PAR_1}{END}.{NL}Come visit us again!{END}"


text_2017__089D92E9:
	.string "Bray-hey-hey-hey-hey...{END}"


text_2018__089D9301:
	.string "Moooo!{END}"

