
text_2100__089D944C:
	.string "{END}"


text_2101__089D944D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}We forest {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1} {SPECIAL_02_PAR_1}{END}are good at{NL}growing plants and making tools.{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Minish Berries{SPECIAL_02_PAR_1}{END} we grow here often{NL}contain items that please the humans.{END}"


text_2102__089D94E4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}There{SINGLE_QUOTE}s a weird guy outside the village{NL}who {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}invents all kinds of tools{SPECIAL_02_PAR_1}{END}.{NL}He came to the village a while ago. We{NL}thought maybe he was back for good.{NL}But all he said was {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{DOUBLE_QUOTE}Got any {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}milk{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}?{DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{END}{NL}Maybe he was thirsty or something.{END}"


text_2103__089D95CD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}There{SINGLE_QUOTE}s a weird guy outside the village{NL}who {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}invents all kinds of tools{SPECIAL_02_PAR_1}{END}.{NL}He came to the village a while ago. We{NL}thought maybe he was back for good.{NL}But all he said was {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{DOUBLE_QUOTE}Got any {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}blue{NL}potions{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}?{DOUBLE_QUOTE} {SPECIAL_02_PAR_1}{END}Maybe he caught a cold...{END}"


text_2104__089D96B5:
	.string "{END}"


text_2105__089D96B6:
	.string "{END}"


text_2106__089D96B7:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F7}Sometimes it{SINGLE_QUOTE}s a flower seed, and{NL}sometimes it{SINGLE_QUOTE}s a stone.{NL}We hide our lucky items in all sorts of{NL}unexpected places.{NL}But the real trick is making it tough{NL}for humans to notice!{END}"


text_2107__089D976B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Sometimes it{SINGLE_QUOTE}s a flower seed, and{NL}sometimes it{SINGLE_QUOTE}s a stone.{NL}We hide our lucky items in all sorts of{NL}unexpected places.{NL}But the real trick is making it tough{NL}for humans to notice!{END}"


text_2108__089D981F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}I{SINGLE_QUOTE}ve been getting better at disguising{NL}things so that humans won{SINGLE_QUOTE}t notice {SINGLE_QUOTE}em!{NL}I love my job!{END}"


text_2109__089D9880:
	.string "{END}"


text_210A__089D9881:
	.string "{END}"


text_210B__089D9882:
	.string "{END}"


text_210C__089D9883:
	.string "{END}"


text_210D__089D9884:
	.string "{END}"


text_210E__089D9885:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}Wow! Good job finding this place! There{NL}aren{SINGLE_QUOTE}t many people who visit me here.{END}"


text_210F__089D98D6:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}Hehhe! Great! Let{SINGLE_QUOTE}s fuse now!{END}"


text_2110__089D98F7:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Hehe! That{SINGLE_QUOTE}s why I can{SINGLE_QUOTE}t get enough{NL}of Kinstone fusion!{END}"


text_2111__089D9932:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Awww... Really?{END}"


text_2112__089D9945:
	.string "{END}"


text_2113__089D9946:
	.string "{END}"


text_2114__089D9947:
	.string "{END}"


text_2115__089D9948:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}You{SINGLE_QUOTE}ve heard of travelers who find a{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone {SPECIAL_02_PAR_1}{END}and get really lucky?{NL}Well, that{SINGLE_QUOTE}s all thanks to items made{NL}by us {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END}!{NL}You see, we thrive on making humans{NL}happy. It gives us energy.{NL}But we only do it in secret!{END}"


text_2116__089D9A27:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}You{SINGLE_QUOTE}ve heard of travelers who pick up a{NL}stone and find something under it?{NL}Well, those items were actually left{NL}there by us {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END}!{NL}You see, we thrive on making humans{NL}happy. It gives us energy.{NL}But we only do it in secret!{END}"


text_2117__089D9B0E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}You{SINGLE_QUOTE}ve heard of travelers who pick up a{NL}stone and find something under it?{NL}Well, those items were actually left{NL}there by us {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END}!{NL}We live for making humans happy, but{NL}we only do it in secret!{END}"


text_2118__089D9BD7:
	.string "{END}"


text_2119__089D9BD8:
	.string "{END}"


text_211A__089D9BD9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Our ancestors, the ancient {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END},{NL}used the portal between our worlds.{NL}It brought them into the human world,{NL}and they settled in this forest.{END}"


text_211B__089D9C6E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Our ancestors, the ancient {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish{SPECIAL_02_PAR_1}{END},{NL}used the portal between our worlds.{NL}It brought them here, into the human{NL}world, and they settled in this forest.{NL}The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elder {SPECIAL_02_PAR_1}{END}says our cultures have{NL}changed much since those old days.{END}"


text_211C__089D9D51:
	.string "{END}"


text_211D__089D9D52:
	.string "{END}"


text_211E__089D9D53:
	.string "{END}"


text_211F__089D9D54:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}If you want to reforge that sword, you{NL}will need the help of an expert smith!{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Master Melari{SPECIAL_02_PAR_1}{END} and his seven{NL}apprentices can help you.{NL}They live in the mountains, where they{NL}can find all the ore they need.{NL}I{SINGLE_QUOTE}m sure the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}elder {SPECIAL_02_PAR_1}{END}would tell you about{NL}him if you asked.{END}"


text_2120__089D9E64:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}If you want that sword reforged, you{NL}should see {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}.{NL}He and his apprentices are skilled in{NL}the arts of metalworking.{NL}That{SINGLE_QUOTE}s why they live in the mountain:{NL}so they can be close to the ore!{END}"


text_2121__089D9F2A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}So how was old {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Melari{SPECIAL_02_PAR_1}{END}?{NL}{NL}And were his apprentices singing their{NL}usual work song?{END}"


text_2122__089D9F81:
	.string "Pico ricopi picoco copi!{END}"


text_2123__089D9F9A:
	.string "{END}"


text_2124__089D9F9B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}There are so many monsters around{NL}these woods lately!{NL}The elder said that even the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}shrine {SPECIAL_02_PAR_1}{END}to{NL}the north is filled with monsters now!{END}"


text_2125__089DA026:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}You fought all the monsters and took{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END} from the altar?{NL}You humans are amazing.{END}"


text_2126__089DA08C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}You fought the monsters all the way to{NL}the altar to get the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Earth Element{SPECIAL_02_PAR_1}{END}?{NL}Wow, humans are amazing!{END}"


text_2127__089DA0F7:
	.string "{END}"


text_2128__089DA0F8:
	.string "{END}"


text_2129__089DA0F9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Do you know about {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces{SPECIAL_02_PAR_1}{END}?{NL}They{SINGLE_QUOTE}re all the rage among humans now.{END}"


text_212A__089DA14A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Do you know about {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces{SPECIAL_02_PAR_1}{END}?{NL}They{SINGLE_QUOTE}re all the rage among humans now.{END}"


text_212B__089DA19B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Do you know about {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces{SPECIAL_02_PAR_1}{END}?{NL}They{SINGLE_QUOTE}re all the rage among humans now.{END}"


text_212C__089DA1EC:
	.string "{END}"


text_212D__089DA1ED:
	.string "{END}"


text_212E__089DA1EE:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Hey, nice clothes...{NL}I want to wear human clothes, too!{END}"


text_212F__089DA229:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}I was born and raised here, so I don{SINGLE_QUOTE}t{NL}know much about the outside world.{NL}I hear there are HUGE green monsters{NL}out there in the woods.{NL}I can{SINGLE_QUOTE}t believe you made it through{NL}there alive! You must be really brave!{END}"


text_2130__089DA2FE:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}That{SINGLE_QUOTE}s it! I{SINGLE_QUOTE}ve decided!{NL}{NL}When I grow up, I{SINGLE_QUOTE}m going to be human!{NL}...I wonder how I{SINGLE_QUOTE}ll do that...{END}"


text_2131__089DA362:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}I{SINGLE_QUOTE}m getting set to leave for town and{NL}visit some of my Minish friends there.{END}"


text_2132__089DA3B2:
	.string "{END}"


text_2133__089DA3B3:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}We {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}live in Hyrule Town and other{NL}places, too--not just in these woods.{END}"


text_2134__089DA408:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}Had you never seen any {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}before{NL}you came here?{NL}Really? That{SINGLE_QUOTE}s so strange.{NL}We Minish live all over the place!{END}"


text_2135__089DA481:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}We {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}live in Hyrule Town and other{NL}places, too--not just in these woods.{END}"


text_2136__089DA4D6:
	.string "{END}"


text_2137__089DA4D7:
	.string "{END}"


text_2138__089DA4D8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}You probably haven{SINGLE_QUOTE}t noticed, but lots{NL}of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish {SPECIAL_02_PAR_1}{END}live right in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Town{SPECIAL_02_PAR_1}{END}!{END}"


text_2139__089DA52F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Maybe I should just get out of this{NL}sleepy little town and move to the city.{NL}Or maybe I should go to the mountains.{NL}The folks out there seem to have fun!{END}"


text_213A__089DA5CC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}I received a letter from my friend who{NL}lives in the town library!{NL}I wish I could live in town, too...{END}"


text_213B__089DA635:
	.string "{END}"


text_213C__089DA636:
	.string "{END}"


text_213D__089DA637:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}Hello!{NL}{NL}We{SINGLE_QUOTE}re doing cutting-edge research on{NL}Pico Blooms here.{NL}You see that plant with the little bud?{NL}We{SINGLE_QUOTE}re working on ways to improve it!{END}"


text_213E__089DA6C6:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}I need {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}milk {SPECIAL_02_PAR_1}{END}to continue my improvements{NL}on this Pico Bloom.{NL}I wish someone would bring me some.{END}"


text_213F__089DA72D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Wow, thanks!{NL}Now I can continue my research!{NL}Come on back when this{NL}flower blossoms!{END}"


text_2140__089DA785:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}My new Pico Bloom hasn{SINGLE_QUOTE}t blossomed yet.{NL}Come back soon, though.{END}"


text_2141__089DA7C8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Look! I succeeded in growing a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Yellow{NL}Pico Bloom{SPECIAL_02_PAR_1}{END}! It{SINGLE_QUOTE}s all thanks to you!{NL}I{SINGLE_QUOTE}m so grateful for all your help!{END}"


text_2142__089DA83C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}I am working on my next Pico Bloom{NL}enhancement...{NL}All I need is some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mt. Crenel Mineral{NL}Water{SPECIAL_02_PAR_1}{END} to complete it.{NL}But the mountain is so far away, and I{NL}don{SINGLE_QUOTE}t know how to get any.{NL}I wish someone would bring me some.{END}"


text_2143__089DA917:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Wow, thanks! This is just what I{NL}needed to complete my research!{NL}Come back when the bud blossoms!{END}"


text_2144__089DA97C:
	.string "{END}"


text_2145__089DA97D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Look! I succeeded in growing a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Blue{NL}Pico Bloom{SPECIAL_02_PAR_1}{END}! It{SINGLE_QUOTE}s all thanks to you!{NL}I{SINGLE_QUOTE}m so grateful for all your help!{END}"


text_2146__089DA9EF:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}I am working on my next Pico Bloom{NL}enhancement...{NL}But I need a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}red potion{SPECIAL_02_PAR_1}{END} to finish. If{NL}only I knew where some could be found.{NL}I wish someone would bring me some.{END}"


text_2147__089DAA99:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Wow, thanks! This is just what I needed{NL}to make that bud blossom!{NL}Come back and see how it turns out!{END}"


text_2148__089DAB02:
	.string "{END}"


text_2149__089DAB03:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Look! I succeeded in growing an{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Orange Pico Bloom{SPECIAL_02_PAR_1}{END}, thanks to your help!{NL}I{SINGLE_QUOTE}m so grateful to you!{END}"


text_214A__089DAB6A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}I{SINGLE_QUOTE}m taking a break from my research,{NL}but I have lots of good ideas.{NL}Super Pico Bloom...{NL}Hyper Pico Bloom...{NL}Cyber Pico Bloom...{NL}Which one should I work on first?{END}"


text_214B__089DAC0F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Hey! What{SINGLE_QUOTE}ve you got there?{NL}Is that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon Milk{SPECIAL_02_PAR_1}{END}?{NL}Did you bring it for me?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}!NNo{END}"


text_214C__089DAC6F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Hey! What{SINGLE_QUOTE}ve you got there?{NL}Is that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mt. Crenel Mineral Water{SPECIAL_02_PAR_1}{END}?{NL}Did you bring it for me?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}!NNo{END}"


text_214D__089DACDB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Hey! What{SINGLE_QUOTE}ve you got there?{NL}Is that a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}red potion{SPECIAL_02_PAR_1}{END}?{NL}Did you bring it for me?{NL}{SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}!NNo{END}"


text_214E__089DAD3B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Oh, sorry then... If you change your{NL}mind, do let me know.{END}"

