
text_1D00__089D7294:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}MYAAAAWWWN!!{NL}{NL}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}What a nap!!{END}"


text_1D01__089D72B5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}Welcome. Goro.{NL}Oh, what a tiny Goron you are...{NL}You make this big Goron happy with this{NL}unexpected visit to my distant home.{NL}And yes, if you should ever accomplish{NL}some major feat...{NL}Well, then you should come back and{NL}visit me again...{NL}Don{SINGLE_QUOTE}t forget.{END}"


text_1D02__089D73B3:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}Welcome. Goro.{NL}Oh, what a tiny Goron you are...{NL}You make this big Goron happy with this{NL}unexpected visit to my distant home.{NL}Tell me, little one, what do you know{NL}about {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shields{SPECIAL_02_PAR_1}{END}?{NL}Well, among us Gorons, who know well{NL}the taste of steel...{NL}They are considered a fine delicacy.{NL}Ah, yes...{NL}Just once, I should like to taste{NL}a fine, fresh shield...{END}"


text_1D03__089D7511:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}Thank you for the delicious {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield {SPECIAL_02_PAR_1}{END}you{NL}gave me last time you came.{NL}I think of that flavor even now... ...{NL}... ... ... ... ... ... ... ... ... ...{NL}... ... ... ... ... ... ... ... ... ...{NL}... ... ... ... ... ... ... ... ... ...{NL}... ... ... ... ... ... ... ... ... ...{NL}... ... ... ... ... ... ... ... ... ...{NL}Sigh... Even thinking about it takes me{NL}to faraway places.{NL}If you ever find another such shield,{NL}you must let me taste it, please!{END}"


text_1D04__089D76CD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BA}Welcome. Goro.{NL}Oh, what a tiny Goron you are...{NL}You make this big Goron happy with this{NL}unexpected visit to my distant home.{NL}Oh! Oh, what is that you have there?{NL}Is that by any chance a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}?{NL}Well, among us Gorons, who know well{NL}the taste of steel...{NL}They are considered a fine delicacy.{NL}Little Goron! Please, goro!{NL}Let me just nibble on the corner,{NL}would you?{NL}I will give it back to you just as soon{NL}as I{SINGLE_QUOTE}ve had the tiniest taste.{NL}Won{SINGLE_QUOTE}t you please just let me have{NL}a bite, a lick, a tiny crumb?{NL}  {SPECIAL_05_PAR_1}{BYTE_1D}{SPECIAL_06_PAR_1}OK!    {SPECIAL_05_PAR_1}{BYTE_1D}{SPECIAL_07_PAR_1}No! Gross!{END}"


text_1D05__089D78E0:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}Welcome. Goro.{NL}Oh, what a tiny Goron you are...{NL}Oh! What{SINGLE_QUOTE}s this!?{NL}You have another {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}?{NL}Will you let me taste this one also?{NL}  {SPECIAL_05_PAR_1}{BYTE_1D}{SPECIAL_06_PAR_1}OK!    {SPECIAL_05_PAR_1}{BYTE_1D}{SPECIAL_07_PAR_1}No! That{SINGLE_QUOTE}s sick!{END}"


text_1D06__089D7987:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}But, little one, if I eat it, you will no{NL}longer have a shield. Do you mind?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}No, it{SINGLE_QUOTE}s fine!    {SPECIAL_05_PAR_1}{BYTE_1D}{SPECIAL_07_PAR_1}Uh, just a little...{END}"


text_1D07__089D7A05:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}I see, goro. Then I will not taste your{NL}delicious shield.{END}"


text_1D08__089D7A42:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BA}Really, goro!? Thank you! GORO!{NL}{NL}I{SINGLE_QUOTE}ll dig right in!!{END}"


text_1D09__089D7A7A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}Nummnummnumm! Slurp, slurp!{NL}Oh, delicious!{NL}It has a deep, rich taste surpassing{NL}even the great praise I have heard!{END}"


text_1D0A__089D7AF1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}Nummnumm! Slurp, slurp! Oh, delicious!{NL}Oh, just a few more bites, please!!{END}"


text_1D0B__089D7B3F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}Nummnumm! Slurp, slurp! Oh, delicious!{NL}That was excellent!{NL}Thank you so much. Now, I finally know{NL}the legendary taste of a shield!{NL}And I will happily fulfill my promise!{NL}{NL}Let me just spit your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield {SPECIAL_02_PAR_1}{END}back{NL}out again!{END}"


text_1D0C__089D7C1E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}Goro goro...?!{NL}{NL}It-It seems your shield has changed{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}shape {SPECIAL_02_PAR_1}{END}a little as I was chewing on it...{NL}Oh, but it{SINGLE_QUOTE}s fine!{NL}{NL}It is still a shield after all, just a{NL}slightly differently shaped one!{NL}I think...{NL}Well, I have to go now! Good-bye, goro!{END}"

