
text_4500__089EF6FC:
	.string "{END}"


text_4501__089EF6FD:
	.string "Hi there, and welcome to the{NL}Happy Hearth! Need a rest, kid?{NL}Well, we can take care of that--and{NL}even throw in a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}present {SPECIAL_02_PAR_1}{END}to boot!{NL}{SPECIAL_07_PAR_1}E{SPECIAL_02_PAR_1}{END}{SPECIAL_05_PAR_1}{BYTE_FF}Forget it      {SPECIAL_05_PAR_1}{BYTE_FF}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupee room{NL}{SPECIAL_05_PAR_1}{BYTE_FF}{SPECIAL_06_PAR_1}{SPECIAL_02_PAR_1} Rupee room {SPECIAL_05_PAR_1}{BYTE_FF}{SPECIAL_06_PAR_1}{SPECIAL_03_PAR_2} Rupee room{END}"


text_4502__089EF787:
	.string "{SPECIAL_05_PAR_1}{BYTE_FF}Forget it      {SPECIAL_05_PAR_1}{BYTE_FF}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupee room{NL}{SPECIAL_05_PAR_1}{BYTE_FF}{SPECIAL_06_PAR_1}{SPECIAL_02_PAR_1} Rupee room {SPECIAL_05_PAR_1}{BYTE_FF}{SPECIAL_06_PAR_1}{SPECIAL_03_PAR_2} Rupee room{END}"


text_4503__089EF7C8:
	.string "...Right. {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees.{NL}The cheap room it is, then.{NL}{SPECIAL_07_PAR_1}E{SPECIAL_06_PAR_1}{END}Yessir!{NL}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees gets you a regular room!{NL}{SPECIAL_07_PAR_1}E{SPECIAL_06_PAR_1}{END}Well now! Come from a good family, do{NL}we? A luxury room for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees!{NL}{SPECIAL_07_PAR_1}E{SPECIAL_06_PAR_1}{END}All payment up front, please!{END}"


text_4504__089EF7FD:
	.string "Yessir!{NL}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees gets you a regular room!{NL}{SPECIAL_07_PAR_1}E{SPECIAL_06_PAR_1}{END}Well now! Come from a good family, do{NL}we? A luxury room for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees!{NL}{SPECIAL_07_PAR_1}E{SPECIAL_06_PAR_1}{END}All payment up front, please!{END}"


text_4505__089EF82C:
	.string "Well now! Come from a good family, do{NL}we? A luxury room for {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Rupees!{NL}{SPECIAL_07_PAR_1}E{SPECIAL_06_PAR_1}{END}All payment up front, please!{END}"


text_4506__089EF877:
	.string "All payment up front, please!{END}"


text_4507__089EF895:
	.string "What{SINGLE_QUOTE}s this?!{NL}Son, you{SINGLE_QUOTE}ve got no cash!{NL}Come back when you grow up{NL}and get a job!{NL}Now off with you! Shoo!{END}"


text_4508__089EF8FE:
	.string "Thanks!{NL}Enjoy your stay!{END}"


text_4509__089EF917:
	.string "Ho, now! You don{SINGLE_QUOTE}t want to stay?{NL}Well, come again!{END}"


text_450A__089EF94A:
	.string "That{SINGLE_QUOTE}s the exit!{NL}Enjoy your stay!{END}"


text_450B__089EF96C:
	.string "And how was your stay?{NL}Did you find your present?{NL}Please come again!{END}"


text_450C__089EF9B1:
	.string "It seems you really get what{NL}you pay for here...{END}"


text_450D__089EF9E2:
	.string "But I guess you don{SINGLE_QUOTE}t really know the{NL}difference until you try each room...{END}"


text_450E__089EFA2E:
	.string "Hey, what do you know about that{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END} stuff?{NL}People are saying it{SINGLE_QUOTE}s some kind of{NL}treasure that can grant you any wish.{NL}Anyway, now the king{SINGLE_QUOTE}s in a big huff{NL}trying to find it.{NL}It{SINGLE_QUOTE}s strange, though. He never struck{NL}me as the greedy type before.{NL}It{SINGLE_QUOTE}s almost like he{SINGLE_QUOTE}s a different{NL}person now...{END}"


text_450F__089EFB5C:
	.string "What{SINGLE_QUOTE}s with the king lately?{NL}He was never like that before...{END}"


text_4510__089EFB9A:
	.string "Yaaay! Yaaay!{END}"


text_4511__089EFBA8:
	.string "Waaait!{END}"


text_4512__089EFBB0:
	.string "Hey!!! Wait up!{END}"


text_4513__089EFBC0:
	.string "It{SINGLE_QUOTE}s so nice to be here at last!{NL}And such a big town it is!{END}"


text_4514__089EFBFC:
	.string "Staying in this inn forever{NL}would start to be a bother...{END}"


text_4515__089EFC36:
	.string "We need to find a nice, quiet place{NL}where we can settle down.{END}"


text_4516__089EFC74:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}is just terrible lately!{NL}Things are going crazy around here!{NL}Would you believe a guard came into my{NL}house the other day?{NL}It{SINGLE_QUOTE}s true! And get this! He demanded{NL}that I give him some kind of {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}force{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE}!{END}"


text_4517__089EFD49:
	.string "Normal people can{SINGLE_QUOTE}t enter the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Royal Valley{SPECIAL_02_PAR_1}{END}.{NL}There{SINGLE_QUOTE}s a cryptic forest that leads{NL}into it, and people get lost there.{NL}The secret to finding your way through{NL}is reading all the signs!{NL}You{SINGLE_QUOTE}ll never make it unless you read{NL}each one carefully.{END}"


text_4518__089EFE3B:
	.string "You want to go to the tomb of{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}King Gustaf of Hyrule{SPECIAL_02_PAR_1}{END}?{NL}Then you{SINGLE_QUOTE}d probably better talk{NL}to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Damp{BYTE_E9}{SPECIAL_02_PAR_1}{END}.{NL}He{SINGLE_QUOTE}s the gravedigger at the cemetery.{NL}Nobody knows the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Royal Crypt {SPECIAL_02_PAR_1}{END}better!{END}"


text_4519__089EFEF1:
	.string "Have you stayed in the best room yet?{NL}I{SINGLE_QUOTE}m trying to figure out where to stay.{END}"


text_451A__089EFF3F:
	.string "The source of water in Hyrule? You{NL}must mean the spring at {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Veil Falls{SPECIAL_02_PAR_1}{END}.{NL}That{SINGLE_QUOTE}s where all our water comes from.{END}"


text_451B__089EFFB1:
	.string "I can{SINGLE_QUOTE}t say this in front of the kids...{NL}I don{SINGLE_QUOTE}t want to alarm them, you know?{NL}But...{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle {SPECIAL_02_PAR_1}{END}has been looking{NL}pretty weird lately.{NL}I can{SINGLE_QUOTE}t say exactly what it is, though.{NL}It{SINGLE_QUOTE}s just...different. Strange.{END}"


text_451C__089F0086:
	.string "I saw it! I saw it with my own two eyes!{NL}{NL}There were monsters inside{NL}of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}!{NL}I{SINGLE_QUOTE}ve heard rumors that some people who{NL}went to the castle never came back!{END}"


text_451D__089F012C:
	.string "School let out early today!{NL}Lucky!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_451E__089F0151:
	.string "Hey! Wait up! Wait for me!{END}"


text_451F__089F016C:
	.string "I{SINGLE_QUOTE}ve got no choice.{NL}I guess I{SINGLE_QUOTE}ll take shelter here...{NL}I know I can hold my own, but those are{NL}some fierce monsters out there...{END}"


text_4520__089F01EC:
	.string "My mom{SINGLE_QUOTE}s a wife, not a wolf.{END}"


text_4521__089F0209:
	.string "My mom{SINGLE_QUOTE}s a wife, not a fife!{END}"


text_4522__089F0226:
	.string "I can{SINGLE_QUOTE}t believe she found a place!{NL}I am so jealous.{END}"


text_4523__089F025A:
	.string "Maybe I should go pay her{NL}a visit sometime.{END}"


text_4524__089F0286:
	.string "Things just aren{SINGLE_QUOTE}t the same around{NL}here now that it{SINGLE_QUOTE}s just the two of us.{END}"


text_4525__089F02D0:
	.string "I hate being here all alone!{NL}{NL}I wish I could find a nice place{NL}to live, like the others did...{END}"


text_4526__089F032F:
	.string "It{SINGLE_QUOTE}s no fun being here alone. Maybe{NL}I should look for a nice house, too.{END}"


text_4527__089F0378:
	.string "Being all alone is...well, lonely. I{SINGLE_QUOTE}m{NL}going to find myself a nice home, too.{END}"


text_4528__089F03C6:
	.string "{END}"


text_4529__089F03C7:
	.string "{END}"


text_452A__089F03C8:
	.string "{END}"


text_452B__089F03C9:
	.string "{END}"


text_452C__089F03CA:
	.string "{END}"


text_452D__089F03CB:
	.string "{END}"


text_452E__089F03CC:
	.string "{END}"


text_452F__089F03CD:
	.string "{END}"

