
text_0300__089B2F04:
	.string "{END}"


text_0301__089B2F05:
	.string "This is the Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}1.{NL}{NL}Would you like to read it?{NL}    {SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_09}Yes  {SPECIAL_05_PAR_1}{BYTE_FF}No{END}"


text_0302__089B2F58:
	.string "This is the Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}2.{NL}{NL}Would you like to read it?{NL}    {SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_0D}Yes  {SPECIAL_05_PAR_1}{BYTE_FF}No{END}"


text_0303__089B2FAB:
	.string "This is the Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}3.{NL}{NL}Would you like to read it?{NL}    {SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_11}Yes  {SPECIAL_05_PAR_1}{BYTE_FF}No{END}"


text_0304__089B2FFE:
	.string "This is the Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}4.{NL}{NL}Would you like to read it?{NL}    {SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_15}Yes  {SPECIAL_05_PAR_1}{BYTE_FF}No{END}"


text_0305__089B3051:
	.string "This is the Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}5.{NL}{NL}Would you like to read it?{NL}    {SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_19}Yes  {SPECIAL_05_PAR_1}{BYTE_FF}No{END}"


text_0306__089B30A4:
	.string "This is the Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}6.{NL}{NL}Would you like to read it?{NL}    {SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_1D}Yes  {SPECIAL_05_PAR_1}{BYTE_FF}No{END}"


text_0307__089B30F7:
	.string "This is the Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}7.{NL}{NL}Would you like to read it?{NL}    {SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}!Yes  {SPECIAL_05_PAR_1}{BYTE_FF}No{END}"


text_0308__089B314A:
	.string "This is the Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}8.{NL}{NL}Would you like to read it?{NL}    {SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}%Yes  {SPECIAL_05_PAR_1}{BYTE_FF}No{END}"


text_0309__089B319D:
	.string "Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}1{NL}    Some Walls Go Boom...{NL}It may look like a regular wall, but{NL}it may be something you can blow up.{NL}There{SINGLE_QUOTE}s actually an easy way to tell.{NL}And I{SINGLE_QUOTE}m here to teach you!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Build up the power in your sword and{NL}start stabbing the wall.{SPECIAL_02_PAR_1}{END}{NL}If you pay attention, you{SINGLE_QUOTE}ll find that{NL}some spots make a different sound!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{NL}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_030A__089B330C:
	.string "    Teach us, Teacher!{NL}Monsters got you?{NL}Don{SINGLE_QUOTE}t give up! {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Start mashing buttons!{SPECIAL_02_PAR_1}{END}{NL}You might be able to escape quickly!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_0B}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_030B__089B33A9:
	.string "    Swiftblade{SINGLE_QUOTE}s Gossip Column{NL}The Magical Boomerang...{NL}Somewhere in Hyrule, you can find an{NL}incredibly handy {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}boomerang{SPECIAL_02_PAR_1}{END}.{NL}It{SINGLE_QUOTE}s designed so you can change its{NL}direction after you throw it!{NL}Or so I{SINGLE_QUOTE}ve been told.{NL}But it{SINGLE_QUOTE}s just a rumor...{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{SPECIAL_0C_PAR_1}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_030C__089B34BC:
	.string "    Swiftblade, Signing Off!{NL}That{SINGLE_QUOTE}s it for our first issue!{NL}We plan to bring you helpful questing{NL}hints every week, rain or shine.{NL}Be sure to check with your local{NL}post office for future issues!{NL}See you in issue 2!{NL}Until next time, warriors!{END}"


text_030D__089B35AE:
	.string "Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}2{NL}    This Year{SINGLE_QUOTE}s Must-Have Item!{NL}Have you seen those sparks that move{NL}along walls?{NL}Your sword doesn{SINGLE_QUOTE}t work, so maybe{NL}you{SINGLE_QUOTE}ve just given up fighting them.{NL}But have you tried ALL your items?{NL}Like...what about your boomerang?{NL}Give that a shot! You might be{NL}surprised at the results!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_0E}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_030E__089B3702:
	.string "    Teach us, Teacher!{NL}Monster took your shield?{NL}Well, don{SINGLE_QUOTE}t get all down about it.{NL}All hope is not lost.{NL}Beat him up quickly, and you might{NL}just get it back!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{SPECIAL_0F_PAR_1}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_030F__089B37C6:
	.string "    Swiftblade{SINGLE_QUOTE}s Gossip Column{NL}The Mirror Shield...{NL}A beautiful, glimmering shield capable{NL}of reflecting monsters{SINGLE_QUOTE} shots.{NL}You can use it to turn their{NL}attacks back at them.{NL}Or so they say...{NL}But it{SINGLE_QUOTE}s just a rumor...{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_10}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0310__089B38C3:
	.string "    Swiftblade, Signing Off!{NL}Issue 2 is out the door!{NL}We{SINGLE_QUOTE}ve got our first reader letter!{NL}Let{SINGLE_QUOTE}s answer it now!{NL}{DOUBLE_QUOTE}Hey, Swiftblade, what{SINGLE_QUOTE}s your best{NL}feature?{DOUBLE_QUOTE}{NL}That would be my eyebrows! I spend{NL}a lot of time grooming these suckers!{NL}See you in issue 3!{NL}Until next time, warriors!{END}"


text_0311__089B39D6:
	.string "Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}3{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}{NL}    {SPECIAL_02_PAR_1}{END}Got a Bone to Pick?{NL}You{SINGLE_QUOTE}re sure to run into more than{NL}a few skeletons on your journey.{NL}That{SINGLE_QUOTE}s why this week{SINGLE_QUOTE}s newsletter is{NL}dedicated to all you bone-breakers!{NL}A good, solid whack to the head should{NL}do the trick. That{SINGLE_QUOTE}s their weak spot!{NL}Try smacking them with a beam{NL}from your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Cane of Pacci{SPECIAL_02_PAR_1}{END}.{NL}You should also try your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Gust Jar{SPECIAL_02_PAR_1}{END}.{NL}That head should just pop right off!{NL}They go all to pieces once they{NL}lose their head.{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_12}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0312__089B3BC1:
	.string "    Teach us, Teacher!{NL}Those darn Bob-ombs!{NL}If you hit them with your sword, they{SINGLE_QUOTE}ll{NL}run all over the place and explode!{NL}But don{SINGLE_QUOTE}t you worry. This newsletter{SINGLE_QUOTE}s{NL}here to teach you how to cope!{NL}Your best bet is arrows!{NL}One shot can take them down!{NL}You can fire from a safe distance,{NL}too! There{SINGLE_QUOTE}s also your Gust Jar...{NL}Draw them in and shoot them out, and{NL}they{SINGLE_QUOTE}ll even blow up whatever they hit!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_13}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0313__089B3D6E:
	.string "    Swiftblade{SINGLE_QUOTE}s Gossip Column{NL}Light Arrows are amazing...{NL}They go through grass!{NL}They fell a monster with one strike!{NL}They{SINGLE_QUOTE}re handy! They{SINGLE_QUOTE}re dandy!{NL}They{SINGLE_QUOTE}re a super-duper-ultra-item!{NL}Or so it seems...{NL}But it{SINGLE_QUOTE}s just a rumor...{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_14}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0314__089B3E75:
	.string "    Swiftblade, Signing Off!{NL}We{SINGLE_QUOTE}ve got more reader mail this week!{NL}{DOUBLE_QUOTE}Hey, Swiftblade! How many siblings{NL}do you have?{DOUBLE_QUOTE}{NL}There are nine of us, not counting{NL}the ghost of Swiftblade the First.{NL}I{SINGLE_QUOTE}m the oldest, but again, that{SINGLE_QUOTE}s if you{NL}don{SINGLE_QUOTE}t count Swiftblade the First!{NL}See you in issue 4!{NL}Until next time, warriors!!!!{END}"


text_0315__089B3FAD:
	.string "Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}4{NL}    Seek Out the Strong!{NL}Have you ever seen a golden monster?{NL}{NL}When you fuse Kinstone pieces, you{NL}might get the rare chance to meet one.{NL}They{SINGLE_QUOTE}re much stronger than the{NL}regular version of that monster.{NL}Of course, if you beat one of {SINGLE_QUOTE}em,{NL}you{SINGLE_QUOTE}ll get something REALLY good!{NL}If you see one, go fight it instantly!{NL}Just drop everything and go!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_16}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0316__089B413D:
	.string "    Teach us, Teacher!{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}{NL}{SPECIAL_02_PAR_1}{END}  Coping with a Thorny Situation{NL}Those thorny little thorn monsters!{NL}Your sword doesn{SINGLE_QUOTE}t hurt {SINGLE_QUOTE}em at all!{NL}But if you bump {SINGLE_QUOTE}em with your{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield {SPECIAL_02_PAR_1}{END}up, they{SINGLE_QUOTE}ll totally flip!{NL}There are other ways, though.{NL}Flip {SINGLE_QUOTE}em with a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bomb{SPECIAL_02_PAR_1}{END}!{NL}Or your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Cane of Pacci{SPECIAL_02_PAR_1}{END}!{NL}Or with a well-placed {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Down Thrust{SPECIAL_02_PAR_1}{END}!{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}How{SINGLE_QUOTE}s that for options? Your head must{NL}be swimming at the possibilities!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_17}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0317__089B42F0:
	.string "    Swiftblade{SINGLE_QUOTE}s Gossip Column{NL}Remote Bombs...{NL}Here{SINGLE_QUOTE}s a secret: you can blow them up{NL}whenever you want! How cool is that?!{NL}Or so it seems...{NL}But it{SINGLE_QUOTE}s just a rumor...{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_18}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0318__089B43BB:
	.string "    Swiftblade, Signing Off!{NL}I went to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Lon Lon Ranch {SPECIAL_02_PAR_1}{END}the other day.{NL}I saw the ghost of Swiftblade the First{NL}defeat a cow with his bare hands!{NL}It was kind of sad, really...{NL}{NL}See you in issue 5!{NL}Until next time, warriors!!!!{END}"


text_0319__089B449E:
	.string "Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}5{NL}    Fire Up That Chilly Chump!{NL}Have you seen a sorcerer who throws{NL}cold curses at you?{NL}Yeah, the one who keeps disappearing!{NL}That{SINGLE_QUOTE}s him!{NL}Well, next time he shows up, whack him{NL}with your lantern!{NL}Fire against ice!{NL}It{SINGLE_QUOTE}s the law of nature!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_1A}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_031A__089B45C9:
	.string "    Teach us, Teacher!{NL}Those pig-faced Moblins...{NL}You see them around the Minish Woods,{NL}right? They{SINGLE_QUOTE}re big and dumb?{NL}Well, they{SINGLE_QUOTE}re also rich!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Beat one up for some quick cash!{SPECIAL_02_PAR_1}{END}{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_1B}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_031B__089B46A1:
	.string "    Swiftblade{SINGLE_QUOTE}s Gossip Column{NL}A tidbit about amulets...{NL}I hear that there{SINGLE_QUOTE}s a mysterious amulet{NL}that raises your abilities if you use it!{NL}Well, that{SINGLE_QUOTE}s what I heard, anyway...{NL}But it{SINGLE_QUOTE}s just a rumor...{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_1C}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_031C__089B478F:
	.string "    Swiftblade, Signing Off!{NL}I went to Smith{SINGLE_QUOTE}s the other day.{NL}The old guy{SINGLE_QUOTE}s still looking pretty good.{NL}... ...{NL}But I AM a little concerned about the{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}guy in green tights {SPECIAL_02_PAR_1}{END}on the hill there...{NL}See you in issue 6!{NL}Until next time, warriors!!!!{END}"


text_031D__089B4883:
	.string "Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}6{NL}    Here{SINGLE_QUOTE}s What You Do!{NL}Have you seen a monster wrapped in{NL}bandages? It tries to grab you?{NL}Well, here{SINGLE_QUOTE}s a pro tip: {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bandages burn{SPECIAL_02_PAR_1}{END}{NL}easily, especially on a mummy!{NL}I don{SINGLE_QUOTE}t have to spell this out, do I?{NL}Yeah, you know what I{SINGLE_QUOTE}m about to say!{NL}That{SINGLE_QUOTE}s right, it{SINGLE_QUOTE}s time to light up{NL}their world! FWOOOSH!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_1E}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_031E__089B49EB:
	.string "    Teach us, Teacher!{NL}Those heavy-handed Floor Masters...{NL}And their irritating friends,{NL}the Wall Masters...{NL}They{SINGLE_QUOTE}re really annoying, but if you{NL}beat one, they say you{SINGLE_QUOTE}ll be rich!!{NL}But it{SINGLE_QUOTE}s just a rumor... Don{SINGLE_QUOTE}t complain{NL}to me if it turns out to be wrong.{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{BYTE_1F}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_031F__089B4B10:
	.string "    Swiftblade{SINGLE_QUOTE}s Gossip Column{NL}Rupee-stealing nasties...{NL}Those Rupee-camouflaged creeps have{NL}been ripping a lot of you off lately.{NL}I{SINGLE_QUOTE}ve heard that you greedy{NL}adventurers are getting soaked!{NL}In fact, I hear that the greedier{NL}you are, the more it takes!{NL}Or so it seems...{NL}But it{SINGLE_QUOTE}s just a rumor...{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2} Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0320__089B4C5C:
	.string "    Swiftblade, Signing Off!{NL}We{SINGLE_QUOTE}ve got reader mail again!{NL}{DOUBLE_QUOTE}Hey, Swiftblade, do you have{NL}a hobby?{DOUBLE_QUOTE}{NL}Training!{NL}{NL}See you in issue 7!{NL}Until next time, warriors!!!!{END}"


text_0321__089B4CFB:
	.string "Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}7{NL}    For Real Swordsmen Only{NL}You know the Roll Attack, right?{NL}Yeah, the one you do midroll!{NL}I bet Grayblade told you to attack{NL}just as you finish the roll, right?{NL}Well, actually, you can do it just as{NL}you start the roll, too!{NL}But the timing is very tricky!{NL}You can do it! Hone your skill!{NL}The journey of a thousand miles begins{NL}with a single step! Or...something!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{DOUBLE_QUOTE}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0322__089B4EA4:
	.string "    Teach us, Teacher!{NL}Camouflaged shell-shockers...{NL}These fiends festoon themselves with{NL}grass and rocks to deceive your eyes.{NL}But you can remove their camo without{NL}trying to pick them up, you know!{NL}Hit them with that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Cane of Pacci{SPECIAL_02_PAR_1}{END}!{NL}Suck them with the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Gust Jar{SPECIAL_02_PAR_1}{END}!{NL}How do you like that!?{NL}Now you{SINGLE_QUOTE}re a camo-buster!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}#Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0323__089B5009:
	.string "    Swiftblade{SINGLE_QUOTE}s Gossip Column{NL}Those short-fused Bob-ombs...{NL}I told you about them in issue 3, but{NL}here{SINGLE_QUOTE}s another thing...{NL}Apparently they drop {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}bombs {SPECIAL_02_PAR_1}{END}at a higher{NL}rate than other enemies!{NL}Or so it seems...{NL}But it{SINGLE_QUOTE}s just a rumor...{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}$Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0324__089B5118:
	.string "    Swiftblade, Signing Off!{NL}The next one is our last issue!{NL}After that, it{SINGLE_QUOTE}ll be time for me to put{NL}down my pen.{NL}As much as I like writing, I{SINGLE_QUOTE}m a{NL}teacher at heart.{NL}But I know you{SINGLE_QUOTE}ll miss me when I{SINGLE_QUOTE}m{NL}gone. I{SINGLE_QUOTE}m like a star! A superstar!{NL}Issue 8, the last one, is coming soon!{NL}Hope you{SINGLE_QUOTE}re looking forward to it!{NL}Until next time, warriors!!!!{END}"


text_0325__089B526C:
	.string "Swordsman Newsletter {SPECIAL_0F_PAR_1}{BYTE_10}8{NL}    The Way to the Sacred Blade{NL}Have you ever wished you could unleash{NL}your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Spin Attack {SPECIAL_02_PAR_1}{END}a little faster?{NL}Or perhaps split faster? Or maybe you{NL}wanted a longer {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Great Spin Attack{SPECIAL_02_PAR_1}{END}?{NL}It{SINGLE_QUOTE}s only natural to want these things.{NL}Every warrior wants to be his best!{NL}So now for some good news! I haven{SINGLE_QUOTE}t{NL}confirmed it, but there MAY be a way!{NL}All of these things could be yours if{NL}you only figure out how to do it!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}&Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0326__089B5443:
	.string "    Teach us, Teacher!{NL}The one-eyed statue Eyegore...{NL}You have to shoot him with an {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}arrow {SPECIAL_02_PAR_1}{END}to{NL}make him move...{NL}But if you beat him, he almost always{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}drops spare arrows {SPECIAL_02_PAR_1}{END}for you!{NL}So don{SINGLE_QUOTE}t you worry about running out of{NL}arrows once you{SINGLE_QUOTE}ve beaten him!{NL}Just fire away!{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}{SINGLE_QUOTE}Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0327__089B5577:
	.string "    Swiftblade{SINGLE_QUOTE}s Gossip Column{NL}Armos, fabled creations of the Minish.{NL}I hear that they {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}drop Kinstone pieces{SPECIAL_02_PAR_1}{END}{NL}when you beat them!{NL}Or so it seems...{NL}But it{SINGLE_QUOTE}s just a rumor...{NL}{SPECIAL_05_PAR_1}{SPECIAL_03_PAR_2}(Continue reading  {SPECIAL_05_PAR_1}{BYTE_FF}That{SINGLE_QUOTE}s enough{END}"


text_0328__089B564B:
	.string "    Swiftblade, Signing Off!{NL}That{SINGLE_QUOTE}s all the news for you!{NL}If you get lonely, just come over{NL}and spar for a while!{NL}And thanks for reading! I hope you{SINGLE_QUOTE}ve{NL}enjoyed it as much as I have.{NL}And now, let me sign off one final time{NL}with that oh-so-familiar farewell...{NL}Until next time, warriors!!!!{END}"

