
text_4E00__089F8504:
	.string "{END}"


text_4E01__089F8505:
	.string "Hey.{NL}What do you want?{NL}My sister{SINGLE_QUOTE}s not here.{NL}She{SINGLE_QUOTE}s at school.{END}"


text_4E02__089F8543:
	.string "You have a weird hat. Where can{NL}I get one of those?{END}"


text_4E03__089F8577:
	.string "Aaaarf!{END}"


text_4E04__089F857F:
	.string "My dog{SINGLE_QUOTE}s real smart.{NL}And a little spoiled, too.{END}"


text_4E05__089F85AF:
	.string "{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Julietta{SPECIAL_02_PAR_1}{END}, from next door, went{NL}back home...{NL}But I{SINGLE_QUOTE}ll see her tomorrow!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4E06__089F85FC:
	.string "My sister{SINGLE_QUOTE}s back now.{NL}I guess she{SINGLE_QUOTE}s supposed to stay in.{END}"


text_4E07__089F8635:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D1}Awooo! Hot! Awoo!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}The fireplace is too hot!{SPECIAL_02_PAR_1}{END}{NL}My master won{SINGLE_QUOTE}t come home, {SINGLE_QUOTE}cuz he{SINGLE_QUOTE}s{NL}head over heels for the girl next door.{NL}But when he puts the fire out, then{NL}sometimes mice come out...{NL}I hate mice, so either way,{NL}I{SINGLE_QUOTE}m never happy!{END}"


text_4E08__089F8721:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D1}It{SINGLE_QUOTE}s too hot! Arf...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}The fireplace is too hot...{SPECIAL_02_PAR_1}{END}{NL}Now there are even more people in here,{NL}and it{SINGLE_QUOTE}s getting too hot to bear!{NL}What will it take to cool this place{NL}down!? Pant, pant, pant!{END}"


text_4E09__089F87E1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D1}Thanks, arf!{NL}You put out the fire.{NL}But I{SINGLE_QUOTE}m still miffed at my master!{NL}{NL}I can{SINGLE_QUOTE}t believe how long he{SINGLE_QUOTE}s been{NL}hanging out with his girlfriend!{NL}Arf! Arf!{END}"


text_4E0A__089F8879:
	.string "Huh? A {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}book {SPECIAL_02_PAR_1}{END}from the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}library{SPECIAL_02_PAR_1}{END}?{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}A Hyrulean Bestiary{SPECIAL_02_PAR_1}{END}, is that the one?{NL}Yeah, I checked it out a while ago.{NL}You came all this way to get it?{NL}Wow! You{SINGLE_QUOTE}re one dedicated librarian!{NL}But... I don{SINGLE_QUOTE}t know how to tell you{NL}this, but it{SINGLE_QUOTE}s back at my house.{NL}Would you mind going there to get it?{NL}I just can{SINGLE_QUOTE}t leave right now, see...{END}"


text_4E0B__089F89C4:
	.string "They say the king{SINGLE_QUOTE}s been weird lately.{NL}{NL}But that doesn{SINGLE_QUOTE}t really have anything{NL}to do with our love...{END}"


text_4E0C__089F8A29:
	.string "{END}"


text_4E0D__089F8A2A:
	.string "{END}"


text_4E0E__089F8A2B:
	.string "I{SINGLE_QUOTE}m writing a letter right now, so I{NL}don{SINGLE_QUOTE}t have any time to play with you.{NL}Sorry.{END}"


text_4E0F__089F8A7D:
	.string "You returned my book?{NL}Thanks!{END}"


text_4E10__089F8A9B:
	.string "They say the king{SINGLE_QUOTE}s been weird lately.{NL}{NL}But that doesn{SINGLE_QUOTE}t really have anything{NL}to do with our love...{END}"


text_4E11__089F8B00:
	.string "You ought to be careful when you{SINGLE_QUOTE}re{NL}running around! You{SINGLE_QUOTE}re awfully tiny!{NL}And not all dogs and cats are nice,{NL}like me. Woof!{NL}Some of them might even take a swipe{NL}at you, arf! Rarf!{END}"


text_4E12__089F8BB4:
	.string "{END}"


text_4E13__089F8BB5:
	.string "MINKA{SPECIAL_0F_PAR_1}{BYTE_1F}019{END}"


text_4E14__089F8BC0:
	.string "MINKA{SPECIAL_0F_PAR_1}{BYTE_1F}020{END}"


text_4E15__089F8BCB:
	.string "Oh, hello.{NL}My brother{SINGLE_QUOTE}s at school.{END}"


text_4E16__089F8BEE:
	.string "I{SINGLE_QUOTE}m writing a letter right now, so I{NL}don{SINGLE_QUOTE}t have any time to play with you.{NL}Sorry.{END}"


text_4E17__089F8C40:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D2}Meowry-meowww!!!{END}"


text_4E18__089F8C54:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D2}Sssss!{END}"


text_4E19__089F8C5E:
	.string "My family is all very close. Same with{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Romio{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s family next door, too.{NL}Hee hee!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4E1A__089F8CB3:
	.string "My brother{SINGLE_QUOTE}s back. Now, he{SINGLE_QUOTE}s not{NL}allowed out anymore...{END}"


text_4E1B__089F8CEB:
	.string "Dear Mom,{NL}Gone to Julietta{SINGLE_QUOTE}s house. Back soon.{END}"


text_4E1C__089F8D1A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}It{SINGLE_QUOTE}s really dangerous up ahead! You{NL}can{SINGLE_QUOTE}t just charge through recklessly!{END}"


text_4E1D__089F8D67:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hey, I{SINGLE_QUOTE}ve heard about you... So you{SINGLE_QUOTE}re{NL}gonna go ahead, are you?{NL}Well, onward to glory then!{NL}Just don{SINGLE_QUOTE}t die out there, OK?{END}"


text_4E1E__089F8DE4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}You made it through that den of evil{NL}and came back alive?!{NL}Amazing! Whoo! Whoo!{END}"


text_4E1F__089F8E37:
	.string "I come from a faraway land. You{NL}can tell by my clothing, can{SINGLE_QUOTE}t you?{END}"


text_4E20__089F8E7B:
	.string "This place isn{SINGLE_QUOTE}t so bad once you get{NL}used to it. I like it here.{END}"


text_4E21__089F8EBC:
	.string "In this cool climate, my clothes are{NL}a little on the unprotective side.{END}"


text_4E22__089F8F04:
	.string "I{SINGLE_QUOTE}m thinking about calling my family{NL}over soon.{NL}Living with your feet on the ground{NL}is not so bad, I{SINGLE_QUOTE}ve decided.{END}"


text_4E23__089F8F75:
	.string "So you{SINGLE_QUOTE}ve been to my hometown?{NL}It{SINGLE_QUOTE}s great, isn{SINGLE_QUOTE}t it?{END}"


text_4E24__089F8FAA:
	.string "Monsters could attack at any time.{NL}Maybe I shouldn{SINGLE_QUOTE}t call my family over.{END}"


text_4E25__089F8FF4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}I really like this house. This is the{NL}best place in this whole human town!{NL}I want to stay here forever.{END}"


text_4E26__089F905F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}This place is getting a little run-down.{NL}I{SINGLE_QUOTE}m thinking about rebuilding the place.{END}"


text_4E27__089F90B4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Welcome!{NL}{NL}This is my new house! Ah... Don{SINGLE_QUOTE}t{NL}you just love that new-house smell?{NL}And I was JUST thinking about building{NL}a new house, so this is great!{END}"


text_4E28__089F914D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Imagine moving from a musty old{NL}mushroom to a fabulous house like this!{NL}It{SINGLE_QUOTE}s like a dream come true!{END}"


text_4E29__089F91B5:
	.string "{END}"


text_4E2A__089F91B6:
	.string "{END}"


text_4E2B__089F91B7:
	.string "Well, I suppose I{SINGLE_QUOTE}d better get dinner{NL}started! Hmm hm hmmm!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_4E2C__089F91F5:
	.string "Oooh, scary... Well, as long as nothing{NL}else happens...{END}"


text_4E2D__089F922D:
	.string "What{SINGLE_QUOTE}s a moss-ster?{END}"


text_4E2E__089F9241:
	.string "It{SINGLE_QUOTE}s so boring not being{NL}able to go outside.{END}"


text_4E2F__089F926E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}The boss might seem rough, but he{SINGLE_QUOTE}s{NL}a real softy at heart...{END}"


text_4E30__089F92AE:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}The boss is a real refined fella, right?{NL}Anybody what{SINGLE_QUOTE}s smart can see dat!{END}"


text_4E31__089F92FC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}I would like to apprentice to the boss,{NL}too, but he barely even notices me...{NL}It{SINGLE_QUOTE}s so sad.{END}"


text_4E32__089F935A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}They call him Punch Mutoh because he{SINGLE_QUOTE}s{NL}like a real punchy fella and all dat.{END}"


text_4E33__089F93AA:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}The boss is the number-one builder in{NL}town. You need a building, you see him.{END}"

