
text_4600__089F057C:
	.string "{END}"


text_4601__089F057D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}I am {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade{SPECIAL_02_PAR_1}{END}, finest swordsman{NL}in all of Hyrule!{NL}If you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}with me, I guarantee that{NL}you will increase your skill dramatically!{END}"


text_4602__089F060E:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_4603__089F064D:
	.string "We shall start with the most basic{NL}of all techniques!{NL}I shall teach you...the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Spin Attack{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}First!!{SPECIAL_02_PAR_1}{END}{NL}Press and hold your sword button...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Second!!{SPECIAL_02_PAR_1}{END}{NL}Build up enough power...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Third!!{SPECIAL_02_PAR_1}{END}{NL}Releeeease your destructive might!!{NL}That{SINGLE_QUOTE}s all, young swordsman!!{NL}{NL}Do you understand?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}F{SPECIAL_03_PAR_2}No{END}"


text_4604__089F0777:
	.string "Haha! Very good!{NL}You are a very quick student.{NL}But one must FEEL the technique,{NL}not just hear about it!{NL}That{SINGLE_QUOTE}s why I will now possess your body{NL}so as to demonstrate the technique!{NL}I call this the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Swiftblade Possession{NL}technique{SPECIAL_02_PAR_1}{END} of training!{NL}Watch this!!{NL}Urrngh!!{NL}Poe...Zeh...SHUN!!!{END}"


text_4605__089F0896:
	.string "Phew...{NL}Now! You must try it {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}yourself{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_07_PAR_1}F`{END}"


text_4606__089F08C5:
	.string "Yes!! Fine work! You{SINGLE_QUOTE}re a quick study.{NL}I will now give you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tiger Scroll{SPECIAL_02_PAR_1}{END}!{NL}If you ever forget this technique,{NL}you can review it with this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}scroll{SPECIAL_02_PAR_1}{END}!{NL}You may view it anytime from{NL}the Quest Status screen!{END}"


text_4607__089F0998:
	.string "There are no more techniques I can{NL}teach you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}with your current sword{SPECIAL_02_PAR_1}{END}!{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}Come again when you have{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}a new sword{SPECIAL_02_PAR_1}{END} in hand!{END}"


text_4608__089F0A18:
	.string "{END}"


text_4609__089F0A19:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}Mn! A new {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}! Fantastic! And you{NL}seem to have acquired new skills with it!{NL}Yes! I am ready to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}you again,{NL}young swordsman!{END}"


text_460A__089F0AA7:
	.string "So? Will you accept this new {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}training{SPECIAL_02_PAR_1}{END}?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_460B__089F0AE8:
	.string "I will now teach you a technique called{NL}the Rock Breaker, so pay attention!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}First!!{SPECIAL_02_PAR_1}{END}{NL}Swing your sword to break pots!{NL}Actually, that{SINGLE_QUOTE}s all there is, young{NL}swordsman!!{NL}Do you understand?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}F{BYTE_0B}No{END}"


text_460C__089F0BB4:
	.string "Yes! Haha! Good!{NL}{NL}If you had said you didn{SINGLE_QUOTE}t understand,{NL}I would have serious doubts about you!{NL}Yes, but one must feel the technique,{NL}not just hear about it!{NL}That{SINGLE_QUOTE}s why I will now possess your body{NL}so as to demonstrate the technique!{NL}That is the secret of the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Swiftblade{NL}Possession technique{SPECIAL_02_PAR_1}{END} of training!{NL}Watch this!!{NL}Gunnghh!!{NL}Poe...Zeh...SHUN!!!{END}"


text_460D__089F0D14:
	.string "Phew...{NL}Now! You must try it {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}yourself{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_07_PAR_1}Fa{END}"


text_460E__089F0D43:
	.string "Yes!! Fine work! Fantastic, even!{NL}I will now give you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tiger Scroll{SPECIAL_02_PAR_1}{END}!{NL}If you ever forget this technique,{NL}you can review it with this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}scroll{SPECIAL_02_PAR_1}{END}!{END}"


text_460F__089F0DDB:
	.string "Come again when you learn{NL}to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}run like the wind{SPECIAL_02_PAR_1}{END}!{END}"


text_4610__089F0E0F:
	.string "{END}"


text_4611__089F0E10:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}Ah! Yes! You have the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Pegasus Boots{SPECIAL_02_PAR_1}{END}!{NL}And you seem to have more skill, too!{NL}Yes! I am ready to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}you again!{END}"


text_4612__089F0E8A:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_4613__089F0EC9:
	.string "You will now learn a new technique,{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Dash Attack{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}First!!{SPECIAL_02_PAR_1}{END}{NL}Equip the Pegasus Boots!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Second!!{SPECIAL_02_PAR_1}{END}{NL}Equip your sword!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Third!!{SPECIAL_02_PAR_1}{END}{NL}Run like crazy!{NL}That{SINGLE_QUOTE}s all, young swordsman!!{NL}{NL}Do you understand?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}F{BYTE_13}No{END}"


text_4614__089F0FA4:
	.string "Yes! Yes!{NL}You are my finest student!{NL}Just equip your sword and the Pegasus{NL}Boots to any button you like!{NL}But one must feel the technique,{NL}not just hear about it!{NL}That{SINGLE_QUOTE}s why I will now possess your body{NL}so as to demonstrate the technique!{NL}This is the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Swiftblade Possession{NL}technique{SPECIAL_02_PAR_1}{END} of training!{NL}Watch this!!{NL}Urrngh!!{NL}Poe...Zeh...SHUN!!!{END}"


text_4615__089F10F9:
	.string "Phew...{NL}Now! You must try it {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}yourself{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_07_PAR_1}Fb{END}"


text_4616__089F1128:
	.string "Yes!! Fine work! You learn quickly!{NL}I will now give you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tiger Scroll{SPECIAL_02_PAR_1}{END}!{NL}If you ever forget this technique,{NL}you can learn again from this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}scroll{SPECIAL_02_PAR_1}{END}!{END}"


text_4617__089F11C4:
	.string "Come again when {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}you can jump farther{NL}{SPECIAL_02_PAR_1}{END}than any other!{END}"


text_4618__089F11FD:
	.string "{END}"


text_4619__089F11FE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}Aha! Yes! You have the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Roc{SINGLE_QUOTE}s Cape{SPECIAL_02_PAR_1}{END}!{NL}And you have acquired new skill!{NL}Yes! I am ready to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}you again!{END}"


text_461A__089F1271:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_461B__089F12B0:
	.string "Now I will teach you a new technique,{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Down Thrust{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}First!!{SPECIAL_02_PAR_1}{END}{NL}Equip the Roc{SINGLE_QUOTE}s Cape!!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Second!!{SPECIAL_02_PAR_1}{END}{NL}Equip the sword!!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Third!!{SPECIAL_02_PAR_1}{END}{NL}Jump!! Then...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Fourth!!{SPECIAL_02_PAR_1}{END}{NL}At your jump{SINGLE_QUOTE}s peak, swing the sword!{NL}That{SINGLE_QUOTE}s all, young swordsman!!{NL}{NL}Do you understand?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}F{BYTE_1B}No{END}"


text_461C__089F13BD:
	.string "Yes! You see it, do you not?!{NL}{NL}But one must feel the technique,{NL}not just hear about it!{NL}That{SINGLE_QUOTE}s why I will now possess your body{NL}so as to demonstrate the technique!{NL}Witness...the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Swiftblade Possession{NL}technique{SPECIAL_02_PAR_1}{END} of training!{NL}Urrngh!!{NL}{NL}Poe...Zeh...SHUN!!!{END}"


text_461D__089F14BE:
	.string "Phew...{NL}Now! You must try it {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}yourself{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_07_PAR_1}Fc{END}"


text_461E__089F14ED:
	.string "Yes!! Fine work! You know the way!{NL}I will now give you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tiger Scroll{SPECIAL_02_PAR_1}{END}!{NL}If you ever forget this technique,{NL}you can review it with this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}scroll{SPECIAL_02_PAR_1}{END}!{END}"


text_461F__089F1586:
	.string "Ha! There is nothing more I can teach{NL}you, young master!{NL}Now, you must train yourself!{END}"


text_4620__089F15DD:
	.string "{END}"


text_4621__089F15DE:
	.string "{END}"


text_4622__089F15DF:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}Believe not what others tell you! I am{NL}the true master swordsman of Hyrule!{NL}My name is {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Grayblade{SPECIAL_02_PAR_1}{END}, and if you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train{SPECIAL_02_PAR_1}{END}{NL}with me, you will learn much!{END}"


text_4623__089F167B:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_4624__089F16BA:
	.string "You will learn the amazing{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Roll Attack{SPECIAL_02_PAR_1}{END}!!{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}First!!{SPECIAL_02_PAR_1}{END}{NL}Roll with {SPECIAL_0C_PAR_1}{BYTE_08} and {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Second!!{SPECIAL_02_PAR_1}{END}{NL}As soon as you get up...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Third!!{SPECIAL_02_PAR_1}{END}{NL}Scream {DOUBLE_QUOTE}Hiyaa!{DOUBLE_QUOTE} and swing your sword!{NL}That{SINGLE_QUOTE}s all, young swordsman!!{NL}{NL}Do you understand?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}F$No{END}"


text_4625__089F17A6:
	.string "Hoho! Well answered!{NL}You have much promise!{NL}But one must feel the technique,{NL}not just hear about it!{NL}That{SINGLE_QUOTE}s why I will now possess your body{NL}so as to demonstrate the technique!{NL}This is the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Grayblade Possession{NL}technique{SPECIAL_02_PAR_1}{END} of training!{NL}Watch this!!{NL}Urrngh!!{NL}Poe...Zeh...SHUN!!!{END}"


text_4626__089F18BD:
	.string "Phew...{NL}Now! You must try it {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}yourself{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_07_PAR_1}Fd{END}"


text_4627__089F18EC:
	.string "Yes!! Fine work! You know the way!{NL}I will now give you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tiger Scroll{SPECIAL_02_PAR_1}{END}!{NL}If you ever forget this technique,{NL}you can review it with this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}scroll{SPECIAL_02_PAR_1}{END}!{END}"


text_4628__089F1985:
	.string "Now, there is nothing left for me{NL}to teach you.{NL}Your training must continue within{NL}the realm of your MIND...{NL}After all, the way of the sword requires{NL}much discipline!! Yes!{END}"


text_4629__089F1A32:
	.string "{END}"


text_462A__089F1A33:
	.string "{END}"


text_462B__089F1A34:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}You are in the presence of the true{NL}master swordsman of Hyrule,{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1} Grimblade{SPECIAL_02_PAR_1}{END}!{NL}If you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}with me, you will become{NL}a true master swordsman!{END}"


text_462C__089F1AC9:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_462D__089F1B08:
	.string "You will learn the meaning of power{NL}with this technique, the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Sword Beam{SPECIAL_02_PAR_1}{END}!{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}First!!{SPECIAL_02_PAR_1}{END}{NL}When your hearts are full...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Second!!{SPECIAL_02_PAR_1}{END}{NL}Swing your mighty sword!!!{NL}That{SINGLE_QUOTE}s...really all there is to it,{NL}young swordsman!!{NL}Do you understand?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}F-No{END}"


text_462E__089F1C01:
	.string "But this is only the beginning!{NL}Now comes the real thing!{NL}One must feel the technique,{NL}not just hear about it!{NL}That{SINGLE_QUOTE}s why I will now possess your body{NL}so as to demonstrate the technique!{NL}This is the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Grimblade Possession{NL}technique{SPECIAL_02_PAR_1}{END} of training!{NL}Watch this!!{NL}Urrngh!!{NL}Poe...Zeh...SHUN!!!{END}"


text_462F__089F1D22:
	.string "Phew...{NL}Now! You must try it {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}yourself{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_07_PAR_1}Fe{END}"


text_4630__089F1D51:
	.string "Yes!! Fine work! You know the way!{NL}I will now give you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tiger Scroll{SPECIAL_02_PAR_1}{END}!{NL}If you ever forget this technique,{NL}you can review it with this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}scroll{SPECIAL_02_PAR_1}{END}!{END}"


text_4631__089F1DEA:
	.string "Now there is nothing more that{NL}I can teach you!!{NL}Your training from now on is{NL}all in your mind!!{NL}The way of the sword is eternal! Yes!{END}"


text_4632__089F1E71:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}You have found the true master{NL}swordsman of Hyrule,{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1} Grimblade{SPECIAL_02_PAR_1}{END}!{NL}If you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}with me, I will teach you{NL}skills you{SINGLE_QUOTE}ve never imagined!{NL}But the room is dark, and I cannot see{NL}your face! We cannot train like this!!{END}"


text_4633__089F1F4E:
	.string "{END}"


text_4634__089F1F4F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}You have found the true master{NL}swordsman of Hyrule,{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1} Waveblade{SPECIAL_02_PAR_1}{END}!{NL}If you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}with me, I will teach you{NL}skills that will make you a master!{END}"


text_4635__089F1FE4:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_4636__089F2023:
	.string "Now you will learn a dangerous{NL}technique for desperate times!{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Peril Beam{SPECIAL_02_PAR_1}{END}!{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}First!!{SPECIAL_02_PAR_1}{END}{NL}You must have only one heart left...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Second!! {SPECIAL_02_PAR_1}{END}Use your last ounce of{NL}strength to swing your sword!{NL}That{SINGLE_QUOTE}s all, young swordsman!!{NL}{NL}Do you understand?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}F6No{END}"


text_4637__089F212B:
	.string "So...{NL}There is no turning back now...{NL}For one must feel the technique,{NL}not just hear about it!{NL}That{SINGLE_QUOTE}s why I will now possess your body{NL}so as to demonstrate the technique!{NL}This is the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Waveblade Possession{NL}technique{SPECIAL_02_PAR_1}{END} of training!{NL}Watch this!!{NL}Urrngh!!{NL}Poe...Zeh...SHUN!!!{END}"


text_4638__089F223C:
	.string "Phew...{NL}Now! You must try it {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}yourself{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_07_PAR_1}Ff{END}"


text_4639__089F226B:
	.string "Yes!! Fine work!{NL}You know the way!{NL}I will now give you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tiger Scroll{SPECIAL_02_PAR_1}{END}!{NL}If you ever forget this technique,{NL}you can review it with this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}scroll{SPECIAL_02_PAR_1}{END}!{END}"


text_463A__089F2304:
	.string "Now there is nothing more that{NL}I can teach you!!{NL}Your training from now on is{NL}all in your mind!!{NL}The way of the sword leads{NL}ever upward! Yes!{END}"


text_463B__089F2392:
	.string "You have found the true master{NL}swordsman of Hyrule,{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1} Waveblade{SPECIAL_02_PAR_1}{END}!{NL}If you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}with me, I will teach{NL}you things you{SINGLE_QUOTE}ve never seen!{NL}Hmn?{NL}{NL}It seems you are not ready{NL}to train here!{NL}Come back when you have{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}more than 10 hearts{SPECIAL_02_PAR_1}{END}!{END}"


text_463C__089F247B:
	.string "{END}"


text_463D__089F247C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}Though my body may perish, I am still{NL}the true master swordsman of Hyrule...{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade the First, Spirit of the{NL}Swordsman{SPECIAL_02_PAR_1}{END}!{NL}If you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}with me, I will teach you{NL}skills that are out of this world!{END}"


text_463E__089F254D:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_463F__089F258C:
	.string "This is a technique that only I have{NL}mastered...{NL}Only one who holds the sacred blade{NL}can perform...the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Great Spin Attack{SPECIAL_02_PAR_1}{END}!{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}First!!{SPECIAL_02_PAR_1}{END}{NL}Do a Spin Attack...{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Second!!{SPECIAL_02_PAR_1}{END}{NL}Press the button repeatedly!{NL}Repeatedly! Repeatedly, do you hear{NL}me? That{SINGLE_QUOTE}s all, young swordsman!!{NL}Do you understand?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Yes   {SPECIAL_05_PAR_1}F?No{END}"


text_4640__089F26BF:
	.string "Wohohoho!{NL}But it is not so easy!{NL}One must feel the technique,{NL}not just hear about it!{NL}That{SINGLE_QUOTE}s why I will now possess your body{NL}so as to demonstrate the technique!{NL}This is the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Spooky Possession{NL}technique{SPECIAL_02_PAR_1}{END} of training!{NL}Watch this!!{NL}Urrngh!!{NL}Poe...Zeh...SHUN!!!{END}"


text_4641__089F27C4:
	.string "Phew...{NL}Now! You must try it {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}yourself{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_07_PAR_1}Fg{END}"


text_4642__089F27F3:
	.string "Yes!! Fine work!{NL}You know the way!{NL}You have passed the test of{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade the First {SPECIAL_02_PAR_1}{END}with such ease!{NL}I will now give you this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Tiger Scroll{SPECIAL_02_PAR_1}{END}!{NL}{NL}If you ever forget this technique,{NL}you can review this {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}scroll{SPECIAL_02_PAR_1}{END}!{END}"


text_4643__089F28CA:
	.string "Now there is nothing more that{NL}I can teach you!!{NL}Your training from now on is{NL}all in your mind!!{NL}The way begins with the sword and ends{NL}with the sword! Yes!{END}"


text_4644__089F2967:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}Though my body may perish, I am still{NL}the true master swordsman of Hyrule...{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade the First, Spirit of the{NL}Swordsman{SPECIAL_02_PAR_1}{END}!{NL}If you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}with me, I will teach you{NL}skills that are out of this world!{NL}Hmn?{NL}{NL}It seems you are not yet ready{NL}to train with me!{NL}Come back when you have{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}all 7 Tiger Scrolls{SPECIAL_02_PAR_1}{END}!{END}"


text_4645__089F2AA0:
	.string "{END}"


text_4646__089F2AA1:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}Swordsmanship is spirit!{NL}{NL}I am the finest or maybe second-finest{NL}swordsman in all of Hyrule, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Scarblade{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Training {SPECIAL_02_PAR_1}{END}with me will forever{NL}transform your swordsmanship!{END}"


text_4647__089F2B50:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_4648__089F2B8F:
	.string "Yes!{NL}Then I will teach you how to more{NL}quickly unleash your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Spin Attack{SPECIAL_02_PAR_1}{END},{NL}which you have already learned!{NL}I take visualization {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}training {SPECIAL_02_PAR_1}{END}very{NL}seriously, I{SINGLE_QUOTE}ll have you know!{NL}Now, quietly close your eyes...{NL}{NL}Visualize {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}your sword moving at an{NL}unthinkable speed{SPECIAL_02_PAR_1}{END}...{NL}Wuoooooohhhh!!!!{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{NL}{SPECIAL_02_PAR_1}{END}SSSSSSPINNNNNNNNINNNNNNG...{END}"


text_4649__089F2CD0:
	.string "Mnuhhh...{NL}{NL}Now, you can perform your Spin Attack{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}much faster{SPECIAL_02_PAR_1}{END}, my student!{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}This is the heart of the sword!{NL}{NL}All begins with belief...{NL}Commit yourself to the blade!{END}"


text_464A__089F2D7B:
	.string "{END}"


text_464B__089F2D7C:
	.string "{END}"


text_464C__089F2D7D:
	.string "{END}"


text_464D__089F2D7E:
	.string "{END}"


text_464E__089F2D7F:
	.string "{END}"


text_464F__089F2D80:
	.string "{END}"


text_4650__089F2D81:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}The spirit and the sword are one!{NL}{NL}I am the nearly best swordsman{NL}in Hyrule, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Splitblade{SPECIAL_02_PAR_1}{END}!{NL}If you {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}with me, you will discover{NL}the secrets of your hidden power!{END}"


text_4651__089F2E2F:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_4652__089F2E6E:
	.string "Mnnh!{NL}{NL}Now I will teach you how to fill your{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Split Gauge{SPECIAL_02_PAR_1}{END} faster than ever!{NL}I take visualization {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}training {SPECIAL_02_PAR_1}{END}very{NL}seriously, I{SINGLE_QUOTE}ll have you know!{NL}Now, quietly close your eyes...{NL}{NL}Visualize {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}your body splitting even{NL}faster than ever before{SPECIAL_02_PAR_1}{END}...{NL}Wuoooooohhhh!!!!{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{NL}{SPECIAL_02_PAR_1}{END}Spuh--Liii--TING!{END}"


text_4653__089F2F8E:
	.string "Mnuhhh...{NL}{NL}Now you will {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fill your Split{NL}Gauge much faster{SPECIAL_02_PAR_1}{END}, my student!{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}This is the truth of the sword!{NL}{NL}And truth is almost the exact opposite{NL}of not-truth!{NL}Commit yourself to the blade!{END}"


text_4654__089F3051:
	.string "{END}"


text_4655__089F3052:
	.string "{END}"


text_4656__089F3053:
	.string "{END}"


text_4657__089F3054:
	.string "{END}"


text_4658__089F3055:
	.string "{END}"


text_4659__089F3056:
	.string "{END}"


text_465A__089F3057:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}Mastery of the sword is mastery{NL}of the soul!{NL}I am kinda like almost the best{NL}swordsman in Hyrule, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Greatblade{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Training {SPECIAL_02_PAR_1}{END}with me will totally change{NL}your sword skill forever and stuff!{END}"


text_465B__089F3119:
	.string "So? Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}train {SPECIAL_02_PAR_1}{END}here?{NL}  {SPECIAL_05_PAR_1}{BYTE_FF}Please {SPECIAL_05_PAR_1}F_No, thanks{END}"


text_465C__089F3158:
	.string "Yes!{NL}All right, I{SINGLE_QUOTE}ll teach you how to prolong{NL}the duration of the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Great Spin Attack{SPECIAL_02_PAR_1}{END},{NL}which you have already learned!{NL}I take visualization {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}training {SPECIAL_02_PAR_1}{END}very{NL}seriously, I{SINGLE_QUOTE}ll have you know!{NL}Now, quietly close your eyes...{NL}{NL}Visualize {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}your sword continuing to move{NL}longer than ever possible{SPECIAL_02_PAR_1}{END}...{NL}Wuoooooohhhh!!!!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}SSSSSSPINNNNNNNNINNNNNNG...{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}SSSSSSPINNNNNNNNINNNNNNG...{NL}SSSSSSPINNNNNNNNINNNNNNG...{NL}SSSSSSPINNNNNNNNINNNNNNG...{NL}SSSSSSPINNNNNNNNINNNNNNG...{NL}SSSSSSPINNNNNNNNINNNNNNG...{NL}SSSSSSPINNNNNNNNINNNNNNG...{NL}SSSSSSPINNNNNNNNINNNNNNG!!!{END}"


text_465D__089F337B:
	.string "Mnuhhh...{NL}{NL}Now your Great Spin Attack will last{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}longer than before{SPECIAL_02_PAR_1}{END}, my student!{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}{NL}{SPECIAL_02_PAR_1}{END}This is the truth of the sword!{NL}{NL}When you doubt another, you bring{NL}clouds into the mind{SINGLE_QUOTE}s skies!{NL}Commit yourself to the blade and stuff!{END}"


text_465E__089F345C:
	.string "Mastery of the sword is mastery{NL}of the soul!{NL}I am kinda like almost the best{NL}swordsman in Hyrule, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Greatblade{SPECIAL_02_PAR_1}{END}!{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Training {SPECIAL_02_PAR_1}{END}with me will totally change{NL}your sword skill forever and stuff!{NL}Hmn?{NL}{NL}Dude... I don{SINGLE_QUOTE}t think you{SINGLE_QUOTE}re even{NL}ready to train here!{NL}Come back when you have learned the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}highest technique{SPECIAL_02_PAR_1}{END} of the sword!{END}"


text_465F__089F35A0:
	.string "Is that so? Then you go now! Shoo!{END}"


text_4660__089F35C3:
	.string "Press and hold your sword button.{NL}Build up enough power.{NL}Then, release your destructive might!!{NL}That{SINGLE_QUOTE}s all there is to it!{END}"


text_4661__089F363E:
	.string "Break the pots with your sword!{NL}That{SINGLE_QUOTE}s all!{END}"


text_4662__089F366A:
	.string "Equip the Pegasus Boots and your{NL}sword, and then run like crazy!!{END}"


text_4663__089F36AC:
	.string "Equip the Roc{SINGLE_QUOTE}s Cape and the sword!!{NL}Jump!!{NL}When you reach your jump{SINGLE_QUOTE}s peak,{NL}swing the sword! That{SINGLE_QUOTE}s all!{END}"


text_4664__089F3716:
	.string "Roll with {SPECIAL_0C_PAR_1}{BYTE_08} and {SPECIAL_0C_PAR_1}{SPECIAL_03_PAR_2}, and then swing{NL}your sword as you start to get up!{END}"


text_4665__089F375D:
	.string "When your hearts are full...swing your{NL}sword with all your might!{END}"


text_4666__089F379F:
	.string "When you have only one heart left...{NL}{NL}Swing the sword with the last{NL}of your waning strength!{END}"


text_4667__089F37FC:
	.string "Perform a Spin Attack...and hit the{NL}button! Again! Again! Again! Again!{END}"

