
text_3400__089E2CF0:
	.string "{END}"


text_3401__089E2CF1:
	.string "Just because you have a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword {SPECIAL_02_PAR_1}{END}and{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield {SPECIAL_02_PAR_1}{END}doesn{SINGLE_QUOTE}t mean you{SINGLE_QUOTE}ll be safe!{NL}I can{SINGLE_QUOTE}t let you go out there alone! Not{NL}until you know some {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}sword techniques{SPECIAL_02_PAR_1}{END}.{END}"


text_3402__089E2D91:
	.string "Ho ho!{NL}So, you{SINGLE_QUOTE}ve learned the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Spin Attack{SPECIAL_02_PAR_1}{END}?{NL}It{SINGLE_QUOTE}s still dangerous, but...maybe{NL}you can handle it.{NL}Well, let{SINGLE_QUOTE}s see how you do.{NL}Show me that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Spin Attack{SPECIAL_02_PAR_1}{END}!{END}"


text_3403__089E2E2F:
	.string "Now that was a real{NL}centennial celebration!{NL}That festival was the best ever!{END}"


text_3404__089E2E7C:
	.string "I{SINGLE_QUOTE}m so lucky! That wasn{SINGLE_QUOTE}t just any old{NL}festival. It was a centennial festival!{NL}It falls EXACTLY on the 100-year mark!{NL}{NL}There won{SINGLE_QUOTE}t be another one until I{SINGLE_QUOTE}m...{NL}Let{SINGLE_QUOTE}s see here... Yow! 118 years old!?{NL}Jeez, am I even gonna be around to{NL}see the next centennial festival?{NL}Ah, sure. Why not? It{SINGLE_QUOTE}ll give me{NL}something to look forward to!{END}"


text_3405__089E2FC6:
	.string "The town is quiet enough, but past the{NL}gates, there are monsters everywhere!{NL}You should visit {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Stockwell{SINGLE_QUOTE}s shop {SPECIAL_02_PAR_1}{END}and{NL}get outfitted before you go out there.{END}"


text_3406__089E3064:
	.string "Lately, the woods have been filled{NL}with nasty monsters.{NL}Ever since the chest was opened, it{SINGLE_QUOTE}s{NL}been all topsy-turvy around here.{END}"


text_3407__089E30E4:
	.string "Meooow...{END}"


text_3408__089E30EE:
	.string "Rowrrr!{END}"


text_3409__089E30F6:
	.string "{END}"


text_340A__089E30F7:
	.string "Yeah!{NL}That{SINGLE_QUOTE}s the one!{NL}But there are monsters out there, kid!{NL}You just make sure you{SINGLE_QUOTE}re careful.{END}"


text_340B__089E3157:
	.string "There are monsters out there, kid!{NL}You just make sure you{SINGLE_QUOTE}re careful.{END}"


text_340C__089E319D:
	.string "{END}"


text_340D__089E319E:
	.string "{END}"


text_340E__089E319F:
	.string "{END}"


text_340F__089E31A0:
	.string "{END}"


text_3410__089E31A1:
	.string "{END}"


text_3411__089E31A2:
	.string "{END}"


text_3412__089E31A3:
	.string "{END}"


text_3413__089E31A4:
	.string "{END}"


text_3414__089E31A5:
	.string "{END}"


text_3415__089E31A6:
	.string "{END}"


text_3416__089E31A7:
	.string "Buggedy-buggedy-BOO!{NL}{NL}Did I scare ya?{END}"


text_3417__089E31CD:
	.string "Kids are just naturally scared of{NL}ghosts, you know what I mean?{END}"


text_3418__089E320D:
	.string "Arf! Arf arf!{END}"


text_3419__089E321B:
	.string "It{SINGLE_QUOTE}s a lot easier for me not being{NL}anyone{SINGLE_QUOTE}s pet.{NL}I don{SINGLE_QUOTE}t have to wait around for meal-{NL}times. I just eat whatever I can find!{END}"


text_341A__089E3299:
	.string "Did you see the tournament!?{NL}It was incredible!{NL}I was out of my seat and cheering{NL}before I even knew it!{END}"


text_341B__089E3302:
	.string "I can{SINGLE_QUOTE}t wait for next year{SINGLE_QUOTE}s{NL}tournament! When{SINGLE_QUOTE}s it supposed to be?{END}"


text_341C__089E3345:
	.string "Yow! That sword-fighting tournament{NL}was so exciting!{NL}Oh, if only my husband were talented{NL}enough to compete...{END}"


text_341D__089E33B4:
	.string "Even I{SINGLE_QUOTE}m a better swordfighter than{NL}my husband is.{NL}He can{SINGLE_QUOTE}t even handle a butter knife!{END}"


text_341E__089E340C:
	.string "I really wanna play a game, but this{NL}place isn{SINGLE_QUOTE}t open yet.{NL}I guess I just got here too early...{END}"


text_341F__089E346C:
	.string "This stall is kind of dirty. I guess that{NL}guy won{SINGLE_QUOTE}t be setting up here today...{END}"


text_3420__089E34BC:
	.string "Hmm... Nothing but fruits and veggies.{NL}What should I cook tonight?{END}"


text_3421__089E34FF:
	.string "Hey, hey! Fresh fruit!{NL}Get your fresh fruit here!{END}"


text_3422__089E3531:
	.string "Come on up and take a look, folks!{NL}{NL}One whiff of these sweet and delicious{NL}fruits, and you{SINGLE_QUOTE}ll be sold! Come on up!{END}"


text_3423__089E35A4:
	.string "Howdy, howdy! Come get your fresh{NL}veggies, grown by Eenie and Meenie!{NL}They{SINGLE_QUOTE}re fresher than fresh, folks!{NL}And they{SINGLE_QUOTE}re good for you, too!{END}"


text_3424__089E362C:
	.string "Don{SINGLE_QUOTE}t forget to eat your veggies!{NL}Everybody needs a balanced diet!{END}"


text_3425__089E366F:
	.string "I just loooove shopping!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}{NL}Oh, and I mustn{SINGLE_QUOTE}t forget to buy some of{NL}that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}surprise-filled bread {SPECIAL_02_PAR_1}{END}from Pita!{END}"


text_3426__089E36DD:
	.string "Oh! I just remembered!{NL}{NL}I need to pick up a bottle of{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon Milk{SPECIAL_02_PAR_1}{END} on the way home!{END}"


text_3427__089E3735:
	.string "{END}"


text_3428__089E3736:
	.string "{END}"


text_3429__089E3737:
	.string "Hey, you wanna know what I heard? I{NL}heard that only kids can see the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}!{END}"


text_342A__089E3788:
	.string "I wonder if we can see the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}, too.{END}"


text_342B__089E37B4:
	.string "Hey, I wanna see the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}, too!{NL}Can I? Can I? Huh? Can I?{END}"


text_342C__089E37F4:
	.string "Hey, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}! Ho, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}!{NL}Come out and play with us!{END}"


text_342D__089E3830:
	.string "{END}"


text_342E__089E3831:
	.string "I think the mayor is doing a fine job,{NL}no matter what people say!{END}"


text_342F__089E3873:
	.string "I won{SINGLE_QUOTE}t say anything, even if you{NL}dig a huge hole in my garden.{END}"


text_3430__089E38B3:
	.string "Aw... It looks like they{SINGLE_QUOTE}re having fun in{NL}there. I wish I could play with them...{END}"


text_3431__089E3905:
	.string "I can{SINGLE_QUOTE}t wait until I{SINGLE_QUOTE}m big enough to go{NL}to school and have fun ALL the time!{END}"


text_3432__089E3952:
	.string "Sorry, but I can{SINGLE_QUOTE}t let you pass.{NL}There are monsters out there!{END}"


text_3433__089E3991:
	.string "We{SINGLE_QUOTE}re working here. Sorry, but we{NL}can{SINGLE_QUOTE}t let you pass.{NL}Sorry.{END}"


text_3434__089E39CE:
	.string "Well, if it isn{SINGLE_QUOTE}t {SPECIAL_06_PAR_1}{END}!{NL}It IS good to see you again.{NL}School is in session right now,{NL}so I{SINGLE_QUOTE}m afraid I can{SINGLE_QUOTE}t let you in.{END}"


text_3435__089E3A43:
	.string "We{SINGLE_QUOTE}re in the middle of a very important{NL}class right now, so you may not enter.{END}"


text_3436__089E3A92:
	.string "There{SINGLE_QUOTE}s an old legend that something{NL}big will happen when Hyrule{SINGLE_QUOTE}s bell rings.{END}"


text_3437__089E3AE1:
	.string "Everyone is afraid of what it might{NL}mean to ring the bell, so they avoid it.{END}"


text_3438__089E3B2E:
	.string "I came to check out a book,{NL}but they{SINGLE_QUOTE}re not open yet.{NL}Hahhh... Well, age brings patience,{NL}sonny. I can wait.{END}"


text_3439__089E3B9B:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade School{SPECIAL_02_PAR_1}{END} in the south end{NL}of town is really awesome.{NL}The teacher, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade{SPECIAL_02_PAR_1}{END}, has an{NL}amazingly direct teaching style.{NL}I wish I could train there...{END}"


text_343A__089E3C44:
	.string "The {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade School{SPECIAL_02_PAR_1}{END} in the south end{NL}of town is really awesome.{NL}The teacher, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Swiftblade{SPECIAL_02_PAR_1}{END}, has an{NL}amazingly direct teaching style.{NL}I wish I could train there...{END}"


text_343B__089E3CED:
	.string "Rrrrr...ARF ARF!{END}"


text_343C__089E3CFE:
	.string "Arf arf arf!{END}"

