
text_0900__089BA7F8:
	.string "Caption{END}"


text_0901__089BA800:
	.string "A young boy who lives in Hyrule. He is{NL}close friends with Princess Zelda.{END}"


text_0902__089BA84A:
	.string "A young boy on a quest with Ezlo to{NL}restore the Four Sword.{NL}With the sword{SINGLE_QUOTE}s power, he hopes to{NL}remove the curse on Princess Zelda.{END}"


text_0903__089BA8CE:
	.string "A bright and cheery princess from{NL}Hyrule{SINGLE_QUOTE}s royal family.{NL}She loves to sneak out of the castle{NL}to visit her good friend, {SPECIAL_06_PAR_1}{END}.{END}"


text_0904__089BA94A:
	.string "A strange creature that looks at first{NL}like a cap. He speaks roughly and{NL}treats {SPECIAL_06_PAR_1}{END} like a child, but he{NL}actually really likes {SPECIAL_06_PAR_1}{END}.{END}"


text_0905__089BA9CC:
	.string "When the young Minish donned Ezlo{SINGLE_QUOTE}s{NL}magic cap, he took this evil form. Now,{NL}he searches for the light force in his{NL}quest to become all-powerful.{END}"


text_0906__089BAA5D:
	.string "The king of Hyrule. Reported to have{NL}been a fine swordsman, he appeared in{NL}the Picori Festival tournament as a{NL}youth and fought to a draw with Smith.{END}"


text_0907__089BAAF3:
	.string "The supporting pillar of Hyrule. He{NL}is also in charge of Princess Zelda{SINGLE_QUOTE}s{NL}education, so when she goes missing,{NL}he gets frustrated.{END}"


text_0908__089BAB76:
	.string "The finest swordsmith in Hyrule. As a{NL}young man, he was a great swordsman.{NL}He and King Daltus are friends and{NL}enjoyed a pleasant rivalry as youths.{END}"


text_0909__089BAC0A:
	.string "The mayor of the town of Hyrule. He{SINGLE_QUOTE}s a{NL}big collector of odd masks. He{SINGLE_QUOTE}s built a{NL}shelter into his garden just in case{NL}monsters ever attack Hyrule.{END}"


text_090A__089BAC9D:
	.string "Second in command at Hyrule{SINGLE_QUOTE}s post{NL}office. She{SINGLE_QUOTE}s mellow and laid-back,{NL}entirely unlike the high-strung and{NL}easily excitable Stamp.{END}"


text_090B__089BAD20:
	.string "A busy, hardworking postal employee,{NL}although he can be a touch edgy.{NL}The stamp he uses is his own personal{NL}one, so please don{SINGLE_QUOTE}t borrow it. Thanks.{END}"


text_090C__089BADB4:
	.string "The proprietor of {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Rem{SINGLE_QUOTE}s Shoe Store{SPECIAL_02_PAR_1}{END}.{NL}Using his {DOUBLE_QUOTE}secret technique,{DOUBLE_QUOTE} he makes{NL}shoes in his sleep. Princess Zelda is{NL}his single biggest source of income.{END}"


text_090D__089BAE4E:
	.string "A gruff-talking academic type who is{NL}obsessed with studying the Picori.{NL}He doesn{SINGLE_QUOTE}t seem to be aware that they{NL}are actually living in his own house.{END}"


text_090E__089BAEE2:
	.string "A sculptor of finely crafted {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}figurines{SPECIAL_02_PAR_1}{END}.{NL}Many consider him the best sculptor{NL}in all of Hyrule. He enjoys collecting{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Mysterious Shells{SPECIAL_02_PAR_1}{END}.{END}"


text_090F__089BAF70:
	.string "Owner of the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Chest Mini-Game Shop{SPECIAL_02_PAR_1}{END}.{NL}Carlov{SINGLE_QUOTE}s younger brother. He detests{NL}gambling, but he has made the biggest{NL}gamble of all: entrepreneurship.{END}"


text_0910__089BB003:
	.string "The handy neighborhood gear seller,{NL}also called {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Stockwell the Well-Stocked{SPECIAL_02_PAR_1}{END}.{NL}He complains that he{SINGLE_QUOTE}s been too busy{NL}lately to see his dog, Fifi.{END}"


text_0911__089BB095:
	.string "His mysterious {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}dungeon-simulation{NL}game{SPECIAL_02_PAR_1}{END} is very popular in Hyrule. It gives{NL}players the illusion of fighting real{NL}monsters in real dungeons.{END}"


text_0912__089BB125:
	.string "He wants to rent out his house in town,{NL}but he{SINGLE_QUOTE}s too overbearing to attract{NL}a tenant. He doesn{SINGLE_QUOTE}t even seem to{NL}realize what the problem is...{END}"


text_0913__089BB1B2:
	.string "This young woman tends to her cuccos{NL}in Hyrule Town.{NL}If you help her gather her loose{NL}cuccos, she{SINGLE_QUOTE}ll give you a reward.{END}"


text_0914__089BB22A:
	.string "Hyrule{SINGLE_QUOTE}s vegetable vendor. He sells fine{NL}produce. He also argues constantly{NL}with the fruit vendor, Pina, over{NL}the health benefits of vegetables.{END}"


text_0915__089BB2BB:
	.string "Hyrule{SINGLE_QUOTE}s fruit vendor. She hates{NL}vegetables, so she won{SINGLE_QUOTE}t even sell{NL}tomatoes, even though they{NL}technically ARE fruits. Freak.{END}"


text_0916__089BB339:
	.string "Though he is an adult, he is very good{NL}at finding Picolyte made by the Minish.{NL}And he is very, VERY convincing about{NL}their healthful properties.{END}"


text_0917__089BB3CA:
	.string "A very serious mail deliveryman.{NL}He continues to make every delivery{NL}right on time every day.{END}"


text_0918__089BB428:
	.string "A hermit who lives on Mount Crenel.{NL}He has lots of Kinstone pieces.{NL}He brags that he won the festival {NL}tournament when he was younger.{END}"


text_0919__089BB4AF:
	.string "A weird old lady living in Percy{SINGLE_QUOTE}s{NL}house without his permission.{NL}She doesn{SINGLE_QUOTE}t want you to turn on the{NL}lights. She might actually be a...{END}"


text_091A__089BB537:
	.string "The gravedigger at the cemetery.{NL}They say he has the power to speak{NL}with the dead. He fuses the Kinstones{NL}he digs up with the local ghosts.{END}"


text_091B__089BB5C3:
	.string "The spirit of an ancient king of Hyrule{NL}who wishes to secure peace in his land{NL}from beyond the grave. He was very{NL}fond of the people of the Wind Tribe.{END}"


text_091C__089BB65B:
	.string "A wizard who lives in the Minish Woods.{NL}She sells magic items with odd powers.{NL}She{SINGLE_QUOTE}s looking for an apprentice to whom{NL}she can teach her mystic spells.{END}"


text_091D__089BB6F3:
	.string "The Great Butterfly Fairy of Minish{NL}Woods. She provides you with a{NL}larger wallet, allowing you to carry{NL}more Rupees with you.{END}"


text_091E__089BB771:
	.string "The Great Mayfly Fairy of Mount{NL}Crenel. She provides you with a larger{NL}bomb bag, allowing you to carry more{NL}bombs with you.{END}"


text_091F__089BB7ED:
	.string "The Great Dragonfly Fairy of Royal{NL}Valley. She gives you a larger{NL}quiver, allowing you to carry{NL}more arrows with you.{END}"


text_0920__089BB863:
	.string "A poet who lives in Western Wood.{NL}He comes home from a long journey to{NL}find his house occupied by an unwanted{NL}guest. Poor guy...{END}"


text_0921__089BB8E4:
	.string "She{SINGLE_QUOTE}s looking for a house in Hyrule{NL}to move into. She is descended from{NL}a line of oracles in the land of{NL}Labrynna.{END}"


text_0922__089BB957:
	.string "She{SINGLE_QUOTE}s looking for a house in Hyrule to{NL}move into. She{SINGLE_QUOTE}s a very helpful person,{NL}but people take advantage of her kind{NL}nature. This really bothers her.{END}"


text_0923__089BB9ED:
	.string "She{SINGLE_QUOTE}s looking for a house in Hyrule to{NL}move into. She is a famous dancer from{NL}the land of Holodrum.{END}"


text_0924__089BBA51:
	.string "A rare butterfly said to bring{NL}happiness to those who catch it.{NL}If you see one on your journeys,{NL}try to grab it!{END}"


text_0925__089BBAC2:
	.string "A strange Ghini who wants to fuse{NL}Kinstone pieces, which is somewhat{NL}peculiar for a monster. She has a lot{NL}of pieces, so keep on fusing!{END}"


text_0926__089BBB4B:
	.string "A Minish living in Minish Village. He{NL}speaks some human languages. He sees{NL}that {SPECIAL_06_PAR_1}{END} is human with one look.{NL}He{SINGLE_QUOTE}s a bit of a human enthusiast.{END}"


text_0927__089BBBD8:
	.string "The elder of the Forest Minish. He has{NL}lived among humans for a long time. He{NL}knows where the four elements are. He{NL}has a twin brother in Hyrule{SINGLE_QUOTE}s library.{END}"


text_0928__089BBC74:
	.string "Not visible to the eyes of adults, they{NL}delight in making humans happy by{NL}hiding helpful items and Rupees under{NL}grass and rocks all over the world.{END}"


text_0929__089BBD08:
	.string "This Town Minish elder is Gentari{SINGLE_QUOTE}s{NL}twin brother. Those large wings that he{NL}is so proud of are trophies from a duel{NL}with a cucco as a young Minish.{END}"


text_092A__089BBD9C:
	.string "These Minish like humans so much that{NL}they moved from Minish Village into{NL}Hyrule itself! They try to make humans{NL}happy, but it sometimes backfires.{END}"


text_092B__089BBE30:
	.string "He lives with his seven apprentices in{NL}Mount Crenel, which contains all the{NL}mineral riches they will ever need.{NL}He seems gruff, but he{SINGLE_QUOTE}s trustworthy.{END}"


text_092C__089BBEC6:
	.string "These seven students followed Melari{NL}from Minish Village to Mount Crenel.{NL}Their song is actually a sign that they{NL}are full-fledged Mountain Minish now.{END}"


text_092D__089BBF5E:
	.string "These rock- and iron-eaters once{NL}lived on Mount Crenel in Western{NL}Hyrule. Now their numbers are few, and{NL}they live quietly in a cave.{END}"


text_092E__089BBFE4:
	.string "Before he became a sorcerer, he was{NL}a simple Minish. He had always been{NL}entranced by the evil that lives in{NL}the hearts of men...{END}"


text_092F__089BC065:
	.string "These vassals serve the king of{NL}Hyrule. They are loyal and diligent.{NL}Like the king himself, they are{NL}courteous yet frank.{END}"


text_0930__089BC0DF:
	.string "The Royal Hyrule Library. Although{NL}the library is well loved, many forget{NL}to return their books, causing no end{NL}of trouble for the librarians.{END}"


text_0931__089BC16E:
	.string "All of these self-trained swordsmen{NL}have won the fighting tournament at{NL}the Picori Festival before. They see{NL}great potential in {SPECIAL_06_PAR_1}{END}.{END}"


text_0932__089BC1F2:
	.string "This couple bakes bread in Hyrule.{NL}Their tasty pastries hold a secret...{NL}If you{SINGLE_QUOTE}re extra lucky, there{SINGLE_QUOTE}ll{NL}be a helpful item hidden inside!{END}"


text_0933__089BC27C:
	.string "This is where all the children of Hyrule{NL}learn. {SPECIAL_06_PAR_1}{END} and Princess Zelda{NL}studied here, too. The two teachers{NL}are twins named Tina and Dina.{END}"


text_0934__089BC305:
	.string "This is the best place in town to relax.{NL}You can also pick up some good tips,{NL}from the latest gossip to observations{NL}about the world.{END}"


text_0935__089BC38B:
	.string "This generous inn gives a gift to{NL}every guest who stays the night.{NL}Guests can unwind in the lobby on{NL}the second floor.{END}"


text_0936__089BC402:
	.string "Zill{SINGLE_QUOTE}s the one with the drippy nose. He{NL}likes to wander around town with his{NL}friends. He knows a lot about Hyrule,{NL}and he might even give you some tips!{END}"


text_0937__089BC49B:
	.string "These carpenters may be rough around{NL}the edges, but they do good work.{NL}They may seem tough, but they{SINGLE_QUOTE}re{NL}in touch with their feminine side.{END}"


text_0938__089BC526:
	.string "Romio and Julietta grew up next door{NL}to one another. They{SINGLE_QUOTE}re dating now,{NL}but they plan to marry once they get{NL}their pets{SINGLE_QUOTE} approval.{END}"


text_0939__089BC5AA:
	.string "Carlov{SINGLE_QUOTE}s Peaceful Hyrule{NL}Scenery Series No. 1{END}"


text_093A__089BC5D8:
	.string "Carlov{SINGLE_QUOTE}s Peaceful Hyrule{NL}Scenery Series No. 2{END}"


text_093B__089BC606:
	.string "Carlov{SINGLE_QUOTE}s Peaceful Hyrule{NL}Scenery Series No. 3{END}"


text_093C__089BC634:
	.string "With a boisterous crow and a cute{NL}crest, these feathered friends{NL}are the most popular pets in Hyrule.{NL}The baby chicks like small bugs.{END}"


text_093D__089BC6BB:
	.string "This small ranch lies just outside{NL}Hyrule Town. Father-and-daughter{NL}team Talon and Malon run it, and they{NL}sell the finest milk in Hyrule!{END}"


text_093E__089BC745:
	.string "The people who built the Wind Ruins.{NL}They now live above the clouds,{NL}suspended by their own magic ability{NL}to control the wind.{END}"


text_093F__089BC7C4:
	.string "An old man plagued by an evil spirit.{NL}Coming to his aid will bring you benefit{NL}in the end, so if you meet him, you must{NL}find a way to help him.{END}"


text_0940__089BC854:
	.string "Tingle (in green) and his twin younger{NL}brothers Ankle (in purple) and Knuckle{NL}(in blue). They believe fusing Kinstones{NL}will help them meet fairies, so they are{NL}recording Kinstone data on their maps.{NL}David Jr. is not technically a relative.{END}"


text_0941__089BC944:
	.string "The Hyrulean vegetables grown in their{NL}fields are exquisitely delicious.{NL}Apparently, Brocco sells the best{NL}of their crops.{END}"


text_0942__089BC9BF:
	.string "This Goron appears when you{NL}successfully fuse certain Kinstone{NL}pieces. He will sell you expensive,{NL}but rare, Kinstone pieces.{END}"


text_0943__089BCA3D:
	.string "Ghosts from the Royal Valley. The one{NL}in the blue cap is Spookter, and the{NL}one in the red cap is Spekter. Spookter{NL}tries to be scary, but he{SINGLE_QUOTE}s just not.{END}"


text_0944__089BCAD6:
	.string "Appears in Minish dungeons.{NL}They drop from the ceiling{NL}unexpectedly. They are slow, so take{NL}your time, and defeat them one by one.{END}"


text_0945__089BCB59:
	.string "Appears in Minish roads {SPECIAL_0F_PAR_1}{BYTE_0D} dungeons.{NL}These monsters have sharp mandibles.{NL}Hit them when they shoot these away.{NL}Avoid their attacks to get in close.{END}"


text_0946__089BCBED:
	.string "Appears in Minish roads.{NL}They come out of the ground when they{NL}sense prey. If you get swallowed, you{SINGLE_QUOTE}ll{NL}take damage and get all dirty!{NL}Watch out, because when you{SINGLE_QUOTE}re all{NL}dirty, Pestos will come after you.{END}"


text_0947__089BCCBA:
	.string "Appears in dungeons.{NL}Covered in hard, spiny shells.{NL}Few attacks work on them. You have{NL}to flip them over to hurt them.{END}"


text_0948__089BCD31:
	.string "Appears in Castor Wilds.{NL}They move when you put an arrow in{NL}their eye. No other attacks work.{NL}You can always just let them pass...{END}"


text_0949__089BCDB4:
	.string "Appears in caves, etc.{NL}Normally stay underground. They{SINGLE_QUOTE}ll pop{NL}out and spit seeds at you, but if you{NL}get to know {SINGLE_QUOTE}em, they{SINGLE_QUOTE}re not so bad.{END}"


text_094A__089BCE3D:
	.string "Appears in the Wind Ruins.{NL}Built by the Minish for the Wind Tribe{NL}long ago. They look like stone statues,{NL}but if you get too close, they move!{END}"


text_094B__089BCECC:
	.string "Appears in various areas.{NL}These bats live in dungeons and caves.{NL}Their movement is unpredictable, so use{NL}ranged weapons from a safe distance.{END}"


text_094C__089BCF5A:
	.string "Appears in various areas.{NL}This thieving fox preys upon travelers{NL}and merchants. He may not be strong,{NL}but he will attack very quickly,{NL}so be careful.{END}"


text_094D__089BCFF0:
	.string "Appears in the Royal Valley, etc. {NL}These dark beasties are attracted to{NL}light, and if they attack you, they{NL}may suck your life away!{END}"


text_094E__089BD075:
	.string "Appears in the Palace of Winds.{NL}These mummies keep coming at you when{NL}you attack. It{SINGLE_QUOTE}s better to fight from a{NL}distance if you want to avoid damage.{END}"


text_094F__089BD109:
	.string "Appears in dungeons.{NL}His hard shell protects him from swords,{NL}but once he rolls into a ball, you can{NL}use the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Gust Jar {SPECIAL_02_PAR_1}{END}to draw him in.{END}"


text_0950__089BD193:
	.string "Appears in dungeons.{NL}They cling to walls and move quickly.{NL}Normal attacks may not work, but the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}boomerang {SPECIAL_02_PAR_1}{END}is pretty effective.{END}"


text_0951__089BD216:
	.string "Appears in Castor Wilds.{NL}These armor-clad soldiers are tough.{NL}Use your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END} and {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}rolling{SPECIAL_02_PAR_1}{END} skills to{NL}find an opening in their defenses...{END}"


text_0952__089BD2A7:
	.string "Appears in the Palace of Winds.{NL}These Dark Nut commanders are strong,{NL}but if you relax and wait for your{NL}opening, you can still defeat them.{END}"


text_0953__089BD334:
	.string "Appears in dungeons.{NL}They move quickly to chase you once{NL}they spot you. Your shield will block{NL}them, but keep on your toes!{END}"


text_0954__089BD3B0:
	.string "Appears in Veil Falls.{NL}These tough Chuchus wear rocks on{NL}their heads. The rocks protect them{NL}from damage, so you{SINGLE_QUOTE}ll have to find{NL}a way to knock the rocks off before{NL}you{SINGLE_QUOTE}ll be able to destroy them.{END}"


text_0955__089BD475:
	.string "Appears in various areas.{NL}These guys move quickly and randomly.{NL}Trap them in a corner and take them{NL}out quickly.{END}"


text_0956__089BD4E6:
	.string "Appears in the Royal Crypt.{NL}They look like doors, but they{SINGLE_QUOTE}re really{NL}traps! If you get too close to one, it{NL}will fall down on you!{END}"


text_0957__089BD569:
	.string "Appears on Mount Crenel, etc.{NL}These strange beasts hover on{NL}propeller-like leaves. You can pull{NL}them out of the sky with your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Gust Jar{SPECIAL_02_PAR_1}{END}.{END}"


text_0958__089BD5F5:
	.string "Appears in various areas.{NL}Their fronts are protected with metal{NL}masks, but their backsides aren{SINGLE_QUOTE}t! Pop{NL}off that mask for an easy battle.{END}"


text_0959__089BD67E:
	.string "Appears in dungeons.{NL}If these guys grab you, they{SINGLE_QUOTE}ll send{NL}you back to the start of the dungeon.{NL}Dodge them as they fall, then attack.{END}"


text_095A__089BD704:
	.string "Appears in dungeons.{NL}If these guys grab you, they{SINGLE_QUOTE}ll send{NL}you back to the start of the dungeon.{NL}Watch out when he attacks with others.{END}"


text_095B__089BD78B:
	.string "Appears in the Eastern Hills, etc.{NL}Five of them pop out at once. If you{NL}smack each one as they pop out of the{NL}ground, they{SINGLE_QUOTE}re a piece of cake.{END}"


text_095C__089BD81A:
	.string "Appears in dungeons.{NL}They often gather in groups in narrow{NL}areas. Once activated, they go a little{NL}crazy. Take them out with arrows.{END}"


text_095D__089BD89F:
	.string "Appears in dungeons.{NL}They float in the air and explode when{NL}touched. Walk carefully, and you may{NL}escape unhurt...{END}"


text_095E__089BD911:
	.string "Appears in caves, dungeons, etc.{NL}Don{SINGLE_QUOTE}t let them grab you: they{SINGLE_QUOTE}ll eat{NL}your shield if they hold you long{NL}enough. Swing your sword to escape.{END}"


text_095F__089BD99D:
	.string "Appears in caves, dungeons, etc.{NL}This Rupee Like has a Rupee dangling{NL}from its head stalk. This clever lure{NL}attracts greedy and delicious heroes.{END}"


text_0960__089BDA2F:
	.string "Appears in various areas.{NL}They{SINGLE_QUOTE}ll come straight for you if they{NL}spot you. Just swing your sword when{NL}they charge at you.{END}"


text_0961__089BDAA8:
	.string "Appears on Mount Crenel, etc.{NL}These huge boulders come crashing{NL}down from cliff walls. They fall in a{NL}random pattern, so watch your step!{END}"


text_0962__089BDB32:
	.string "Appears in the Palace of Winds.{NL}They{SINGLE_QUOTE}re not fast, but that iron ball is{NL}a bruiser! Try to hit them after they{NL}swing the ball.{END}"


text_0963__089BDBB0:
	.string "Appears in various areas.{NL}They hide under common rocks and{NL}grass. Be careful, because they can{NL}pop out when you least expect it!{END}"


text_0964__089BDC31:
	.string "Appears in Minish Woods, etc.{NL}They rush you on sight. They also{NL}block head-on attacks with their{NL}spears, so circle around to attack.{END}"


text_0965__089BDCB6:
	.string "Appears in various areas.{NL}They fire arrows at you on sight.{NL}Block these with your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield {SPECIAL_02_PAR_1}{END}and{NL}then close in to attack.{END}"


text_0966__089BDD30:
	.string "Appears in the sky.{NL}They swim through clouds like fish{NL}in water. Attack them in that brief{NL}moment when they pop out!{END}"


text_0967__089BDDA5:
	.string "Appears in Minish roads, dungeons,{NL}etc. There are red and blue ones.{NL}They may look small and weak, but{NL}their hard shells make them formidable.{END}"


text_0968__089BDE34:
	.string "Appears in Minish roads, dungeons,{NL}etc. There are red and blue ones.{NL}The blue ones are stronger and{NL}throw things down on your head.{END}"


text_0969__089BDEB8:
	.string "Appears in Deepwood Shrine.{NL}These mushroom beasties scatter{NL}spores all over dungeons. When their{NL}caps are red, they are invincible.{END}"


text_096A__089BDF3C:
	.string "Appears in the Palace of Winds, etc.{NL}They fire magic bolts from afar. Hit{NL}them when they appear so they don{SINGLE_QUOTE}t{NL}cast another spell!{END}"


text_096B__089BDFBE:
	.string "Appears in the Palace of Winds.{NL}They wield fire magic. Hit them when{NL}they appear so they don{SINGLE_QUOTE}t cast{NL}another spell!{END}"


text_096C__089BE031:
	.string "Appears in the Palace of Winds.{NL}They wield ice magic. They{SINGLE_QUOTE}re weak{NL}against fire, so attack with fire for a{NL}quick battle!{END}"


text_096D__089BE0AA:
	.string "Appears in dungeons.{NL}They float in midair. They won{SINGLE_QUOTE}t hurt{NL}you, but if you touch them, you won{SINGLE_QUOTE}t{NL}be able to use your sword for a while.{END}"


text_096E__089BE132:
	.string "Appears in various areas.{NL}There are red and blue ones. They{SINGLE_QUOTE}ve{NL}appeared in every Zelda game to date.{NL}They spit rocks, so be careful!{END}"


text_096F__089BE1B7:
	.string "Appears in... Well, we{SINGLE_QUOTE}re not sure!{NL}The legendary Golden Octorok. It can{SINGLE_QUOTE}t{NL}be confirmed, but they are said to{NL}shoot chunks of pure gold...{END}"


text_0970__089BE242:
	.string "Appears in... Well, we{SINGLE_QUOTE}re not sure!{NL}The legendary Golden Tektite.{NL}Its basic attack is the same,{NL}but it has much more power.{END}"


text_0971__089BE2BE:
	.string "Appears in... Well, we{SINGLE_QUOTE}re not sure!{NL}The legendary Golden Rope. It{SINGLE_QUOTE}s much{NL}more aggressive than the normal ones:{NL}it will attack you on sight.{END}"


text_0972__089BE34A:
	.string "Appears in various areas.{NL}The black one is Crow. If you touch{NL}Takkuri, he will steal Rupees from{NL}you, so be careful!{END}"


text_0973__089BE3BF:
	.string "Appears in the sky.{NL}They float on clouds. They don{SINGLE_QUOTE}t move,{NL}but they do throw lightning bolts.{NL}Steal their clouds with the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Gust Jar{SPECIAL_02_PAR_1}{END}.{END}"


text_0974__089BE447:
	.string "Appears in dungeons.{NL}Blue ones jump, and red ones throw{NL}bones. See what happens when you{NL}remove their heads with the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Gust Jar{SPECIAL_02_PAR_1}{END}.{END}"


text_0975__089BE4CA:
	.string "Appears in various areas.{NL}They appear under rocks and grass.{NL}If they grab you, you won{SINGLE_QUOTE}t be able to{NL}move. Swing your sword to get away.{END}"


text_0976__089BE552:
	.string "Appears in various areas.{NL}Chuchus come in many colors.{NL}Each color is a little different, but{NL}ranged weapons work well against all.{END}"


text_0977__089BE5D5:
	.string "Appears on Mount Crenel, etc.{NL}They move by jumping long distances.{NL}Their movement can be unpredictable,{NL}so attack them when they are still.{END}"


text_0978__089BE661:
	.string "Appears in various areas.{NL}A trap with sharp blades. Some are{NL}triggered by nearby intruders, while{NL}others follow a set path.{END}"


text_0979__089BE6DD:
	.string "Appears in Wind Ruins, Veil Falls.{NL}These baddies move freely underground{NL}when attacking. You never know where{NL}they will pop up, so keep your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}shield{SPECIAL_02_PAR_1}{END}{NL}raised and at the ready!{END}"


text_097A__089BE78E:
	.string "Appears in Deepwood Shrine, etc.{NL}This caterpillar moves in a zigzag{NL}pattern. If you hit him on the nose, he{NL}gets upset and starts running around.{END}"


text_097B__089BE820:
	.string "Appears in various areas.{NL}These Chuchus project spikes from{NL}their bodies at the first sign of{NL}danger. Try a well-placed bomb.{END}"


text_097C__089BE89E:
	.string "Appears in the Temple of Droplets.{NL}Frozen solid by the power of the Water{NL}Element. He{SINGLE_QUOTE}s been frozen so long that{NL}his hunger is unbearable.{END}"


text_097D__089BE929:
	.string "Appears in Palace of Winds.{NL}Females are larger than males.{NL}They fly around the Palace of Winds,{NL}preying on adventurers.{END}"


text_097E__089BE9A1:
	.string "This is a legendary Goron with a body{NL}bigger than a mountain. This Goron is{NL}so big, in fact, that no one has ever{NL}seen all of it at once.{END}"


text_097F__089BEA2B:
	.string "Appears in Deepwood Shrine.{NL}A perfectly ordinary Chuchu. Though{NL}not much of an enemy usually, they are{NL}terrifying to anyone Minish-sized.{END}"


text_0980__089BEAB5:
	.string "Appears in the Cave of Flames.{NL}A Gleerok with a hard, rocky shell found{NL}in Mount Crenel. Hiding in lava, this{NL}beast spews fire on everything it sees.{END}"


text_0981__089BEB4B:
	.string "Appears in the Wind Ruins.{NL}Constructed by the Wind Tribe to repel{NL}intruders, this sturdy machine cannot{NL}be destroyed by any external force.{END}"


text_0982__089BEBD7:
	.string "Appears in the Temple of Droplets.{NL}An ordinary blue Chuchu. Fighting him{NL}while Minish-sized is daunting, but just{NL}try to avoid that electric attack.{END}"


text_0983__089BEC6C:
	.string "These two became fast friends because{NL}of Smith and the king of Hyrule. Zelda{NL}wishes that the sometimes unreliable{NL}{SPECIAL_06_PAR_1}{END} were just a wee bit stronger.{END}"


text_0984__089BECFF:
	.string "The Minish Ezlo, before he was cursed{NL}by Vaati. He is a famous Minish sage.{NL}Even among Minish inventors, he was{NL}renowned for his amazing creations.{END}"


text_0985__089BED93:
	.string "Appears in Dark Hyrule Castle.{NL}This is the strongest Dark Nut, with a{NL}good balance of attack and defense.{NL}They will do anything to stop you.{END}"


text_0986__089BEE20:
	.string "The sorcerer Vaati took this form{NL}after draining the power of the light{NL}force from Princess Zelda. The evil{NL}beams from his eyes are devastating.{END}"


text_0987__089BEEB1:
	.string "Once Vaati{SINGLE_QUOTE}s body has been shattered,{NL}this dark form rises up, all that{NL}remains of the evil sorcerer. Only the{NL}sacred Four Sword can defeat him.{END}"


text_0988__089BEF42:
	.string "This is the embodiment of purest evil,{NL}the final form of the power-mad Vaati.{NL}Its mind is consumed with a hunger for{NL}destruction. Find its weakness.{END}"


text_0989__089BEFD7:
	.string "This strange red postbox has the{NL}ability to fuse Kinstone pieces with{NL}you. Some say there is really just a{NL}person hiding inside it...{END}"


text_098A__089BF05D:
	.string "{END}"


text_098B__089BF05E:
	.string "{END}"


text_098C__089BF05F:
	.string "{END}"

