
text_0400__089B5968:
	.string "(Empty){END}"


text_0401__089B5970:
	.string "Smith{SINGLE_QUOTE}s Sword{END}"


text_0402__089B597E:
	.string "White Sword{END}"


text_0403__089B598A:
	.string "White Sword (Two Elements){END}"


text_0404__089B59A5:
	.string "White Sword (Three Elements){END}"


text_0405__089B59C2:
	.string "{END}"


text_0406__089B59C3:
	.string "Four Sword{END}"


text_0407__089B59CE:
	.string "Bombs{END}"


text_0408__089B59D4:
	.string "Remote Bombs{END}"


text_0409__089B59E1:
	.string "Bow{END}"


text_040A__089B59E5:
	.string "Light Arrow{END}"


text_040B__089B59F1:
	.string "Boomerang{END}"


text_040C__089B59FB:
	.string "Magical Boomerang{END}"


text_040D__089B5A0D:
	.string "Small Shield{END}"


text_040E__089B5A1A:
	.string "Mirror Shield{END}"


text_040F__089B5A28:
	.string "Flame Lantern{END}"


text_0410__089B5A36:
	.string "Flame Lantern{END}"


text_0411__089B5A44:
	.string "Gust Jar{END}"


text_0412__089B5A4D:
	.string "Cane of Pacci{END}"


text_0413__089B5A5B:
	.string "Mole Mitts{END}"


text_0414__089B5A66:
	.string "Roc{SINGLE_QUOTE}s Cape{END}"


text_0415__089B5A71:
	.string "Pegasus Boots{END}"


text_0416__089B5A7F:
	.string "Fire Rod{END}"


text_0417__089B5A88:
	.string "Ocarina of Wind{END}"


text_0418__089B5A98:
	.string "(DEBUG) Mega Crush{END}"


text_0419__089B5AAB:
	.string "(DEBUG) Enemy Set{END}"


text_041A__089B5ABD:
	.string "(DEBUG) Cell Overwrite Set{END}"


text_041B__089B5AD8:
	.string "Power Wrist{END}"


text_041C__089B5AE4:
	.string "Empty Bottle{END}"


text_041D__089B5AF1:
	.string "Empty Bottle{END}"


text_041E__089B5AFE:
	.string "Empty Bottle{END}"


text_041F__089B5B0B:
	.string "Empty Bottle{END}"


text_0420__089B5B18:
	.string "Empty Bottle{END}"


text_0421__089B5B25:
	.string "Butter{END}"


text_0422__089B5B2C:
	.string "Lon Lon Milk{END}"


text_0423__089B5B39:
	.string "Lon Lon Milk (1{SPECIAL_0F_PAR_1}{BYTE_15}2){END}"


text_0424__089B5B4D:
	.string "Red Potion{END}"


text_0425__089B5B58:
	.string "Blue Potion{END}"


text_0426__089B5B64:
	.string "Water{END}"


text_0427__089B5B6A:
	.string "Mt. Crenel Mineral Water{END}"


text_0428__089B5B83:
	.string "Fairy{END}"


text_0429__089B5B89:
	.string "Red Picolyte{END}"


text_042A__089B5B96:
	.string "Orange Picolyte{END}"


text_042B__089B5BA6:
	.string "Yellow Picolyte{END}"


text_042C__089B5BB6:
	.string "Green Picolyte{END}"


text_042D__089B5BC5:
	.string "Blue Picolyte{END}"


text_042E__089B5BD3:
	.string "White Picolyte{END}"


text_042F__089B5BE2:
	.string "Nayru{SINGLE_QUOTE}s Charm{END}"


text_0430__089B5BF0:
	.string "Farore{SINGLE_QUOTE}s Charm{END}"


text_0431__089B5BFF:
	.string "Din{SINGLE_QUOTE}s Charm{END}"


text_0432__089B5C0B:
	.string "{END}"


text_0433__089B5C0C:
	.string "{END}"


text_0434__089B5C0D:
	.string "Smith{SINGLE_QUOTE}s Blade{END}"


text_0435__089B5C1B:
	.string "Broken Picori Sword{END}"


text_0436__089B5C2F:
	.string "Bottle of Dog Food{END}"


text_0437__089B5C42:
	.string "Lon Lon Ranch Key{END}"


text_0438__089B5C54:
	.string "Wake-Up Mushroom{END}"


text_0439__089B5C65:
	.string "Library Book: A Hyrulean Bestiary{END}"


text_043A__089B5C87:
	.string "Library Book: Legend of the Picori{END}"


text_043B__089B5CAA:
	.string "Library Book: A History of Masks{END}"


text_043C__089B5CCB:
	.string "Graveyard Key{END}"


text_043D__089B5CD9:
	.string "Tingle Trophy{END}"


text_043E__089B5CE7:
	.string "Carlov Medal{END}"


text_043F__089B5CF4:
	.string "Mysterious Shells{END}"


text_0440__089B5D06:
	.string "Earth Element{END}"


text_0441__089B5D14:
	.string "Fire Element{END}"


text_0442__089B5D21:
	.string "Water Element{END}"


text_0443__089B5D2F:
	.string "Wind Element{END}"


text_0444__089B5D3C:
	.string "Grip Ring{END}"


text_0445__089B5D46:
	.string "Power Bracelets{END}"


text_0446__089B5D56:
	.string "Flippers{END}"


text_0447__089B5D5F:
	.string "Map of Hyrule{END}"


text_0448__089B5D6D:
	.string "Spin Attack{END}"


text_0449__089B5D79:
	.string "Roll Attack{END}"


text_044A__089B5D85:
	.string "Dash Attack{END}"


text_044B__089B5D91:
	.string "Rock Breaker{END}"


text_044C__089B5D9E:
	.string "Sword Beam{END}"


text_044D__089B5DA9:
	.string "Great Spin Attack{END}"


text_044E__089B5DBB:
	.string "Down Thrust{END}"


text_044F__089B5DC7:
	.string "Peril Beam{END}"


text_0450__089B5DD2:
	.string "Dungeon Map{END}"


text_0451__089B5DDE:
	.string "Compass{END}"


text_0452__089B5DE6:
	.string "Big Key{END}"


text_0453__089B5DEE:
	.string "Small Key{END}"


text_0454__089B5DF8:
	.string "1 Rupee{END}"


text_0455__089B5E00:
	.string "5 Rupees{END}"


text_0456__089B5E09:
	.string "20 Rupees{END}"


text_0457__089B5E13:
	.string "50 Rupees{END}"


text_0458__089B5E1D:
	.string "100 Rupees{END}"


text_0459__089B5E28:
	.string "200 Rupees{END}"


text_045A__089B5E33:
	.string "{END}"


text_045B__089B5E34:
	.string "Jabber Nut{END}"


text_045C__089B5E3F:
	.string "Kinstone Piece{END}"


text_045D__089B5E4E:
	.string "5 Bombs{END}"


text_045E__089B5E56:
	.string "5 Arrows{END}"


text_045F__089B5E5F:
	.string "Heart{END}"


text_0460__089B5E65:
	.string "Fairy{END}"


text_0461__089B5E6B:
	.string "{END}"


text_0462__089B5E6C:
	.string "Heart Container{END}"


text_0463__089B5E7C:
	.string "Pieces of Heart{END}"


text_0464__089B5E8C:
	.string "Big Wallet (Increased Size){END}"


text_0465__089B5EA8:
	.string "Big Bomb Bag (Increased Size){END}"


text_0466__089B5EC6:
	.string "Big Quiver{END}"


text_0467__089B5ED1:
	.string "Kinstone Bag{END}"


text_0468__089B5EDE:
	.string "Brioche{END}"


text_0469__089B5EE6:
	.string "Slice of Cake{END}"


text_046A__089B5EF4:
	.string "Croissant{END}"


text_046B__089B5EFE:
	.string "Slice of Pie{END}"


text_046C__089B5F0B:
	.string "10 Bombs{END}"


text_046D__089B5F14:
	.string "30 Bombs{END}"


text_046E__089B5F1D:
	.string "10 Arrows{END}"


text_046F__089B5F27:
	.string "30 Arrows{END}"


text_0470__089B5F31:
	.string "Tiger Scrolls{END}"


text_0471__089B5F3F:
	.string "{END}"


text_0472__089B5F40:
	.string "{END}"


text_0473__089B5F41:
	.string "Go to Save Screen{END}"


text_0474__089B5F53:
	.string "Go to Sleep Screen{END}"


text_0475__089B5F66:
	.string "Spin Attack{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}{NL}{SPECIAL_02_PAR_1}{END}Press and hold your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{NL}{SPECIAL_02_PAR_1}{END}button. Charge and release!{END}"


text_0476__089B5FB0:
	.string "Roll Attack{NL}Roll! Then swing your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{NL}{SPECIAL_02_PAR_1}{END}as you start to get up!{END}"


text_0477__089B5FF4:
	.string "Dash Attack{NL}Equip your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Pegasus Boots{NL}{SPECIAL_02_PAR_1}{END}and {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}, then dash away!{END}"


text_0478__089B603C:
	.string "Rock Breaker{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}{NL}{SPECIAL_02_PAR_1}{END}Break pots with your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}!{NL}That{SINGLE_QUOTE}s all there is to it!{END}"


text_0479__089B6088:
	.string "Sword Beam{NL}When your hearts are full,{NL}swing your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}!{END}"


text_047A__089B60C4:
	.string "Great Spin Attack{NL}Perform a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Spin Attack{SPECIAL_02_PAR_1}{END}...and{NL}hit the button repeatedly!{END}"


text_047B__089B6111:
	.string "Down Thrust{NL}Equip the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Roc{SINGLE_QUOTE}s Cape{SPECIAL_02_PAR_1}{END} and{NL}the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}!! Jump and swing!{END}"


text_047C__089B615A:
	.string "Peril Beam{NL}When you have only one{NL}heart left, swing the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sword{SPECIAL_02_PAR_1}{END}!{END}"

