
text_2400__089DC008:
	.string "{END}"


text_2401__089DC009:
	.string "Oh! Oh, thank you! You{SINGLE_QUOTE}re the one who{NL}returned me to normal, aren{SINGLE_QUOTE}t you?{NL}I don{SINGLE_QUOTE}t know how you did it, but{NL}I can{SINGLE_QUOTE}t thank you enough...{NL}Listen... Have you seen how strange{NL}the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king {SPECIAL_02_PAR_1}{END}has been lately?{NL}That{SINGLE_QUOTE}s because it{SINGLE_QUOTE}s not the king at all!{NL}It{SINGLE_QUOTE}s {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}! He{SINGLE_QUOTE}s taken over the castle!{NL}One by one, he turned us all to stone.{NL}Everyone, cursed by his evil magic...{NL}Then, the monsters arrived. Even{NL}paralyzed, I saw it all...{NL}I only pray it{SINGLE_QUOTE}s not too late to undo{NL}his evil...{END}"


text_2402__089DC1E1:
	.string "{SPECIAL_06_PAR_1}{END}! We need your help!{NL}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati {SPECIAL_02_PAR_1}{END}took our petrified princess to{NL}the roof of the castle...{NL}He must be planning something fiendish.{NL}You must stop him!{END}"


text_2403__089DC277:
	.string "The real {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king of Hyrule {SPECIAL_02_PAR_1}{END}must be locked{NL}up somewhere in the castle...{NL}Please find him. As soon as we{SINGLE_QUOTE}ve{NL}recovered, we{SINGLE_QUOTE}ll start looking, too.{END}"


text_2404__089DC307:
	.string "Oh! Thank you for restoring me.{NL}I feel so much better now!{NL}Don{SINGLE_QUOTE}t worry about me. I{SINGLE_QUOTE}ll be fine.{NL}Now, go help the others!{END}"


text_2405__089DC37F:
	.string "Leave this to us!{NL}You go save {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}!{END}"


text_2406__089DC3B1:
	.string "Don{SINGLE_QUOTE}t worry--we{SINGLE_QUOTE}ll protect the king.{NL}You have to go save {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Princess Zelda{SPECIAL_02_PAR_1}{END}!{END}"


text_2407__089DC3FE:
	.string "Gah! I hate to admit it, but we{SINGLE_QUOTE}re{NL}just no match for those beasts!{END}"


text_2408__089DC441:
	.string "{END}"


text_2409__089DC442:
	.string "{END}"


text_240A__089DC443:
	.string "{END}"


text_240B__089DC444:
	.string "{END}"


text_240C__089DC445:
	.string "Oh! {SPECIAL_06_PAR_1}{END}!{NL}{NL}Are you the one who broke the{NL}curse and returned me to normal?{NL}You{SINGLE_QUOTE}ve grown quite brave since{NL}I last saw you, I must say.{NL}But, oh, how this castle has suffered{NL}while I was under {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Vaati{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s curse...{NL}Is this all the work of one man?{NL}{NL}As {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king of Hyrule{SPECIAL_02_PAR_1}{END}, I must do{NL}something about this villain...{NL}But... Ah, I{SINGLE_QUOTE}m old, and I would only{NL}hold you back.{NL}{SPECIAL_06_PAR_1}{END}, you have the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}sacred blade{SPECIAL_02_PAR_1}{END}{NL}now. We must rely on you.{NL}Please! You must find a way to rescue{NL}my {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Zelda{SPECIAL_02_PAR_1}{END}.{NL}Take this key. You can use it to get{NL}out of the castle from the basement.{END}"


text_240D__089DC666:
	.string "If I were to join you, I fear I would{NL}only be a hindrance.{NL}Please, {SPECIAL_06_PAR_1}{END}, you must find a way{NL}to save my daughter.{END}"


text_240E__089DC6D6:
	.string "{END}"


text_240F__089DC6D7:
	.string "{END}"


text_2410__089DC6D8:
	.string "{END}"

