
text_4C00__089F6EB4:
	.string "SHICYO{SPECIAL_0F_PAR_1}{BYTE_1F}TEI{SPECIAL_0F_PAR_1}{BYTE_1F}000{END}"


text_4C01__089F6EC5:
	.string "Aherrrm herrmmm!{NL}I am {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hagen{SPECIAL_02_PAR_1}{END}, mayor of this fair town!{NL}Mayors are usually very important and{NL}busy folk, I{SINGLE_QUOTE}ll have you know...{NL}But I still have a hobby, of course!{NL}I collect unusual masks!{NL}I just love them!{NL}They{SINGLE_QUOTE}re beautiful!{NL}Simply magnificent, I tell you!{END}"


text_4C02__089F6FC9:
	.string "Aherrm!{NL}{NL}Yes! That{SINGLE_QUOTE}s me, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hagen{SPECIAL_02_PAR_1}{END}.{NL}I am mayor of this town.{NL}What{SINGLE_QUOTE}s that? You want a book?{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}A History of Masks{SPECIAL_02_PAR_1}{END}?{NL}And you say I checked it out,{NL}do you? Yes, indeed I did...{NL}Or wait... Did I?{END}"


text_4C03__089F7089:
	.string "Ahh, you seem to have found the book,{NL}safe and sound and in fine shape!{NL}But only because you listened to my{NL}masks like a good little boy, right?{NL}War har har har!{END}"


text_4C04__089F712B:
	.string "I{SINGLE_QUOTE}m going to have to pick up volume 2.{NL}That last book was just getting good!{END}"


text_4C05__089F7178:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}The person living here is the mayor,{NL}very important you know.{NL}Doesn{SINGLE_QUOTE}t it all just sound so...official?{END}"


text_4C06__089F71E2:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}The mayor likes strange masks.{NL}Sometimes, he even makes his own.{END}"


text_4C07__089F7226:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}The mayor took off for his {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}cabin by the{NL}lake{SPECIAL_02_PAR_1}{END} clutching a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}book{SPECIAL_02_PAR_1}{END}. We saw him go...{NL}But after the chest was opened, the{NL}road to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END} was blocked.{NL}You won{SINGLE_QUOTE}t be able to get through.{END}"


text_4C08__089F72ED:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F6}When the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}mayor {SPECIAL_02_PAR_1}{END}came back, he didn{SINGLE_QUOTE}t{NL}have that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}book {SPECIAL_02_PAR_1}{END}anymore.{NL}I{SINGLE_QUOTE}m sure he just left it at his {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}lakeside{NL}cabin{SPECIAL_02_PAR_1}{END}. He{SINGLE_QUOTE}s pretty forgetful like that.{END}"


text_4C09__089F7389:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}You want to go to the cabin{NL}by the lake?{NL}Well, let me just mark{NL}it here on your {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}.{NL}Err... Yes! There. It{SINGLE_QUOTE}s right here.{NL}You should be able to find it now.{END}"


text_4C0A__089F742C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}So the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}book {SPECIAL_02_PAR_1}{END}WAS at the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}lake{SPECIAL_02_PAR_1}{END}, then.{END}"


text_4C0B__089F745A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}Ah, but I do love our absentminded{NL}old mayor. He{SINGLE_QUOTE}s a fine man.{END}"


text_4C0C__089F749C:
	.string "You know, these masks see everything{NL}that goes on in my private life.{NL}Maybe you should just ask my masks!{NL}{END}"


text_4C0D__089F7507:
	.string "I think I{SINGLE_QUOTE}ve finally got a good grasp{NL}of how things run in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule{SPECIAL_02_PAR_1}{END}.{NL}Things run so smoothly around here,{NL}and I haven{SINGLE_QUOTE}t even done a thing!{NL}I wonder how much better this place{NL}would be if I actually did anything!{END}"


text_4C0E__089F75DC:
	.string "Aherrm!! That hole in the garden leads{NL}to a shelter of sorts.{NL}But it{SINGLE_QUOTE}s not like I{SINGLE_QUOTE}m trying to run off{NL}and save myself alone or anything!{NL}Just keep that in mind!{NL}{END}"


text_4C0F__089F767E:
	.string "I{SINGLE_QUOTE}m thinking of ways to increase the{NL}library{SINGLE_QUOTE}s budget to buy more books.{NL}Especially the ones about masks,{NL}you know.{END}"


text_4C10__089F76F2:
	.string "I may look somewhat idle to you,{NL}but no, sir!{NL}I will be working terrifically hard as{NL}soon as you leave.{NL}You can bet on that! Hoho!{END}"


text_4C11__089F7775:
	.string "These are the times that really test my{NL}mettle as a mayor, I tell you.{NL}Hyrule is my responsibility to the last.{NL}Everyone to the shelters!{END}"


text_4C12__089F77FF:
	.string "Monsters are coming!{NL}Everyone stay indoors!{NL}Oh, that doesn{SINGLE_QUOTE}t apply to you, my boy!{NL}You go get {SINGLE_QUOTE}em, {SPECIAL_06_PAR_1}{END}!{NL}Your sword and bravery{NL}will save the day!{END}"


text_4C13__089F7890:
	.string "SHICYO{SPECIAL_0F_PAR_1}{BYTE_1F}TEI{SPECIAL_0F_PAR_1}{BYTE_1F}019{END}"


text_4C14__089F78A1:
	.string "I hope I don{SINGLE_QUOTE}t sound like I{SINGLE_QUOTE}m bragging,{NL}but I have a cabin at {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Lake Hylia{SPECIAL_02_PAR_1}{END}.{NL}It{SINGLE_QUOTE}s a gorgeous little place where I go{NL}to enjoy my hobby, mask making.{END}"


text_4C15__089F7937:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}That {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}cabin by the lake{SPECIAL_02_PAR_1}{END} is{NL}really quite far.{END}"


text_4C16__089F796A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}The mayor wouldn{SINGLE_QUOTE}t be nearly so{NL}charming if he weren{SINGLE_QUOTE}t so carefree.{END}"

