
text_0D00__089C9EEC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}I planted a bean near my house,{NL}but it just doesn{SINGLE_QUOTE}t want to grow...{END}"


text_0D01__089C9F33:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}Oh, did you want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{END}"


text_0D02__089C9F5E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}You{SINGLE_QUOTE}re ready to quit? Well, OK...{END}"


text_0D03__089C9F83:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Hey, our Kinstones fit! I have a{NL}feeling something good will happen.{END}"


text_0D04__089C9FCB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Did you see that? Man, that {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean{SPECIAL_02_PAR_1}{END}{NL}is really something, isn{SINGLE_QUOTE}t it?{END}"


text_0D05__089CA012:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F6}There{SINGLE_QUOTE}s an old lady living out in the{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}woods{SPECIAL_02_PAR_1}{END} who absolutely loves {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}mushrooms{SPECIAL_02_PAR_1}{END}.{NL}Anyway, I hear she{SINGLE_QUOTE}s working on some{NL}special kind of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}potion{SPECIAL_02_PAR_1}{END} or something.{END}"


text_0D06__089CA0B7:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F7}Wanna {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Let{SINGLE_QUOTE}s do it!{END}"


text_0D07__089CA0E1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F6}Not interested...?{NL}Well, maybe next time!{END}"


text_0D08__089CA10E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}We did it! Wow! I just know my luck{SINGLE_QUOTE}s{NL}gonna turn around now!{END}"


text_0D09__089CA14E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}So I hear that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}mushroom lady {SPECIAL_02_PAR_1}{END}finished{NL}her new {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}potion{SPECIAL_02_PAR_1}{END}. It{SINGLE_QUOTE}s bright red.{NL}That is one seriously nasty color{NL}for a {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}potion{SPECIAL_02_PAR_1}{END}. I{SINGLE_QUOTE}m not touching it!{END}"


text_0D0A__089CA1E9:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FB}Have you seen that watery spot down{NL}to the south a bit?{NL}Is it just me, or is there something{NL}really suspicious about that place?{NL}I can{SINGLE_QUOTE}t quite put my finger on it,{NL}but it weirds me out...{END}"


text_0D0B__089CA2A8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}What, you wanna {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{END}"


text_0D0C__089CA2CF:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}No? All right, then.{NL}Whatever.{END}"


text_0D0D__089CA2F1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FF}Hey, they fit!{NL}...I wonder what that means.{END}"


text_0D0E__089CA320:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FC}Did you ever check out that watery{NL}spot? Was I right? It was weird, huh?{END}"


text_0D0F__089CA36C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_B0}What is it? What do you want from me?!{NL}{NL}You{SINGLE_QUOTE}re after my {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean{SPECIAL_02_PAR_1}{END}, aren{SINGLE_QUOTE}t you!?{NL}{NL}Well, I{SINGLE_QUOTE}ll NEVER tell you where it is!{NL}It{SINGLE_QUOTE}s mine! Mine, do you hear me! Mine!{NL}But...I suppose if you can {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse a{NL}Kinstone {SPECIAL_02_PAR_1}{END}with me, I might tell you.{NL}...{NL}{NL}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}How was I? Did I sound like an elder?{NL}I{SINGLE_QUOTE}ve been practicing my elder-ese!{END}"


text_0D10__089CA4A8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}Huh? You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Yeah, all right!{END}"


text_0D11__089CA4E1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}You changed your mind?{NL}That{SINGLE_QUOTE}s so selfish!{END}"


text_0D12__089CA50E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}Hey! A perfect fuse!{NL}Maybe we{SINGLE_QUOTE}ll get lucky now!{END}"


text_0D13__089CA541:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_B0}You{SINGLE_QUOTE}re here to steal my {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean{SPECIAL_02_PAR_1}{END},{NL}aren{SINGLE_QUOTE}tcha?{NL}Well, you{SINGLE_QUOTE}re out of luck! It{SINGLE_QUOTE}s{NL}grown way too big now!! Ha ha!{NL}{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}So how was my elder impersonation?{NL}He talks JUST like that! Doesn{SINGLE_QUOTE}t he?{END}"


text_0D14__089CA5FA:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F9}I planted a bean {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}back {SPECIAL_02_PAR_1}{END}there,{NL}but it just won{SINGLE_QUOTE}t sprout...{END}"


text_0D15__089CA63A:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Sure, why not! Let{SINGLE_QUOTE}s do it!{END}"


text_0D16__089CA679:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}You changed your mind? Well, I{SINGLE_QUOTE}ll be{NL}here if you change your mind again.{END}"


text_0D17__089CA6C5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FA}We did it! We{SINGLE_QUOTE}re in for a run{NL}of good luck now!{END}"


text_0D18__089CA6F8:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F8}My {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean {SPECIAL_02_PAR_1}{END}grew! ...Kind of a lot!{NL}A little too much, actually!{END}"


text_0D19__089CA73C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_0C_PAR_1}I planted a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean {SPECIAL_02_PAR_1}{END}on that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}mountain to{NL}the left{SPECIAL_02_PAR_1}{END}... But it won{SINGLE_QUOTE}t sprout.{NL}I guess a metalworker like me just{NL}isn{SINGLE_QUOTE}t cut out to be a gardener...{END}"


text_0D1A__089CA7D2:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_0C_PAR_1}So you want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Let{SINGLE_QUOTE}s do it!{END}"


text_0D1B__089CA805:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_0C_PAR_1}Oh, not interested anymore, eh?{NL}Well, that{SINGLE_QUOTE}s a shame.{END}"


text_0D1C__089CA83E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_0C_PAR_1}What a perfect fit! You can{SINGLE_QUOTE}t even{NL}see the seam! Impeccable work!{END}"


text_0D1D__089CA883:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_0C_PAR_1}Whoa!{NL}That {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean {SPECIAL_02_PAR_1}{END}I planted got HUGE!{NL}I guess I{SINGLE_QUOTE}ve got a green thumb{NL}as well as an, er...iron one!{END}"


text_0D1E__089CA8EB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}I just planted a big ol{SINGLE_QUOTE} {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean{SPECIAL_02_PAR_1}{END}...{NL}{NL}It hasn{SINGLE_QUOTE}t sprouted yet, but when it{NL}does, it{SINGLE_QUOTE}s gonna be a big sucker!!{END}"


text_0D1F__089CA95B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{END}Huh? Oh, you want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse{NL}Kinstones{SPECIAL_02_PAR_1}{END}? Why, sure! You got it!{END}"


text_0D20__089CA99E:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Whaaat, you{SINGLE_QUOTE}re gonna quit? Well,{NL}come on back sometime, y{SINGLE_QUOTE}hear?{END}"


text_0D21__089CA9E1:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Wow! Seein{SINGLE_QUOTE} how well that fit, I{SINGLE_QUOTE}d guess{NL}we{SINGLE_QUOTE}re in for a spell of good luck!{END}"


text_0D22__089CAA30:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_04_PAR_2}Hey, listen to this! You remember that{NL}big {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}bean {SPECIAL_02_PAR_1}{END}I planted?{NL}Well, would you believe it finally{NL}sprouted! I wonder where it leads!{END}"


text_0D23__089CAAB8:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Sure! Let{SINGLE_QUOTE}s see how well they fit!{END}"


text_0D24__089CAAFB:
	.string "Oh, you had a change of heart?{NL}Well, I{SINGLE_QUOTE}ll be here...{END}"


text_0D25__089CAB30:
	.string "What a fit! Look at that! And you know{NL}what that means? Good luck for us!{END}"


text_0D26__089CAB7A:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}, don{SINGLE_QUOTE}t you?{NL}Well, OK! Let{SINGLE_QUOTE}s give it a try.{END}"


text_0D27__089CABC4:
	.string "Oh, you don{SINGLE_QUOTE}t want to?{NL}Well, we can try again later.{END}"


text_0D28__089CABF9:
	.string "They fit perfectly! I wonder{NL}what{SINGLE_QUOTE}s going to happen!{END}"


text_0D29__089CAC2E:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Let{SINGLE_QUOTE}s do it!{END}"


text_0D2A__089CAC5B:
	.string "Oh, you want to quit? Well, we can{NL}always try again later!{END}"


text_0D2B__089CAC96:
	.string "They fit perfectly! Things are{NL}starting to look up!{END}"


text_0D2C__089CACCA:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}OK, but let{SINGLE_QUOTE}s be careful about it!{END}"


text_0D2D__089CAD0D:
	.string "You want to quit? I hope you come{NL}back, so we can try again later.{END}"


text_0D2E__089CAD50:
	.string "Oh, they fit! Perfectly, in fact!{NL}They say that means good luck for us!{END}"


text_0D2F__089CAD98:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_05_PAR_1}You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Let{SINGLE_QUOTE}s give it a try!{END}"


text_0D30__089CADD0:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FD}Oh, you want to quit?{NL}We can always try later, I guess.{END}"


text_0D31__089CAE0B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_FE}They fit perfectly! I wonder, does{NL}that mean we{SINGLE_QUOTE}re in for good luck?{END}"


text_0D32__089CAE53:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{SPECIAL_07_PAR_1}You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Yeah, sure. Why not?{END}"


text_0D33__089CAE8B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_08}Oh, you want to quit?{NL}That{SINGLE_QUOTE}s too bad.{END}"


text_0D34__089CAEB4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_08}They fit perfectly! We{SINGLE_QUOTE}re looking at{NL}a whole heap of good luck now!{END}"


text_0D35__089CAEFB:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F0}You want to fuse Kinstones?{NL}OK! Let{SINGLE_QUOTE}s do this!{END}"


text_0D36__089CAF2D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_EF}Oh, you want to quit?{NL}Well, come back anytime.{END}"


text_0D37__089CAF5F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_EE}Finally! A perfect match means we{SINGLE_QUOTE}re{NL}in for some spectacular good luck!{END}"


text_0D38__089CAFAA:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_EC}You want to fuse Kinstones in this dire{NL}time? ...Well, I can see no harm in it.{END}"


text_0D39__089CAFFD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_EB}Ah, and now you{SINGLE_QUOTE}ve changed your mind.{NL}I suppose it is for the best.{END}"


text_0D3A__089CB044:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_EA}Ah, a perfect fit. My, but that{SINGLE_QUOTE}s{NL}nice. Good luck to you.{END}"


text_0D3B__089CB081:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F1}You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Sure, why not?{END}"


text_0D3C__089CB0B3:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F2}Oh, you want to quit?{NL}Well, come again.{END}"


text_0D3D__089CB0DE:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F1}They fit perfectly! I didn{SINGLE_QUOTE}t expect that!{NL}Maybe something good will happen now.{END}"


text_0D3E__089CB131:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Let{SINGLE_QUOTE}s give it a shot!{END}"


text_0D3F__089CB167:
	.string "Oh, you want to quit? Well, I look{NL}forward to trying again later!{END}"


text_0D40__089CB1A9:
	.string "They fit perfectly! You know what this{NL}means? Good luck for both of us!{END}"


text_0D41__089CB1F1:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Oh, please, please, yes!{END}"


text_0D42__089CB22A:
	.string "Oh, you want to quit? But...I was{NL}looking forward to it so much...{END}"


text_0D43__089CB26D:
	.string "Oh, that{SINGLE_QUOTE}s so pretty! A perfect{NL}fit! Now, I know we{SINGLE_QUOTE}ll get lucky!{END}"


text_0D44__089CB2AF:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D0}You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}I would love to!{END}"


text_0D45__089CB2E3:
	.string "Oh, you want to quit? Well, I{SINGLE_QUOTE}ll be{NL}here, so come on back!{END}"


text_0D46__089CB31E:
	.string "They fit perfectly!{NL}I feel a strange power within!{END}"


text_0D47__089CB351:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Let{SINGLE_QUOTE}s give it a go!{END}"


text_0D48__089CB385:
	.string "Oh, you want to quit?{NL}Lame, kid. Real lame.{END}"


text_0D49__089CB3B1:
	.string "They fit perfectly!{NL}Time to celebrate!{END}"


text_0D4A__089CB3D8:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Oh, Tingle is so happy!{END}"


text_0D4B__089CB410:
	.string "Oh, you want to quit? You{SINGLE_QUOTE}re making{NL}Tingle oh-so-very sad!{END}"


text_0D4C__089CB44B:
	.string "They fit perfectly! At last, Tingle{NL}can finally turn into a fairy, too!{END}"


text_0D4D__089CB493:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Of course!{END}"


text_0D4E__089CB4BE:
	.string "Oh, you want to quit?{NL}Well, whatever.{END}"


text_0D4F__089CB4E4:
	.string "They fit perfectly! We{SINGLE_QUOTE}re looking{NL}at a heap of good luck now!{END}"


text_0D50__089CB522:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Very well.{END}"


text_0D51__089CB54D:
	.string "Oh, you want to quit?{NL}Pshaw!{END}"


text_0D52__089CB56A:
	.string "Excellent. A perfect fit!{NL}Now, where{SINGLE_QUOTE}s my good fortune?{END}"


text_0D53__089CB5A2:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Sure, kid.{END}"


text_0D54__089CB5CD:
	.string "Oh, you want to quit?{NL}Too bad...{END}"


text_0D55__089CB5EE:
	.string "They fit perfectly.{NL}Does that mean I{SINGLE_QUOTE}m lucky now?{END}"


text_0D56__089CB620:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}I{SINGLE_QUOTE}d be glad to! Thank you!{END}"


text_0D57__089CB65B:
	.string "Oh, you want to quit?{NL}Come again! Hey, hey!{END}"


text_0D58__089CB687:
	.string "They fit perfectly! Oh, I expect my{NL}sales will triple because of this!{END}"


text_0D59__089CB6CE:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}{END}"


text_0D5A__089CB6EF:
	.string "Oh, you want to quit?{NL}Come again!{END}"


text_0D5B__089CB711:
	.string "They fit perfectly! This will{NL}be good for business!{END}"


text_0D5C__089CB745:
	.string "Must deliver the mail...{NL}Hey, that{SINGLE_QUOTE}s a Kinstone piece!{END}"


text_0D5D__089CB77C:
	.string "Well, I{SINGLE_QUOTE}ve got work to do,{NL}so if you don{SINGLE_QUOTE}t mind...{END}"


text_0D5E__089CB7AF:
	.string "Perfect! I can feel the super delivery{NL}power coursing through my veins!{NL}Now, I return to my route refreshed!{END}"


text_0D5F__089CB81C:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}I hope they fit!{END}"


text_0D60__089CB84D:
	.string "Oh, you want to quit?{NL}Well, let{SINGLE_QUOTE}s try again later!{END}"


text_0D61__089CB880:
	.string "A perfect fit! I can{SINGLE_QUOTE}t wait{NL}to see what happens now!{END}"


text_0D62__089CB8B5:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}I hope they fit!{END}"


text_0D63__089CB8E6:
	.string "Oh, you want to quit?{NL}Too bad! Your loss!{END}"


text_0D64__089CB910:
	.string "They fit perfectly!{NL}But...nothing{SINGLE_QUOTE}s happening!{END}"


text_0D65__089CB93F:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Certainly!{END}"


text_0D66__089CB96A:
	.string "You{SINGLE_QUOTE}re quitting?{END}"


text_0D67__089CB97B:
	.string "They fit perfectly.{NL}I guess we{SINGLE_QUOTE}ll get lucky.{END}"


text_0D68__089CB9A8:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}You got it!{END}"


text_0D69__089CB9D4:
	.string "Oh, you want to quit?{NL}Too bad!{END}"


text_0D6A__089CB9F3:
	.string "Hey, look at that! Nice work!{NL}I wonder what will happen...{END}"


text_0D6B__089CBA2E:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Sure!{END}"


text_0D6C__089CBA54:
	.string "Oh, you want to quit?{NL}Well, let{SINGLE_QUOTE}s try again later!{END}"


text_0D6D__089CBA87:
	.string "Oh, wonderful! They fit!{NL}I{SINGLE_QUOTE}m so happy!{END}"


text_0D6E__089CBAAE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D3}You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}OK-hay-hay!!!{END}"


text_0D6F__089CBADF:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D3}Aw... You{SINGLE_QUOTE}re quitting?{END}"


text_0D70__089CBAF9:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D3}Neiiiighhhh!!! They fit!{NL}They fit! It{SINGLE_QUOTE}s wonderful!{END}"


text_0D71__089CBB2F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_AE}What, you want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{END}"


text_0D72__089CBB58:
	.string "Oh, so you changed your mind?{NL}All right...{END}"


text_0D73__089CBB83:
	.string "Huh... They fit.{END}"


text_0D74__089CBB94:
	.string "So you want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}I hope they fit again this time...{END}"


text_0D75__089CBBDA:
	.string "Oh, you want to quit? I{SINGLE_QUOTE}m disappointed,{NL}{SPECIAL_06_PAR_1}{END}. Very disappointed!{END}"


text_0D76__089CBC19:
	.string "A perfect fit!{NL}I feel a poem coming on!{NL}... ... ...{NL}... ... ...{NL}... ... ...{NL}... ... ...{NL}Er, yes.{NL}Indeed, indeed.{END}"


text_0D77__089CBC8A:
	.string "You would like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Gladly!{END}"


text_0D78__089CBCB8:
	.string "You{SINGLE_QUOTE}ve decided to quit? Return{NL}anytime, and we will try again.{END}"


text_0D79__089CBCF7:
	.string "A perfect match. We are all in{NL}for some good luck.{END}"


text_0D7A__089CBD2A:
	.string "Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{END}"


text_0D7B__089CBD50:
	.string "You{SINGLE_QUOTE}ve changed your mind?{NL}Ah, well...{END}"


text_0D7C__089CBD76:
	.string "We{SINGLE_QUOTE}ve made a perfect match! Maybe I{SINGLE_QUOTE}ll{NL}get lucky enough to find a home!{END}"


text_0D7D__089CBDBE:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Yeah, sure!{END}"


text_0D7E__089CBDEA:
	.string "Oh, you want to quit?{NL}Well, let{SINGLE_QUOTE}s try again later!{END}"


text_0D7F__089CBE1D:
	.string "They fit perfectly!{NL}I wonder if we{SINGLE_QUOTE}ll get lucky...{END}"


text_0D80__089CBE50:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}I{SINGLE_QUOTE}m on it!{END}"


text_0D81__089CBE7B:
	.string "Oh, you want to quit?{NL}Where{SINGLE_QUOTE}s your spirit, man?{END}"


text_0D82__089CBEAB:
	.string "They fit perfectly! I have...{NL}a good feeling about this!{END}"


text_0D83__089CBEE4:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Yeah, OK.{END}"


text_0D84__089CBF0E:
	.string "Oh, you want to quit?{NL}Well, maybe later!{END}"


text_0D85__089CBF37:
	.string "They fit perfectly! Hm... I hope{NL}some good luck comes our way.{END}"


text_0D86__089CBF76:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}Hn... You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}OK, that sounds good.{END}"


text_0D87__089CBFB5:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}Oh, you want to quit?{NL}OK, that sounds good.{END}"


text_0D88__089CBFE4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}Hn. They fit perfectly...{NL}So that{SINGLE_QUOTE}s good.{END}"


text_0D89__089CC011:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D1}Rarf! Arf arf! You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse{NL}Kinstones{SPECIAL_02_PAR_1}{END}? Rarf arf!{END}"


text_0D8A__089CC04D:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D1}Arf arf! You{SINGLE_QUOTE}re quiting?{NL}Rrrrrrrr ARF ARF ARF!!!{END}"


text_0D8B__089CC081:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D1}Rarf! A perfect fit! Arf!{END}"


text_0D8C__089CC09E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D2}Rowr! Would you like to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse{NL}Kinstones{SPECIAL_02_PAR_1}{END}? Mrow...{END}"


text_0D8D__089CC0D5:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D2}You{SINGLE_QUOTE}re stopping so soon?{NL}Meow... That{SINGLE_QUOTE}s too bad.{END}"


text_0D8E__089CC109:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D2}They fit! Perfectly!{NL}Purrrrrrrr...{END}"


text_0D8F__089CC12F:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}Mooooooo... You want to{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fyoooooose Kinstones{SPECIAL_02_PAR_1}{END}?{END}"


text_0D90__089CC164:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}You want to quit? We{SINGLE_QUOTE}ll try again later.{NL}It{SINGLE_QUOTE}s not like I{SINGLE_QUOTE}m going anywhere! Moo...{END}"


text_0D91__089CC1B9:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}Mooo! A perfect fit!{NL}I feel so...content...{END}"


text_0D92__089CC1E8:
	.string "Hey, do you want to fuse{NL}Kinstones with me? Well?{END}"


text_0D93__089CC21A:
	.string "What, you want to quit? Whatever!{NL}Just make sure you come back!{END}"


text_0D94__089CC25A:
	.string "Look at that! A perfect fit!{NL}That means good luck for us.{END}"


text_0D95__089CC294:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}I hope you{SINGLE_QUOTE}ve got one that fits!{END}"


text_0D96__089CC2D5:
	.string "You want to quit? What do you hope{NL}to gain by doing that?{END}"


text_0D97__089CC30F:
	.string "They fit perfectly. Why...I can{NL}see my brother{SINGLE_QUOTE}s smiling face...{END}"


text_0D98__089CC350:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Yeah, let{SINGLE_QUOTE}s see if they fit!{END}"


text_0D99__089CC38D:
	.string "Oh, you want to quit?{NL}Is it me...?{END}"


text_0D9A__089CC3B0:
	.string "They fit perfectly! Tingle would{NL}be so proud of me!{END}"


text_0D9B__089CC3E4:
	.string "Let{SINGLE_QUOTE}s {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}!{NL}I hope they fit...{END}"


text_0D9C__089CC411:
	.string "Oh, you want to quit?{NL}I see how it is...{END}"


text_0D9D__089CC43A:
	.string "Wow. I didn{SINGLE_QUOTE}t actually think{NL}that would work...{END}"


text_0D9E__089CC46A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_B0}You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Yes, please!{END}"


text_0D9F__089CC49A:
	.string "Oh, you want to quit?{NL}What a shame...{END}"


text_0DA0__089CC4C0:
	.string "They fit beautifully! This is a sign{NL}of good things to come!{END}"


text_0DA1__089CC4FD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_F7}You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Sure, bring it on!{END}"


text_0DA2__089CC533:
	.string "Oh, what a shame...{NL}You want to quit...{END}"


text_0DA3__089CC55B:
	.string "Look at that! They fit perfectly! Well,{NL}we{SINGLE_QUOTE}re sure to get some good luck now!{END}"


text_0DA4__089CC5A9:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D5}You want to--BRRKAWK--{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse{NL}Kinstones{SPECIAL_02_PAR_1}{END}? Buckawk!!{END}"


text_0DA5__089CC5E0:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D5}You want to quit?{NL}BRRKAWK!{END}"


text_0DA6__089CC5FE:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D5}Perfect! BRRKAWK!{END}"


text_0DA7__089CC613:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D6}You want to--cheep cheep!--{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse{NL}Kinstones{SPECIAL_02_PAR_1}{END}? PEEP!{END}"


text_0DA8__089CC64B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D6}You want to quit... You think{NL}I{SINGLE_QUOTE}m too young? Peep-peep!{END}"


text_0DA9__089CC686:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D6}Perfect! PEEP!{END}"


text_0DAA__089CC698:
	.string "You want to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END}?{NL}Sure, I bet we can do this!{END}"


text_0DAB__089CC6D4:
	.string "You want to quit?{NL}Well, I{SINGLE_QUOTE}ll be right here, waiting...{END}"


text_0DAC__089CC70B:
	.string "OK!! Now we get happy!{NL}See you later!{END}"


text_0DAD__089CC731:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}Hey! How{SINGLE_QUOTE}d you find me, kid?{NL}You{SINGLE_QUOTE}re a real humdinger!{NL}So, since you found me, I{SINGLE_QUOTE}m going to{NL}give you {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}my number-one treasure{SPECIAL_02_PAR_1}{END}!{NL}And keep up the good work!{END}"


text_0DAE__089CC7CF:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}You came back!{NL}I{SINGLE_QUOTE}m so happy! I was just getting lonely!{NL}Except...I don{SINGLE_QUOTE}t have anything else{NL}to give you. Sorry!{END}"


text_0DAF__089CC842:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}So, have you met the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Great Fairy {SPECIAL_02_PAR_1}{END}of{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Minish Woods{SPECIAL_02_PAR_1}{END}?{NL}She lives right off that little side path!{END}"


text_0DB0__089CC8AA:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}And have you met the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Great Fairy {SPECIAL_02_PAR_1}{END}of{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Mount Crenel{SPECIAL_02_PAR_1}{END}?{NL}She lives behind a wall that you have{NL}to break open with a bomb.{END}"


text_0DB1__089CC928:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_02_PAR_1}{BYTE_0D}What about the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Great Fairy {SPECIAL_02_PAR_1}{END}near{NL}the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Royal Crypt{SPECIAL_02_PAR_1}{END}? Have you met her?{NL}She lives behind a wall that you have{NL}to break open with a bomb.{END}"


text_0DB2__089CC9B7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}I found a--moo!--{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END} in{NL}this delicious grass.{NL}Do you want to try {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fusing it{NL}with one of mine{SPECIAL_02_PAR_1}{END}? Moo...{NL}I--moo--licked it until it was really{NL}clean and shiny.{END}"


text_0DB3__089CCA68:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}This grass is delicious!{NL}Moo... Want a nibble?{END}"


text_0DB4__089CCA9A:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D5}Well done of you to get here, BRRKAWK!{NL}{NL}I have secretly taken possession of{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Anju{SPECIAL_02_PAR_1}{END}{SINGLE_QUOTE}s {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece{SPECIAL_02_PAR_1}{END}!{NL}Hm? No, I didn{SINGLE_QUOTE}t steal it, you rude boy!{NL}I just borrowed it...secretly.{END}"


text_0DB5__089CCB50:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D5}Wha--? The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone piece {SPECIAL_02_PAR_1}{END}fused and{NL}disappeared, BRRKAWK!{NL}Now, I can{SINGLE_QUOTE}t give it back to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Anju{SPECIAL_02_PAR_1}{END}!{NL}But I{SINGLE_QUOTE}m still happy, BRRKAWK!{END}"


text_0DB6__089CCBD6:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D6}Eep! One of the Minish! PEEP!{NL}{NL}I{SINGLE_QUOTE}m not like my brothers! I won{SINGLE_QUOTE}t chase{NL}you around and peck at you! Peepeep!{NL}Not only that! I also have some good{NL}info for you!{NL}Somewhere in Hyrule, there{SINGLE_QUOTE}s a {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Great{NL}Fairy{SPECIAL_02_PAR_1}{END} who helps honest adventurers.{NL}If you see her, answer her every{NL}question truthfully! PEEP!{END}"

