
text_2E00__089DFF04:
	.string "{END}"


text_2E01__089DFF05:
	.string "Wallet 300 Rupees{END}"


text_2E02__089DFF17:
	.string "Arrow Quiver 300 Rupees{END}"


text_2E03__089DFF2F:
	.string "10 Bombs 30 Rupees{END}"


text_2E04__089DFF42:
	.string "30 Bombs 80 Rupees{END}"


text_2E05__089DFF55:
	.string "10 Remote Bombs 40 Rupees{END}"


text_2E06__089DFF6F:
	.string "30 Remote Bombs 100 Rupees{END}"


text_2E07__089DFF8A:
	.string "Shield 40 Rupees{END}"


text_2E08__089DFF9B:
	.string "Mirror Shield 350 Rupees{END}"


text_2E09__089DFFB4:
	.string "10 Arrows 20 Rupees{END}"


text_2E0A__089DFFC8:
	.string "30 Arrows 50 Rupees{END}"


text_2E0B__089DFFDC:
	.string "Figurine Ticket 15 Rupees{END}"


text_2E0C__089DFFF6:
	.string "Bottle 200 Rupees{END}"


text_2E0D__089E0008:
	.string "Magic Boomerang 350 Rupees{END}"


text_2E0E__089E0023:
	.string "Fire Rod 350 Rupees{END}"


text_2E0F__089E0037:
	.string "Sleeping Shroom 50 Rupees{END}"


text_2E10__089E0051:
	.string "Brioche 10 Rupees{END}"


text_2E11__089E0063:
	.string "Slice of Cake 10 Rupees{END}"


text_2E12__089E007B:
	.string "Croissant 20 Rupees{END}"


text_2E13__089E008F:
	.string "Slice of Pie 20 Rupees{END}"


text_2E14__089E00A6:
	.string "Red Top Piece 30 Rupees{END}"


text_2E15__089E00BE:
	.string "Red Bottom Piece 30 Rupees{END}"


text_2E16__089E00D9:
	.string "Blue Top Piece 30 Rupees{END}"


text_2E17__089E00F2:
	.string "Blue Bottom Piece 30 Rupees{END}"


text_2E18__089E010E:
	.string "Green Top Piece 30 Rupees{END}"


text_2E19__089E0128:
	.string "Dog Food{END}"

