
text_3700__089E5FB4:
	.string "{END}"


text_3701__089E5FB5:
	.string "I can hear those schoolkids laughing{NL}all the way over here.{END}"


text_3702__089E5FF1:
	.string "You know, even this headband can be{NL}used as a weapon.{NL}A real man has to be able to do battle{NL}with whatever is at his disposal.{END}"


text_3703__089E6070:
	.string "Meoooow...{END}"


text_3704__089E607B:
	.string "Rowrrr!{END}"


text_3705__089E6083:
	.string "{END}"


text_3706__089E6084:
	.string "{END}"


text_3707__089E6085:
	.string "{END}"


text_3708__089E6086:
	.string "{END}"


text_3709__089E6087:
	.string "{END}"


text_370A__089E6088:
	.string "{END}"


text_370B__089E6089:
	.string "{END}"


text_370C__089E608A:
	.string "{END}"


text_370D__089E608B:
	.string "{END}"


text_370E__089E608C:
	.string "{END}"


text_370F__089E608D:
	.string "{END}"


text_3710__089E608E:
	.string "{END}"


text_3711__089E608F:
	.string "{END}"


text_3712__089E6090:
	.string "Buggedy-buggedy-BOO!{NL}{NL}...Still nothin{SINGLE_QUOTE}, huh?{END}"


text_3713__089E60BD:
	.string "Yeah, I{SINGLE_QUOTE}m just about ready to hang up{NL}my sheet and leave the ghost business.{END}"


text_3714__089E610A:
	.string "Arf arf!{END}"


text_3715__089E6113:
	.string "I{SINGLE_QUOTE}m really good friends with that{NL}dog on the other side of town.{NL}We{SINGLE_QUOTE}re nothing alike, but we still{NL}get along really well.{END}"


text_3716__089E618D:
	.string "There{SINGLE_QUOTE}s a ghost in the well...{END}"


text_3717__089E61AC:
	.string "This water feels good...{END}"


text_3718__089E61C5:
	.string "Is there really a ghost in the well?{END}"


text_3719__089E61EA:
	.string "I wonder what I should make for dinner{NL}tonight? Hyrule stew maybe?{END}"


text_371A__089E622D:
	.string "Tch! This stall is such a mess!{NL}{NL}Maybe that{SINGLE_QUOTE}s why Beedle{SINGLE_QUOTE}s not here{NL}selling his Picolyte.{END}"


text_371B__089E6287:
	.string "I wish we had a butcher...{END}"


text_371C__089E62A2:
	.string "Hey, hey! Lowest prices anywhere!{END}"


text_371D__089E62C4:
	.string "Hurry up and buy, or I{SINGLE_QUOTE}ll pelt you with{NL}fruits! Hey, hey!{END}"


text_371E__089E62FE:
	.string "Hey, hey! You buy, or{NL}I don{SINGLE_QUOTE}t let you leave!{END}"


text_371F__089E632B:
	.string "What is this! I haven{SINGLE_QUOTE}t sold anything{NL}all day! Hey, hey!{END}"


text_3720__089E6364:
	.string "I really don{SINGLE_QUOTE}t feel like going back{NL}to the castle for a while.{NL}I{SINGLE_QUOTE}m scared, because people have said{NL}there are monsters INSIDE the castle!{END}"


text_3721__089E63EE:
	.string "{END}"


text_3722__089E63EF:
	.string "I just want to jump right in the river!{NL}But it doesn{SINGLE_QUOTE}t look like I can...{END}"


text_3723__089E6439:
	.string "Kids are great, aren{SINGLE_QUOTE}t they?{END}"


text_3724__089E6456:
	.string "Only a few guards are still out there{NL}looking for that {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force {SPECIAL_02_PAR_1}{END}stuff.{END}"


text_3725__089E64A4:
	.string "There{SINGLE_QUOTE}s an old legend that something{NL}big will happen when Hyrule{SINGLE_QUOTE}s bell rings.{END}"


text_3726__089E64F3:
	.string "If nothing at all happens, does that{NL}mean all the legends are just lies?{END}"


text_3727__089E653C:
	.string "Figures that the search for that {DOUBLE_QUOTE}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light{NL}force{SPECIAL_02_PAR_1}{END}{DOUBLE_QUOTE} isn{SINGLE_QUOTE}t going too well...{NL}I mean, that stuff never existed{NL}in the first place!{NL}I{SINGLE_QUOTE}m just disappointed in the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}. He{NL}should have known better.{END}"


text_3728__089E6600:
	.string "Rrrrr...ARF ARF!{END}"


text_3729__089E6611:
	.string "Arf arf arf!{END}"


text_372A__089E661E:
	.string "Awooooo!!!{END}"


text_372B__089E6629:
	.string "I{SINGLE_QUOTE}m the best stray dog in town.{NL}{NL}When it comes to begging for treats,{NL}I know all the tricks!{END}"


text_372C__089E6686:
	.string "Each of those figurines is handmade.{NL}Yup! Each and every one of {SINGLE_QUOTE}em!{NL}I bet you have no idea how much{NL}they{SINGLE_QUOTE}re worth. Hehehehe...{END}"


text_372D__089E6706:
	.string "There are fewer and fewer guards{NL}out here with each passing day...{NL}Where do you think they{SINGLE_QUOTE}ve all gone?{END}"


text_372E__089E676E:
	.string "I keep wondering how you get to the{NL}rooftop deck at the Happy Hearth Inn.{NL}There{SINGLE_QUOTE}s got to be a way. Have you{NL}been up there yet?{END}"


text_372F__089E67ED:
	.string "Not only am I a collector of figurines,{NL}but I{SINGLE_QUOTE}m also rich! Filthy, stinkin{SINGLE_QUOTE} rich!{END}"


text_3730__089E683F:
	.string "If you ever find a complete set of{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}figurines{SPECIAL_02_PAR_1}{END}, you should tell me.{NL}You...do know what I{SINGLE_QUOTE}m talking about,{NL}don{SINGLE_QUOTE}t you? Well? Get to it!{END}"


text_3731__089E68C7:
	.string "!?{NL}{NL}Whooooooooooooaaaaaaaaaaaaaaa!!!!{NL}{NL}You did it! I can{SINGLE_QUOTE}t believe you did it!{NL}This is...a totally complete set!{NL}How incredibly awesome! And you even{NL}got the legendary Carlov Medal!!! {NL}It shines with a beautiful light...{NL}It{SINGLE_QUOTE}s every collector{SINGLE_QUOTE}s dream!{NL}What you{SINGLE_QUOTE}ve shown me here... It{SINGLE_QUOTE}s{NL}just... It{SINGLE_QUOTE}s just amazing.{NL}Here, feel free to go in my house and{NL}take whatever you want in thanks...{NL}{SINGLE_QUOTE}Cuz, you know, I{SINGLE_QUOTE}m rich! Hahaha!{END}"


text_3732__089E6A6B:
	.string "Way to go, man.{NL}What an awesome day...{END}"


text_3733__089E6A92:
	.string "When I run, the thing that I{SINGLE_QUOTE}m eating{NL}always falls out of my mouth.{END}"


text_3734__089E6AD6:
	.string "Yaaay! Yaaaay!{END}"


text_3735__089E6AE5:
	.string "I{SINGLE_QUOTE}m planting my flower bed.{END}"


text_3736__089E6B01:
	.string "You{SINGLE_QUOTE}ve got to water these every day.{END}"


text_3737__089E6B26:
	.string "It{SINGLE_QUOTE}s OK to collect figurines, but if{NL}anyone starts calling {SINGLE_QUOTE}em dolls, well...{NL}That would just be bad.{END}"


text_3738__089E6B8C:
	.string "I wonder if the force looks{NL}really big to Picori...{END}"


text_3739__089E6BC0:
	.string "That dog over there{SINGLE_QUOTE}s not very friendly{NL}to strangers, but I like that in a dog.{END}"


text_373A__089E6C10:
	.string "Good work getting here! I don{SINGLE_QUOTE}t get{NL}many visitors, as you can imagine.{END}"


text_373B__089E6C57:
	.string "Whoa! You made it here really quickly!{NL}You{SINGLE_QUOTE}re full of surprises, aren{SINGLE_QUOTE}t you?{END}"


text_373C__089E6CA4:
	.string "Thanks for coming.{NL}{NL}Hardly anyone ever visits, and it gets{NL}lonely here. Please take this.{END}"


text_373D__089E6CFE:
	.string "The view from here is nice.{NL}{NL}And Swiftblade{SINGLE_QUOTE}s screams during{NL}training seem to complement the scene.{END}"


text_373E__089E6D62:
	.string "Good job getting up here.{NL}Really. That{SINGLE_QUOTE}s impressive.{NL}You must have really put yourself out{NL}to find a way here. Please take this.{END}"


text_373F__089E6DE3:
	.string "I wonder how I{SINGLE_QUOTE}m going to get down...{NL}Those cucco chicks just terrify me.{END}"


text_3740__089E6E2D:
	.string "Lately, Mutoh{SINGLE_QUOTE}s been grumbling about{NL}how there{SINGLE_QUOTE}s no work with any punch.{NL}I wish I could do something about that,{NL}but I don{SINGLE_QUOTE}t even know what he means!{END}"


text_3741__089E6EC3:
	.string "I{SINGLE_QUOTE}m so glad the boss is back to his{NL}usual self.{NL}It just makes you grateful{NL}for the good times, you know?{END}"

