
text_3800__089E7044:
	.string "{END}"


text_3801__089E7045:
	.string "So you{SINGLE_QUOTE}ve actually seen{NL}the inside of {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Anju{SINGLE_QUOTE}s henhouse{SPECIAL_02_PAR_1}{END}?{NL}Hehehehe...{END}"


text_3802__089E708C:
	.string "Each town has its own life, its{NL}own rhythm! You know what I mean?{NL}I love towns with lots of rhythm! But{NL}it has to keep up the pace!{END}"


text_3803__089E7110:
	.string "Meoooow...{END}"


text_3804__089E711B:
	.string "Rowrrr!{END}"


text_3805__089E7123:
	.string "{END}"


text_3806__089E7124:
	.string "{END}"


text_3807__089E7125:
	.string "{END}"


text_3808__089E7126:
	.string "{END}"


text_3809__089E7127:
	.string "{END}"


text_380A__089E7128:
	.string "{END}"


text_380B__089E7129:
	.string "{END}"


text_380C__089E712A:
	.string "{END}"


text_380D__089E712B:
	.string "{END}"


text_380E__089E712C:
	.string "{END}"


text_380F__089E712D:
	.string "{END}"


text_3810__089E712E:
	.string "{END}"


text_3811__089E712F:
	.string "{END}"


text_3812__089E7130:
	.string "Buggedy-buggedy-BOO!{NL}{NL}...So, umm... Yeah. Anyway.{END}"


text_3813__089E7162:
	.string "Wait a minute... I see now! You{SINGLE_QUOTE}re so{NL}scared, you can hardly speak!{END}"


text_3814__089E71A6:
	.string "Arf arf!{END}"


text_3815__089E71AF:
	.string "I must look like a huge oversized{NL}monster to you right now, huh?{NL}Just be grateful I don{SINGLE_QUOTE}t EAT you,{NL}pip-squeak.{END}"


text_3816__089E721E:
	.string "You can see everything from up here...{END}"


text_3817__089E7245:
	.string "Ah... This is great.{END}"


text_3818__089E725A:
	.string "I love being a kid...{END}"


text_3819__089E7270:
	.string "So, what{SINGLE_QUOTE}ll it be tonight? We haven{SINGLE_QUOTE}t{NL}had Tektite souffle in ages...{END}"


text_381A__089E72B5:
	.string "Tch! Would you look at this mess?{NL}{NL}I{SINGLE_QUOTE}m sure Beedle could use this spot to{NL}sell Picolyte if it weren{SINGLE_QUOTE}t such a pigsty.{END}"


text_381B__089E732A:
	.string "Come on now, hurry up and figure out{NL}what you{SINGLE_QUOTE}re going to buy already!{END}"


text_381C__089E7371:
	.string "Hey, hey! Veggies makes the ideal gift,{NL}perfect for all occasions!{END}"


text_381D__089E73B4:
	.string "Send a few of these as a gift, and{NL}make me a happy, happy woman!{NL}Hey, hey!{END}"


text_381E__089E73FF:
	.string "Hey, hey! The other vendor{SINGLE_QUOTE}s not doing{NL}so hot, but neither am I!{END}"


text_381F__089E7440:
	.string "My arm{SINGLE_QUOTE}s getting tired, so buy, buy,{NL}buy! Hey, hey!{END}"


text_3820__089E7474:
	.string "Maybe I should get back{NL}to the castle soon...{END}"


text_3821__089E74A2:
	.string "{END}"


text_3822__089E74A3:
	.string "I give up. There{SINGLE_QUOTE}s no {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}{NL}out here. Man, am I tired.{END}"


text_3823__089E74E4:
	.string "Kids are really the most wonderful{NL}things ever.{END}"


text_3824__089E7514:
	.string "There are a lot fewer guards looking{NL}for the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force {SPECIAL_02_PAR_1}{END}now...{END}"


text_3825__089E7558:
	.string "There{SINGLE_QUOTE}s an old legend that something{NL}big will happen when Hyrule{SINGLE_QUOTE}s bell rings.{END}"


text_3826__089E75A7:
	.string "That time may be coming soon...{NL}I can just feel it.{END}"


text_3827__089E75DB:
	.string "It{SINGLE_QUOTE}s tough work, being the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}mailman{SPECIAL_02_PAR_1}{END}.{NL}Look at him, always runnin{SINGLE_QUOTE} around!{END}"


text_3828__089E7627:
	.string "Rrrrr...ARF ARF!{END}"


text_3829__089E7638:
	.string "Arf arf!{END}"


text_382A__089E7641:
	.string "Awoooo!{END}"


text_382B__089E7649:
	.string "Everyone here is so nice.{END}"


text_382C__089E7663:
	.string "I hear you{SINGLE_QUOTE}ve got a good chance of{NL}turning up some rare {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}figurines{SPECIAL_02_PAR_1}{END}...{NL}If you hand over lots of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Mysterious{NL}Shells{SPECIAL_02_PAR_1}{END} in one big load, that is...{NL}Hehehe...{END}"


text_382D__089E7701:
	.string "!?{NL}{NL}The {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}light force{SPECIAL_02_PAR_1}{END}!{NL}{NL}Man. That sounded impressive. If I find{NL}it, I{SINGLE_QUOTE}m gonna shout that so loudly!{END}"


text_382E__089E7767:
	.string "Kids are so innocent and simple.{NL}Well, until they grow up, anyway...{END}"


text_382F__089E77AC:
	.string "I{SINGLE_QUOTE}m a rich guy, see?{NL}And I{SINGLE_QUOTE}m a collector to boot.{END}"


text_3830__089E77DE:
	.string "If you ever find a complete set of{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}figurines{SPECIAL_02_PAR_1}{END}, you should tell me.{NL}You...do know what I{SINGLE_QUOTE}m talking about,{NL}don{SINGLE_QUOTE}t you? Well? Get to it!{END}"


text_3831__089E7866:
	.string "!?{NL}{NL}Whooooooooooooaaaaaaaaaaaaaaa!!!!{NL}{NL}You did it! I can{SINGLE_QUOTE}t believe you did it!{NL}This is...a totally complete set!{NL}How incredibly awesome! And you even{NL}got the legendary Carlov Medal!!! {NL}It shines with a beautiful light...{NL}It{SINGLE_QUOTE}s every collector{SINGLE_QUOTE}s dream!{NL}What you{SINGLE_QUOTE}ve shown me here... It{SINGLE_QUOTE}s{NL}just... It{SINGLE_QUOTE}s just amazing.{NL}Here, feel free to go in my house and{NL}take whatever you want in thanks...{NL}{SINGLE_QUOTE}Cuz, you know, I{SINGLE_QUOTE}m rich! Hahaha!{END}"


text_3832__089E7A0A:
	.string "Way to go, man.{NL}What an awesome day...{END}"


text_3833__089E7A31:
	.string "My food is coming up, I think...{END}"


text_3834__089E7A52:
	.string "Yaaay! Yaaay!{END}"


text_3835__089E7A60:
	.string "I have to tend the flower beds{NL}out back, too.{END}"


text_3836__089E7A8E:
	.string "Huh?{NL}{NL}This flower bed looks a{NL}little strange.{END}"


text_3837__089E7ABC:
	.string "Oh! You found me. You must be{NL}quite an attentive young man!{NL}Well, now you{SINGLE_QUOTE}ve got something to{NL}brag about to your friends.{NL}I feel I should give you something to{NL}reward your abilities of perception!{NL}Call it a {DOUBLE_QUOTE}Master of Sur-Prize{DOUBLE_QUOTE}!{NL}Good job!{END}"


text_3838__089E7BAC:
	.string "I have to say, good job on meeting me!{NL}{NL}Seriously, you{SINGLE_QUOTE}ll be able to brag about{NL}this to your friends forever!{END}"


text_3839__089E7C1A:
	.string "Once you start collecting figurines,{NL}there{SINGLE_QUOTE}s no end to it!{NL}As soon as new limited-edition specials{NL}come out, my eyes glass over, man.{END}"


text_383A__089E7CA0:
	.string "We tend to stay inside a lot. Don{SINGLE_QUOTE}t want{NL}to get trampled, you know?{NL}Not that being stepped on would kill{NL}us, but it doesn{SINGLE_QUOTE}t sound fun, does it?{END}"


text_383B__089E7D30:
	.string "What{SINGLE_QUOTE}s a ghost? Is that like a guest{NL}who{SINGLE_QUOTE}s overstayed his welcome?{END}"


text_383C__089E7D73:
	.string "You come here a lot... I guess you{NL}must like this place.{END}"


text_383D__089E7DAC:
	.string "Yellow is a rare color for us Minish.{NL}There{SINGLE_QUOTE}s a good side and a bad side to{NL}being rare, though.{NL}Two yellow ones rarely ever show up in{NL}the same place, so they never meet up!{END}"


text_383E__089E7E5A:
	.string "Thanks for coming.{NL}{NL}Hardly anyone ever visits, and it gets{NL}lonely here. Please take this.{END}"


text_383F__089E7EB4:
	.string "The view from here is nice.{NL}{NL}And Swiftblade{SINGLE_QUOTE}s screams during{NL}training seem to complement the scene.{END}"


text_3840__089E7F18:
	.string "Good job getting up here.{NL}Really. That{SINGLE_QUOTE}s impressive.{NL}You must have really put yourself out{NL}to find a way here. Please take this.{END}"


text_3841__089E7F99:
	.string "I wonder how I{SINGLE_QUOTE}m going to get down...{NL}Those cucco chicks just terrify me.{END}"


text_3842__089E7FE3:
	.string "Lately, Mutoh{SINGLE_QUOTE}s been grumbling about{NL}how there{SINGLE_QUOTE}s no work with any punch.{NL}I wish I could do something about that,{NL}but I don{SINGLE_QUOTE}t even know what he means!{END}"


text_3843__089E8079:
	.string "I{SINGLE_QUOTE}m so glad the boss is back to his{NL}usual self.{NL}It just makes you grateful{NL}for the good times, you know?{END}"

