
text_2500__089DC788:
	.string "{END}"


text_2501__089DC789:
	.string "Here we are, {SPECIAL_06_PAR_1}{END}!{NL}Doesn{SINGLE_QUOTE}t it look fun?{NL}{SPECIAL_07_PAR_1}%{SPECIAL_02_PAR_1}{END}Come on! Let{SINGLE_QUOTE}s look around!{END}"


text_2502__089DC7B3:
	.string "Come on! Let{SINGLE_QUOTE}s look around!{END}"


text_2503__089DC7CF:
	.string "{SPECIAL_06_PAR_1}{END}, there{SINGLE_QUOTE}s a storyteller here!{NL}We should stop and listen to--{NL}Oh! I wonder what{SINGLE_QUOTE}s over there...{END}"


text_2504__089DC830:
	.string "So the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori {SPECIAL_02_PAR_1}{END}ARE real! My father{NL}always told me they were.{NL}Oh! Look at that!{END}"


text_2505__089DC882:
	.string "Say, wasn{SINGLE_QUOTE}t there going to be a {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}sword-{NL}fighting tournament{SPECIAL_02_PAR_1}{END} at the castle?{NL}I wonder who won this year...{NL}{NL}Oh, wow! Over here!{END}"


text_2506__089DC903:
	.string "{SPECIAL_06_PAR_1}{END}! Where are you going?{NL}Over here! This way!{END}"


text_2507__089DC931:
	.string "{END}"


text_2508__089DC932:
	.string "{END}"


text_2509__089DC933:
	.string "{END}"


text_250A__089DC934:
	.string "{END}"


text_250B__089DC935:
	.string "{END}"


text_250C__089DC936:
	.string "Welcome to the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Picori Festival{SPECIAL_02_PAR_1}{END}!{NL}{NL}They say that, every hundred years,{NL}the Picori come to Hyrule...{NL}And this is the 100th year, to the day,{NL}since the last time the Picori were here!{END}"


text_250D__089DC9EE:
	.string "Long, long ago, and then even longer{NL}before that...{NL}Evil creatures appeared in the world{NL}of humans.{NL}They were powerful, frightening{NL}beasts, and they created such trouble!{NL}But then the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END} came from the sky,{NL}bringing humans powerful magic.{NL}With the magic light force and the{NL}Picori Blade, the beasts were repelled.{NL}And the world of humans once more{NL}knew peace, thanks to the Picori.{NL}So as not to forget our gratitude, we{NL}hold this festival each year.{NL}Now, remember, little ones... The Picori{NL}only appear before good little children.{NL}If you only do bad deeds, you will{NL}never get to see them! So be good!{END}"


text_250E__089DCC4F:
	.string "I don{SINGLE_QUOTE}t believe in the Picori!{NL}{NL}I{SINGLE_QUOTE}m not a kid anymore! I{SINGLE_QUOTE}m too old to{NL}believe in any stupid old fairy tales!{END}"


text_250F__089DCCBC:
	.string "Do you think I{SINGLE_QUOTE}ll really see the Picori{NL}if I{SINGLE_QUOTE}m on my best behavior all the time?{END}"


text_2510__089DCD0D:
	.string "Come on up! Come one, come all!{NL}Gather round and have a look-see!{NL}I{SINGLE_QUOTE}m having a huge sale on all manner{NL}of delicious and festive vegetables!{END}"


text_2511__089DCD99:
	.string "Oh, hi! Are you enjoying the festival?{NL}It{SINGLE_QUOTE}s so much fun!{NL}I{SINGLE_QUOTE}m so happy to be here! And my fresh{NL}fruits are just delicious! Buy some!{END}"


text_2512__089DCE1D:
	.string "Come one! Come all! Try your luck,{NL}and win incredible prizes!{END}"


text_2513__089DCE5B:
	.string "Hey, guy, have you ever seen the{NL}Picori? I saw one just the other day!{NL}It wore a red cone-shaped hat, and{NL}it was really small...{NL}And it was standing inside my dad{SINGLE_QUOTE}s{NL}shoe! I really saw it! I swear!{END}"


text_2514__089DCF20:
	.string "So, so, so... I{SINGLE_QUOTE}ve been good all year?{NL}Like, all year long?{NL}And you know how the Picori only{NL}show themselves if you{SINGLE_QUOTE}ve been good?{NL}And so, so, so I{SINGLE_QUOTE}m just waiting for{NL}the Picori to come and play with me.{END}"


text_2515__089DCFEB:
	.string "Only once every hundred years does{NL}the mystic doorway open.{NL}This is the door that links the human{NL}world to the world of the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}.{NL}When this door opens, the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END} can{NL}enter our world. And guess what!{NL}This marks the hundredth year{NL}since they last appeared here!{NL}I{SINGLE_QUOTE}m sure something wonderful is{NL}going to happen at this festival!{END}"


text_2516__089DD13C:
	.string "Each year, there is a sword-fighting{NL}tournament at the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Picori Festival{SPECIAL_02_PAR_1}{END}.{NL}This year{SINGLE_QUOTE}s tournament is already over.{NL}I couldn{SINGLE_QUOTE}t believe how fast it went!{NL}I hear {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}the victor was a mysterious{NL}man dressed entirely in black{SPECIAL_02_PAR_1}{END}.{END}"


text_2517__089DD21B:
	.string "They say the Picori bring happiness{NL}to all the humans they meet...{NL}I wonder when they will bring{NL}happiness to me...{END}"


text_2518__089DD28F:
	.string "Are you enjoying yourself, {SPECIAL_06_PAR_1}{END}?{NL}This is the biggest festival in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule{SPECIAL_02_PAR_1}{END}!{NL}If you don{SINGLE_QUOTE}t stop to enjoy it,{NL}you{SINGLE_QUOTE}ll miss out on all the fun!{END}"


text_2519__089DD319:
	.string "I{SINGLE_QUOTE}ve been on the road for a while.{NL}I came back in time for the festival.{NL}It feels wonderful to be back in Hyrule{NL}again, in this joyous time!{NL}I... I must put these feelings{NL}into verse!{END}"


text_251A__089DD3D1:
	.string "I love festivals. It{SINGLE_QUOTE}s like seeing your{NL}town transform into another world!{NL}It really gives you a chance to think{NL}about how well we have it here...{END}"


text_251B__089DD464:
	.string "People from all over the place come to{NL}Hyrule Town for the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Picori Festival{SPECIAL_02_PAR_1}{END}.{END}"


text_251C__089DD4B4:
	.string "You{SINGLE_QUOTE}re the boy from old Master{NL}Smith{SINGLE_QUOTE}s place, right?{NL}I{SINGLE_QUOTE}m sure you know this, but he{SINGLE_QUOTE}s the{NL}best swordsmith Hyrule{SINGLE_QUOTE}s ever seen!{NL}Every year, I enter the tournament{NL}trying to win that sword of his.{NL}I haven{SINGLE_QUOTE}t won yet, and maybe I never{NL}will, but the tournament was awesome!{NL}The winner this year was a new face.{NL}I{SINGLE_QUOTE}ve been wondering where he{SINGLE_QUOTE}s from.{NL}He used some incredible techniques and{NL}won the whole tourney in record time!{END}"


text_251D__089DD658:
	.string "I{SINGLE_QUOTE}ve been dispatched from {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}{NL}up north to watch over the festivities.{END}"


text_251E__089DD6AC:
	.string "I{SINGLE_QUOTE}ve never seen the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori {SPECIAL_02_PAR_1}{END}before...{END}"


text_251F__089DD6D5:
	.string "You two must be great friends!{END}"


text_2520__089DD6F4:
	.string "I{SINGLE_QUOTE}m going to look for {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}! Mom said{NL}there{SINGLE_QUOTE}d be {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori {SPECIAL_02_PAR_1}{END}at the festival!{END}"


text_2521__089DD746:
	.string "I saw it! There was a {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori {SPECIAL_02_PAR_1}{END}here{NL}just a second ago! No, really!{END}"


text_2522__089DD78B:
	.string "This is my first ever {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Picori Festival{SPECIAL_02_PAR_1}{END}!{NL}So...where are all the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Picori{SPECIAL_02_PAR_1}{END}, anyway?{END}"


text_2523__089DD7E1:
	.string "Day and night, he{SINGLE_QUOTE}s going on and on{NL}about Picori this and Picori that!{NL}Doesn{SINGLE_QUOTE}t he know they{SINGLE_QUOTE}re nothing but a{NL}silly fairy tale to make kids behave?{END}"


text_2524__089DD874:
	.string "I{SINGLE_QUOTE}m just on my way back from seeing{NL}the tournament at {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Castle{SPECIAL_02_PAR_1}{END}.{NL}Let me tell you! Watching all those{NL}sword fights made me hungry!{END}"


text_2525__089DD8FE:
	.string "Phew... Preparing for the festival left{NL}me absolutely exhausted...{NL}Still, I{SINGLE_QUOTE}m just enjoying watching{NL}people have fun.{END}"


text_2526__089DD974:
	.string "Hey, hey! Come on up!{NL}Take a shot! Win a prize!{END}"


text_2527__089DD9A4:
	.string "My sister and I came a long way to see{NL}the {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}Picori Festival{SPECIAL_02_PAR_1}{END} this year.{NL}Is it true the festival{SINGLE_QUOTE}s named after{NL}tiny people the size of my thumb?{NL}I want to see what they look like! Do{NL}you know where I can go to see them?{END}"

