
text_3A00__089E8FE0:
	.string "{END}"


text_3A01__089E8FE1:
	.string "Some people still refuse to take{NL}shelter. I don{SINGLE_QUOTE}t know what to tell them!{END}"


text_3A02__089E902B:
	.string "{END}"


text_3A03__089E902C:
	.string "Now that everyone{SINGLE_QUOTE}s gone...{NL}I{SINGLE_QUOTE}m kind of scared.{END}"


text_3A04__089E905C:
	.string "I saw something... Do you think it was{NL}a ghost? Or maybe...a monster?{NL}I{SINGLE_QUOTE}m not afraid! I{SINGLE_QUOTE}m going to defend{NL}Hyrule, no matter what!{END}"


text_3A05__089E90DE:
	.string "This used to be such a lively town...{NL}Whatever happened to this place?{END}"


text_3A06__089E9125:
	.string "Hey, you! It{SINGLE_QUOTE}s too dangerous to be{NL}just wandering around! Get inside!{END}"


text_3A07__089E916B:
	.string "{END}"


text_3A08__089E916C:
	.string "We{SINGLE_QUOTE}ll protect you!{NL}You can return home safely!{END}"


text_3A09__089E919B:
	.string "Maybe those monsters are why the {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}king{SPECIAL_02_PAR_1}{END}{NL}has been acting so strange lately...{END}"


text_3A0A__089E91EA:
	.string "It{SINGLE_QUOTE}s too dangerous here! Go home!{END}"


text_3A0B__089E920C:
	.string "We{SINGLE_QUOTE}re shorin{SINGLE_QUOTE} up the town{SINGLE_QUOTE}s defenses,{NL}so we{SINGLE_QUOTE}ll be ready if the monsters strike!{END}"


text_3A0C__089E925C:
	.string "Hey, you can{SINGLE_QUOTE}t be out here!{NL}Get back inside now!{END}"


text_3A0D__089E928D:
	.string "There aren{SINGLE_QUOTE}t even any animals here{NL}anymore... What{SINGLE_QUOTE}s happening?{END}"


text_3A0E__089E92CD:
	.string "I{SINGLE_QUOTE}m a rich guy, see?{NL}And I{SINGLE_QUOTE}m a collector to boot.{END}"


text_3A0F__089E92FF:
	.string "If you ever find a complete set of{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}figurines{SPECIAL_02_PAR_1}{END}, you should tell me.{NL}You...do know what I{SINGLE_QUOTE}m talking about,{NL}don{SINGLE_QUOTE}t you? Well? Get to it!{END}"


text_3A10__089E9387:
	.string "!?{NL}{NL}Whooooooooooooaaaaaaaaaaaaaaa!!!!{NL}{NL}You did it! I can{SINGLE_QUOTE}t believe you did it!{NL}This is...a totally complete set!{NL}How incredibly awesome! And you even{NL}got the legendary Carlov Medal!!! {NL}It shines with a beautiful light...{NL}It{SINGLE_QUOTE}s every collector{SINGLE_QUOTE}s dream!{NL}What you{SINGLE_QUOTE}ve shown me here... It{SINGLE_QUOTE}s{NL}just... It{SINGLE_QUOTE}s just amazing.{NL}Here, feel free to go in my house and{NL}take whatever you want in thanks...{NL}{SINGLE_QUOTE}Cuz, you know, I{SINGLE_QUOTE}m rich! Hahaha!{END}"


text_3A11__089E952B:
	.string "Way to go, man.{NL}What an awesome day...{END}"


text_3A12__089E9552:
	.string "Lately, Mutoh{SINGLE_QUOTE}s been grumbling about{NL}how there{SINGLE_QUOTE}s no work with any punch.{NL}I wish I could do something about that,{NL}but I don{SINGLE_QUOTE}t even know what he means!{END}"


text_3A13__089E95E8:
	.string "I{SINGLE_QUOTE}m so glad the boss is back to his{NL}usual self.{NL}It just makes you grateful{NL}for the good times, you know?{END}"

