
text_3F00__089EA820:
	.string "Boy, when I was your age I was quite{NL}the little terror!{NL}I was tearing up opponents left and{NL}right at the Picori Festival tourney.{NL}Oh, I was really something back in{NL}the day...{NL}In fact, I still have a lot of the{NL}{SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces {SPECIAL_02_PAR_1}{END}I won at the tourney.{NL}So I wouldn{SINGLE_QUOTE}t say no if you were{NL}interested in fusing Kinstones...{END}"


text_3F01__089EA960:
	.string "That green cap and green clothes...{NL}Are you...perhaps...a fairy?!{NL}Woohaaa!{SPECIAL_0F_PAR_1}{BYTE_0B} I knew it! I knew it!{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tingle{SPECIAL_02_PAR_1}{END} wants to be a fairy, too!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}Actually, {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tingle {SPECIAL_02_PAR_1}{END}has some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstones{SPECIAL_02_PAR_1}{END},{NL}you know!{NL}And I have given {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstones{SPECIAL_02_PAR_1}{END} to my{NL}brothers, too.{NL}If you can fuse {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstones{SPECIAL_02_PAR_1}{END} with me and{NL}each of my brothers, well...{NL}I don{SINGLE_QUOTE}t want to give it away, but you{SINGLE_QUOTE}ll{NL}get something very, very, VERY good!{NL}Good luck, Mr. Fairy!{END}"


text_3F02__089EAB00:
	.string "Have you found all of Tingle{SINGLE_QUOTE}s{NL}brothers yet?{NL}If you can fuse {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstones{SPECIAL_02_PAR_1}{END} with all of{NL}us, Tingle has a surprise for you...{NL}In fact, Tingle is POSITIVE you will get{NL}something very, very, VERY good!{NL}Good luck, Mr. Fairy!{END}"


text_3F03__089EABDC:
	.string "Hey! Mr. Fairy! You{SINGLE_QUOTE}ve got some nice{NL}pieces there!{NL}Would you be surprised to know Tingle{NL}has a new piece, too? Let{SINGLE_QUOTE}s fuse them!{END}"


text_3F04__089EAC5C:
	.string "That{SINGLE_QUOTE}s twice we{SINGLE_QUOTE}ve fused our{NL}Kinstones perfectly so far!{NL}Say... I wonder if this will make me into{NL}a real and true fairy! It will, right?{NL}You wouldn{SINGLE_QUOTE}t lie to me, now!{NL}Tingle Tingle Kooloo-Limpa!{NL}I can{SINGLE_QUOTE}t wait to be a fairy!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_3F05__089EAD3D:
	.string "Oh, Mr. Fairy. Hello.{NL}{NL}My brother {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tingle {SPECIAL_02_PAR_1}{END}is always telling{NL}us about you.{NL}He says he owes a lot to you fairies,{NL}and I know he{SINGLE_QUOTE}d want me to thank you.{NL}In fact, he gave me some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone{NL}pieces{SPECIAL_02_PAR_1}{END} that you might want to fuse!{NL}What do you say?{NL}Want to try it?{END}"


text_3F06__089EAE41:
	.string "Have you seen {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Knuckle{SPECIAL_02_PAR_1}{END}?{NL}{NL}He{SINGLE_QUOTE}s my twin brother, and he{SINGLE_QUOTE}s dressed{NL}all in blue. I don{SINGLE_QUOTE}t know where he is!{END}"


text_3F07__089EAEAB:
	.string "Have you noticed that some people will{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse Kinstones{SPECIAL_02_PAR_1}{END} whenever you want?{NL}And some people won{SINGLE_QUOTE}t fuse with you{NL}even though you have Kinstones?{NL}Well, that just means you have to be{NL}persistent and keep asking them!{END}"


text_3F08__089EAF82:
	.string "Hey, Mr. Fairy! I{SINGLE_QUOTE}ve been holding on to{NL}this, just like {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}my brother Tingle {SPECIAL_02_PAR_1}{END}asked!{NL}And I have {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces{SPECIAL_02_PAR_1}{END}!{NL}Want to try and {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse {SPECIAL_02_PAR_1}{END}with me?{END}"


text_3F09__089EB019:
	.string "All of us brothers look alike, but the{NL}one in white isn{SINGLE_QUOTE}t really our brother.{NL}What I can{SINGLE_QUOTE}t figure out is why he tries{NL}to dress up like us, though...{END}"


text_3F0A__089EB0AE:
	.string "Are you Mr. Fairy? Oh, yeah. Look at{NL}those clothes. You{SINGLE_QUOTE}ve got to be him!{NL}I received some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces{SPECIAL_02_PAR_1}{END}{NL}from {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tingle{SPECIAL_02_PAR_1}{END}.{NL}He said I should try and {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse {SPECIAL_02_PAR_1}{END}them{NL}with you, Mr. Fairy!{NL}So what do you think?{NL}Should we try to {SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}fuse{SPECIAL_02_PAR_1}{END}?{END}"


text_3F0B__089EB19A:
	.string "I{SINGLE_QUOTE}m not even related to that {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tingle{SPECIAL_02_PAR_1}{END}!{NL}So...why am I helping him so much?{END}"


text_3F0C__089EB1E6:
	.string "I have new {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces {SPECIAL_02_PAR_1}{END}from {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tingle{SPECIAL_02_PAR_1}{END}.{NL}{NL}But to tell you the truth, I{SINGLE_QUOTE}d{NL}rather be out adventuring, like you.{NL}And what{SINGLE_QUOTE}s with these crazy clothes{NL}he makes us all wear, anyway?{END}"


text_3F0D__089EB29D:
	.string "The real key to finding treasure is{NL}{SPECIAL_02_PAR_1}{SPECIAL_03_PAR_2}looking at your map {SPECIAL_02_PAR_1}{END}constantly!{NL}Take a step, check the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map{SPECIAL_02_PAR_1}{END}! Take{NL}another step, look at the {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}map {SPECIAL_02_PAR_1}{END}again!{NL}I tell ya... All this talk is making me{NL}want to go on an adventure, too!{END}"


text_3F0E__089EB37C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}This is one solid wall... I{SINGLE_QUOTE}m going to{NL}need a few friends to give me a hand.{END}"


text_3F0F__089EB3CC:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}Hn. This rock{SINGLE_QUOTE}s too hard... My hands{NL}are starting to hurt...{END}"


text_3F10__089EB40C:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}I wonder what{SINGLE_QUOTE}s in here. Probably{NL}more delicious rocks, hn?{END}"


text_3F11__089EB44B:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BA}It{SINGLE_QUOTE}s nice to have my friends helping.{NL}Even if I slack off, no one complains...{END}"


text_3F12__089EB49D:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}One more push! GORO! This is fun...{NL}I{SINGLE_QUOTE}m kind of sad we{SINGLE_QUOTE}re almost done.{END}"


text_3F13__089EB4E7:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}Thank goodness! We{SINGLE_QUOTE}re finally through!{NL}That was a long way to dig...{END}"


text_3F14__089EB52F:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}Together, there{SINGLE_QUOTE}s no rock we{NL}can{SINGLE_QUOTE}t dig through!{END}"


text_3F15__089EB562:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_BA}These rocks are delicious. I just want{NL}to stay here forever!{END}"


text_3F16__089EB5A2:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B7}It{SINGLE_QUOTE}s nice having all my friends here,{NL}but sometimes...I can{SINGLE_QUOTE}t tell them apart!{END}"


text_3F17__089EB5F4:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B8}You know... With six Gorons all here at{NL}once, it starts to smell a little...ripe.{END}"


text_3F18__089EB649:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}That Goron statue outside the cave is{NL}a little scary...{END}"


text_3F19__089EB684:
	.string "Ah, so you moved that gravestone,{NL}and now you can go outside...{NL}But I would get lonely here by myself,{NL}so could you come see me sometime?{NL}I{SINGLE_QUOTE}ll have plenty of {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Kinstone pieces{SPECIAL_02_PAR_1}{END}{NL}ready, so please, do come back!{END}"


text_3F1A__089EB756:
	.string "Oh, you came back to visit!{NL}I{SINGLE_QUOTE}m so happy!{NL}I know this is a grave, but please,{NL}make yourself feel at home!{END}"


text_3F1B__089EB7C0:
	.string "Oh, no, no, no! Why, you still have{NL}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones left to fuse!{NL}Why, you{SINGLE_QUOTE}ve only just begun!{NL}The road is long, Mr. Fairy!{END}"


text_3F1C__089EB839:
	.string "Oh, dear! You have {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones{NL}left to go! You{SINGLE_QUOTE}re not even trying!{NL}I mean, you haven{SINGLE_QUOTE}t seen anything yet!{NL}There are still TONS out there!{END}"


text_3F1D__089EB8C4:
	.string "Well! You have {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones left to{NL}fuse! {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tingle {SPECIAL_02_PAR_1}{END}is impressed!{END}"


text_3F1E__089EB907:
	.string "Just a wee bit more, Mr. Fairy! That{SINGLE_QUOTE}s{NL}right! You only have {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} to go!{NL}Just a wee, tiny bit, and you{SINGLE_QUOTE}ll have{NL}fused every last Kinstone there is!{END}"


text_3F1F__089EB997:
	.string "You fused each and every last{NL}Kinstone! Way to go, Mr. Fairy!{NL}You can claim this Tingle trophy{NL}as your own with pride now!{END}"


text_3F20__089EBA12:
	.string "How many Kinstones do you have left to{NL}fuse? Let{SINGLE_QUOTE}s see... {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones?{NL}You{SINGLE_QUOTE}ve only just begun your quest for{NL}happiness, Mr. Fairy!{END}"


text_3F21__089EBA96:
	.string "Tch tch tch! You have {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones{NL}left to fuse!? You haven{SINGLE_QUOTE}t seen a thing!{NL}There are tons out there still!{END}"


text_3F22__089EBB02:
	.string "How many Kinstones are left?{NL}Let{SINGLE_QUOTE}s see... {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones to fuse!{NL}I guess you{SINGLE_QUOTE}ve seen quite a bit of{NL}happiness! No reason to give up now!{END}"


text_3F23__089EBB8A:
	.string "Oh, you{SINGLE_QUOTE}re doing QUITE well! Quite{NL}well indeed!{NL}In fact, you only have {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} left to{NL}go! Keep fusing those Kinstones!{END}"


text_3F24__089EBBFD:
	.string "We knew you could do it! {NL}You fused all the Kinstones!{NL}Way to go, Mr. Fairy! I can practically{NL}see my brother{SINGLE_QUOTE}s smiling face now!{END}"


text_3F25__089EBC7F:
	.string "How many Kinstones are left for you{NL}to fuse? Let{SINGLE_QUOTE}s see... {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1}!?{NL}What are you doing, wasting your time{NL}here! You{SINGLE_QUOTE}ve got work to do, Mr. Fairy!{END}"


text_3F26__089EBD0C:
	.string "How many have you not found yet?{NL}Let{SINGLE_QUOTE}s see...{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} left to go!{NL}You haven{SINGLE_QUOTE}t seen anything yet!{NL}There are tons out there still!{END}"


text_3F27__089EBD87:
	.string "How many have you not found yet?{NL}Let{SINGLE_QUOTE}s see...{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} left to go!{NL}I guess you{SINGLE_QUOTE}ve seen quite a few!{NL}But this means you have to press on!{END}"


text_3F28__089EBE09:
	.string "Got many Kinstones left to fuse? Let{NL}me see... Hm. Nope! Only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} to go!{NL}That{SINGLE_QUOTE}s not bad at all! In fact, I think{NL}you might just fuse them all!{END}"


text_3F29__089EBE97:
	.string "You found them all! Can you feel the{NL}happiness flow through you, Mr. Fairy?{END}"


text_3F2A__089EBEE3:
	.string "So. Fused a lot of Kinstones already?{NL}Let{SINGLE_QUOTE}s see here...{NL}Ooo, no... Man! You{SINGLE_QUOTE}ve got{NL}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones left?{NL}Goodness, man! Get to it!{NL}Time{SINGLE_QUOTE}s a-wastin{SINGLE_QUOTE}!!!{END}"


text_3F2B__089EBF77:
	.string "Oh, oh, oh... You still have {NL}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones left to fuse?{NL}Still a ways to go! Sigh... If only{NL}I could search for happiness myself...{END}"


text_3F2C__089EBFFB:
	.string "Wow! You{SINGLE_QUOTE}re getting closer! Only{NL}{SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} Kinstones left to go!{NL}You{SINGLE_QUOTE}ve found quite a few. Do you think{NL}you could set a few aside for me?{END}"


text_3F2D__089EC07E:
	.string "You just HAVE to be close now... How{NL}many Kinstones do you have to fuse?{NL}Only {SPECIAL_06_PAR_1}{SPECIAL_01_PAR_1} left to go! I{SINGLE_QUOTE}m getting all{NL}sad thinking of the end being so near!{END}"


text_3F2E__089EC112:
	.string "You found every last one?! You are the{NL}man, er, I mean fairy, Mr. Fairy!{NL}Oh, I do so want to go on an adventure{NL}with you! I do, I do, I do!{END}"


text_3F2F__089EC19E:
	.string "Mr. Fairy! You did it! How incredible!{NL}You fused every last Kinstone there is!{NL}Tingle would love ever so much to send{NL}you something special now!{END}"


text_3F30__089EC22F:
	.string "Awwww!{SPECIAL_0F_PAR_1}{BYTE_0B} Woooo-weeee!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}{SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Tingle{SPECIAL_02_PAR_1}{END} wants a trophy, too!{SPECIAL_0F_PAR_1}{BYTE_0B}{NL}Please take good care of it!{SPECIAL_0F_PAR_1}{BYTE_0B}{END}"


text_3F31__089EC288:
	.string "What are you doing here?!{NL}{NL}This is a graveyard!{NL}There are ghosts here!{NL}Oh yeah, speaking of which, my{NL}brother lives in {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule Town{SPECIAL_02_PAR_1}{END}.{NL}He{SINGLE_QUOTE}s a troublesome prankster, but{NL}I often wonder how he{SINGLE_QUOTE}s doing...{END}"


text_3F32__089EC353:
	.string "Holder of the sacred powers, we grant{NL}you the power of wind...{END}"


text_3F33__089EC392:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E4}What? What happened!?{NL}It blew up?{END}"


text_3F34__089EC3B7:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}That was too close, moo! I thought I{SINGLE_QUOTE}d{NL}be ground chuck for sure!{END}"


text_3F35__089EC3FB:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}I{SINGLE_QUOTE}m gonna eat a lot of grass so that{NL}I can make delicious milk! Oh, and moo.{END}"


text_3F36__089EC44B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}I{SINGLE_QUOTE}m so full!{NL}{NL}Mmm! Moo! But it{SINGLE_QUOTE}s so delicious!{NL}I just can{SINGLE_QUOTE}t stop eating. Moo...{END}"


text_3F37__089EC49E:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}You know that puddle of water in the{NL}middle of the pasture?{NL}There{SINGLE_QUOTE}s something kind of suspicious{NL}about it. Moo! Call it a cow{SINGLE_QUOTE}s intuition.{END}"


text_3F38__089EC52C:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D4}Nothing makes me happier than just{NL}standing around, eating grass all day.{END}"


text_3F39__089EC579:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_B9}I{SINGLE_QUOTE}ve sold all my {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}pieces{SPECIAL_02_PAR_1}{END}!{NL}{NL}Yeah! I KNEW coming to {SPECIAL_02_PAR_1}{SPECIAL_02_PAR_1}Hyrule {SPECIAL_02_PAR_1}{END}was a{NL}good idea!{END}"


text_3F3A__089EC5CD:
	.string "{SPECIAL_03_PAR_2}{SPECIAL_01_PAR_1}{BYTE_E4}Hey! There{SINGLE_QUOTE}s a symbol up there, but{NL}you{SINGLE_QUOTE}re too short for me to see it!{SPECIAL_01_PAR_1}{NL}{NL}Well, no problem.{NL}I{SINGLE_QUOTE}ll remember the spot...{END}"


text_3F3B__089EC645:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_90}No matter how many times I see that{NL}happen, it still rattles me...{END}"


text_3F3C__089EC68B:
	.string "{SPECIAL_03_PAR_2}{END}{BYTE_D3}Please! Buy some {SPECIAL_02_PAR_1}{SPECIAL_01_PAR_1}Lon Lon Milk{SPECIAL_02_PAR_1}{END} from me!{NL}{NL}If you don{SINGLE_QUOTE}t, my wagon will be too{NL}heavy on the trip home!{END}"

